### ISSUE TITLE
add angle in tree layout

### ISSUE THREAD

**Issue by yonicd** [JohnCoene/echarts4r#1]
add angle to label of open nodes in tree for readbility.

here is an example of it:

https://github.com/metrumresearchgroup/d3Tree/blob/master/inst/htmlwidgets/d3tree.js#L189

in an app: https://metrumrg.shinyapps.io/d3Tree/

**Comment by JohnCoene** [comment]
Perhaps I pushed the package a bit early and the documentation isn't as good as it should, I'll improve it.

```r
df <- data.frame(
    parent = c("earth","earth","forest","forest","ocean","ocean","ocean","ocean"), 
    child = c("ocean","forest","tree","sasquatch","fish","seaweed","mantis shrimp","sea monster")
)

df %>% 
    e_charts() %>% 
    e_tree(parent, child, label = list(offset = c(10, 15)))
```

More options on `e_tree` label [here](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-tree.label).
