### ISSUE TITLE
Adding control buttons

### ISSUE THREAD

**Issue by RB000** [JohnCoene/echarts4r#10]
Hello
Is there any way to add some buttons or drop down Menu to some charts !!

**Comment by JohnCoene** [comment]
It's not supported in ECharts natively and is done in the official examples with dat.gui. It would be quite difficult to implement in R and I'm unsure of its usefulness give we can use shiny or other interactive documents to have said drop-downs. You will find examples of Shiny with echarts4r [online](http://shiny.john-coene.com/echarts4rShiny/) and in the [documentation](http://shiny.john-coene.com/echarts4rShiny/). In hope this helps.
