### ISSUE TITLE
Could we have more than 3 levels using the e_tree function ?

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/echarts4r#101]
Basically, I want to plot a Decision Tree using that function. But found that I could not have more than 3 levels .

**Comment by JohnCoene** [comment]
您好！Sorry for the late response, overwhelmed with fixing issues across multiple repositories =/

It's totally possible natively but needs to be implemented in the R package. To do so may I ask you how you normally how such data a `data.frame` does not seem ideal, do you use `data.tree` for instance?
