### ISSUE TITLE
title.left: center not working properly in echarts_from_json

### ISSUE THREAD

**Issue by Blanket58** [JohnCoene/echarts4r#102]
I cannot use the option "title.left: center" to make the title in my plot at the center position.
Here are my json options:

{
    "title": {
        "text": "",
        "textStyle": {
            "fontSize": 30
        },
        "textAlign": "center",
        "left": "center"
    },
    "legend": {
        "data": [],
        "bottom": 10
    },
    "xAxis": [
        {
            "type": "category",
            "data": []
        }
    ],
    "yAxis": [
        {
            "type" : "value",
            "name" : "",
            "axisLabel": {
                "formatter": "{value} %"
            }
        },
        {
            "type": "value",
            "name": "",
            "show": false,
            "min": ""
        }
    ],
    "series": [
        {
            "name":"",
            "type":"bar",
            "data":[]
        },
        {
            "name":"",
            "type":"bar",
            "data":[]
        },
        {
            "name":"",
            "type":"bar",
            "data":[]
        },
        {
            "name":"",
            "type":"bar",
            "data":[]
        },
        {
            "name":"rate",
            "type":"line",
            "yAxisIndex": 1,
            "itemStyle": {
                "normal": {
                    "label": {
                        "show": true,
                        "formatter": "{c} %",
                        "textStyle": {
                            "color": "black",
                            "fontSize": 15
                        }
                    },
                    "lineStyle": {
                        "color": "darkgray",
                        "width": 5
                    }
                }
            },
            "symbol": "triangle",
            "symbolSize": 10,
            "data":[],
            "animation": false
        }
    ],
    "animation": false,
    "color": ["#60acfc", "#5bc49f", "#feb64d", "#ff7c7c", "darkgray"]
}

When I set title.left to be "center" the plot will looks like below, the title was supposed to be at the center top of the image.

![The plot](http://47.102.97.73/owncloud/index.php/s/4fb8kTUKbidr1Z0/download)

**Comment by JohnCoene** [comment]
This worked for me.

```js
{
   "title":{
      "text":"My title",
      "textStyle":{
         "fontSize":30
      },
      "textAlign":"center",
      "left":"center"
   },
   "legend":{
      "data":[

      ],
      "bottom":10
   },
   "xAxis":[
      {
         "type":"category",
         "data":[
            "a",
            "b",
            "c"
         ]
      }
   ],
   "yAxis":[
      {
         "type":"value",
         "name":"",
         "axisLabel":{
            "formatter":"{value} %"
         }
      },
      {
         "type":"value",
         "name":"",
         "show":false,
         "min":""
      }
   ],
   "series":[
      {
         "name":"",
         "type":"bar",
         "data":[
            1,
            2,
            3
         ]
      },
      {
         "name":"",
         "type":"bar",
         "data":[
            1,
            3,
            2
         ]
      },
      {
         "name":"",
         "type":"bar",
         "data":[
            3,
            2,
            1
         ]
      },
      {
         "name":"",
         "type":"bar",
         "data":[
            3,
            1,
            2
         ]
      },
      {
         "name":"rate",
         "type":"line",
         "yAxisIndex":1,
         "itemStyle":{
            "normal":{
               "label":{
                  "show":true,
                  "formatter":"{c} %",
                  "textStyle":{
                     "color":"black",
                     "fontSize":15
                  }
               },
               "lineStyle":{
                  "color":"darkgray",
                  "width":5
               }
            }
         },
         "symbol":"triangle",
         "symbolSize":10,
         "data":[

         ],
         "animation":false
      }
   ],
   "animation":false,
   "color":[
      "#60acfc",
      "#5bc49f",
      "#feb64d",
      "#ff7c7c",
      "darkgray"
   ]
}
```

![image](https://user-images.githubusercontent.com/7833796/63917325-b24fd100-ca3a-11e9-855b-963762a017b5.png)

Can you try that, if it does not work reinstall the Github version. 

```r
install.packages("remotes")
remotes::install_github("JohnCoene/echarts4r")
```

Let me know if this did not work, you can close if it's all good now.

**Comment by Blanket58** [comment]
I figured out the reason. I use package `jsonlite` to read my json file to be a R object, which is without any data, and then put data into the R object in R and use `jsonlite::toJSON()` to serialize it to be json, which is the final input to `echarts_from_json()`.

The problem is function `toJSON()` will automatically wrap any value with square brackets, so the following hand-written json option works fine:
```
{
   "title":{
      "text":[
         "Title here"
      ],
      "textStyle":{
         "fontSize":[
            30
         ]
      },
      "textAlign":"center",
      "left":"center"
   },

...

}
```

But this one, which is the output of function `jsonlite::toJSON`, is not working:
```
{
   "title":{
      "text":[
         "Title here"
      ],
      "textStyle":{
         "fontSize":[
            30
         ]
      },
      "textAlign":["center"],
      "left":["center"]
   },

...

}
```

**Comment by JohnCoene** [comment]
There are parameters in `jsonlite::toJSON` that allow removing those.

```r
> x <- list(x = 1)
> jsonlite::toJSON(x)
{"x":[1]} 
> jsonlite::toJSON(x, auto_unbox = TRUE)
{"x":1} 
```

**Comment by Blanket58** [comment]
Really thankful!!!
echarts4r is a really great package!
