### ISSUE TITLE
How can I use javascript function in echarts_from_json() ?

### ISSUE THREAD

**Issue by Blanket58** [JohnCoene/echarts4r#105]
`jsonlite` will quote the function as a string, therefore echarts will not parse it, is there any way to solve this?
```
   "yAxis":[  
      {  
         "type":"value",
         "name":"",
         "axisLabel":{  

         },
         "show":false,
         "min":"function(value) {return value.min - 200;}"
      }
```

**Comment by JohnCoene** [comment]
I don't think this is going to work I'm afraid. Within other functions you can wrap JavaScript functions with `htmlwidgets::JS` as shown in [these examples](https://echarts4r.john-coene.com/articles/tooltip.html).
