### ISSUE TITLE
Output files too heavy

### ISSUE THREAD

**Issue by Rexpert** [JohnCoene/echarts4r#109]
Hallo John,

1st of all, thanks for the great work you've done in echarts4r. I just have a little curious about the output files' size. I used `htmlwidget::saveWidget(a, "a.html", selfcontained = F)` to save the bar chart. However, is it possible to reduce the file size as I found the file produced contained other chart's resources, like in the `a_files\echarts4r-4.3.2\plugins\`,  `a_files\echarts4r-4.3.2\themes\`, etc, which may not necessary for plotting the bar chart. 

This is annoying me because the files are too big and heavy, it does take very long time to load. It will be very appreciate if you can solve this.

**Comment by JohnCoene** [comment]
Hi Rexpert,

Thank you for the feedback. It's true that echarts4r has grown to be quite large (hence splitting [echarts4r.maps](https://echarts4r-maps.john-coene.com/) and [echarts4r.assets(https://echarts4r-assets.john-coene.com/)]) However I'm afraid the large size does not come from the themes but other files, below is what I see from my terminal.

![image](https://user-images.githubusercontent.com/7833796/65836227-46d67900-e2f0-11e9-9b40-13288c59879d.png)

It's a good point and I'll mark as enhancement but I'm not sure I can address it short term, apologies, feel to let me know if I miss something.

**Comment by Rexpert** [comment]
Hi John, I think you misunderstood my statement. I means the output files are too huge, not the library itself, which includes in the output of `a.html`'s file.

Note: `selfcontained` parameter is disabled in `saveWidget()` so I obtained a bunch of `.js` files in a `a_file` folder. There are many unwanted `.js` files in that folder.

**Comment by JohnCoene** [comment]
Sorry it took so long to tackle, most dependencies are now dynamic. Feel free to reopen, thanks again for flagging this.
