### ISSUE TITLE
Displaying extra variables in tooltips

### ISSUE THREAD

**Issue by jyjek** [JohnCoene/echarts4r#11]
Hi
I'm trying to make  plot with  extra variables in tooltips, but can't understand how to make it.
Tutorial from API didn't help me 
Example  :
```
library(dplyr)
library(echarts4r)
mtcars %>%  
  tibble::rownames_to_column("model") %>% 
  e_charts(wt) %>% 
  e_scatter(mpg,bind=model) %>%
  e_tooltip(formatter = htmlwidgets::JS("
                                        function(params){
                                        return('<strong>' + params.name + 
                                        '</strong><br />wt: ' + params.value[0] + 
                                        '<br />mpg: ' +  params.value[1] +
                                        '<br />qsec: ' +  this.qsec )   }  "))
```
expected result  something like this:
https://github.com/jbkunst/highcharter/issues/54

**Comment by JohnCoene** [comment]
Closing, assuming will follow your issue (answered) on [stackoverflow](https://stackoverflow.com/questions/50554304/displaying-extra-variables-in-tooltips-echarts4r).

**Comment by szmsu2011** [comment]
Hi.

It seems that the solution only allows the passing of one additional variable to the chart for displaying in the tooltip.
Is there a way to display, for example, all variables in the data passed to the chart in the tooltip?

**Comment by swsoyee** [comment]
@szmsu2011  https://github.com/JohnCoene/echarts4r/issues/287#issuecomment-795350351 it would be helpful.

**Comment by szmsu2011** [comment]
> @szmsu2011 [#287 (comment)](https://github.com/JohnCoene/echarts4r/issues/287#issuecomment-795350351) This would be helpful.

Thanks for the reply. In such a way, only the variables passed to the chart for plotting, e.g., x, y, z, size, color, ..., are shown as params in the console. Is there a way to pass redundant variables to the chart just for the tooltip display?

Thanks.

**Comment by swsoyee** [comment]
I don't know if there is a more general way to complete this task, but I could provide a tricky way to make it possible.

1. Join all information by a separator you want to use in tooltip to the label column.
2. [Display label by JavaScript function (split the label)](https://github.com/swsoyee/2019-ncov-japan/blob/master/03_Components/Network/Network.R#L210-L233)
3. [Display tooltip by another JavaScript function (split the label and use the remain information)](https://github.com/swsoyee/2019-ncov-japan/blob/master/03_Components/Network/Network.R#L257-LL279)

<img width="351" alt="截屏2021-04-07 22 08 14" src="https://user-images.githubusercontent.com/20528423/113871364-c7cbd600-97ed-11eb-8f48-a3adb873815a.png">

**Comment by tyluRp** [comment]
It looks like `bind` parameter is only available for scatter plots. Is this true? Can we bind data to other graphs like `e_graph_nodes()`?

**Comment by JohnCoene** [comment]
It should always be possible to add additional data with `e_add`, see https://github.com/JohnCoene/echarts4r/issues/146#issuecomment-871160283

**Comment by tyluRp** [comment]
Thanks @JohnCoene! Exactly what I was looking for.

**Comment by tyluRp** [comment]
Looks like I spoke to soon, I don't think `e_add` is working as expected when plotting network graphs, see https://github.com/JohnCoene/echarts4r/issues/146#issuecomment-887124656

**Comment by JohnCoene** [comment]
@tyluRp Do you have an example of you are trying to achieve so I can look into it
