### ISSUE TITLE
e_treemap font color

### ISSUE THREAD

**Issue by nschwamm** [JohnCoene/echarts4r#112]
I'm trying to set a custom theme for the treemap - and I can't change the font color. For normal line charts and what not - you can edit the label color with markTextColor within e_theme_custom; but that does not work for e_treemap.

Any help would be great!

**Comment by helgasoft** [comment]
How about some code?  Here is an example:
```r
df <- data.frame(
 parent = c("earth", "earth", "earth", "mars", "mars"), 
 child = c("forest", "ocean", "iceberg", "elon", "curiosity"),
 value = ceiling(rnorm(5, 10, 2))
)
df %>% e_charts() %>%
 e_treemap(parent, child, value, 
           label=list(color='yellow'), 
           upperLabel=list(show=TRUE, color='blue'))
```

**Comment by nschwamm** [comment]
@helgasoft - that's exactly the solution I was looking for! Thank you!
