### ISSUE TITLE
How to use dayLabel.firstDay in e_calendar?

### ISSUE THREAD

**Issue by xavidp** [JohnCoene/echarts4r#115]
How can we change the first day of the week displayed in the e_calendar?
According to echarts, it should be something related to:  `dayLabel.firstDay`
https://echarts.apache.org/en/option.html#calendar.dayLabel.firstDay

However, I don't seem to be able to find the right syntax to make it work in echarts4r (in case it's implemented, ported, exposed, or whatever thing it's needed to let it work also in echarts4r)

Any clue?

Example of code I used:

```r
df %>% 
  e_charts(event_date) %>% 
  e_calendar(range = c("2019-04", "2019-09"), dayLabel.firstDay=1) %>% 
  e_heatmap(x, coord_system = "calendar") %>% 
  e_visual_map(max = max(df$x),
               min = min(df$x)) %>% 
  e_title("Calendar", "Heatmap")

```

**Comment by JohnCoene** [comment]
I don't have the data in the `df` object so I cannot reproduce. Normally it should be.

```r
df %>% 
  e_charts(event_date) %>% 
  e_calendar(range = c("2019-04", "2019-09"), dayLabel = list(firstDay=1)) %>% 
  e_heatmap(x, coord_system = "calendar") %>% 
  e_visual_map(max = max(df$x),
               min = min(df$x)) %>% 
  e_title("Calendar", "Heatmap")
```

Does that work?

**Comment by xavidp** [comment]
thanks, it works like a charm! (now I see, convert to list ...).

**Comment by JohnCoene** [comment]
Yes, I have a short description of that [here](https://echarts4r.john-coene.com/articles/get_started.html#navigate-options)
