### ISSUE TITLE
HI,Would you catch the leaflet`s click events to put the chart on the map?

### ISSUE THREAD

**Issue by woshiliyuchun** [JohnCoene/echarts4r#117]
When I click on a node on the map, the data chart information of that node will be displayed. Thanks for your help

**Comment by JohnCoene** [comment]
You mean you want to click on a [leaflet](https://rstudio.github.io/leaflet/) and want the respective echarts4r graph to show?

**Comment by woshiliyuchun** [comment]
> You mean you want to click on a [leaflet](https://rstudio.github.io/leaflet/) and want the respective echarts4r graph to show?

Yes! That`s what i mean.Do you have any solutions？
Very grateful for your reply

**Comment by JohnCoene** [comment]
Something like this should work. You can pick up the marker clicked with `id_marker_click`.

```r
library(shiny)
library(leaflet)
library(echarts4r)

ui <- fluidPage(
  h3("Click on a marker"),
  fluidRow(
    column(6, leafletOutput("leaf")),
    column(6, echarts4rOutput("echart"))
  )
)

server <- function(input, output){

  data(quakes)

  output$leaf <- renderLeaflet({
    leaflet(data = quakes[1:20,]) %>% addTiles() %>%
      addMarkers(~long, ~lat, popup = ~as.character(mag), label = ~as.character(mag))
  })

  dataset <- eventReactive(input$leaf_marker_click, {
    data.frame(
      x = 1:10,
      y = runif(10)
    )
  })

  output$echart <- renderEcharts4r({
    dataset() %>% 
      e_chart(x) %>% 
      e_line(y)
  })

}

shinyApp(ui, server)
```

Is that what you were after?

**Comment by woshiliyuchun** [comment]
his seems to suit my needs very well. I'll repeat it myself. Thanks again

**Comment by woshiliyuchun** [comment]
this seems to suit my needs very well. I'll repeat it myself. Thanks again

**Comment by JohnCoene** [comment]
Great! Don't hesitate to open other issues if you need help :)

**Comment by JohnCoene** [comment]
Note that you can also pick up which element is clicked in echarts4r, see [Shiny docs](https://echarts4r.john-coene.com/articles/shiny.html#callbacks)

**Comment by woshiliyuchun** [comment]
Yes, I will try them all

**Comment by woshiliyuchun** [comment]
HI，JohnCoene,
I have run it again, I successfully ran it by my own dataset and took it over, and the map location on the left is shown correctly. However, there is one problem, which is that the chart on the right corresponding to each location node is the same figure. I feel that there is no connection between longitude, latitude or location name and the image on the right.
Ask for your help,thanks for reply

**Comment by JohnCoene** [comment]
我看不懂但是我会说有点中文，写中文吧 :)

**Comment by woshiliyuchun** [comment]
LOL.I’m sorry for my poor English.
我的问题是:如何才能使得我制作的数据图表和左侧点击的地图位置一一对应

**Comment by JohnCoene** [comment]
不好意色我的中文不够好。:(

Is this better?

```r
library(dplyr)
library(shiny)
library(leaflet)
library(echarts4r)

ui <- fluidPage(
  h3("Click on a marker"),
  fluidRow(
    column(6, leafletOutput("leaf")),
    column(6, echarts4rOutput("echart"))
  )
)

server <- function(input, output){

  data(quakes)

  # use layerId
  output$leaf <- renderLeaflet({
    leaflet(data = quakes[1:20,]) %>% addTiles() %>%
      addMarkers(
        ~long, ~lat, 
        popup = ~as.character(mag), 
        label = ~as.character(mag),
        layerId = ~as.character(stations)
      )
  })

  dataset <- eventReactive(input$leaf_marker_click, {
    quakes %>% 
      filter(stations == input$leaf_marker_click$id)
  })

  output$echart <- renderEcharts4r({
    station <- unique(dataset()$stations)
    title <- paste("是", station, "站")

    dataset() %>% 
      e_chart(depth) %>% 
      e_line(mag) %>% 
      e_title(title)
  })

}

shinyApp(ui, server)
```

**Comment by woshiliyuchun** [comment]
i like `id` .This is a perfect solution to my question. Thank you.
I think your Chinese is better than my English :)
