### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by RB000** [JohnCoene/echarts4r#12]
Hello
is it possible to add text or labels from another variable to some charts ! And how to add caption under the plot !

**Comment by JohnCoene** [comment]
You can add a title like so:

```r
mtcars %>%
  e_charts(mpg) %>%
  e_line(qsec) %>%
  e_title("My Title", "subtext", "www.link.com", "www.sublink.com")
```
There are many more options to be passed to `e_title`, they are listed in the [official documentation](https://ecomfe.github.io/echarts-doc/public/en/option.html#title).

For instance:

```r
mtcars %>%
  e_charts(mpg) %>%
  e_line(qsec) %>%
  e_title("My Title", bottom = 10) # place at the bottom
```
You can show labels like so:

```r
mtcars %>%
  e_charts(mpg) %>%
  e_line(qsec, label = list(normal = list(show = TRUE))) 
```

Then again more options in the official documentation, [here](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.label) are the options for `e_line` (it's likely the same for all series).

Feel free to re-open if it does not have the intended effect.

**Comment by JohnCoene** [comment]
In the dev version (`1.2.0`), you can now simply.

```r
mtcars %>%
    e_charts(mpg) %>%
    e_line(qsec) %>% 
    e_labels()
```
