### ISSUE TITLE
Problems in e_x_axis with e_boxplot

### ISSUE THREAD

**Issue by jlejarraga** [JohnCoene/echarts4r#123]
Hi John,

Thank you for this package, I really love it. Only one minor thing:

I can not plot a e_boxplot trying to rotate the x_axis_Label with: 
      e_x_axis(axisLabel = list(fontSize = 9, rotate = 45))
But I can rotate x_axis_Label in e_barplot usiong the same function. Below, i have illustrated an example which explain easier the issue:

1) With the following code, I cannot plot the boxplot (Error in FUN(X[[i]], ...) :  'options' must be a fully named list, or have no names (NULL)).

```r
mtcars %>% 
  group_by(row.names(mtcars)) %>%
  e_charts() %>% 
  e_boxplot(serie = disp, outliers = FALSE) %>% 
  e_y_axis(axisLabel = list(fontSize = 7)) %>% 
  e_x_axis(axisLabel = list(fontSize = 9, rotate = 45))
```

2) With the following correction, I can plot perfectly the boxplot, rotating the x_axis_labels

```r
x <- mtcars %>% 
  group_by(row.names(mtcars)) %>% 
  e_charts() %>% 
  e_boxplot(serie = disp, outliers = FALSE) %>% 
  e_y_axis(axisLabel = list(fontSize = 7))

y <- x$x$opts$xAxis
x$x$opts$xAxis <- list()
x$x$opts$xAxis[[1]] <- y

x %>% 
  e_x_axis(axisLabel = list(fontSize = 9, rotate = 45))
```
Could you check the code for this specific function?

Thank you in advance,
regards, 
JLC

**Comment by JohnCoene** [comment]
Thanks for the bug report and the time you spent looking into this. I'll fix this soon!

**Comment by JohnCoene** [comment]
Thanks again! I just pushed a fix. Feel free to re-open if it does not work for you
