### ISSUE TITLE
Order of data with e_line

### ISSUE THREAD

**Issue by vacon04** [JohnCoene/echarts4r#126]
Hello! Thank you for the wrapper for echarts, things are looking great.

I noticed that when I try to plot certain X and Y values, the chart reorders the data, so that lower X values are always plotted before higher X values.

For example, if I try to plot
```
data.frame(x = c(20, 50, 40),
           y = c(120, 200, 50)) %>% 
    e_charts(x) %>%
    e_line(y) 
```

I get the following 
![Rplot](https://user-images.githubusercontent.com/7259598/74337590-92089a00-4d6e-11ea-911a-c3fb43b77651.jpeg)

However, when I see a plot with the same data at the echarts site [https://www.echartsjs.com/examples/en/editor.html?c=line-in-cartesian-coordinate-system](url) you can see that the chart is different.
![image](https://user-images.githubusercontent.com/7259598/74337737-e01d9d80-4d6e-11ea-8bdb-7ab9a2054ac8.png)

Basically, the chart done natively with JS follows the order of the data, while the chart done with the R wrapper reorders the data. This is confirmed by inspecting the resulting code:

```
> data.frame(x = c(20, 50, 40),
+            y = c(120, 200, 50)) %>% 
+     e_charts(x) %>%
+     e_line(y) %>% 
+     e_inspect(
+         json = TRUE,
+         pretty = TRUE
+     )
{
  "yAxis": [
    {
      "show": true
    }
  ],
  "xAxis": [
    {
      "type": "value"
    }
  ],
  "legend": {
    "data": [
      "y"
    ]
  },
  "series": [
    {
      "data": [
        {
          "value": [20, 120]
        },
        {
          "value": [40, 50]
        },
        {
          "value": [50, 200]
        }
      ],
      "yAxisIndex": 0,
      "xAxisIndex": 0,
      "name": "y",
      "type": "line",
      "coordinateSystem": "cartesian2d"
    }
  ]
} 
```

Is there a way to override this type of behaviour? Thank you!

**Comment by JohnCoene** [comment]
I had not anticipated people needing to do this.

I have just added a `reorder` argument to the `e_charts` function to address this, reinstall the Github version.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/echarts4r")
```

```r
data.frame(
    x = c(20, 50, 40),
    y = c(120, 200, 50)
  ) %>% 
  e_charts(x, reorder = FALSE) %>%
  e_line(y)
```

Let me know if this works.

**Comment by vacon04** [comment]
Perfect, it works as expected. That was a crazy quick response, thank you very much for your help.

**Comment by JohnCoene** [comment]
Thank you for submitting this please don't hesitate to share any other issue you run into.
