### ISSUE TITLE
How to draw a timeline map with markPoint

### ISSUE THREAD

**Issue by swsoyee** [JohnCoene/echarts4r#135]
Hi, John, I'm very love your work of this package!
And I have a problem about how to draw some mark point on a dynamics map with timeline.

Here is my code:
https://github.com/swsoyee/2019-ncov-japan/blob/master/Components/ComfiredMap.R#L4-L75

and now I was able to draw dynamics titles on the plot:
![map](https://user-images.githubusercontent.com/20528423/76425486-0cb7ea00-63ed-11ea-9342-208f10c2bd99.gif)

```R
# Create title list
  timeSeriesTitle <- lapply(seq_along(byDate$date), function(i) {
    return(
      list(
        text = byDate$date[[i]],
        subtext = paste0('各都道府県合計新規', newByDate[[i]], '人')
      )
    )
  })

...
# Add to the plot
    e_timeline_serie(
      title = timeSeriesTitle
    )
```

Now I want to add a mark (popup is the best) on each province with the infected increase number by each day, and could you give me some advises? Because I can't find out any example for this type of plot on the internet.

Thank you very much.

**Comment by JohnCoene** [comment]
Looks really neat! Hope I get to see the final product!

So you're pushing echarts4r and ECharts.js to its limit but it's doable. There is a "graphics API" but it's very clunky and I would advise using it. In the official examples I have seen they use the title to do so, just like you did with the dates because you can have multiple titles in echarts4r.

Reinstall the package and use `e_timeline_serie` with the *new* `index` argument where 1 is the first title and 2 is the second title.

```r
library(echarts4r)

mtcars %>% 
  group_by(cyl) %>% 
  e_charts(qsec, timeline = T) %>% 
  e_scatter(mpg) %>% 
  e_timeline_serie(
    title = list(
      list(text = "A"),
      list(text = "B"),
      list(text = "C")
    ),
    index = 1 # first title
  ) %>% 
  e_timeline_serie(
    title = list(
      list(text = "X", right = 20, top = 50),
      list(text = "Y", right = 20, bottom = 30),
      list(text = "Z", right = 20, top = 60)
    ),
    index = 2 # second title
  )
```
![echarts_multi_title](https://user-images.githubusercontent.com/7833796/76432678-977bf300-63b3-11ea-9b0f-64734c89d054.gif)

Let me know if that works for you

**Comment by swsoyee** [comment]
Thank you for your quick response!
I will have a try later (in about 8 hours later).

And I still have some question:
1. Using the second `title` will achieve my goal, but now it only provide the options of `right`, `top` and so on? can I use the lat or lng options to pin the `title` to it's correct position? I'm afraid that when the user zoom in or move the map, the x and y may not be add to the right position (I will test it tonight).
2. Except `title` and `index`, do you have some plan to add more options in `e_timeline_serie` function to draw more useful plot? Just like this:
> image cite from [here](https://www.eneba.com/steam-plague-inc-evolved-steam-key-global)
![image](https://user-images.githubusercontent.com/20528423/76480756-03f9ff00-6453-11ea-803a-d4ec8a2b8427.png)

Add some marks on the map, with the time goes by the popup will be shown or hidden. 

Thank you for those excellent R packages which are made by your and your team!
And your https://github.com/JohnCoene/coronavirus work inspire me so much, too!

**Comment by JohnCoene** [comment]
ECharts.js is capable of doing it. My issue is the API I provide to the user. I still have not come up with a convenient way of handling this, particularly in those instances where the underlying JavaScript library is iteself convoluted.

However, I just pushed a new function `e_timeline_on_serie` allows you to add stuff to each serie by timeline step. So this enables mark point but on timeline.

Beware, as I mentioned, it makes from one hell of a mess: [more docs](https://echarts.apache.org/en/option.html#series-map.markPoint)

```r
library(dplyr)
library(echarts4r)
library(echarts4r.maps)

df <- USArrests

points <- list(
  list(
    data = list(
      list(coord = list(-100, 41)),
      list(coord = list(-95, 33))
    ),
    itemStyle = list(color = "#6cf"),
    symbol = 'pin'
  ),
  list(), # skip
  list(
    data = list(
      list(coord = list(-97, 32))
    ),
    itemStyle = list(color = "#6cf"),
    symbol = 'pin'
  )
)


# scale 0 to 1
.scl <- function(x){
    (x - min(x)) / (max(x) - min(x))
}

df %>% 
  mutate(
      State = row.names(.),
      Rape = .scl(Rape),
      Murder = .scl(Murder),
      Assault = .scl(Assault)
  ) %>% 
  select(State, Rape, Murder, Assault) %>% 
  group_by(State) %>% 
  tidyr::gather("Key",  "Value", Murder, Rape, Assault) %>% 
  group_by(Key) %>% 
  e_charts(State, timeline = TRUE) %>% 
  em_map("USA") %>% 
  e_map(Value, map = "USA") %>% 
  e_visual_map(min = 0, max = 1) %>% 
  e_timeline_opts(autoPlay = TRUE) %>% 
  e_timeline_serie(
    title = list(
      list(text = "Assault", subtext = "Percentage based on arrests"),
      list(text = "Murder", subtext = "Percentage based on arrests"),
      list(text = "Rape", subtext = "Percentage based on arrests")
    )
  ) %>% 
  e_timeline_on_serie(
    markPoint = points,
    serie_index = 1
  )
```

![echart_tl](https://user-images.githubusercontent.com/7833796/76575841-b0be9580-64c0-11ea-87df-f5aeca43a014.gif)

If any idea of how to make this convenient comes to mind please share so I can implement, issue is not technical but aesthetics

**Comment by swsoyee** [comment]
Thank you John, I have made the plot last night by the `index` option you provided.
![image](https://user-images.githubusercontent.com/20528423/76579554-05d5c800-6510-11ea-9474-0641f6f7b1fe.png)

As I mentioned in the last reply,  it's a little bit hard to mark the right position by `x` and `y`. And when the user move our zoom in or out, the `title` will not change it's position (absolutely).

I will try the new function you provide and make a feedback as soon as possible.

**Comment by swsoyee** [comment]
Hi John, thank you for your kindness help, and I finally made it!

![Kapture 2020-03-14 at 0 03 21](https://user-images.githubusercontent.com/20528423/76633971-ec249700-6588-11ea-917d-166bfb5ed319.gif)

**Comment by JohnCoene** [comment]
It looks gorgeous, nice work! You should submit it in the Shiny Contest if you haven't yet :) [Contest](https://community.rstudio.com/t/shiny-contest-2020-is-here/51002)

**Comment by JohnCoene** [comment]
I saw you submitted your application to the contest, nicely done. Please feel free to share any thought on the "timeline API". I know it's convoluted and I'm looking to simplify that but I'm unsure how. If you have any thought please feel free to share them with me here or @ jcoenep[at]gmail.com :)

**Comment by swsoyee** [comment]
Thank you John, I will keep going to think a simple way to write some timeline series, and if I have some new idea, I will share with you as soon as possible.
I think the usage of `e_timeline_on_serie` quite easy to understand and easy to control with the help of official documents, although it also need some loop function to create the timeline series. 
Using a table contains all options as input for generation may be a more easy to use? But I'm not sure about that.

**Comment by JohnCoene** [comment]
You should submit: https://2020.erum.io/covidr-contest/

**Comment by swsoyee** [comment]
@JohnCoene Thank you John! I have followed you and already knew the contest! I have created an issue in that repo but they only accepted those apps which have English version😂, and I'm pushing myself to do a localization. Maybe the English version will be released in several days.

**Comment by JohnCoene** [comment]
Well, sorry to hear this: they should really accept other languages! I hope you manage to translate it, your app is one of the best :)

**Comment by vyomdirt** [comment]
Hey @swsoyee , can you share the code you used to mark those points on the timeline chart?

Having some issues replicating it using `e_timeline_on_serie`

**Comment by swsoyee** [comment]
@vyomdirt 

https://github.com/swsoyee/2019-ncov-japan/blob/c66a17ce4a40795f225cf02f0437906027a13e3e/03_Components/Main/ConfirmedMap.server.R#L417-L419

It looks a bit complicated, the key point is to provide the correct data structure and then just add it in a loop.

**Comment by vyomdirt** [comment]
@swsoyee 

Thanks a lot, but I finally got it to work!

Thanks for your help.
