### ISSUE TITLE
Excluding a plugin

### ISSUE THREAD

**Issue by nteetor** [JohnCoene/echarts4r#136]
I've run into a situation where the included leaflet.js is interfering with {leaflet}'s included javascript files. Is there a standard way to exclude particular plugins when using the package?

**Comment by JohnCoene** [comment]
Had not thought of that. 

This should be fixed now. Would you mind reinstalling the Github version and trying again? echarts4r would use (if required) the dependencies as installed leaflet package.

**Comment by nteetor** [comment]
Awesome, thank you, John! I'll be able to test this out first thing tomorrow morning.

**Comment by nteetor** [comment]
The fix seems to have done the trick.

**Comment by JohnCoene** [comment]
Thanks, I'll go ahead and close. Feel free to open any other issue.
