### ISSUE TITLE
Change axis titles in e_scatter_3d

### ISSUE THREAD

**Issue by charlie86** [JohnCoene/echarts4r#143]
Hi, do you know if it's possible to override the default labels of "X", "Y", and "Z"? I see it done [here](https://echarts.apache.org/examples/en/editor.html?c=scatter3d&gl=1&theme=dark) but can't figure out how to do it in R.

**Comment by JohnCoene** [comment]
You can do it with the axis functions, use those ending in 3d.

```r
df <- data.frame(
  x = 1:100,
  y = runif(100, 10, 25),
  z = rnorm(100, 100, 50)
)

df %>% 
  e_charts(x) %>% 
  e_line_3d(y, z, smooth = TRUE) %>% 
  e_visual_map() %>%
  e_x_axis_3d(name="Hello") %>%
  e_y_axis_3d(name="World") %>%
  e_z_axis_3d(name="ZZZ")
```

**Comment by charlie86** [comment]
amazing, thank you for the super quick response!
