### ISSUE TITLE
Bind series to e_map

### ISSUE THREAD

**Issue by vacon04** [JohnCoene/echarts4r#146]
Is there a way to bind more series to e_map? The idea is not to display them in the actual visual map, but to use those values in the tooltip.

```R
> df <- data.frame(
+     region = c("Rajasthan", "Odisha", "Gujarat"), 
+     value = c(1,2, 3),
+     value_2 = c(4, 5, 6)
+ )
> 
> df %>% 
+     e_charts(region) %>%
+     em_map("India") %>% 
+     e_map(value, map = "India") %>% 
+     e_visual_map(value, bind = value_2) %>% 
+     e_theme("infographic") %>% 
+     e_inspect()
Error in e_visual_map_(e, serie, calculable, type, scale, ...) : 
  object 'value_2' not found
```

I know that the error actually says "serie", as in a single one, but is there a way to send this new element to the next step so that it can be used on the tooltip?

Thanks!

**Comment by JohnCoene** [comment]
Apologies for the late response. It's currently not possible but something I will look into for the next release. Thank you.

**Comment by JohnCoene** [comment]
Very sorry, I've looked into this and it's unfortunately not possible. `bind` maps to `name` internally and this is already in use by the `map` serie.

Apologies for this.

**Comment by jordancampbell23** [comment]
Hi John,

I just wanted to double check that it is not possible to reference other columns/variables than the one being mapped in the tooltip.

-Jordan

**Comment by JohnCoene** [comment]
It does not make for great code but this works.

```r
library(echarts4r)

cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100),
  tooltip = sample(letters, length(cns), replace = TRUE)
)

cns |> 
  e_charts(country) |> 
  e_map(value) |> 
  e_visual_map(value) |> 
  e_add('extra', tooltip) |> 
  e_tooltip(
    formatter = htmlwidgets::JS(
      'function(params){
        return "<span>" + params.data.extra.tooltip + "</span>";
      }'
    )
  )
```

**Comment by jordancampbell23** [comment]
That works great, thanks for adding that functionality!

**Comment by tyluRp** [comment]
Note that this doesn't seem to work with network graph type plots:
```r
library(echarts4r)

value <- rnorm(10, 10, 2)

nodes <- data.frame(
  name = sample(LETTERS, 10),
  value = value,
  size = value,
  tooltip = "foo",
  stringsAsFactors = FALSE
)

edges <- data.frame(
  source = sample(nodes$name, 20, replace = TRUE),
  target = sample(nodes$name, 20, replace = TRUE),
  stringsAsFactors = FALSE
)

e_charts() |> 
  e_graph() |> 
  e_graph_nodes(nodes, name, value, size) |> 
  e_graph_edges(edges, source, target) |> 
  e_add('extra', tooltip) |> 
  e_tooltip(
    formatter = htmlwidgets::JS(
      'function(params){
        return "<span>" + params.data.extra.tooltip + "</span>";
      }'
    )
  )
```

**Comment by JohnCoene** [comment]
OK, I see the issue. Internally `e_add` uses the data passed to `e_charts` but none is passed in case; hence it does not work.

I've just added the `.data` argument to `e_add`.

```r
e_charts() |> 
  e_graph() |> 
  e_graph_nodes(nodes, name, value, size) |> 
  e_graph_edges(edges, source, target) |> 
  e_add('extra', tooltip, .data = nodes) |> 
  e_tooltip(
    trigger = "item",
    formatter = htmlwidgets::JS(
      'function(params){
        return "<span>" + params.data.extra.tooltip + "</span>";
      }'
    )
  )
```

Let me know if this works

**Comment by tyluRp** [comment]
Thanks! However, with:

```r
library(echarts4r)

value <- rnorm(10, 10, 2)

nodes <- data.frame(
  name = sample(LETTERS, 10),
  value = value,
  size = value,
  tooltip = "foo",
  stringsAsFactors = FALSE
)

edges <- data.frame(
  source = sample(nodes$name, 20, replace = TRUE),
  target = sample(nodes$name, 20, replace = TRUE),
  stringsAsFactors = FALSE
)

e_charts() |> 
  e_graph() |> 
  e_graph_nodes(nodes, name, value, size) |> 
  e_graph_edges(edges, source, target) |> 
  e_add('extra', tooltip, .data = nodes) |> 
  e_tooltip(
    trigger = "item",
    formatter = htmlwidgets::JS(
      'function(params){
        return "<span>" + params.data.extra.tooltip + "</span>";
      }'
    )
  )
```

I do not see the tooltip, but I do see this:

```
Uncaught TypeError: Cannot read property 'tooltip' of undefined
    at eval (eval at tryEval (htmlwidgets.js:252), <anonymous>:2:45)
    at e._showTooltipContent (echarts-en.min.js:45)
    at e.<anonymous> (echarts-en.min.js:45)
    at e._showOrMove (echarts-en.min.js:45)
    at e._showSeriesItemTooltip (echarts-en.min.js:45)
    at e._tryShow (echarts-en.min.js:45)
    at e.<anonymous> (echarts-en.min.js:45)
    at XO (echarts-en.min.js:45)
    at echarts-en.min.js:35
    at echarts-en.min.js:45
```

Are these types of graphs a bit different when it comes to `e_add` since there are 2 datasets being passed instead of 1?

**Comment by JohnCoene** [comment]
Sorry, I just added this argument, it will need reinstalling the latest version. https://github.com/JohnCoene/echarts4r/commit/aeefc417e0b8b4de15b352016670a27867c004ff

It does reveal the tooltip on my end, you will still see errors when hovering edges. Do you need custom tooltip on them too? Happy to add it, I just don't know how to nicely implement this

**Comment by tyluRp** [comment]
Ah, it's working on my end with the development version! Thank you! For the edges, I don't have an immediate use case for it. I am really just interested in adding additional information to the tooltip when hovering over the nodes.
