### ISSUE TITLE
Suggests instead of Depends: R (>= 3.4.2)?

### ISSUE THREAD

**Issue by happyshows** [JohnCoene/echarts4r#15]
Hi,

I'm running on an earlier subversion of 3.4, and I'm pretty sure there will be a couple like my case. Could you change the depends to suggests so that we won't have to upgrade R to try out the package?
Thanks.

**Comment by JohnCoene** [comment]
Sorry it took so long; you can reinstall directly from github, bitbucket or coding,net now.

```r
# install.packages("devtools")
devtools::install_github("JohnCoene/echarts4r") # github
devtools::install_bitbucket("JohnCoene/echarts4r") # bitbucket
devtools::install_git("https://git.coding.net/JohnCoene/echarts4r.git") # coding.net
```
