### ISSUE TITLE
enhancement: chart alignment 

### ISSUE THREAD

**Issue by dmaupin12** [JohnCoene/echarts4r#150]
I was wondering if there is a way to right align plots within a shinymobile f7card. On my phone when the y axis figures are larger than three 000s (ie 1,000), the numbers get cut off. Having the ability to align the figure right might help show the figures. Really great package!

**Comment by JohnCoene** [comment]
Thank you.

I hope to further develop [mobileCharts](https://github.com/Rinterface/mobileCharts) to work specifically with shinyMobile but it's still early in development and lacks many of the features of echarts4r.

In echarts4r, you can pad the grid to allow more space for the labels.

```r
cars %>%
  e_charts(speed) %>%
  e_scatter(dist) %>%
  e_grid(
    left = 200 # pixels
    top = "15%" # percentage = responsive
  )
```

I hope this helps :+1:

**Comment by dmaupin12** [comment]
Appreciate the followup and mobileCharts looks promising as well!
