### ISSUE TITLE
how to set Gradient areaColor in e_geo

### ISSUE THREAD

**Issue by shitongbin** [JohnCoene/echarts4r#151]
In the api,geo part ,I found the Gradient areaColor set like color: {
    type: 'radial',
    x: 0.5,
    y: 0.5,
    r: 0.5,
    colorStops: [{
        offset: 0, color: 'red' // color at 0% position
    }, {
        offset: 1, color: 'blue' // color at 100% position
    }],
    global: false // false by default
},
colorStops set with Square brackets and big parantheses，how to trans this in R，I set this like  colorStops = c(list(offset = 0,color = 'rgba(147, 235, 248, 0)'),
                                                         list(offset = 1,color = 'rgba(147, 235, 248, .2)'),
                                                         globalCoord = FALSE) ，but it like not work.

**Comment by shitongbin** [comment]
maybe use list replace vector

**Comment by shitongbin** [comment]
`          colorStops = list(
            list(offset = 0, color = 'rgba(147, 235, 248, 0)'),
            list(offset = 1, color = 'rgba(147, 235, 248, .2)')
          )`  
Solved！！

**Comment by JohnCoene** [comment]
Yes indeed, these are nested list :)
