### ISSUE TITLE
Fliping coordinates doesn't work with e_error_bar()

### ISSUE THREAD

**Issue by yasminaadm** [JohnCoene/echarts4r#153]
Hello, 

I have the following issue when trying to flip an `e_error_bar()` 

``` 
df <- data.frame(
    x = factor(c(1, 2)),
    y = c(1, 5),
    upper = c(1.1, 5.3),
    lower = c(0.8, 4.6)
)

df %>%
    e_charts(x) %>%
    e_bar(y) %>%
    e_error_bar(lower, upper) 
```
![image](https://user-images.githubusercontent.com/64425708/80391402-f935e500-88ad-11ea-82a6-b8f0834daa55.png)

``` 

df %>%
    e_charts(x) %>%
    e_bar(y) %>%
    e_error_bar(lower, upper) %>% 
    e_flip_coords()
``` 
![image](https://user-images.githubusercontent.com/64425708/80391375-f0ddaa00-88ad-11ea-9900-2cc6189c5a75.png)

Regards,

Yasmina

**Comment by JohnCoene** [comment]
Hi Yasmina,

Thank you for reporting this.

This does indeed not work as the error bars are not native to echarts and use a custom renderer. I'll flag that and eventually look into it.

Apologies!

**Comment by helgasoft** [comment]
This fix is doable, but so time consuming and such a low priority, that I personally would wait for a financial sponsorship.

**Comment by barveaditya** [comment]
@helgasoft what do you mean when you say sponsorship? How much is it? I am new to this. :)

**Comment by helgasoft** [comment]
How much? - first estimate US$300.
Why "_low priority_"? Because one can easily chart hundreds of bars horizontally and display them nicely with _e_datazoom_. So I don't see the value of a vertical layout. But you can prove me wrong, eventually, with a really convincing use case...

**Comment by JohnCoene** [comment]
No no no, we don't charge for anything here! Please don't sell services here, even if it goes to an open-source project.
