### ISSUE TITLE
`e_bar_()` no longer working

### ISSUE THREAD

**Issue by jonmcalder** [JohnCoene/echarts4r#154]
Hi @JohnCoene! Thanks again for this great pkg - I love using it.

It appears `e_bar_()` was broken in the process of updating `echarts4rProxy` etc for version 0.3.

``` r
library(echarts4r)

mtcars %>% 
  e_chart(cyl) %>% 
  e_bar_("mpg")
#> Error in UseMethod("e_bar_"): no applicable method for 'e_bar_' applied to an object of class "c('echarts4r', 'htmlwidget')"
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JohnCoene** [comment]
Hi Jon,

Thanks for reporting. I just pushed a fix to Github: let me know if this works.

**Comment by jonmcalder** [comment]
Thank you for the quick fix 👍 

And sorry for my delayed response!
