### ISSUE TITLE
Map with 1 country color codes all countries

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/echarts4r#155]
When I group by countries and summarise the data, sometimes the data only has a single country and so I have data that looks like:

```r
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns[269, ]
#>           country    value
#> 269 United States 92.70658
```

However, when I try to plot it, all countries are color coded:

```r
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns[269,] %>% 
  e_charts(country) %>%
  e_map(value) %>% 
  e_visual_map(value)
```

You can bypass this if you add a dummy row, for example:

```r
cns[269,] %>% 
  bind_rows(
    data.frame(
      country = "placeholder", 
      value = 0
    )
  ) %>% 
  e_charts(country) %>%
  e_map(value) %>% 
  e_visual_map(value)
```

Is this expected behavior?

As always, awesome package, recently made the switch from plotly to echarts4r 👍

**Comment by JohnCoene** [comment]
Sorry I have not come back to you on this. I'm still looking for an elegant solution (internally)

**Comment by tyluRp** [comment]
Hi John -- No worries, I appreciate all your support :D
