### ISSUE TITLE
Does the `indicator` option work in `e_radar`?

### ISSUE THREAD

**Issue by swsoyee** [JohnCoene/echarts4r#156]
Hi, John,
I'm coming again😁, Thank you for your kindness reply every time.

I want to ask a simple question about `e_radar`. I want to set different max value for each axis in radar chart, and it seems that the `indicator` options may work.
https://echarts.apache.org/en/option.html#radar.indicator

But it's not working with my code.
Example:
```r
df <- data.frame(
  x = LETTERS[1:5],
  y = c(20, 1, 2, 3, 4)
)

df %>% 
  e_charts(x) %>%  
  e_radar(y, indicator = list(
    list(name = "A", max = 30),
    list(name = "B", max = 5),
    list(name = "C", max = 5),
    list(name = "D", max = 5),
    list(name = "E", max = 5)
  )) %>% 
  e_tooltip(trigger = "item")
```

Is the option supported now?
Thank you!

**Comment by swsoyee** [comment]
Okay, I find the solution... Using `e_radar_opts` will achieved it. 
(Maybe consider add more examples in documentation page?)

```r
df <- data.frame(
  x = LETTERS[1:5],
  y = c(20, 1, 2, 3, 4)
)

df %>%
  e_charts(x) %>%
  e_radar(y) %>%
  e_radar_opts(
    indicator = list(
    list(name = "A", max = 30),
    list(name = "B", max = 5),
    list(name = "C", max = 5),
    list(name = "D", max = 5),
    list(name = "E", max = 5)
  )) %>%
  e_tooltip(trigger = "item")
```

**Comment by albatross11** [comment]
also works for me ,thanks  bro
