### ISSUE TITLE
Ho To Change Font Of e_liquid() Chart ? e_grid is Also Not working. Graphs size is not increasing and Its not fit in Box or Column

### ISSUE THREAD

**Issue by kmaheshkulkarni** [JohnCoene/echarts4r#157]
> ### When the Numbers are more than 5 Digit then it's not fitted in graph

```
value<- 12345.67
liquid <- data.frame(name= c(value, 0.5, 0.4, 0.2), color = c("#ffc107", "#195030"))
liquid %>% 
              e_charts() %>% 
              e_liquid(
                serie = name, 
                color = color,
                label = list(
                  formatter = "{c}"
                )
              ) %>%
              e_title("Delta Paint Consumption", "Paint Volume in CC")%>%
              e_grid(width = "100%", left = "70%")
```
![echart](https://user-images.githubusercontent.com/18054137/81909401-2d1c4480-95e8-11ea-8ce7-53a2efa7f807.png)

**Comment by JohnCoene** [comment]
Yes, you can define the `fontSize` of the `label`. The full list of options is [here](https://github.com/ecomfe/echarts-liquidfill#api)

```r
value<- 12345.67
liquid <- data.frame(name= c(value, 0.5, 0.4, 0.2), color = c("#ffc107", "#195030"))
liquid %>% 
  e_charts() %>% 
  e_liquid(
    serie = name, 
    color = color,
    label = list(
      fontSize = 30,
      formatter = "{c}"
    )
  ) %>%
  e_title("Delta Paint Consumption", "Paint Volume in CC")%>%
  e_grid(width = "100%", left = "70%")
```

Let me know if this works for you.

**Comment by kmaheshkulkarni** [comment]
> Yes, you can define the `fontSize` of the `label`. The full list of options is [here](https://github.com/ecomfe/echarts-liquidfill#api)
> 
> ```r
> value<- 12345.67
> liquid <- data.frame(name= c(value, 0.5, 0.4, 0.2), color = c("#ffc107", "#195030"))
> liquid %>% 
>   e_charts() %>% 
>   e_liquid(
>     serie = name, 
>     color = color,
>     label = list(
>       fontSize = 30,
>       formatter = "{c}"
>     )
>   ) %>%
>   e_title("Delta Paint Consumption", "Paint Volume in CC")%>%
>   e_grid(width = "100%", left = "70%")
> ```
> 
> Let me know if this works for you.

Hi @JohnCoene Its working for me right now.
But Question is Graph is not fitting in Box or Column.
Its Alignment goes wrong. You Can See in Picture Where the Title started from Left corner
and Graph Started from middle.
So How Can we Manage. ?
Even e_grid() is not working properly when I increase or decreasing Size of Chart

**Comment by JohnCoene** [comment]
I'm not sure I understand the issue, the graph is neatly in the `DIV` and nothing overflows. What exactly do you want to do? What do you mean exactly by it's "not fitting in Box or Column"

**Comment by kmaheshkulkarni** [comment]
> I'm not sure I understand the issue, the graph is neatly in the `DIV` and nothing overflows. What exactly do you want to do? What do you mean exactly by it's "not fitting in Box or Column"

Hi @JohnCoene, Thanks for your Fast Reply,
I want to Say The Graph is not fits in Card Container.
I maximize the size of Graph But Its Not Fits Proper In Card Container.,
From Below Image You can see the Graph's alignment in Card which is not proper
If I maximize width of chart upto 600px then the chart is cross the Card's margin.
This code from UI side
I Use bs4Dash Package for this

```
bs4Card(width = 4, height = "450px", 
echarts4rOutput("TheoPaint", width = "500px") %>% withSpinner(color="#ffc107")),

bs4Card(width = 4, height = "450px",
echarts4rOutput("ActPaint", width = "500px")%>% withSpinner(color="#ffc107")),
               
bs4Card(width = 4, height = "450px", 
echarts4rOutput("Delta", width = "500px") %>% withSpinner(color="#ffc107"))
```

![box](https://user-images.githubusercontent.com/18054137/81939837-7c786a00-9614-11ea-94ff-aa2daef11091.png)

**Comment by zhiiiyang** [comment]
@kmaheshkulkarni, have you tried enabling `radius` to change the size of the ring?

```
liquid %>% 
  e_charts() %>% 
  e_liquid(
    serie = name, 
    color = color,
    label = list(
      fontSize = 30,
      formatter = "{c}"
    ),
   radius = "90%"
  ) 
```

**Comment by JohnCoene** [comment]
@kmaheshkulkarni looking at your code again, the issue is that you force echarts4r output to 500px. @zhiiiyang hints at the solution use `radius` instead.

**Comment by kmaheshkulkarni** [comment]
> Hello, @zhiiiyang Thanks for Support. Finally, It works Perfect.
> Thanks for Help also Thanks you @JohnCoene, I like your work
> Both are doing a great job in the R Open Source environment.
> I Hope in Future we will Do better.
