### ISSUE TITLE
renderUI and graph resizing

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/echarts4r#158]
I've ran into a bug where my graphs are no longer resizing, this seems to have happened when I switched from `echarts4rOutput` to `renderUI`. The only way I can get the graph to resize is if I switch to a different tab, slightly change the browser windows dimension, or inspect the element. See below for a reproducible example:

```r
library(shiny)
library(shinydashboard)
library(echarts4r)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      column(
        width = 3,
        box(
          width = 12,
          title = "stuff"
        )
      ),
      column(
        width = 9,
        tabsetPanel(
          tabPanel(
            title = "tab1",
            echarts4rOutput("chart1"),
            uiOutput("chart2")
          ),
          tabPanel(
            title = "tab2"
          )
        )
      )
    )
  )
)

server <- function(input, output) { 
  output$chart1 <- renderEcharts4r({
    data.frame(x = 0:1, y = 0) %>%
      e_charts(x) %>%
      e_scatter(y) %>%
      e_draft()
  })
  
  output$chart2 <- renderUI({
    tagList(
      data.frame(x = 0:1, y = 0) %>%
        e_charts(x) %>%
        e_scatter(y) %>%
        e_draft()
    )
  })
}

shinyApp(ui, server)
```

Once you hit the icon to collapse the sidebar, the graph that's rendered from `renderUI` does not resize automatically.

![image](https://user-images.githubusercontent.com/35909636/83207067-283ab300-a107-11ea-8ce4-0c074751262d.png)

**Comment by JohnCoene** [comment]
Hi Tyler,

I'm not sure this is a bug, without the correct render/output functions htmlwidgets cannot find the widget and execute "resize," below I do the same with plotly and observe the same effect.

```r
library(shiny)
library(plotly)
library(shinydashboard)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      column(
        width = 3,
        box(
          width = 12,
          title = "stuff"
        )
      ),
      column(
        width = 9,
        tabsetPanel(
          tabPanel(
            title = "tab1",
            echarts4rOutput("chart1"),
            uiOutput("chart2")
          ),
          tabPanel(
            title = "tab2"
          )
        )
      )
    )
  )
)

server <- function(input, output) { 
  output$chart1 <- renderEcharts4r({
    data.frame(x = 0:1, y = 0) %>%
      e_charts(x) %>%
      e_scatter(y) %>%
      e_draft()
  })
  
  output$chart2 <- renderUI({
    tagList(
      plot_ly(diamonds, x = ~cut)
    )
  })
}

shinyApp(ui, server)
```

I might be missing something, why do you want to use renderUI/uiOutput?

**Comment by tyluRp** [comment]
The reason I've switched to `renderUI()` is because I am using `lapply()` to render any number of graphs depending on user inputs. So for example, someone might select a country from a drop down and receive a country graph. Then the same user selects a region and both the country and region graph are rendered. 

Prior, I used the render/output functions for ever possible graph but this made graphs "stick" in one spot e.g. if I have 3 render/outputs (worldwide, country, region) and the user selects country and region the graphs will be render below a "missing" worldwide graph. With `renderUI()`, the graphs will be rendered together and at the top, no "sticky" position.

Below is kind of an example, though instead of drop downs, I've just added a slider:

```r
library(shiny)
library(shinydashboard)
library(echarts4r)
library(shinyWidgets)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      column(
        width = 3,
        box(
          width = 12,
          title = "Settings",
          sliderInput(
            inputId = "slider",
            label = "Slider",
            min = 1,
            max = 3,
            value = 1
          )
        )
      ),
      column(
        width = 9,
        tabsetPanel(
          tabPanel(
            title = "tab1",
            echarts4rOutput("chart1"),
            uiOutput("chart2")
          ),
          tabPanel(
            title = "tab2"
          )
        )
      )
    )
  )
)

server <- function(input, output) { 
  n <- reactive(input$slider)
  
  output$chart1 <- renderEcharts4r({
    data.frame(x = 0:1, y = 0) %>%
      e_charts(x) %>%
      e_scatter(y) %>%
      e_draft()
  })
  
  output$chart2 <- renderUI({
    lapply(1:n(), function(x) {
      tagList(
        data.frame(x = 0:1, y = 0) %>%
          e_charts(x) %>%
          e_scatter(y) %>%
          e_draft()
      )
    })
  })
}

shinyApp(ui, server)
```

If there is a better way to go about this, I am all ears. I am not sure if `lapply()` + `renderUI()` is good practice or not, but it's a trick I have been using for rendering lists whose lengths can change based on the user.

**Comment by JohnCoene** [comment]
In theory, this should be doable but would involve making custom shiny::renderXXX and corresponding XXXoutput functions, which I do not know much about I'm afraid. I will look into it.

In the meantime, here is how I tackle such issue, I'm not saying this is the right solution or elegant. It's using shinyjs to show/hide charts when needed.

```r
library(shiny)
library(shinyjs) # use shinjs
library(shinydashboard)
library(echarts4r)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    useShinyjs(), # import dependencies
    fluidRow(
      column(
        width = 3,
        box(
          width = 12,
          title = "Settings",
          sliderInput(
            inputId = "slider",
            label = "Slider",
            min = 1,
            max = 3,
            value = 1
          )
        )
      ),
      column(
        width = 9,
        tabsetPanel(
          tabPanel(
            title = "tab1",
            echarts4rOutput("world"),
            echarts4rOutput("country"),
            echarts4rOutput("region")
          ),
          tabPanel(
            title = "tab2"
          )
        )
      )
    )
  )
)

server <- function(input, output) { 
  n <- reactive(input$slider)

  # for convenience
  create_chart <- function(){
    data.frame(x = 1:10, y = runif(10)) %>%
      e_charts(x) %>%
      e_line(y)
  }

  # show hide charts at will
  observe({
    if(input$slider == 1){
      show("world")
      hide("country")
      hide("region")
    } else if(input$slider == 2){
      show("world")
      show("country")
      hide("region")
    } else if(input$slider == 3){
      show("world")
      show("country")
      show("region")
    }
  })
  
  # 3 charts out 
  output$world <- renderEcharts4r(create_chart())
  output$country <- renderEcharts4r(create_chart())
  output$region <- renderEcharts4r(create_chart())

}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
Hi Tyler, I know this is was not an ideal solution I suggested but I was wondering if it helped at all.

**Comment by tyluRp** [comment]
Hi John, apologies for the delay. This solution did work for us! A small reproducible example of what we plan to do:
```r
library(shiny)
library(shinyjs) # use shinjs
library(shinyWidgets)
library(shinydashboard)
library(echarts4r)

ui <- dashboardPage(
  dashboardHeader(),
  dashboardSidebar(),
  dashboardBody(
    useShinyjs(), # import dependencies
    fluidRow(
      column(
        width = 3,
        box(
          width = 12,
          title = "Settings",
          pickerInput(
            inputId = "locations",
            label = "Locations",
            choices = c("world", "country", "region"),
            multiple = TRUE,
            selected = ""
          )
        )
      ),
      column(
        width = 9,
        tabsetPanel(
          tabPanel(
            title = "tab1",
            echarts4rOutput("world"),
            echarts4rOutput("country"),
            echarts4rOutput("region")
          ),
          tabPanel(
            title = "tab2"
          )
        )
      )
    )
  )
)

server <- function(input, output) { 
  
  # for convenience
  create_chart <- function(title) {
    data.frame(x = 1:10, y = runif(10)) %>%
      e_charts(x) %>%
      e_line(y) %>% 
      e_title(title)
  }
  
  # show hide charts at will
  observe({
    choices <- c("world", "country", "region")
    
    lapply(choices, function(x) {
      if (x %in% input$locations)
        show(x)
      else
        hide(x)
    })
  })
  
  # 3 charts out 
  output$world <- renderEcharts4r(create_chart("Worldwide"))
  output$country <- renderEcharts4r(create_chart("Country"))
  output$region <- renderEcharts4r(create_chart("Region"))
  
}

shinyApp(ui, server)
```

Thanks for your help on this 👍

**Comment by JohnCoene** [comment]
I've been looking into providing a different `render*` and complimentary `*Output` functions but I'm afraid it's not going to be possible, htmlwidgets and shiny will then try to work off based on the `id` of said functions rather than that of the charts. Sorry for the late response it had me dig into the source code of both shiny and htmlwidgets for a while.

**Comment by tyluRp** [comment]
Hi John,

I learned the hard way that renderUI can result in laggy UI, then read:
> If you run this code yourself, you’ll notice that it takes a fraction of a second to appear after the app loads. That’s because it’s reactive: the app must load, trigger a reactive event, which calls the server function, yielding HTML to insert into the page. This is one of the downsides of renderUI(); relying on it too much can create a laggy UI. For good performance, strive to keep fixed as much of the user interface as possible, using the techniques described earlier in the chapter.

From https://mastering-shiny.org/action-dynamic.html.

So I ended up avoiding renderUI in the end, and as a result the resizing issue is no longer a problem for me. I am mostly just relying on show/hide logic like you had demonstrated.
