### ISSUE TITLE
@media print css behavior

### ISSUE THREAD

**Issue by sdmcallister** [JohnCoene/echarts4r#159]
Not sure if this is the right place to file this issue. The default image behaviour when printing to PDF from a browser can result in images to be split across pages which looks bad. To fix this I've added a snippet to my custom CSS file: 
```
@media print {
  div.echarts4r.html-widget.html-widget-static-bound { 
    page-break-inside: avoid;
  }
}
```
Can/should this be added as default behaviour?

**Comment by JohnCoene** [comment]
Hi Steve, that sounds like a good idea to me! Feel free to create a pull request, otherwise I can add it myself. Thanks you!

**Comment by JohnCoene** [comment]
Added that to the package, thanks again!
