### ISSUE TITLE
support svg render?

### ISSUE THREAD

**Issue by DongZhang1103** [JohnCoene/echarts4r#16]
Hi,
    I have 2 questions about echarts4r.
   1. How to export graph when use echarts4r pakage?
   2.If the picture is enlarged, it will become blurred; and if it is not enlarged, it is often not clear in the word. And Echarts support both svg and canvas now. Could you add svg render support for Echarts in echarts4r pkage?  

Thanks

**Comment by JohnCoene** [comment]
Answering your questions in reverse order,I have added the ability to render as `SVG`.

1. reinstall the package `devtools::install_github("JohnCoene/echarts4r")`
2. Set `renderer="svg"` in `e_charts`

Even using svg the visualisation requires the libraries (`<script></script>`) so I'm unsure it will help including them in Word document.

However, I see two options to include them in Word.

1. Open you visualisation in your browser, `echarts4r` default to will width and height of your screen so the resulting screen shot might be clearer. *If you're in RStudio, check the top of the Viewer, there's a button to open in browser.*
2. Use the built-in save as image tool, it might also return a clearer image.

```r
library(echarts4r)

USArrests %>% 
  e_charts(UrbanPop) %>% 
  e_line(Assault) %>% 
  e_toolbox_feature(feature = c("saveAsImage")) # adds ability to save plot as image in the top right
```

Normally you would not save the plot as an image, you would save the whole widget.

```r
# plot as object
USArrests %>% 
  e_charts(UrbanPop) %>% 
  e_line(Assault) -> plot

# save plot
htmlwidgets::saveWidget(plot, file = "plot.html")
```

Let me know if this is unclear, please close if this answers your question.

**Comment by DongZhang1103** [comment]
Thank you sou much. So great!

**Comment by ilona-grabowicz** [comment]
@JohnCoene Could you please add a functionality to be able to save the images?? For me it is a big disadvantage that these plots cannot be saved easily to png, for example. The png() -> plot -> dev.off() doesn't work either.

**Comment by JohnCoene** [comment]
These are interactive charts that are ultimately meant for HTML outputs and it's difficult to provide an automated/reproducible way to save them as PNG, there is [an old opened issue](https://github.com/ramnathv/htmlwidgets/issues/95) on htmlwidgets on the topic. I'm afraid webshot does not work properly with echarts4r so I?m out of solutions at this stage.

**Comment by rdatasculptor** [comment]
Webshot2 works like a charm.
