### ISSUE TITLE
Setting x axis intervals removes limits hoverable items in plot. 

### ISSUE THREAD

**Issue by rl627** [JohnCoene/echarts4r#160]
Hi,

When I set x axis type as "categorical" and specify interval some of the items/dots disappear from the plot (as seen int Plot 2 below). However, when I keep the x axis type as "value" the items are all visible. Is there any way to display all items/dots when x-axis is categorical with specified intervals?

code for these two plots are attached below.

![image](https://user-images.githubusercontent.com/45013044/84080912-fc42eb80-a9aa-11ea-899c-a7667b26acc6.png)

```r
## Simulate data
dfa =  tibble(x =rep(1:25,2),
              loc = c(rep("town A",25),rep("town B",25)),
              mean = c(rep(2,25),rep(20,25)),
              y = rnorm(50,mean,4))
## plot where x axis is 'value'
base_plot = dfa %>% 
  group_by(loc) %>% 
  e_charts(x) %>% 
  e_line(y, symbolSize =10,) 

## Plot 1: when x-axis type is value (Items/dots are all visible)
base_plot%>% e_x_axis(type = "value",
                      axisLabel = list(interval = 7))

##  Plot 1:  when x-axis type is categorical (Items/dots dissapear)
base_plot%>% e_x_axis(type = "category",
                      axisLabel = list(interval = 7))
```

**Comment by JohnCoene** [comment]
The argument `type` is available in echarts4r but should not really be used as the data and various aspects of the visualisation other than `type` need to change depending on whether `x` is categorical or not. 

Therefore, you should first make `x` categorical, then controlling label intervals as you do will work correctly (label intervals change but not symbols on line).

```r
library(echarts4r)

# simulate data
dfa <- tibble::tibble(
  x = rep(1:25, 2),
  loc = c(rep("town A", 25), rep("town B", 25)),
  mean = c(rep(2, 25), rep(20, 25)),
  y = rnorm(50, mean, 4)
)

# make categorical
dfa$x <- as.factor(dfa$x)

# base plot
p <- dfa %>% 
  group_by(loc) %>% 
  e_charts(x) %>% 
  e_line(y, symbolSize = 10)

# Control labels
p %>% 
  e_x_axis(
    axisLabel = list(
      interval = 0 
    )
  )

p %>% 
  e_x_axis(
    axisLabel = list(
      interval = 7
    )
  )
```

**Comment by rl627** [comment]
Thanks John, 


When I run the code you provided, the symbols on the line still disappear when interval = 7. However, I noticed that if I remove the "symbolSize = 10" in e_line() of the base plot then all the symbols on the line remain. 

```
p <- dfa %>% 
  group_by(loc) %>% 
  e_charts(x) %>% 
  #e_line(y, symbolSize = 10) %>% 
  e_line(y)

p %>% 
  e_x_axis(
    axisLabel = list(
      interval = 7
    )
  )
```
Is there a way to specify a symbolSize while having it work correctly (label intervals change but not symbols on line).


Thanks for all the help and great package!

**Comment by JohnCoene** [comment]
Strange, could you install the github version and chekc again? I do not see that even when I set the `symbolSize`, that might have been an issue fixed when I bumped echarts JavaScript version up.

```r
library(echarts4r)

# simulate data
dfa <- tibble::tibble(
  x = rep(1:25, 2),
  loc = c(rep("town A", 25), rep("town B", 25)),
  mean = c(rep(2, 25), rep(20, 25)),
  y = rnorm(50, mean, 4)
)

# make categorical
dfa$x <- as.factor(dfa$x)

# base plot
dfa %>% 
  group_by(loc) %>% 
  e_charts(x) %>% 
  e_line(y, symbolSize = 10) %>% 
  e_x_axis(
    axisLabel = list(
      interval = 7
    )
  )
```

![image](https://user-images.githubusercontent.com/7833796/84177131-bd806480-aa82-11ea-9bf3-75494bbf10d1.png)

**Comment by rl627** [comment]
I installed from github and reran, still the same issue. I tried updating R (4.0.1 now, it was 3.6.2), Rstudio, and other packages to no avail. 

remotes::install_github("JohnCoene/echarts4r.suite")
library(echarts4r)
# simulate data
dfa <- tibble::tibble(
  x = rep(1:25, 2),
  loc = c(rep("town A", 25), rep("town B", 25)),
  mean = c(rep(2, 25), rep(20, 25)),
  y = rnorm(50, mean, 4)
)

# make categorical
dfa$x <- as.factor(dfa$x)

# base plot
dfa %>% 
  group_by(loc) %>% 
  e_charts(x) %>% 
  e_line(y, symbolSize = 10) %>% 
  e_x_axis(
    axisLabel = list(
      interval = 7
    )
  )

![image](https://user-images.githubusercontent.com/45013044/84183658-3fa86300-aa5a-11ea-88d4-2625ce2901bf.png)

**Comment by JohnCoene** [comment]
Sorry for not being clear. {echarts4r.suite} pulls from CRAN not github, use `remotes::install_github("JohnCoene/echarts4r")`

**Comment by rl627** [comment]
O! That works thanks!
