### ISSUE TITLE
Error with e_scatter on Debian OS

### ISSUE THREAD

**Issue by AThibault92** [JohnCoene/echarts4r#162]
Hello,

I recently installed the github version of echarts4r (0.3.1), and the scatter plots don't work anymore on my Debian server, but work perfectly on my Windows PC.

When I run :
```
e_chart(cars, speed) %>% 
  e_scatter(dist, symbolSize = 10)
```
It return me this error :  incorrect size (1) at position 1, expecting : 50

Do you have any clues on how to solve this ?

Thank you for your help !

**Comment by JohnCoene** [comment]
This is really strange, I cannot reproduce this on my end. Could you tell me which version of echarts4r you are on please? Does this only happen with `e_scatter`?

**Comment by AThibault92** [comment]
It works perfectly on windows with both github (0.3.1) and CRAN (0.2.3) version.

But on Debian, it only works with CRAN version, the github version show this error :
incorrect size (1) at position 1, expecting : 50
It doesn't work for : e_scatter, e_area and e_line
But I works for e_bar

**Comment by JohnCoene** [comment]
Thanks for the quick response, I cannot reproduce it inside docker but it seems this is caused by dplyr, which version of it are you on?

```r
packageVersion("dplyr")
```

I recently upgraded all the internals to use dplyr >= `0.7.0`, it should work with dplyr `0.1.0`.

```r
install.packages("dplyr")
remotes::install_github("JohnCoene/echarts4r")
```

This ought to work, let me know. Thank you and sorry for the trouble.

**Comment by AThibault92** [comment]
My dplyr version is 0.8.3

After the update to dplyr 1.0.0, it seems to work !

Thank you :)
