### ISSUE TITLE
Boxplot grouping

### ISSUE THREAD

**Issue by matthias-a** [JohnCoene/echarts4r#163]
Hi there,

I wanted to use the boxplot example from your webpage, but i was not sure if the grouping feature works as expected:
![grafik](https://user-images.githubusercontent.com/26443836/84676313-a67fbd80-af2d-11ea-91c5-3597b81aa85a.png)

For my case I wanted the x-axis to show the categories A, B and C with their corresponding boxplot.
I could not find a way to achieve it with the current functions, but when the coding in `e_boxplot_`  change from 

```
# xaxis
e$x$opts$xAxis[[1]]$data <- append(e$x$opts$xAxis$data, list(nm))
```
to

```
# xaxis
e$x$opts$xAxis[[1]]$data <- append(e$x$opts$xAxis[[1]]$data, list(nm))
```
(line 1087 in  echarts4r/R/add_.R)

one gets this:
![grafik](https://user-images.githubusercontent.com/26443836/84677667-56a1f600-af2f-11ea-9311-d33845a2a22d.png)

Do you think this small change is correct or is there another way to do so?

**Comment by JohnCoene** [comment]
Thank you very much Matthias, both for identifying the issue and providing the fix. I have pushed that to Github!
