### ISSUE TITLE
Have visual map handle colors out of the current data range

### ISSUE THREAD

**Issue by nschwamm** [JohnCoene/echarts4r#164]
Is it possible to have e_visual_map display values across a defined range, instead of just within the range of data. For example, if I want a scatter plot of percents that is colored by value, is there a way so that e_visual_map maps according to a scale of 0-1 instead of min of data to max of data. I tried feeding in min=0 and max=1 but it still scales such that the minimum data point in the series is assigned to the bottom of the visual map and the maximum gets the top. 

Example attached below. Optimal outcome would be having the value of .7, and .7 be closer to yellow instead of red (which would be reserved for a value of 0 that doesn't exist in this set of data).

```r
library(tidyverse)
library(echarts4r)

tribble(
  ~ElectionYear,  ~Percent, ~ID,
  "A", .6, 1,
  "A", .7, 2,
  "B", .9, 3,
  "B", .7, 4, 
  "C", .5, 5,
  "C", .8, 6
) %>%
  e_charts(ElectionYear) %>%
  e_scatter(Percent,symbol_size = 10, bind=ID) %>%
  e_y_axis(
    formatter = e_axis_formatter(style = "percent"),
    min= 0,
    max=1
  ) %>%
  e_legend(show=F) %>%
  e_visual_map(Percent,min=0,max=1,
               inRange=list(color=c("#fc8d59","#ffffbf","#91cf60")),
               scale = NULL
               ) %>%
  e_title(
    "Performance At Interval"
  ) 

```

Thanks!

**Comment by nschwamm** [comment]
This can potentially be alleviated with some usage of e_add (applying the color manually), but I was hoping there may be some way to resolve this with e_visual_map.

**Comment by JohnCoene** [comment]
Below is what I think you need.

1. Don't pass `serie` to `e_visual_map` as it is used to determine the range of the visual map, thereby overwriting `min` and `max`.
2. Use `precision` to define the number of decimals.

There is more documentation on the visual map [here](https://echarts.apache.org/en/option.html#visualMap-continuous.range), it can be customised to a great extent.

```r
library(tidyverse)
library(echarts4r)

tribble(
  ~ElectionYear,  ~Percent, ~ID,
  "A", .6, 1,
  "A", .7, 2,
  "B", .9, 3,
  "B", .7, 4, 
  "C", .5, 5,
  "C", .8, 6
) %>%
  e_charts(ElectionYear) %>%
  e_scatter(Percent,symbol_size = 10, bind = ID) %>%
  e_y_axis(
    formatter = e_axis_formatter(style = "percent"),
    min = 0,
    max = 1
  ) %>%
  e_legend(show=F) %>%
  e_visual_map(
    min = 0, max = 1, # don't pass serie 
    precision = 1, # set precision for comma
    inRange = list(color = c("#fc8d59","#ffffbf","#91cf60")),
    scale = NULL
  ) %>%
  e_title(
    "Performance At Interval"
  ) 
```

**Comment by nschwamm** [comment]
That's perfect - thank you!
