### ISSUE TITLE
e_add when using timeline 

### ISSUE THREAD

**Issue by nschwamm** [JohnCoene/echarts4r#165]
Hi - 

If I want to set bars to custom colors, I typically can do that with e_add. For example, this code works perfectly:

```r
library(dplyr)
library(echarts4r)

tibble(
  A=c("a","b","c","a","b","c"),
  B=c("A","B","C","D","E","F"),
  D=c(1,2,3,4,5,6),
  color=c("black","red","green","orange","purple","grey")
) %>%
  e_charts(B) %>%
  e_bar(D) %>%
  e_add("itemStyle",color)
```
However, if I group the data by say column A to use as a timeline, I get the error `Error in `*tmp*` [[j]] : subscript out of bounds`

```r
library(dplyr)
library(echarts4r)

tibble(
  A=c("a","b","c","a","b","c"),
  B=c("A","B","C","D","E","F"),
  D=c(1,2,3,4,5,6),
  color=c("black","red","green","orange","purple","grey")
) %>%
  group_by(A) %>%
  e_charts(B,timeline=T) %>%
  e_bar(D) %>%
  e_add("itemStyle",color)
```

I'm guessing that the timeline changes the nesting somehow, but I'm unsure how to resolve. Thanks!

**Comment by JohnCoene** [comment]
Thanks for reporting this, that was a bug. I just pushed a fix which solves this issue. You can reinstall from Github and try again.

```r
remotes::install_github("JohnCoene/echarts4r")
```

**Comment by JohnCoene** [comment]
I hope this work, feel free to reopen if not. Note that the fix is now on CRAN.

**Comment by nschwamm** [comment]
This worked great - thank you for the quick fix!
