### ISSUE TITLE
Series not stacked together with common x axis

### ISSUE THREAD

**Issue by clarencejychan** [JohnCoene/echarts4r#167]
I have a dataset that looks as such 
```
              offset              timestamp                  env
             <int> <chr>                   <chr>      
  1         274296 2020-05-31 22:37:24     Staging     
  2         299192 2020-06-01 07:37:20     Staging     
  3         412355 2020-06-01 22:45:12     Staging
  4         387772 2020-05-31 22:36:55    Prod        
  5         300718 2020-06-01 07:36:45     Prod       
  6         410614 2020-06-01 22:36:27     Prod     
```

I'm trying to show a stacked line graph grouped by the environment.

When I render the chart it shows up as two line graphs with the x axis ordering not being respected.

```
test %>% group_by(env) %>%
  e_charts(timestamp, reorder = FALSE) %>%
  #e_x_axis(axisLabel = list(formatter = JS(date_formatter, "(value) => format_date(value);"))) %>%
  e_y_axis(
    axisLabel = list(formatter = JS(duration_formatter, "(value) => format_duration(value / 1000, true);")),
    name = "Offset", nameLocation = "middle", nameTextStyle = list(padding = 80)
  ) %>%
  e_line(offset) %>%
  e_tooltip(formatter = JS(duration_formatter, "(point) => {
            return `<table class=\"tooltip_table\">
                      <tr><td>Offset Value</td><td>${format_duration(point.value[1] / 1000, true)}</tr>
                    </table>`;
          }"))
```

It ends up looking something like

![image](https://user-images.githubusercontent.com/14989024/86162014-fda39780-bac2-11ea-86d4-2f0d94a89cb8.png)

Might there be something I'm doing wrong here?

**Comment by JohnCoene** [comment]
The class of ‘timestamp’ is character and will therefore be treated as a categorical variable. Convert it to ‘POSIXct’ or ‘POSIXlt’ and it should work.

**Comment by clarencejychan** [comment]
@JohnCoene  I'll give that a shot right now and get back to you. Thanks!

**Comment by clarencejychan** [comment]
@JohnCoene  just one final question

with the current dataset after mutating using `as.POSIXCT`

the dataset looks like 

```
           offset              timestamp                  env        timestamp2     
           <int>                   <chr>                   <chr>       <dttm>                  
1         274296 2020-05-31 22:37:24     Staging      2020-05-31 22:37:24     
2         299192 2020-06-01 07:37:20     Staging      2020-06-01 07:37:20     
3         412355 2020-06-01 22:45:12     Staging      2020-06-01 22:45:12     
4         387772 2020-05-31 22:36:55     Prod          2020-05-31 22:36:55     
5         300718 2020-06-01 07:36:45     Prod          2020-06-01 07:36:45     
6         410614 2020-06-01 22:36:27     Prod           2020-06-01 22:36:27    
```

The x axis seems to be fixed, but the starting position of the graph seems to be a bit off.

![image](https://user-images.githubusercontent.com/14989024/86163725-86233780-bac5-11ea-8a83-ac9391ee1532.png)

Is this to be expected? The even spacing from the first screenshot is gone and I'm wondering if I have to do something in order to retain that sort of spacing.

Thanks for your help!

**Comment by JohnCoene** [comment]
What happens under the hood is that echarts4r sets the axis type to `time` and echarts.js subsequently takes decision as to the start and end points. There are [many options to the axis](https://echarts.apache.org/en/option.html#xAxis.min) which you can pass to `e_x_axis` and `e_y_axis` respectively. You could use `e_x_axis(min = "2020-01-01 00:00:00")` for instance. Does this help?
