### ISSUE TITLE
Formatting date axis label to DD-MM-YYYY

### ISSUE THREAD

**Issue by AThibault92** [JohnCoene/echarts4r#168]
Hello,

I try to change the default date format (which is MM-DD-YYYY) to a DD-MM-YYYY format.

Here is the code I tried (my javascripts skills are pretty low...) but it does not work :(

```r
date <- lubridate::ymd_h("2020-01-01 00")
for (i in 1:300){
  date[i+1] <- lubridate::ymd_h("2020-01-01 00") + i * 3600 
}

df <- data.frame(
  date = date,
  value = rnorm(n = 301)
)

df %>%
  echarts4r::e_charts(date) %>%
  echarts4r::e_line(value) %>%
  echarts4r::e_x_axis(
    type = "time", 
    formatter =  htmlwidgets::JS(
      'function(value){
        label = value.getDay() + "-" + value.getMonth() + "-" + value.getYear();
        return label;
      }'
    )
  )
```

I also tried to change the axis ticks interval to one day using ` axisLabel = list(interval = 24*3600)` or ` axisLabel = list(interval = 1)` but nothing appened...

Thank you for your help :)

**Comment by JohnCoene** [comment]
Hey,

Strange, by default dates do show as `dd-mm-yyyy` in my browser. I'm not sure where you are located, this might be the issue.

Your code was nearly correct, you need to convert the string to a date with `new Date` to return an object of type `Date` so you can access the methods. There's a decent reference of those methods [here](https://www.w3schools.com/jsref/jsref_obj_date.asp); careful, `getDay` returns day of week and `getMonth` returns 0-11 (not 1-12).

```r
library(echarts4r)

date <- lubridate::ymd_h("2020-01-01 00")
for (i in 1:300){
  date[i+1] <- lubridate::ymd_h("2020-01-01 00") + i * 3600 
}

df <- data.frame(
  date = date,
  value = rnorm(n = 301)
)

df %>%
  echarts4r::e_charts(date) %>%
  echarts4r::e_line(value) %>%
  echarts4r::e_x_axis(
    type = "time", 
    formatter =  htmlwidgets::JS(
      'function(value){
        // convert to date format
        let date = new Date(value);
        
        label = date.getDate() + "-" + (parseInt(date.getMonth()) + 1) + "-" + date.getFullYear();
        return label;
      }'
    )
  )
```

**Comment by AThibault92** [comment]
Thank you for your help and for the explanation :) ! It works !

Do you have any clues for the axis interval too ?

**Comment by JohnCoene** [comment]
Great!

The interval takes milliseconds, so the below returns daily interval.

```r
# 1000 ms * 60 seconds * 60 mins * 24 = 1 day
df %>%
  echarts4r::e_charts(date) %>%
  echarts4r::e_line(value) %>%
  echarts4r::e_x_axis(
    interval = 24 * 60 * 60 * 1000
  ) 
```

**Comment by AThibault92** [comment]
Thank you, it works perfectly :)
