### ISSUE TITLE
Documentation on e_treemap itemStyle

### ISSUE THREAD

**Issue by psimm** [JohnCoene/echarts4r#169]
Hi, I'd like to ask for clarification please. How does the itemStyle argument of e_treemap work? It says 'Name of column containing styles to pass to child'. What should the column contain? A string? Should it be a list column?

This is one unsuccessful attempt that I made:

```
df <- data.frame(
  parent = c("earth", "earth", "earth", "mars", "mars"), 
  child = c("forest", "ocean", "iceberg", "elon", "curiosity"),
  value = ceiling(rnorm(5, 10, 2)),
  style = 'borderWidth = 2'
)

df %>% 
  e_charts() %>% 
  e_treemap(parent, child, value, itemStyle = style)
```

**Comment by JohnCoene** [comment]
Hi Paul,

Yes indeed the documentation is not clear at all. It does indeed take a list column.

```r
library(echarts4r)

df <- data.frame(
  parent = c("earth", "earth", "earth", "mars", "mars"), 
  child = c("forest", "ocean", "iceberg", "elon", "curiosity"),
  value = ceiling(rnorm(5, 10, 2)),
  borderWidth = 10,
  borderColor = "#000"
)

df %>% 
  tidyr::nest(style = c(borderWidth, borderColor)) %>% 
  e_charts() %>% 
  e_treemap(parent, child, value, itemStyle = style)
```

![image](https://user-images.githubusercontent.com/7833796/87045274-fcc3e180-c1f7-11ea-8e9e-d64d4b99aa85.png)

I hope this helps!

**Comment by psimm** [comment]
Hi John, 

yes that example helps a lot. Thank you for adding it to the documentation!
