### ISSUE TITLE
timeline question

### ISSUE THREAD

**Issue by jiangnight** [JohnCoene/echarts4r#17]
hello,thank you for your contributions to visualization of R,and i want to ask how can i combine timeline with e_pie

**Comment by JohnCoene** [comment]
If you are referring to [timeline](https://ecomfe.github.io/echarts-examples/public/editor.html?c=mix-timeline-finance), I'm afraid I have not integrated that in the packages yet.

**Comment by JohnCoene** [comment]
Sorry it took so long to come around, the package needed much work elsewhere. 

The timeline component works very differently than the rest of echarts and thus will take some time to implement correctly, in the meantime there is a _very_ low level API to it now in the dev version, examples in the documentation and one the [website](https://echarts4r.john-coene.com/articles/gallery.html).

**Comment by jiangnight** [comment]
No matter , thanks for your effort.

**Comment by JohnCoene** [comment]
@jiangnight This has now been implmement, see [website](https://echarts4r.john-coene.com/articles/timeline.html) for examples :+1:
