### ISSUE TITLE
Opacity argument not applied on density plot

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#172]
I would like to remove the colored area under a density curve, and I think `areaStyle` is the appropriate argument for that (not sure though, I started to use this package today). However, changing `opacity` from 0 to 1 doesn't seem to have an effect on the plot:
```
library(echarts4r)

df <- data.frame(
    x = 1:100,
    y = rnorm(100, 20, 12)
)

df %>%
    e_charts() %>% 
    e_density(y, areaStyle = list(opacity = 1))

# Different opacity but same result
df %>%
    e_charts() %>% 
    e_density(y, areaStyle = list(opacity = 0))
```
Is there a reason for that? Am I missing something?

`echarts4r 0.3.2`

**Comment by JohnCoene** [comment]
Bonjour Etienne, 

No you're not missing anything: j'ai push un fix, la version Github permet de faire ça maintenant..

**Comment by etiennebacher** [comment]
Parfait, merci :+1:
