### ISSUE TITLE
change map

### ISSUE THREAD

**Issue by fjptwenger** [JohnCoene/echarts4r#175]
I learn   **e_map**  to draw a world map ,but how can I change the map label ？just modify to other languages ？
for example，the code from [here](https://echarts4r.john-coene.com/articles/map.html)：

```r
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns %>% 
  e_charts(country) %>% 
  e_map(value) %>% 
  e_visual_map(value)
```
change english to other language? any examples ，thanks！

**Comment by JohnCoene** [comment]
The way to do so would be either 1) to find a GeoJSON where the names of the polygons are already in the language you want or 2) to get a GeoJSON in english and replace the `name` property with that in the language you want.

Below an example not with a world map but just the map of Beijing.

```r
library(echarts4r)

url <- "https://raw.githubusercontent.com/apache/incubator-echarts/master/map/json/province/beijing.json"
geo_json <- jsonlite::read_json(url)

# polygon names to generate fake data
nms <- purrr::map(geo_json$features, function(x){
    x$properties$name
}) %>% 
    unlist()

df <- tibble::tibble(name = nms, value = runif(length(nms)))

df %>% 
  e_charts(name) %>% 
  e_map_register("beijing", geo_json) %>% 
  e_map(value, "beijing") %>% 
  e_visual_map(value)
```

Does this help?

**Comment by fjptwenger** [comment]
Very helpful, thank you
