### ISSUE TITLE
Adapt the size of a graph to the number of observations

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#176]
Here's an example of a shiny app:
```
library(shiny)
library(shinyWidgets)
library(echarts4r)
library(tibble)
library(dplyr)

data_test <- tibble(
  ind = "individual_1",
  test_var = 1
)

for (i in 2:50){
  data_test <- data_test %>%
    add_row(
      ind = paste0("individual_", i),
      test_var = i
    )
}


ui <- fluidPage(
  pickerInput(
    "choose_ind",
    "choose individuals",
    choices = data_test$ind,
    multiple = TRUE,
    options = list(`actions-box` = TRUE)
  ),
  echarts4rOutput("test_plot")
)

server <- function(input, output, session) {
  
  output$test_plot <- renderEcharts4r({
    data_test %>%
      filter(ind %in% input$choose_ind) %>%
      arrange(test_var) %>%
      e_charts(ind) %>%
      e_bar(test_var) %>%
      e_flip_coords() %>%
      e_tooltip(trigger = "axis")
  })
  
}

shinyApp(ui, server)
```
If you select all the observations, some of the y-axis labels are not displayed to avoid overlapping. I would like to automatically increase the size of the plot so that every axis ticks can be read.

Here's what I tried so far:
* put `height = "auto"` in `echarts4rOutput()`. With this, the plot isn't displayed at all.
* use `session$clientData$output_pid_width` in `e_charts` ([this worked for `plotly` but apparently not here](https://community.rstudio.com/t/controlling-the-height-of-fluidrow-in-shiny/4968/3))

Increasing the size in pixels is not an option because this will make the size fixed (and too large if there are just a few observations). 

Is there a way to automatically increase the size of echarts plots?

**Comment by JohnCoene** [comment]
As far as I know this is rather uncommon. I'd be inclined to say bad practice but I might be wrong.

Chart resizing and responsiveness pertains to the width while the height is left untouched, when it is resized it is mainly to maintain aspect ratio of the chart.

```r
library(shiny)
library(shinyWidgets)
library(echarts4r)
library(tibble)
library(dplyr)

data_test <- tibble(
  ind = "individual_1",
  test_var = 1
)

for (i in 2:50){
  data_test <- data_test %>%
    add_row(
      ind = paste0("individual_", i),
      test_var = i
    )
}

script <- tags$script(
  "Shiny.addCustomMessageHandler('chart-height', function(x){
    console.log(x);
    $('#test_plot').height(x);
  })"
)

ui <- fluidPage(
  tags$head(
    script
  ),
  pickerInput(
    "choose_ind",
    "choose individuals",
    choices = data_test$ind,
    multiple = TRUE,
    options = list(`actions-box` = TRUE)
  ),
  echarts4rOutput("test_plot")
)

server <- function(input, output, session) {

  observeEvent(input$choose_ind, {
    session$sendCustomMessage("chart-height", length(input$choose_ind) * 30)
  })
  
  output$test_plot <- renderEcharts4r({
    req(input$choose_ind)

    data_test %>%
      filter(ind %in% input$choose_ind) %>%
      arrange(test_var) %>%
      e_charts(ind) %>%
      e_bar(test_var) %>%
      e_flip_coords() %>%
      e_tooltip(trigger = "axis")
  })
  
}

shinyApp(ui, server)
```

echarts.js automatically adjusts the placement of text on categorical axis for readability.

**Comment by etiennebacher** [comment]
Thank you but there is a strange behaviour. When I run the app, and then select the two first individuals, it's okay; then selecting the third makes the width of bars decrease and some labels disappear; adding a fourth individual makes the entire plot disappear. The plot and labels are fine from 9 individuals and more. Any idea why?

Also, why would you say this is bad practice?

**Comment by JohnCoene** [comment]
The way I have done it here is to add a custom message that changes the height to a certain number of pixels depending on how many variables are selected.

This sets the chart's height to `30 pixels * number of selection in dropdown` ~ 10 selected = 300pixels hight, ~20 = 600 pixels high.

```r
session$sendCustomMessage("chart-height", length(input$choose_ind) * 30)
```

You can increase that to 40, it should do :)

```r
session$sendCustomMessage("chart-height", length(input$choose_ind) * 40)
```

**Comment by etiennebacher** [comment]
Thank you for your answer. I still observe this behavior when I choose 20, 40, 50 or 60 (though it is not necessarily with the same number of individuals). For example, use 40 and select 3 individuals; in my case, no bar is displayed. All the bars appear when I use 100, whatever the number of individuals selected, but then the bars are unnecessarily large.

I realize that what I ask may be strange, also because I could use `e_tooltip(trigger = "axis")` to interactively show to what country corresponds a bar. But in my scenario, I have a lot of countries to display and I would like the user to be able to easily see where is which country. It would be quite boring to hover each bar to find a particular country, hence my question.

**Comment by JohnCoene** [comment]
On the resiziing it's just about defining the pixels in function of the height. The below seems to work a bit better.

For the tooltip, it is doable but would be rather large, would labels be better?

```r
library(shiny)
library(shinyWidgets)
library(echarts4r)
library(tibble)
library(dplyr)

data_test <- tibble(
  ind = "individual_1",
  test_var = 1
)

for (i in 2:50){
  data_test <- data_test %>%
    add_row(
      ind = paste0("individual_", i),
      test_var = i
    )
}

# 40 pixels for each bar + 50 for legend
resize_height <- function(x){
  (x * 40) + 60
}

script <- tags$script(
  "Shiny.addCustomMessageHandler('chart-height', function(x){
    console.log(x);
    $('#test_plot').height(x);
  })"
)

ui <- fluidPage(
  tags$head(
    script
  ),
  pickerInput(
    "choose_ind",
    "choose individuals",
    choices = data_test$ind,
    multiple = TRUE,
    options = list(`actions-box` = TRUE)
  ),
  echarts4rOutput("test_plot")
)

server <- function(input, output, session) {

  observeEvent(input$choose_ind, {
    session$sendCustomMessage("chart-height", resize_height(length(input$choose_ind)))
  })
  
  output$test_plot <- renderEcharts4r({
    req(input$choose_ind)

    data_test %>%
      filter(ind %in% input$choose_ind) %>%
      arrange(test_var) %>%
      e_charts(ind) %>%
      e_bar(test_var, label = list(show = TRUE, position = "insideRight")) %>%
      e_flip_coords() %>%
      e_tooltip(trigger = "axis")
  })
  
}

shinyApp(ui, server)
```

**Comment by etiennebacher** [comment]
Indeed this works better. 

Concerning the tooltip, I wasn't expecting a modification, I just explained that I could use it to see the name of individuals, but this is not necessary anymore because your solution allows to see all labels on the y-axis (I didn't know how to put number in the bars though, so thanks for the example).

Thanks for your help ;)
