### ISSUE TITLE
Add an identical axis at the top when flipping coordinates

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#177]
I have a plot with flipped coordinates:

```r
library(echarts4r)
library(dplyr)

USArrests %>%
  mutate(State = rownames(USArrests)) %>%
  slice(1:5) %>%
  arrange(Murder) %>%
  e_charts(State) %>%
  e_bar(Murder) %>%
  e_flip_coords()
```

My actual plot is quite long and I would like to display the same x-axis at the top so that the user doesn't need to scroll down to see the x-axis. I know this is not very common but I think it could be useful. 

Therefore in the example above, the output would be the same graph but with an horizontal axis displaying 0, 3, 6, etc. at the top.

This issue is similar to #28 but the difference is that the second axis I would like to show is identical to the first one. Is it possible to do so?

**Comment by helgasoft** [comment]
Is this what you are looking for ?
```
library(echarts4r)
library(dplyr)

USArrests %>%
  mutate(State = rownames(USArrests)) %>%
  slice(1:5) %>%
  arrange(Murder) %>%
  e_charts(State) %>%
  e_bar(Murder) %>%
  e_flip_coords() %>%
  e_x_axis(position='top')
```

**Comment by etiennebacher** [comment]
This is not what I looking for since your code just moves the axis at the top whereas I would like to have the same axis both at the top and the bottom. 

The link you refer to has two y-axis (before flipping coords) but those axis have a different scale, whereas I would like to know if I can have exactly the same axis at the top and at the bottom.

**Comment by helgasoft** [comment]
Complete madness, but mission accomplished. 
```r
USArrests %>% mutate(State = rownames(USArrests)) %>% slice(1:5) %>% arrange(Murder) %>%
  e_charts(State) %>%
  e_bar(Murder, x_index=1, y_index=1) %>%
  e_grid(height = "50%", top = "20%") %>% 
  e_grid(height = "50%", top = "20%") %>% 
  e_x_axis(gridIndex = 1, show=FALSE) %>%
  e_y_axis(gridIndex = 1) %>%
  e_bar(Murder, x_index=2, y_index=2) %>%
  e_flip_coords()
```

**Comment by JohnCoene** [comment]
Technically the equivalent of ggplot2 facets should be doable but that's also compete madness to program :(

**Comment by etiennebacher** [comment]
thanks @helgasoft !

**Comment by helgasoft** [comment]
Simpler and without Yaxis duplication
```r
USArrests %>% mutate(State = rownames(USArrests)) %>% slice(1:5) %>% arrange(Murder) %>%
  e_charts(State) %>%
  e_bar(Murder, x_index=0, y_index=0) %>%
  e_bar(Murder, x_index=1, y_index=1) %>%   #, color='blue', name='i.am.Blue') %>%
  e_flip_coords() %>% 
  e_y_axis(index=1, axisLabel=list(show=FALSE))
```
