### ISSUE TITLE
Link to echarts apache project more prominently in documentation

### ISSUE THREAD

**Issue by gadenbuie** [JohnCoene/echarts4r#182]
It would be helpful both to the original echarts project and to users evaluating web charting packages to link more prominently to <https://echarts.apache.org/>. Ideally, in the project README, the front page of the pkgdown site, or on the about page (or all of these).

**Comment by JohnCoene** [comment]
Hi Garrick, yes indeed. It's linked to in nearly every man page but not enough on the website and README. I've just remedied to that, it's in the README and homepage (sidebar too)
