### ISSUE TITLE
e_common (validateScalarName)

### ISSUE THREAD

**Issue by vacon04** [JohnCoene/echarts4r#186]
Hello

Sorry for not leaving a good reproducible example. When I use the e_common function to change the font I get the following error

```R
... %>%
e_common(font_family = "Arial")

Error in validateScalarName(name) : 
  Invalid argument 'name' (must be a non-empty character string and contain no '/' or '\')
```
This didn't use to happen before, but the error now shows up after updating to the latest echarts4r 0.3.3 development version.
I am using the following versions of the packages that I think could be responsible for this new problem.

- echarts4r_0.3.3

- htmltools_0.5.0.9000

- rlang_0.4.7.9000

- htmlwidgets_1.5.1

- vctrs_0.3.2.9000

Let me know if you need more information. Thanks for the amazing job with the package.

**Comment by JohnCoene** [comment]
Would you mind reinstalling the package and trying again? I think I broke that then fixed it again under `0.3.3` (bad practice I know =/).

This does not raise any error on the latest.

**Comment by vacon04** [comment]
Mmm it's weird. With the latest version I can run the code with the e_common(... ) function and it works. If I re-run the same code but remove the e_common(...) part I get the error once again.

**Comment by JohnCoene** [comment]
Ah I seem to understand. `e_common` is not meant to be piped.

```r
e_common(font_family = "Arial")

e_charts(cars, dist) %>%
  e_line(speed)
```

**Comment by vacon04** [comment]
Dang. Such a dumb mistake. So if I pipe it then it breaks the whole thing. Sorry for the inconvenience.

**Comment by JohnCoene** [comment]
Not at all, it's not clear enough in the docs.
