### ISSUE TITLE
Linetype not taken into account in legend

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#188]
This issue is related to [this SO question](https://stackoverflow.com/questions/60444923/echarts4r-how-to-match-line-type-with-legend). I couldn't find a solution but another issue (#48) is quite similar. Here, the problem is not with colors but with the type of line.

Indeed, the [solution given](https://github.com/JohnCoene/echarts4r/issues/48#issuecomment-443497040) in #48 doesn't work with linetype:
```
tt <- data.frame(
  x = seq(1:15), 
  a = rnorm(15, mean = 10, sd = 5), 
  b = rnorm(15, mean = 5, sd = 3),
  c = rnorm(15, mean = 8, sd = 2)
) 

# Line type is not displayed in legend
tt %>%
  e_charts(x) %>%
  e_line(b, symbol = 'none', smooth = FALSE, lineStyle = list(type = "dashed"))

# Line type not displayed at all
tt %>%
  e_charts(x) %>%
  e_line(b, symbol = 'none', smooth = FALSE, type = "dashed") 
```

**Comment by JohnCoene** [comment]
Sorry to say that this is not a bug, Echarts.js does not reflect the line type in the legend.

![image](https://user-images.githubusercontent.com/7833796/90047518-52e1e400-dcd2-11ea-9838-7254b0440e54.png)

**Comment by MdoubleDash** [comment]
Then why close the issue? Isn't it something that one can improve in the library?

> Sorry to say that this is not a bug, Echarts.js does not reflect the line type in the legend.
> 
> ![image](https://user-images.githubusercontent.com/7833796/90047518-52e1e400-dcd2-11ea-9838-7254b0440e54.png)

**Comment by JohnCoene** [comment]
Sorry, I can only make fixes and changes to the echarts4r R package not the underlying Apache ECharts.js library. 

If you want to request that feature you may open an issue on that repository: https://github.com/apache/incubator-echarts

**Comment by ymansiaux** [comment]
Hi,

I have managed to used a dashed line in a my legend with this method :
https://github.com/apache/echarts/issues/9552

```
e_legend(icons = 'path://M180 1000 l0 -40 200 0 200 0 0 40 0 40 -200 0 -200 0 0 -40z, M810 1000 l0 -40 200 0 200 0 0 40 0 40 -200 0 -200 0 0 -40zm, M1440 1000 l0 -40 200 0 200 0 0 40 0 40 -200 0 -200 0 0 -40z')
```
