### ISSUE TITLE
Error In Documentation - Tooltip Article Code Examples

### ISSUE THREAD

**Issue by stu000** [JohnCoene/echarts4r#193]
In the Tooltip vignette  (https://echarts4r.john-coene.com/articles/tooltip.html) , it appears that a couple of the code examples are incorrect.  It looks like when JS is nested in R - it may not render properly into HTML, as per example below:

```r
e_tooltip(formatter = htmlwidgets::JS("
    function(params){
        return( )
      }
    "ltip(formatter = htmlwidgets::JS("
    function(params){
        return( )
      }
    ")
)
```

Thanks for the great package.

**Comment by JohnCoene** [comment]
Thank you, I had not noticed
