### ISSUE TITLE
Expose span parameter of loess in e_loess function

### ISSUE THREAD

**Issue by stu000** [JohnCoene/echarts4r#194]
Could you please expose the "span" parameter from stats::loess as an available parameter in e_loess ?  It can be useful to tweak this parameter, to get appropriate level of smoothing.

Thanks for the excellent package.

**Comment by JohnCoene** [comment]
Sure, I added `span` to the Github version. Would you say that more arguments of the `stats::loess` function should be exposed? If so I should find a better way to allow the user to pass them along.

**Comment by stu000** [comment]
Thank you for the amazingly timely response !!!  Making the span parameter accessible is definitely the most important to make e_loess more widely useful  I find it helpful in some visualizations to map the span parameter to a slider. (see for example https://kalmenson.shinyapps.io/COVID/  - select "Charts 2" for echarts).  

More generally, for the class of fitting/smoothing function (e_lm, e_glm, e_loess) - I can imagine cases where people will want to have access to many of the underlying parameters.  In ggplot2::stats_smooth, they have a parameter:  model.args=list(), which allows for generic parameters to be passed through to the underlying modeling function.  Perhaps it would be helpful to have a similar approach at some point.  Note that the "span" parameter is one that is exposed in stats_smooth at top level (rather than in model.args param list), as it is the most widely used.

**Comment by JohnCoene** [comment]
Great, that was my thought too, passing those arguments as a `list` so the function can use `do.call` internally.

✅ I've added `model_args` argument to `e_lm` and `e_loess`. 
🔴 That means I removed `span`.

```r
mtcars %>% 
  e_charts(disp) %>% 
  e_scatter(mpg, qsec) %>% 
  e_loess(mpg ~ disp, model_args = list(span = 2))
```

**Comment by stu000** [comment]
Nice !  This works for my app, and adds a lot of functionality.  In particular, this should be useful in combination with echarts4rProxy to interactively tune lm/glm/loess models without need to redraw underlying data.  Thank you !

**Comment by JohnCoene** [comment]
Thank you. Much of the "proxy" functions are rather fragile, please do let me know if you run into issues, I'll be more than happy to fix whatever needs fixing!
