### ISSUE TITLE
Centering x and y axis labels/titles and adjusting their font size

### ISSUE THREAD

**Issue by barveaditya** [JohnCoene/echarts4r#198]
Hi John, 

Firstly, thank you for developing echarts4r. I love the R package, and it is a pleasure to use. 

I am, however, having trouble centering the axis labels. By default, they appear at the end of axis (see attached). I would like to go traditional here and have them in the center of the axis. Is there a way to do this? Also, I would like to increase their font size. I am sorry if this has been documented already, but I am unable to find it. 
Thank you,
Adi
![echarts](https://user-images.githubusercontent.com/14080760/94673321-73abda80-030e-11eb-9b62-1303f5ea6dd2.png)

**Comment by JohnCoene** [comment]
Thank you.

There are hundreds of options that are not documented but nonetheless available, I have a bit on that [here](https://echarts4r.john-coene.com/articles/get_started.html#navigate-options-1).

For instance the options used below were found [here](https://echarts.apache.org/en/option.html#xAxis)

```r
library(echarts4r)

cars %>% 
  e_charts(dist) %>% 
  e_scatter(speed) %>% 
  e_x_axis(
    name = "SPEED",
    nameLocation = "middle",
    nameTextStyle = list(
      color = "red",
      fontSize = 24
    )
  )
```

![image](https://user-images.githubusercontent.com/7833796/94686683-74069e80-032b-11eb-9a85-8898025cc864.png)

Let me know if this answers your question

**Comment by JohnCoene** [comment]
I'll assume this fixed the problem and close the issue. Reopen if that is not the case.
