### ISSUE TITLE
Converting examples from echarts.apache.org

### ISSUE THREAD

**Issue by barveaditya** [JohnCoene/echarts4r#206]
Hi folks, 

I was looking at https://echarts.apache.org/examples/en/editor.html?c=graph&theme=light and loved the network plot. 
Is there a simple way to convert these examples into R code? I do a lot of graph/network plots, and would really appreciate if you could convert the example above to R code. 

In addition, converting at least some of the unusual plots from echarts.apache to R code would really benefit R users.  

Thank you!

**Comment by JohnCoene** [comment]
There is a family of functions for this but it may not work with all example; the one you link to uses `fetch` on data not accessible from R and reshapes the data with JavaScript.

[Echarts4r from JSON](https://echarts4r.john-coene.com/reference/echartsnjson?q=json)

**Comment by barveaditya** [comment]
@JohnCoene thanks for the reply. The data could be anything. This data, called lesmis, is available in at least few R packages. CEoptim, geomnet for example have les miserable data available. 

I could paste the data here if you want. But could you help convert the code or make the R version of the plot it look like the one in the example?

**Comment by swsoyee** [comment]
@barveaditya It very easy to reproduce this in R. Try to follow this step below.
1. Open the the site your provided. (https://echarts.apache.org/examples/en/editor.html?c=graph&theme=light)
2. In the editor part, add the `console.log()` function in the 71 line:
   ```js
       myChart.setOption(option);
       console.log(myChart.getOption());
    }, 'xml');
   ```
3. Open the console and copy the output and save it as a json file. also see: https://stackoverflow.com/questions/7627113/save-the-console-log-in-chrome-to-a-file
4. Using the code below, and you will make it
   ```r
    library(echarts4r)
    json <- readLines("../../Desktop/data.json")
    echarts_from_json(json)
   ```
![image](https://user-images.githubusercontent.com/20528423/95358262-d4857500-0903-11eb-8d83-15508b46c1d9.png)


Also upload the data for you here [data.txt](https://github.com/JohnCoene/echarts4r/files/5342126/data.txt) (Github is not allow to upload json file so I change the file name).

**Comment by JohnCoene** [comment]
We could bring support to load the gexf file from the front-end via echarts4r.

In the meantime you can read and convert the gexf files in R so you can use them with ehcarts4r or other libraries.

```r
file <- system.file("gexf-graphs/lesmiserables.gexf", package = "rgexf")
gexf <- read.gexf(file)

ig <- gexf.to.igraph(gexf)
igraph::as_data_frame(ig, what = "both") 
```

**Comment by barveaditya** [comment]
Hi John, 

Thanks a lot for the detailed answer. Will try it out for sure!!
