### ISSUE TITLE
Color the blank countries 

### ISSUE THREAD

**Issue by yzhangbluesky** [JohnCoene/echarts4r#208]
Hi John, 

Thank you for creating this awesome package. Really appreciate it! 

I wonder is there any way we can color the blank countries as grey instead of leaving them as complete white? 

The codes look like this:
![Screen Shot 2020-10-07 at 10 21 10 AM](https://user-images.githubusercontent.com/67762753/95343857-fe4c8680-0886-11eb-9eca-d93af0524b0f.png)
With the map output:
![Screen Shot 2020-10-07 at 10 21 23 AM](https://user-images.githubusercontent.com/67762753/95343892-060c2b00-0887-11eb-8ac7-979005b1d536.png)

We don't have any data on those blank countries like Greenland, Oman ... But it would be nice if we can paint these countries as grey to make them less contrast. Can you offer some insight on how to do this with echarts4r? 

Thank you in advance!

**Comment by JohnCoene** [comment]
Thank  you.

Yes, you can change that, along with other things, the full list of options is [here](https://echarts.apache.org/en/option.html#series-map.type)

```r
library(echarts4r)

cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns %>% 
  e_charts(country) %>% 
  e_map(
    value,
    itemStyle = list(
      areaColor = "blue"
    )
  ) %>% 
  e_visual_map(value)
```

**Comment by yzhangbluesky** [comment]
Wonderful! Thank you so much for your quick reply and help!
