### ISSUE TITLE
[Suggestion] Add code style formatter to improve the code readable

### ISSUE THREAD

**Issue by swsoyee** [JohnCoene/echarts4r#210]
@JohnCoene How about add `{styler}` and `{lint}` to this project? If you think it's necessary and don't have time to import this package you can assign this issue to me. Because the `{styler}` may bring big changes in the first commit so I need to confirm this.

**Comment by JohnCoene** [comment]
I only used {lint} a few times, I'm not too familiar with it but the code sure could do with some linting. Your contributions so far have been amazing feel free to add this if you want.
