### ISSUE TITLE
e_facet not loaded?

### ISSUE THREAD

**Issue by jamessmythe** [JohnCoene/echarts4r#212]
Hi John,

This is a fantastic package, thank you so much.

I was excited to use e_facet but the function doesn't seem to be loading with the package? It's in the help file but not found as a function. As a work-round I copied the function into my app separately.

Thanks,
James

**Comment by JohnCoene** [comment]
Hi James,

Thanks. Yes indeed, I got excited too trying to write that function however I could never finish it. It's technically possible with Echarts.js to mimic facets but I'm afraid I found out it was too convoluted and rather clunky.

I'll see if I either remove the man page or can manage to finish this function, thanks again!

**Comment by jamessmythe** [comment]
Understood, thank you. This is a beautiful package and fills a huge gap for me between ggplot/plotly and highcharter. Much appreciated!

**Comment by JohnCoene** [comment]
Thank you for the kind word; genuinely means a lot to see the package come in useful to others. Don't hesitate if you come across other issues/questions.

**Comment by maskegger** [comment]
Hi John, I got here googling for e_facet() and it seems the function is still up on the documentation site https://echarts4r.john-coene.com/reference/e_facet.html

Also, what would you recommend as an alternative to faceting within echarts4r? Thanks!

**Comment by JohnCoene** [comment]
Though technically one could facet with ECharts.js by placing charts within regions of a lot (which can be done from R) it is too much of a pain (even in JS).

Instead I use the [chart connection](https://echarts4r.john-coene.com/articles/connect.html)
