### ISSUE TITLE
Multiple densities on same chart

### ISSUE THREAD

**Issue by ajo1993** [JohnCoene/echarts4r#216]
Hello,

Thanks again for this amazing package!

I can't seem to get multiple density curves on the same chart if not by adding a timeline. Below is an example. I would simply like multiple curves on the same plot similar to what I'd get by doing geom_density(aes(x=Petal.Length,colour=y) in ggplot.

Apologies if I've missed something obvious. Based on the package documentation and examples I couldn't find a solution to this.

thank you very  much

Alessandro

With timeline :

```r
iris %>%
  group_by(Species) %>%
  e_chart(timeline = T) %>%
  e_density(Petal.Length, legend = T)
```

Without timeline:

```r
iris %>%
  group_by(Species) %>%
  e_chart(timeline = F) %>%
  e_density(Petal.Length, legend = T)
```

Error: Can't convert a list to a quosure

**Comment by JohnCoene** [comment]
Hi, 

That was a bug indeed, thanks for reporting!

I just pushed a fix, you can reinstall the Github version and it should work fine.

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/echarts4r")
```

_Example_

```r
iris %>%
  group_by(Species) %>%
  e_chart() %>%
  e_density(Petal.Length, legend = TRUE)
```

Let me know if this works.

**Comment by ajo1993** [comment]
Thank you very much John!

Working fine with the Github version now.

Thanks again
