### ISSUE TITLE
Add vertical average line to density plot

### ISSUE THREAD

**Issue by ajo1993** [JohnCoene/echarts4r#217]
Hi,

I am trying to add a vertical line to a grouped e_density chart to mark the average of each density. Is this possible on echarts4r?
I see it is possible and very easy to do when adding the average of the y variable, with the below code. However, I can't find a way to incorporate the xAxis option that varies on the basis of the specific curve.

If it can't be done in one line like for the y axis that's fine. Can you suggest how else I could do that? Maybe by including a second df with averages to the plot?

Thanks

Alessandro

Adding average of y variable:

iris %>%
  group_by(Species) %>%
  e_chart(timeline = F) %>%
  e_density(Petal.Length, legend = T) %>% 
  e_mark_line(data = list(type="average"))

Adding average of x variable:

iris %>%
  group_by(Species) %>%
  e_chart(timeline = F) %>%
  e_density(Petal.Length, legend = T) %>% 
  e_mark_line(data = list(xAxis="average"))  <-------- ???

No error, but no line showing

**Comment by etiennebacher** [comment]
The argument you need to change is `valueIndex` (its default value is 1):
```
iris %>%
  group_by(Species) %>%
  e_chart(timeline = F) %>%
  e_density(Petal.Length, legend = T) %>%
  e_mark_line(data = list(type = "average", valueIndex = 0))
```
See [here](https://echarts.apache.org/en/option.html#series-scatter.markLine.data.0.valueIndex) for the rest of possible arguments

**Comment by ajo1993** [comment]
Apologies, hadn't seen that in the documentation.

Your package is really good, simple to use with great aesthetics!

Thanks!

**Comment by etiennebacher** [comment]
Not my package :sweat_smile: it's for you @JohnCoene
