### ISSUE TITLE
Using group_by to one-line plot multiple boxplots does not set the x axis labels correctly

### ISSUE THREAD

**Issue by lianos** [JohnCoene/echarts4r#219]
First: thank you for the package, I've only just encountered it, but it looks like it has a lot of promise.

It seems like in order to draw multiple box plots on the x-axis w/ out writing `e_boxplot(...)` for every value over *x*, we need to use `group_by()`

So, taking the example from the `e_boxplot()` man page which has data in a wide format, we have:

```r
library(dplyr)
library(echarts4r)

df <- data.frame(
  x = c(1:10, 25),
  y = c(1:10, -6))

df %>%
  e_charts() %>%
  e_boxplot(x, outliers = TRUE) %>% 
  e_boxplot(y, outliers = TRUE)
```

If we had multiple categories we wanted to create boxplots for across the x-axis, that can get tedious, so it seems we need to rather convert the data into a long format, and use group_by, like so:

```r
dfl <- data.frame(
  var = rep(c("x", "y"), each = nrow(df)),
  value = c(df$x, df$y))

dfl %>% 
  group_by(var) %>% 
  e_charts() %>% 
  e_boxplot(value)
```

1. Just want to clarify that this is the suggested way to do that(?)
2. The issue is that when we plot the data in this way, the labels on the *x*-axis or the boxplots are all "value" instead of "x" and "y".

Perhaps there is a way to use the `name` parameter in the `e_boxplot()` to address this, but not quite sure how if so.

Thanks!

**Comment by swsoyee** [comment]
@lianos I have check the source code, and the labels of x-axis may not be set properly when using `group_by()` function. But you could manually set labels by using `e_x_axis()` at present.

```r
library(dplyr)
library(echarts4r)

dfl <- data.frame(
  var = rep(c("x", "y"), each = nrow(df)),
  value = c(df$x, df$y))

dfl %>% 
  group_by(var) %>% 
  e_charts() %>% 
  e_boxplot(value) %>%
  e_x_axis(data = c("x", "y"))
```

**Comment by lianos** [comment]
I see, thanks for digging around in the codebase! For now, I'd be too nervous to use that approach about mislabeling the order of the x-axis to rely on that ...

I'm not all that familiar with it just yet, did you chase the code logic down to the `.name_it()` call from within the `e_boxplot_()` function?

Poking around, here's a naive way for a quick fix to the codebase that looks to be working on my side, if we squeeze this oneliner above [this line in `add_.R`](https://github.com/JohnCoene/echarts4r/blob/3504d8d99c9e6cb4a963c1a3bf903f01f6cc599f/R/add_.R#L1101) it seems to do the trick:

```r
      if (serie == name && length(e$x$data) > 1L) name <- names(e$x$data)[i]
```

Again, likely too simple and specific to this function -- perhaps there's a better way somewhere higher up the call stack ... just having some fun.

Thanks again!

**Comment by JohnCoene** [comment]
Thanks, there is definitely an issue here somewhere, I'll take a look.

**Comment by JohnCoene** [comment]
Pushed a fix, hope this works.

```r
df <- data.frame(
  x = c(
    rnorm(100),
    runif(100, -5, 10),
    rnorm(100, 10, 3)
  ),
  grp = c(
    rep(LETTERS[1], 100),
    rep(LETTERS[2], 100),
    rep(LETTERS[3], 100)
  )
)

df %>% 
  group_by(grp) %>% 
  e_charts() %>% 
  e_boxplot(x)
```

**Comment by lianos** [comment]
Hi John,

Thanks for taking a look.

This does indeed fix the `group_by()` use case, however the original code that users will find in the Example section of `e_boxplot()` which has data in a wide format and one `e_boxplot()` call per column now has `null` for the x axis label names.

For instance:

```r
df <- data.frame(
  x = c(1:10, 25),
  y = c(1:10, -6))

df %>%
  e_charts() %>%
  e_boxplot(x, outliers = TRUE) %>% 
  e_boxplot(y, outliers = TRUE)
```

**Comment by JohnCoene** [comment]
Thanks for spotting this, just fixed!
