### ISSUE TITLE
Chain _functions?

### ISSUE THREAD

**Issue by happyshows** [JohnCoene/echarts4r#22]
Hi, 

How to plot when you have a dynamic set of data frame which you don't know how many series you have. Is there a way to do this programmatically instead of a bunch of if else?    

df %>%
      e_charts(label) %>% 
      e_bar_("a") %>% 
      e_bar_("b") %>% 
      e_bar_("c")

something like lapply(c('a','b','c'),function(x){}) , I don't know the exact implementation

**Comment by JohnCoene** [comment]
This is also related to issue #8 I think, as, ideally, this should be a group argument, i.e.:

```r
df %>%
  group_by(grp) %>%
  e_charts(x) %>%
  e_bar(y)
```

Will update the :package: as soon as I find the time.

**Comment by JohnCoene** [comment]
Happy to say that this is now implemented. Simply group your data with `dplyr::group_by`, i.e.:

```r
df <- data.frame(
  grp = rep(LETTERS[1:10], 20),
  x = runif(200),
  y = runif(200)
)

df %>% 
  group_by(grp) %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_title("Grouped data")
```

**Comment by happyshows** [comment]
or boxplot

**Comment by JohnCoene** [comment]
Hi Shows,

`dplyr::group_by` will work with most functions, where it makes sense, it will not crash where shouldn't be used but will not returned the expected results (takes only the first group). However, `e_histogram` is a mistake of mine, it should have been included (note that it was one of the last functions I had to apply this new functionality to so I am confident the others are all right).

I pushed a fixed for `histogram`, `boxplot` is somewhat hacky, I will revisit this. I'll keep this open in case you find any other anomalies.

**Comment by happyshows** [comment]
cool appreciate the feedback

**Comment by happyshows** [comment]
also, could you try some examples for group_by with stacked bar chart? I think the bar simply override with each other not stacked 'up'. Not sure it's related to my configuration or the e_bar function itself.

**Comment by happyshows** [comment]
The new behavior of histogram is a bit strange.

Try below..

```
mtcars %>% group_by(mpg) %>% e_charts() %>% e_histogram(carb)
```

**Comment by JohnCoene** [comment]
Closing this is now on #46, only `e_histogram` remains problematic thanks @happyshows
