### ISSUE TITLE
Unable to implement features in "faceted" densities

### ISSUE THREAD

**Issue by ajo1993** [JohnCoene/echarts4r#220]
Hi,

I am working with "faceted" density charts. I understand that e_facet is still work in progress so I tried replicating an example I saw on the echarts4r page but for densities (chart 6 here https://echarts4r.john-coene.com/articles/grid.html).

I've managed to facet two densities with the code below but I am struggling with implementing some features to both charts in the canvass. What I am trying to do is:

1. Fixing the two x axes to allow comparison between the two densities. Ideally, I'd also like to fix the y axes. I tried with options min and max in e_x_axis, even duplicating them after each density as below but only the bottom x axis responds. I would prefer not to manually fix min and max, but just have e_charts choose axes that are fixed between top and bottom chart.

2.  Having one title per chart (or even y axis title per chart will do), so in the example below Sepal.Width in the top one and Petal.Width in the bottom one. 

3. Ideally, not making the chart zoom in or out when I make a curve disappear by clicking on legend element. Would like axes to always remain fixed.

Thank you

Alessandro

Example:

```r
iris %>% 
  group_by(Species) %>% 
  e_charts(Sepal.Length) %>% 
  e_density(Sepal.Width,y_index=1,x_index=1) %>% 
  e_x_axis(max=10,min=-2) %>% 
  e_density(Petal.Length) %>% 
  e_x_axis(max=10,min=-2) %>%
  e_x_axis(gridIndex=1) %>% 
  e_y_axis(gridIndex=1) %>% 
  e_grid(height = "35%") %>% 
  e_grid(height = "35%", top = "50%") %>% 
  e_axis_labels(x = "ff", y = "gg") %>% 
  e_title("Hello world")
```

**Comment by JohnCoene** [comment]
Hi Alessandro,

I'm very sorry for the late response, it's been hectic on my end.

1. Can't be automatically defined by echarts4r (you can compute it outside the chart is you want, e.g.: `min <- min(data$x)` then use `min`). You can work with both axis but specify the `index` of the axis you work with (starts counting at 0). By default there is only axis `index = 0` you add one `index = 1`.
2. You can actually have multiple titles, use it twice and specific the top margin.
3. If I understand correctly you want to show the legend but disable it? `selectedMode = FALSE`

```r
iris %>% 
  group_by(Species) %>% 
  e_charts(Sepal.Length) %>%
  e_density(Sepal.Width,y_index=1,x_index=1) %>% 
  e_density(Petal.Length) %>% 
  e_x_axis(max=10,min=-2) %>%
  e_x_axis(max=10,min=-2, index = 1) %>% 
  e_x_axis(gridIndex=1) %>% 
  e_y_axis(gridIndex = 1) %>% 
  e_grid(height = "35%") %>% 
  e_grid(height = "35%", top = "50%") %>% 
  e_title("Something") %>% 
  e_title("Soemthing else", top = "45%") %>% 
  e_legend(selectedMode = FALSE)
```
![image](https://user-images.githubusercontent.com/7833796/98288449-27a42380-1fa7-11eb-9df5-2365869c77a3.png)

Let me know if that answers your question.

**Comment by JohnCoene** [comment]
I'll assume this works and close. Feel free to reopen if that is not the case.
