### ISSUE TITLE
e_bar: add custom labels with data not used for plotting

### ISSUE THREAD

**Issue by u909090** [JohnCoene/echarts4r#225]
Hi,

Is it possible to add custom labels to a bar chart using data not used for plotting.
Example:
```R
df <- data.frame(Category = c("A","B", "C"), N=c(1, 3, 6), percent=c(10, 30, 60))
df
  Category N percent
1        A 1      10
2        B 3      30
3        C 6      60
```
I can only customise labels from data used to build the plot (i.e. `Category` and `percent`, but not `N`)
```R
df %>% 
  e_charts(Category) %>% 
  e_bar(percent, label=list(show=T, formatter = "{@y}%"))
```
How could one add the `N` values to the labels in order to get for instance, `10% (N=1)`? 

Thanks !

**Comment by JohnCoene** [comment]
You can use a combination of `bind` and the `formatter` you already use; `bind` essentially adds the `name` argument to the data in the serie.

```r
df <- data.frame(Category = c("A","B", "C"), N=c(1, 3, 6), percent=c(10, 30, 60))

df %>% 
  e_charts(Category) %>% 
  e_bar(percent, bind = N, label=list(show=T, formatter = "{@y}% (N={b})"))
```

Feel free to reopen if that does not answer your question. (closing otherwise I lose track and end up with loads of dangling issues)

**Comment by u909090** [comment]
Perfect. Thanks John !

**Comment by tyluRp** [comment]
How you you get the labels to sit on top of the bars? The closest I got was using the `padding` option but it only accepts 4 values for top/left/up/right.
