### ISSUE TITLE
e_legend problem

### ISSUE THREAD

**Issue by helgasoft** [JohnCoene/echarts4r#226]
Attribute _legend=FALSE_ is not respected when **all** _e_line_(s) between _e_chart_ and _e_legend_ have it.
```r
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE)     # ok
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE) %>% e_legend(right='8%')     # no
mtcars %>% e_chart(hp) %>% e_line(gear) %>% e_line(carb, legend=FALSE) %>% e_legend(right='8%')    # ok
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE) %>% e_line(carb, legend=FALSE) %>% e_legend(right='8%')    # no
```
Why it matters? Because one could
1)  start with a static layout of several 'default' e_lines (without a legend), and one e_legend defined for future e_lines
2) then the user may dynamically add several more e_lines which require a legend

The start (1) will display incorrectly.

**Comment by JohnCoene** [comment]
With maggrittr in general the order of operations should not matter, `e_legend` applies changes to the entire plot, i.e.: to series (e.g.: `e_line`) passed before _and_ after it. Were the order of operation matter for these kinds of things it would eventually become impossible to manage.

The `legend` argument controls whether the name of the serie is added to the `data` object nested in `legend`. The second and foruth examples you give are actually correct; `gear` was not added to the legend data object but a legen is also defined. It should not show anything but ECharts.js, under-the-hood, understand the user wants to show the `serie` named `gear` and thus adds it.

```r
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE) %>% e_legend(right='8%') 
```

It's to do with the native JavaScript library and not echarts4r here (I think ECharts.js handles it correctly).

**Comment by helgasoft** [comment]
Thank you, it helped me understand how it works and I found a solution. This is what I wanted:
```r
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE) %>% e_legend(right='8%', data=list())	# now ok
mtcars %>% e_chart(hp) %>% e_line(gear, legend=FALSE) %>% e_line(carb, legend=FALSE) %>% e_legend(right='8%', data=list())	# now ok
```
