### ISSUE TITLE
Using variables as series

### ISSUE THREAD

**Issue by sprengholz** [JohnCoene/echarts4r#227]
I'm using an echart4r on a large dashboard where the series to print can be selected from hundreds of options. Thus, I tried to pass a variable as the series name to my chart, but it is not working. Simplified example:

```r
variable <- "POWER"

data %>% 
  e_charts(TIME) %>% 
  e_line(variable)
```

As soon as I replace _variable_ with _POWER_ everything is fine. But that's a hardcoded solution I cannot use. Is there any way of passing in a variable holding the column name as a string? Whatever I tried (!!, get, expr,...) did not work here.

**Comment by etiennebacher** [comment]
Try with `e_line_` instead. More generally, all functions of the type `e_*_()` work with character vectors but not `e_*()` functions.

**Comment by JohnCoene** [comment]
Yes, thanks @etiennebacher, there are escape hatches ending in `_` where relevant meant for this :)

**Comment by sprengholz** [comment]
Awesome! Thanks a lot! Somehow missed that in the docs - glad its working now :)
