### ISSUE TITLE
e_pictorial: adding solid background to icons

### ISSUE THREAD

**Issue by vl0001** [JohnCoene/echarts4r#228]
Hi,

Is it possible to specify a solid white background to the icons used in pictorial plots. When using tooltip on this kind of charts the mouse has to exactly hover the icon line to popup.

Example:
```R
y <- rnorm(10, 10, 2)
df <- data.frame(x = 1:10, y = y, z = y - rnorm(10, 5, 1))

df %>% 
  e_charts(x) %>% 
  e_pictorial(
    y, 
    name = "volume",
    symbol = ea_icons("microphone"), 
    symbolRepeat = TRUE, 
    z = -1,
    symbolSize = c(20, 30)
  ) %>%  
  e_tooltip()
```

Trying to use SVG paths by adding `fill='white'` does not solve the issue.

**Comment by JohnCoene** [comment]
I'm afraid not.

The `ea_icons` function is just convenience to access svg patterns and the tooltip will only triggered when that is hovered.

```r
ea_icons("microphone")                                                      
```

```
[1] "path://M52,75.9V86h14c1.1,0,2,0.9,2,2s-0.9,2-2,2H34c-1.1,0-2-0.9-2-2s0.9-2,2-2h14V75.9\r\n\t\tc-13.4-1-24-12.3-24-25.9c0-1.1,0.9-2,2-2s2,0.9,2,2c0,12.1,9.9,22,22,22s22-9.9,22-22c0-1.1,0.9-2,2-2s2,0.9,2,2\r\n\t\tC76,63.7,65.4,74.9,52,75.9z M65,25v25c0,8.3-6.7,15-15,15s-15-6.7-15-15V25c0-8.3,6.7-15,15-15S65,16.7,65,25z M61,25\r\n\t\tc0-6.1-4.9-11-11-11s-11,4.9-11,11v25c0,6.1,4.9,11,11,11s11-4.9,11-11V25z"
```

You are by no means limited to these, you can use any other patterns you find or create. The only way to do what you ask is to recreate an SVG with a background.

Sorry.

**Comment by JohnCoene** [comment]
I'm going to go ahead and close this issue otherwise I lose track. Feel free to reopen if you think this can and should be implemented.
