### ISSUE TITLE
Axis formatter not applied after adding tooltip 

### ISSUE THREAD

**Issue by sprengholz** [JohnCoene/echarts4r#229]
Hi there! I added a custom date formatter for my x axis. The following code works fine, the dates are displayed in the correct format:

```
graph <- data %>% 
  e_charts(DATE) %>%
  e_line(POWER) %>%
  e_x_axis(formatter = htmlwidgets::JS("function (value) {return echarts.format.formatTime('dd.MM.yyyy', value);}"))
```

However, when I add a tooltip, the date formatter is not applied anymore:

```
graph <- data %>% 
  e_charts(DATE) %>%
  e_line(POWER) %>%
  e_x_axis(formatter = htmlwidgets::JS("function (value) {return echarts.format.formatTime('dd.MM.yyyy', value);}")) %>%
  e_tooltip()
```

I tried to swap the e_x_axis and e_tooltip commands. In this case, the date format is fine but the tooltip is not shown anymore.

**Comment by sprengholz** [comment]
After restarting R, problem did not show up again. Sorry for complaining...

**Comment by JohnCoene** [comment]
No problem, glad it's resolved
