### ISSUE TITLE
e_tooltip: show a picture

### ISSUE THREAD

**Issue by LuWinter** [JohnCoene/echarts4r#230]
Hi,

Is it possible to show a picture in the tooltip by adding a <img> path to JS function and passing to the formatter like this ?

```
region_sales %>%   
  e_chart(x = Region) %>%   
  e_pie(serie = Sales) %>%  
  e_labels(fontSize = 16) %>%   
  e_tooltip(formatter = htmlwidgets::JS("   
                function(params){   
                    var my_img = '<img class = \"img\" src =\"example.jpg\">';   
                return my_img;}")) 
```

I tried it and got this :
![test](https://user-images.githubusercontent.com/60804792/99207376-d0008600-27f8-11eb-8279-1d371de1b148.png)

**Comment by helgasoft** [comment]
Yes, it's possible.  Please provide an easily reproducible example next time.
```r
iris %>% group_by(Species) %>% summarise(across(.fns=median)) %>%
  e_chart(Species) %>% 
  e_pie(Petal.Length) %>%
  e_tooltip(formatter = htmlwidgets::JS("   
      function(params){   
          var my_img = '<img src =\"http://simpleicon.com/wp-content/uploads/beer-64x64.png\" height=30>';
      return my_img + '<br>'+ params.name +': '+ params.value;}")) 
```

**Comment by LuWinter** [comment]
Thanks a lot ！

And whether it is difficult to show a local image in the tooltip ? I read some answers about using local image in <img>. It is said that the local image should be put in the same folder with the html file, but we don`t have any html file when developing the shiny app ?

**Comment by helgasoft** [comment]
There is a file structure for Shiny.  One would use _&lt;img src='www/image1.png'&gt;_
   <application folder>
   |-- shiny.R
   |-- www
   &nbsp; &nbsp; &nbsp; |-- image1.png &nbsp; (and .css, etc.)

**Comment by LuWinter** [comment]
Yeah, it works very well in shiny!
You perfectly solved my problem !

**Comment by swsoyee** [comment]
@LuWinter Maybe you could try to change the slash in Windows.
ref: https://kb.iu.edu/d/azzp

**Comment by LuWinter** [comment]
I think the bug is not because of the slash in windows, here is my test code. It works in Linux but fails in windows

```
pacman::p_load(dplyr, echarts4r, shiny)

download.file(url = "http://simpleicon.com/wp-content/uploads/beer-64x64.png", 
              destfile = "www/test.png")
dir('www')
ui <- fluidPage(
  sidebarLayout(

    sidebarPanel(
    ),
    mainPanel(
      echarts4rOutput(outputId = "irisPlot")
    )
  )
)

server <- function(input, output) {
  output$irisPlot <- renderEcharts4r({
    iris %>% group_by(Species) %>% summarise(across(.fns=median)) %>%
      e_chart(Species) %>% 
      e_pie(Petal.Length) %>%
      e_tooltip(formatter = htmlwidgets::JS("   
      function(params){   
          var my_img = '<img src =\" test.png \" height=30>';
      return my_img + '<br>'+ params.name +': '+ params.value;}"))
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by JohnCoene** [comment]
It will likely depend on other things in your environment. Are using RStudio and the same version of shiny in both instances?

I suggest you explicitly serve the static files (images, and more) to avoid this issue.

```r
# place BEFORE ui
shiny::addResourcePath("assets", "www")
```

Then you can access images in `www` directory via the `assets` prefix e.g.: `<img src="assets/img.png" />`

**Comment by JohnCoene** [comment]
I'll go ahead and close this issue, I assume @helgasoft answered your question, feel free to reopen if that is not the case.
