### ISSUE TITLE
Boxplot with groups showing name of column instead of group

### ISSUE THREAD

**Issue by barveaditya** [JohnCoene/echarts4r#231]
df <- data.frame(
  x = c(
    rnorm(100),
    runif(100, -5, 10),
    rnorm(100, 10, 3)
  ),
  grp = c(
    rep(LETTERS[1], 100),
    rep(LETTERS[2], 100),
    rep(LETTERS[3], 100)
  )
)

df %>% 
  group_by(grp) %>% 
  e_charts() %>% 
  e_boxplot(x)

This example from your page creates three boxplots title 'x' on the x-axis rather than name of groups. please fix. 
![Screenshot 2020-11-16 at 16 15 36](https://user-images.githubusercontent.com/14080760/99278480-01904600-2827-11eb-98b8-097cdd86e8aa.png)

**Comment by JohnCoene** [comment]
Yes, that was fixed here https://github.com/JohnCoene/echarts4r/issues/219#issuecomment-715894870

Make sure you're on the latest version

**Comment by barveaditya** [comment]
@JohnCoene  - for some weird reason, no joy. 
![Screenshot 2020-11-17 at 09 22 16](https://user-images.githubusercontent.com/14080760/99371156-71014680-28b6-11eb-8ebe-aa132437d32e.png)

**Comment by JohnCoene** [comment]
Can you restart your R session after the install and try again please?

**Comment by barveaditya** [comment]
@JohnCoene thank you... that worked!! What exactly happened there?

**Comment by lianos** [comment]
You downloaded and installed a new version of echarts4r, but you still had the previous version loaded in your workspace.

**Comment by JohnCoene** [comment]
Yes indeed. `library` does not reload if the package is already in the environment.
