### ISSUE TITLE
Reset callback

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/echarts4r#233]
Is it possible to reset callbacks, e.g. id_clicked_data?

**Comment by JohnCoene** [comment]
Hi Tyler, 

No there is not. It could be implemented but would be somewhat hacky. Could you tell me what you are trying to achieve? This should not be necessary I think.

**Comment by tyluRp** [comment]
Hi John! I have a series of graphs where the top most graph updates the graphs beneath it. For example, I click a country and the graphs beneath it represent the data within that country. However, with so many of these, I am hoping I can give the user a "reset" button. Without reset logic, I fall into subset errors when binding data that is ultimately a blank dataframe due to filters that no longer make sense.

I am playing around with the idea of managing the reset logic on my own with `reactiveValues`.

**Comment by JohnCoene** [comment]
Yes, I would use reactive values as well.

```r
library(shiny)
library(echarts4r)

ui <- fluidPage(
  echarts4rOutput("main"),
  fluidRow(
    column(6, echarts4rOutput("plot1")),
    column(6, echarts4rOutput("plot2"))
  ),
  actionButton("btn", "reset to 10 obs")
)

server <- function(input, output){

  responsive <- reactiveValues(
    x = NULL,
    y = NULL
  )

  make_data <- function(x){
    samp <- runif(x)
    data.frame(
      x = 1:length(samp),
      y = samp
    )
  }

  output$main <- renderEcharts4r({
    e_chart(cars, speed) %>% 
      e_scatter(dist, symbol_size = 10)
  })

  observeEvent(input$main_clicked_data, {
    responsive$x <- input$main_clicked_data$value[1]
    responsive$y <- input$main_clicked_data$value[2]
  })

  output$plot1 <- renderEcharts4r({
    req(responsive$x)
    e_chart(make_data(responsive$x), x) %>% 
      e_scatter(y, symbol_size = 11)
  })

  output$plot2 <- renderEcharts4r({
    req(responsive$y)

    e_chart(make_data(responsive$y), x) %>% 
      e_scatter(y, symbol_size = 15)
  })

  observeEvent(input$btn, {
    responsive$x <- 10
    responsive$y <- 10
  })

}

shinyApp(ui, server)
```

**Comment by tyluRp** [comment]
Thanks! I will give it a try.
