### ISSUE TITLE
Possible to change order of the timeline items? update: show right labels

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#234]
I noticed the order of the timeline is determined alphabetically. Is it op possible to change the order of the timeline items customizable? 
Many thanks in advance!

**Comment by JohnCoene** [comment]
Would you have a reprex? It should not reorder factor and character vectors, only numerics.

You can also ensure the data and groups are in the correct order before passing it to `e_charts` and use `reorder = FALSE`, e.g.: `e_charts(data, reorder = FALSE)`

**Comment by rdatasculptor** [comment]
Thank you for your quick response!

I can show you what I mean with one your examples:

```
df <- data.frame(
  year = c(
    rep(2016, 25),
    rep(2017, 25),
    rep(2018, 25),
    rep(2019, 25)
  ),
  x = rnorm(100),
  y = rnorm(100),
  grp = c(
    rep("A", 50),
    rep("B", 50)
  )
) 
#let me reorder the year variable by turning it into a factor and changing the level order
df$year <- factor(df$year, levels = c("2019","2018","2016","2017"))

df %>%
  group_by(year) %>% 
  e_charts(x, timeline = TRUE %>% 
  e_scatter(y, symbol_size = 5)

df %>%
  group_by(year) %>% 
  e_charts(x, timeline = TRUE, reorder = FALSE) %>% 
  e_scatter(y, symbol_size = 5)
```
Both plots will give a timeline orderd in alphabetical/numerical order.

**Comment by JohnCoene** [comment]
That was a bug indeed, I just pushed a fix. Could you try again and let me know if this works?

**Comment by rdatasculptor** [comment]
Yes it definately works now! thank you so much!
