### ISSUE TITLE
How to add legend of stacked bars in case of timeline?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#235]
If I make a stacked bar chart, I can add a nice looking legend. 

Like this (and I am thankfully using one of your examples again :)):

```r
set.seed(321)
df1 <- data.frame(
  x = LETTERS[1:10],
  a = runif(10),
  b = runif(10),
  c = runif(10),
  d = runif(10),
  group = 1
)

df1 %>% 
  e_charts(x) %>% 
  e_bar(a, stack = "grp") %>% 
  e_bar(b, stack = "grp") %>% 
  e_bar(c, stack = "grp2") %>% 
  e_bar(d, stack = "grp2") 
```

However, the legend dissappears when adding a timeline by using a `group_by()`.

```r
set.seed(123)
df2 <- data.frame(
  x = LETTERS[1:10],
  a = runif(10),
  b = runif(10),
  c = runif(10),
  d = runif(10),
  group = 2
)
df <- bind_rows(df1, df2)

df %>% 
  group_by(group) %>%
  e_charts(x, timeline = TRUE) %>% 
  e_bar(a, stack = "grp") %>% 
  e_bar(b, stack = "grp") %>% 
  e_bar(c, stack = "grp2") %>% 
  e_bar(d, stack = "grp2") %>%
  e_legend(show = TRUE)

```
As you can see the timeline appears at the bottom of the graph, but the legend, with the meaning of the stacked bars disappears. Is there a way to get the legend back? Or could this be some kind of bug?

Many thanks in advance!

**Comment by JohnCoene** [comment]
I'll try and debug that this week; it requires explicitly using the `name` when using the timeline.

```r
devtools::load_all()

set.seed(321)
df1 <- data.frame(
  x = LETTERS[1:10],
  a = runif(10),
  b = runif(10),
  c = runif(10),
  d = runif(10),
  group = 1
)

set.seed(123)
df2 <- data.frame(
  x = LETTERS[1:10],
  a = runif(10),
  b = runif(10),
  c = runif(10),
  d = runif(10),
  group = 2
)
df <- dplyr::bind_rows(df1, df2)

df %>% 
  group_by(group) %>%
  e_charts(x, timeline = TRUE) %>% 
  e_bar(a, stack = "grp", name = "a") %>% 
  e_bar(b, stack = "grp", name = "b") %>% 
  e_bar(c, stack = "grp2", name = "c") %>% 
  e_bar(d, stack = "grp2", name = "d") 
```

**Comment by rdatasculptor** [comment]
yes, it works with this solution! I would never had found out myself. Thanks!

**Comment by JohnCoene** [comment]
Closed by accident, will fix so default show the legend

**Comment by JohnCoene** [comment]
Thanks for reporting this again, last commit should fix this.

**Comment by rdatasculptor** [comment]
I wanted it to try it, but when installing the newest github version the package doesn't seem to contain the function `e_hide_grid_lines` anymore. Was this intented? Or maybe I did something wrong during the intallation.

**Comment by rdatasculptor** [comment]
For what's worth it I've tested the fix for this issue. I can confirm the fix was a succes! Thanks again.
