### ISSUE TITLE
Enhance Sunburst chart via allowing specifying itemStyle by each slice

### ISSUE THREAD

**Issue by happyshows** [JohnCoene/echarts4r#24]
Maybe like below? Didn't get a chance to modify the wrappers.

```
.build_sun <- function(e, parent, child, value, itemStyle){
  e$x$data %>%
    dplyr::select_(
      parent,
      name = child,
      value = value,
      itemStyle = itemStyle
    ) -> data
  
  d3r::d3_nest(data, value_cols = c("value","itemStyle"), json = FALSE, root = NULL) -> x
  x <- x[["children"]][[1]]
  x$colname <- NULL
  jsonlite::toJSON(x, auto_unbox = T, pretty = FALSE)
}
```

**Comment by JohnCoene** [comment]
Hi Shows,

Thank you for the suggesting. I have implemented it, the only issue being that `itemStyle` is not applied to `parent` and only to `child`. `itemStyle` is an array in the original library which means we need to pass a `list` of `data.frame`s or a `list` of `list`s.

It is imperfect but may work in future version. I plan on focusing more on `echarts4r` around October once work quiets down, I'll tackle this issue (amongst many others).

**example**

```r
df <- data.frame(
  parent = c("earth", "earth", "earth", "mars", "mars"), 
  child = c("forest", "ocean", "iceberg", "elon", "curiosity"),
  value = ceiling(rnorm(5, 10, 2))
)

df$color <- "red"
df$borderColor <- "black"

df %>% 
  tidyr::nest(color, borderColor, .key = "style") %>%
  e_charts() %>% 
  e_sunburst(parent, child, value, style) 
```

Let me know what you think.

**Comment by happyshows** [comment]
cool thanks. I'll continue to post code chunks where I see maybe useful, you can take a look when you're available.

**Comment by happyshows** [comment]
@JohnCoene could you take a look at your example code again? Latest version is breaking your example.

**Comment by JohnCoene** [comment]
Hi Shows, I must thank you for sticking to the package despite all its bugs! I just pushed a fix. Thanks for reporting that :)

**Comment by JohnCoene** [comment]
By the way, I also pushed some great performances improvements (in the rendered data.frame) by greatly lightening the output, I hope you see a difference.

**Comment by kovla** [comment]
I think it would be really useful to include the example of using `itemStyle=` in the help section for this function. It is hard to discern what the desired format should be, and the error message itself is not very informative.
