### ISSUE TITLE
e_zoom and Shiny

### ISSUE THREAD

**Issue by helgasoft** [JohnCoene/echarts4r#240]
Tried to use the **e_zoom** example in a Shiny context. Doesn't seem to work thru the proxy...
```r
library(shiny); library(echarts4r)
runApp( list( 
  ui = fluidPage( 
    actionButton("zm", "Zoom"),
    echarts4rOutput("plot"),
  ),
  server = function(input, output, session){

    output$plot <- renderEcharts4r({
      cars %>%
        e_charts(dist) %>%
        e_scatter(speed) %>%
        e_datazoom()
    })
    
    observeEvent(input$zm, {
      echarts4rProxy("plot") %>% 
        e_zoom(
          dataZoomIndex = 0,
          start = 20, end = 40
        )
    })
  }))
```

**Comment by JohnCoene** [comment]
Yes indeed. I started implementing most proxies then realised there were too many so I created `e_dispatch_action_p`: there's an example for datazoom in the documentation, [here](https://echarts4r.john-coene.com/reference/e_dispatch_action_p.html)

**Comment by helgasoft** [comment]
oops, missed this one.  It works - thanks.
Maybe e_zoom should be retired then.

**Comment by JohnCoene** [comment]
No problem, it's the package's fault. `e_zoom` is for buttons, there's an example of it in the man page.
