### ISSUE TITLE
Possible to use different colors per category in combination with timeline in scatterplot with category axis?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#243]
I think I have an simple question, that maybe is less simple to be answered. I was wondering if there is a way to use both timeline functions and to give categories different color each in a scatterplot. I looked in the official echarts documentation, but I couldn't find anything that looked like an answer.

If I do something like this:

```r
df <- data.frame(
  year = c(
    rep(2016, 25),
    rep(2017, 25),
    rep(2018, 25),
    rep(2019, 25)
  ),
  x = rep(letters[1:4],25),
  y = rnorm(100),
  grp = c(
    rep("A", 50),
    rep("B", 50)
  )
) 
df %>%
  group_by(year) %>% 
  e_charts(x, timeline = TRUE) %>% 
  e_scatter(y, symbol_size = 20)

```
You can see the x axis has 4 categories: a, b, c and d. Is it possible to give dots that belong to the same category its own category color? So in this case there would be four different colors, for each category one. How can I do this?

Many thanks in advance!

**Comment by JohnCoene** [comment]
Sorry, I'm afraid it's not possible.

One can use the visual map based on the y axis like so:

```r
library(echarts4r)

df <- data.frame(
  year = c(
    rep(2016, 25),
    rep(2017, 25),
    rep(2018, 25),
    rep(2019, 25)
  ),
  x = rep(letters[1:4],25),
  y = rnorm(100),
  grp = c(
    rep("A", 50),
    rep("B", 50)
  )
)

df %>%
  group_by(year) %>% 
  e_charts(x, timeline = TRUE) %>% 
  e_scatter(y, symbol_size = 20) %>%
  e_visual_map(
    type = "piecewise",
    pieces = list(
      list(gt = 0, lt = 2),
      list(gt = -3, lt = 0)
    ),
    outOfRange = "grey"
  )
```

Alternatively you could highlight those regions with [this](https://echarts.apache.org/examples/en/editor.html?c=area-pieces)

**Comment by rdatasculptor** [comment]
Thank you for your suggestions! I will take a look.  I will close the issue.

**Comment by JohnCoene** [comment]
Thanks, sorry it cannot be done.

**Comment by rdatasculptor** [comment]
I suddenly had an idea, it can be done using` e_add`!

e.g. like this:

```
df <- data.frame(
  year = c(
    rep(2016, 25),
    rep(2017, 25),
    rep(2018, 25),
    rep(2019, 25)
  ),
  x = rep(letters[1:4],25),
  y = rnorm(100),
  grp = c(
    rep("A", 50),
    rep("B", 50)
  )
) 
df %>% mutate(color=ifelse(x=="a","blue", 
                           ifelse(x=="b","yellow",
                                  ifelse(x=="c", "red","green")))) %>%
  group_by(year) %>% 
  e_charts(x, timeline = TRUE) %>% 
  e_scatter(y, symbol_size = 20) %>%
  e_add("itemStyle", color)
```
