### ISSUE TITLE
Removal of annoying behaviour in package installation

### ISSUE THREAD

**Issue by happyshows** [JohnCoene/echarts4r#25]
Hi,

I found it a bit annoying to see below chain of installations whenever I try to update the package. Could you keep the Import list to essential and move them to suggests? I believe the latter one won't trigger installation of dependent package each time.

d3r/data.tree -> visNetwork -> DiagrammeR

**Comment by JohnCoene** [comment]
I will look into this, the package is very large indeed. `data.tree` is only required for one function which makes it annoying (`e_tree` of course) I think I can replace that with `d3r` (already in use).

**Comment by happyshows** [comment]
my point is we can still use the functions as-is without re-installing them by moving it to suggest.(I believe that's the case) If any user did not install d3r for example, their code will crash once. But it will save us from quick iterations during development.

**Comment by JohnCoene** [comment]
Done!
