### ISSUE TITLE
How to use e_gauge with timeline?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#251]
The documentation says that `e_gauge` is one the supported chart types that makes it possible to use the timeline feature.
Is there maybe an example somewhere that I can use to make it work?

When I try things like:

```
df <- data.frame(group=c(1,2), value=c(10,90))

df %>% group_by(group) %>%
e_charts(timeline=TRUE) %>%
  e_gauge(value, "PERCENT")
```

It fails with error:

```
Error in e_gauge.echarts4r(., value, "PERCENT") : 
  object 'value' not found
```

Obviously this not the way to go. Can you please point me in the right direction if possible?

Many thanks in advance!

**Comment by JohnCoene** [comment]
I think @etiennebacher just put a neat fix, it should work nicely now.

**Comment by etiennebacher** [comment]
For future visitors of this issue, the code above won't work but must be replaced with:
```
df <- data.frame(group=c(1,2), value=c(10,90))

df %>% group_by(group) %>%
  e_charts(timeline=TRUE) %>%
  e_gauge_("value", "PERCENT")
```

**Comment by rdatasculptor** [comment]
Thank you for the fix Etienne! It's very helpful.
