### ISSUE TITLE
chart_types.rmd vignette won't knit, correction suggested

### ISSUE THREAD

**Issue by Stephen-McDaniel** [JohnCoene/echarts4r#258]
First, incredible work!  Thank you!

Working with the vignettes, this one wouldn't knit. Eliminated lowest level NULL and now it knits. 

Removed NULL in tree tibble, starting at line 251:

`tree <- tibble(
  name = "earth",        # 1st level
  children = list(
    tibble(name = c("land", "ocean"),             # 2nd level
       children = list(
         tibble(name = c("forest", "river")),   # 3rd level 
         tibble(name = c("fish", "kelp"),
            children = list(
               tibble(name = c("shark", "tuna"),  # 4th level 
               children = c("tuna", "triggerfish")
            ))
         )
       ))
  )
)
`

Changed from:
`
tree <- tibble(
  name = "earth",        # 1st level
  children = list(
    tibble(name = c("land", "ocean"),             # 2nd level
       children = list(
         tibble(name = c("forest", "river")),   # 3rd level 
         tibble(name = c("fish", "kelp"),
            children = list(
               tibble(name = c("shark", "tuna"),  # 4th level 
               NULL  # kelp
            ))
         )
       ))
  )
)
`

**Comment by JohnCoene** [comment]
Apologies for this.

It works but on the dev version. You just happen to catch a specific part of the API that was in flux at the time.

I have moreover changed some of these example to demonstrate how it works with [data.tree](https://cran.r-project.org/web/packages/data.tree/index.html) which is much easier to work with than nested tibbles.
