### ISSUE TITLE
Toolbox tooltip in Chinese

### ISSUE THREAD

**Issue by happyshows** [JohnCoene/echarts4r#26]
Hi John,

It appears that all tooltip features are in Chinese. Is there a way to toggle it to English? I can help you translate that.

**Comment by JohnCoene** [comment]
Hey Shows,

Thanks but that's built-in the library as such (since eCharts is mainly developed by Baidu), I'm unsure as to how we could translate the titles.

**Comment by kovla** [comment]
This indeed would be very useful. Chinese characters would be a deal breaker for many applications, especially commercial ones. This might be relevant: https://github.com/apache/incubator-echarts/issues/2321

**Comment by JohnCoene** [comment]
Thanks! I'll try that, just worried that the translated file is a bit old and from a previous version.

**Comment by JohnCoene** [comment]
Updated the underlying JavaScript libraries, [toolbox documentation](https://echarts4r.john-coene.com/articles/toolbox.html) is now in English.

**Comment by happyshows** [comment]
Great, thanks John.
