### ISSUE TITLE
Surface plots not showing up correctly

### ISSUE THREAD

**Issue by mattwarkentin** [JohnCoene/echarts4r#262]
Hi John,

I'm not sure if I've done something wrong or formatted my data incorrectly, but my surface plot seems to form an envelope, rather than simply a sheet. Should be reproducible with:
```r
library(tidyverse)
library(echarts4r)

z <- function(x, y) {
  x * (y ^ 2)
}

data <-
  expand_grid(
    x = seq(0, 2, by = 0.1), 
    y = seq(0, 1, by = 0.1)
  ) %>% 
  mutate(z = z(x, y))

data %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```

**Comment by mattwarkentin** [comment]
Actually the example code in `?e_surface` doesn't look right either...
```r
data("volcano")

surface <- as.data.frame(as.table(volcano))
surface$Var1 <- as.numeric(surface$Var1)
surface$Var2 <- as.numeric(surface$Var2)

surface %>%
  e_charts(Var1) %>%
  e_surface(Var2, Freq) %>%
  e_visual_map(Freq)
```
![Screen Shot 2021-01-14 at 12 36 11 PM](https://user-images.githubusercontent.com/27825069/104627513-1d686a80-5665-11eb-8920-a1329978714c.png)

**Comment by mattwarkentin** [comment]
This is using the current dev version on GitHub, for context.

**Comment by JohnCoene** [comment]
I'm not sure how to fix this, it's definitely on ECharts.js side. I get the same from the online editor pasting in the data generated by your example, see below.

![image](https://user-images.githubusercontent.com/7833796/104633450-705f1380-569f-11eb-8b9f-948f7ddefce4.png)

**Comment by mattwarkentin** [comment]
Hmm, there has to be some issue with how the data are structured - in a way that `ECharts.js` doesn't like. But I can't figure it. 

When I try to replicate their 3D surface example [here](https://echarts.apache.org/examples/en/editor.html?c=surface-wave&gl=1), it works in `R`...
```r
library(tidyverse)
library(echarts4r)

expand_grid(
  x = seq(-3, 3, by = 0.05),
  y = seq(-3, 3, by = 0.05)
) %>% 
  mutate(z = sin(x * x + y * y) * x / 3.14) %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```
![Screen Shot 2021-01-14 at 2 38 17 PM](https://user-images.githubusercontent.com/27825069/104640098-2ca3e400-5676-11eb-8db7-3ba645306952.png)

**Comment by mattwarkentin** [comment]
Okay, getting closer. I think it doesn't like strictly positive domains for X and Y. I adapted my original example to be spanning zero on for X and Y...
```r
expand_grid(
  x = seq(-1, 1, by = 0.1), 
  y = seq(-1, 1, by = 0.1)
) %>% 
  mutate(z = x * (y ^ 2)) %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```
![Screen Shot 2021-01-14 at 2 40 37 PM](https://user-images.githubusercontent.com/27825069/104640447-7f7d9b80-5676-11eb-94df-9f4b3f6e1a49.png)

**Comment by mattwarkentin** [comment]
Scratch that, everything is working right all of a sudden...

**Comment by mattwarkentin** [comment]
Nope, this isn't true...let me dig into this more...

**Comment by mattwarkentin** [comment]
Okay, for some reason it doesn't like the X-axis have a wider domain the Y-axis. I have no idea why this would be true. But if the X-axis spans more of the real number line than Y, it formats wonky.

**Comment by JohnCoene** [comment]
I seem to have understood what it is but it's a bit late and my brain is mush: can't figure out exactly how to fix this.

_Order matters_

Your original example works, below I scramble it... that breaks.

```r

library(dplyr)

scramble <- function(data){
  x <- sample(1:nrow(data), nrow(data))
  data[x, ]
}

data <- expand.grid(
  x = seq(-3, 3, by = 0.05),
  y = seq(-3, 3, by = 0.05)
) %>% 
  mutate(z = sin(x * x + y * y) * x / 3.14) %>% 
  scramble()

data %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```

**Comment by mattwarkentin** [comment]
Somehow we both seem to have found different ways to break it...

**Comment by mattwarkentin** [comment]
Works
expand_grid(
  x = seq(-3, 3, by = 0.05),
  y = seq(-3, 3, by = 0.05)
) %>% 
  mutate(z = sin(x * x + y * y) * x / 3.14) %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)


Doesn't
```r
expand_grid(
  x = seq(-3, 4, by = 0.05), # only difference
  y = seq(-3, 3, by = 0.05)
) %>% 
  mutate(z = sin(x * x + y * y) * x / 3.14) %>% 
  e_charts(x) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```

**Comment by JohnCoene** [comment]
That's some flimsy chart type.

**Comment by JohnCoene** [comment]
I'm not sure what `surface` wants from us really.

```r
data("volcano")

surface <- as.data.frame(as.table(volcano))
surface$Var1 <- as.numeric(surface$Var1)
surface$Var2 <- as.numeric(surface$Var2)

rng <- c(0, 1)

surface %>%
  mutate(
    Var1 = scales::rescale(surface$Var1, to = rng),
    Var2 = scales::rescale(surface$Var2, to = rng),
    Freq = scales::rescale(surface$Freq, to = rng)
  ) %>% 
  arrange(Var1, Var2, Freq) %>% 
  e_charts(Var1) %>%
  e_surface(Var2, Freq) %>%
  e_visual_map(Freq)
```

**Comment by JohnCoene** [comment]
_I checked, version of echarts.js and echarts GL match_

**Comment by mattwarkentin** [comment]
Hmm, very odd indeed...

**Comment by helgasoft** [comment]
This _data_ parameter is shaky, better use _equation_
```r
tmp <- e_chart() %>% e_surface(y=NULL, z=NULL)
tmp$x$opts$series[[1]] <- list(
    type = 'surface',
    equation = list(
          x = list(min=-3,max=4,step=0.05), 
          y = list(min=-3,max=3,step=0.05), 
          z = htmlwidgets::JS("function (x, y) { return Math.sin(x * x + y * y) * x / Math.PI; }")
    )
)
tmp
```

**Comment by helgasoft** [comment]
... and reading the [docs](https://echarts.apache.org/en/option-gl.html#series-surface.data) one more time solves the problem. It's the **order** of the coordinates that matters - leading is Y, not X.
```r
coord <- list()
for (y in seq(0, 1, by = 0.1))
  for (x in seq(0, 2, by = 0.1)) {
    z <- x * (y ^ 2)
    coord <- c(coord, list(list(x,y,z)))
  }
tmp <- e_chart() %>% e_surface(y=NULL, z=NULL)
tmp$x$opts$series[[1]] <- list(
  type = 'surface',
  data = coord    # nothing wrong with data param
)
tmp
```

**Comment by JohnCoene** [comment]
I had forgotten I did at that option a long time ago (sorry too many features in echarts4r I lose track myself).

Data must be ordered in most cases (x axis), you prevent that with the `reorder = FALSE` when initialising the plot.

```r
data("volcano")

surface <- as.data.frame(as.table(volcano))
surface$Var1 <- as.numeric(surface$Var1)
surface$Var2 <- as.numeric(surface$Var2)

surface %>%
  e_charts(Var1, reorder = FALSE) %>%
  e_surface(Var2, Freq) %>%
  e_visual_map(Freq)
```

**Comment by mattwarkentin** [comment]
That doesn't seem to solve the original issue:
```r
library(tidyverse)
library(echarts4r)

expand_grid(
  x = seq(0, 2, by = 0.1), 
  y = seq(0, 1, by = 0.1)
) %>% 
  mutate(z = x * (y ^ 2)) %>% 
  e_charts(x, reorder = FALSE) %>% 
  e_surface(y, z) %>% 
  e_visual_map(z)
```

**Comment by helgasoft** [comment]
gotta start with (leading) Y
```r
library(tidyverse)
library(echarts4r)
expand_grid(
    y = seq(0, 1, by = 0.1),
    x = seq(0, 2, by = 0.1)
) %>% 
    mutate(z = x * (y ^ 2)) %>% 
    e_charts(x, reorder = FALSE) %>% 
    e_surface(y, z) %>% 
    e_visual_map(z)
```

**Comment by mattwarkentin** [comment]
Fair enough. Thanks.
