### ISSUE TITLE
Connected charts with the same legend

### ISSUE THREAD

**Issue by adsoncostanzifilho** [JohnCoene/echarts4r#263]
Is there some way to have the connected graphics sharing the same legend?

For example [here](https://echarts4r.john-coene.com/articles/connect.html) you presented connected graphics sharing the same legend. However, I would like to have the legend just for the **first graphic** and make the others interactive based on just one legend.

I have tried something like this:

```r
require(echarts4r)
require(dplyr)

base_chart <- mtcars %>% 
    e_charts(x = mpg, height = 200) %>% 
    e_group("4charts") # all charts in the same group
  
e4 <- base_chart %>% e_scatter(hp, name = "Click me!")
e5 <- base_chart %>% e_scatter(wt, name = "Click me!", legend =FALSE)
e6 <- base_chart %>% e_scatter(drat, name = "Click me!", legend =FALSE)
e7 <- base_chart %>% e_scatter(qsec, name = "Click me!", legend =FALSE) %>%
  e_connect_group("4charts") # connect charts

e_arrange(e4, e5, e6, e7, rows = 2, cols = 2)
```

The graphics are connected when we hover the legend, but when we click on the legend it only disables the first one.

Thank you!

**Comment by JohnCoene** [comment]
When you pass `legend = FALSE` the serie is not added the legend storage (internal). It's difficult to explain but essentially you want to include every serie in the legend but you only want to show one, see below.

```r
base_chart <- mtcars %>% 
    e_charts(x = mpg, height = 200) %>% 
    e_group("4charts") # all charts in the same group
  
e4 <- base_chart %>% e_scatter(hp, name = "Click me!")
e5 <- base_chart %>% e_scatter(wt, name = "Click me!") %>% e_legend(FALSE)
e6 <- base_chart %>% e_scatter(drat, name = "Click me!") %>% e_legend(FALSE)
e7 <- base_chart %>% e_scatter(qsec, name = "Click me!") %>% e_legend(FALSE) %>%
  e_connect_group("4charts") # connect charts

e_arrange(e4, e5, e6, e7, rows = 2, cols = 2)
```

**Comment by adsoncostanzifilho** [comment]
That is exactly what I was looking for!

Thank you for your help, and thank you for this awesome package!
