### ISSUE TITLE
stacked bar charts stack names

### ISSUE THREAD

**Issue by Stephen-McDaniel** [JohnCoene/echarts4r#265]
May I ask what is the logic of stack="grp" and stack="grp2" in the stacked bar example? 

What does the two unique names of the stacks do from a presentation/interaction level? From what I can gather, the groups are placed in front of/behind of each other?

Thanks.

```r
df <- data.frame(
  x = LETTERS[1:10],
  a = runif(10),
  b = runif(10),
  c = runif(10),
  d = runif(10)
)

df %>% 
  e_charts(x) %>% 
  e_bar(a, stack = "grp") %>% 
  e_bar(b, stack = "grp") %>% 
  e_bar(c, stack = "grp2") %>% 
  e_bar(d, stack = "grp2") 
```

**Comment by JohnCoene** [comment]
On the chart this produces serie `a`, and `b` are stacked on top of one another and `c`, and `d` are stacked separately.

Then those two group are side-by-side (dodge in ggplot2).

![image](https://user-images.githubusercontent.com/7833796/105056487-8b050400-5a74-11eb-8edf-df33d990108e.png)

Not sure I do a great job of explaining

**Comment by Stephen-McDaniel** [comment]
Hi John,

This makes sense from a technical standpoint. It is a subgroup of the X-axis group. 

Visually, it is a bit tricky to decide when to use this...

By the way, incredible work on this package! 

Thank you
