### ISSUE TITLE
Liquifill and Wordcloud are not Shown in Home Page

### ISSUE THREAD

**Issue by swsoyee** [JohnCoene/echarts4r#267]
Maybe the reason is the echarts version has been update to 5.0.
https://echarts4r.john-coene.com/articles/chart_types.html

![image](https://user-images.githubusercontent.com/20528423/106086024-a9e65300-6164-11eb-8e6f-de36c8e9eab1.png)

More investigation needed.

**Comment by JohnCoene** [comment]
Yes indeed, just pushed a fix. Thanks.
