### ISSUE TITLE
user defined fill colors for e_bar?

### ISSUE THREAD

**Issue by bklingen** [JohnCoene/echarts4r#270]
I'm looking for a way to specify user-defined fill colors for bar charts, something along the `ggplot` equivalent of
```{r}
library(ggplot2)
plotdata <- data.frame(x=c("a","b"), y=5:6, z=factor(1:2))
ggplot(data=plotdata, aes(x=x, y=y, fill=z)) +
  geom_col()
```

I understand why 
```{r}
library(echarts4r)
e_charts(data=plotdata, x=x) %>%
  e_bar(y) %>%
  e_color(c("red", "blue"))
```
doesn't work, but is there a simple alternative?
(My use case is to plot somewhere between 5 and 100 bars, and to color a few of them in different colors.)
Thanks!

**Comment by swsoyee** [comment]
Hi, you could set each bar color by setting `itemStyle`:
https://echarts.apache.org/en/option.html#series-bar.itemStyle

Something like:
```r
library(echarts4r)
e_charts(data = plotdata, x = x) %>%
  e_bar(y, itemStyle = list(color = 'black'))
```

**Comment by bklingen** [comment]
Thanks! The second option, grouping the data, works great!

I tried the first using `itemstyle` as well, but it seems to only accept a single color. The echart example [here](https://echarts.apache.org/examples/en/editor.html?c=bar-data-color) shows how the `itemstyle` has to be specifically tied to the datapoint in the series defining the bar.

I simplified [this other example](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category-stack) a bit to show the options directly that would yield a bar chart with three bars, each of a different color, but it uses "empty" arrays such as [
```
option = {
    xAxis: {
        type: 'category',
        data: [1, 2, 3]
    },
    yAxis: {
        type: 'value'
    },
    series: [
        {
            type: 'bar',
            stack: 'total',
            data: [4, , ,]
        },
        {
            type: 'bar',
            stack: 'total',
            data: [, 7, ,]
        },
        {
            type: 'bar',
            stack: 'total',
            data: [, , 5]
        }
    ]
}
```
This translates to R code as:
```{r}
opts <- list(
  xAxis = list(
    type = "category",
    data = c(1,2,3)
  ),
  yAxis = list(
    type = "value"
  ),
  series = list(
    list(
      type = "bar",
      stack = "total",
      data = c(4,NA,NA),
      color = "red"
    ),
    list(
      type = "bar",
      stack = "total",
      data = c(NA,7,NA),
      color = "blue"
    ),
    list(
      type = "bar",
      stack = "total",
      data = c(NA,NA,5),
      color = "green"
    )
  )
)

e_charts() %>% 
  e_list(opts)
```
which gives 
![image](https://user-images.githubusercontent.com/4784206/107319851-9b097580-6a6d-11eb-9c14-1152999f7056.png)
but wouldn't scale well to more categories.
