### ISSUE TITLE
endLabel initialize

### ISSUE THREAD

**Issue by jordancampbell23** [JohnCoene/echarts4r#274]
Hi,

I think I may be missing something relatively simple, but encountering a hiccup with endLabel on a date/time variable. It works by row number. When initializing by a non-row number variable I'm encountering NA values.

The first example below is an example of this issue. The second is a work around.

```r
sample <- data.frame(year = 1901:2000,
                     values = seq(from = 55, to = 75, length.out = 100) * rnorm(100, 1, 0.03))

sample %>%
  mutate(year = as.character(year)) %>%
  e_chart(year) %>%
  e_line(values,
         endLabel = list(show = T,
                         formatter = htmlwidgets::JS("
                          function (params) {
                    return(params.value[1])}
                                                      "))) %>%
  e_animation(duration = 10000)

sample %>%
  mutate(row = row_number()) %>%
  e_chart(row) %>%
  e_line(values,
         endLabel = list(show = T,
                         formatter = htmlwidgets::JS("
                          function (params) {
                    return(params.value[1])}
                                                      "))) %>%
  e_animation(duration = 10000)
```

Thanks in advance!

**Comment by JohnCoene** [comment]
I'm not sure what's wrong but it's an issue in echarts4r by the looks of it.

It works if you pass `year` as a numeric then set the axis type to `category.`

```r
sample %>%
  e_chart(year) %>%
  e_line(
    values,
    endLabel = list(
      show = TRUE,
      formatter = "{@[1]}",
      valueAnimation = TRUE
    )
  ) %>%
  e_animation(duration = 10000) %>% 
  e_x_axis(type = "category")
```

**Comment by JohnCoene** [comment]
Ah, I think I know what the issue is, it's the upgrade to version 5 and how axis are treated. I'll try to sort this out.

**Comment by jordancampbell23** [comment]
Great, thank you!

Your fix worked great for the example I provided.

I did run into an issue w/ more granular dates, but developed a workaround...little hack but may help someone.

`
year <- c(rep(2010, 12),
          rep(2011, 12),
          rep(2012, 12),
          rep(2013, 12),
          rep(2014, 12),
          rep(2015, 12),
          rep(2016, 12),
          rep(2017, 12),
          rep(2018, 12),
          rep(2019, 12))


year <- (year + seq(from = 0, to = 0.9166666, length.out = 12))



sample <- data.frame(year = year,
                     values = 1:120)


sample %>%
  e_chart(year) %>%
  e_line(
    values,
    endLabel = list(
      show = TRUE,
      formatter = "{@[1]}",
      valueAnimation = TRUE
    )
  ) %>%
  e_animation(duration = 10000) %>% 
  e_x_axis(type = "category",
           formatter = htmlwidgets::JS("function (value, index) {return Math.round(value);}")
  )
`

**Comment by JohnCoene** [comment]
Ah but here `year` is a actually not representing a year but a double/numeric. So there's no need for hack I think, using min max will do.

```r
sample %>%
  e_chart(year) %>%
  e_line(
    values,
    endLabel = list(
      show = TRUE,
      formatter = "{@[1]}",
      valueAnimation = TRUE
    )
  ) %>%
  e_animation(duration = 10000) %>% 
  e_x_axis(min = 2010, max = 2020)
```

Unless I am missing something

**Comment by jordancampbell23** [comment]
Yes, that works perfectly! Thanks again!
