### ISSUE TITLE
Problem setting label width and height

### ISSUE THREAD

**Issue by ymansiaux** [JohnCoene/echarts4r#277]
Hi,

I have issues trying to modify the width and height of the label text block.

```
df <- state.x77 %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("State")

df %>% 
  e_charts(x = State) %>% 
  e_line(serie = Population,
         label = list(show= TRUE, backgroundColor = "yellow", width = 90, height = 90)) 
```

I manage to change many parameters such as backgroundColor, fontSize etc .... but it seems that changing the values of width and height has no effect on the size of the yellow text area.

Thanks for your help

Yohann

**Comment by JohnCoene** [comment]
I can't make this work either but it's not echarts4r, options for with and height are correctly serialised so I think it's on echarts.js' side :(

**Comment by ymansiaux** [comment]
Thanks for your answer.
What I don't understand is that this parameter works perfectly when I use the "try it out" option in Echarts documentation website ...

**Comment by ymansiaux** [comment]
@JohnCoene I may have found something : https://echarts.apache.org/v4/en/option.html#series-line.emphasis.label.height

"Notice, width and height only work when rich specified."  I am going to try to add the "rich" parameter

**Comment by ymansiaux** [comment]
@JohnCoene 

Here is the solution : 

using ```echarts4r v0.3.3```
```
df %>% 
  e_charts(x = State) %>% 
  e_line(serie = Population,
         label = list(show= TRUE, backgroundColor = "yellow", width = 90, height = 90, rich = list())) 
```
However I had additionnal issues with parameters such as verticalAlign .... Using "rich" is not that clear to me.

using ```echarts4r v0.4.0.9000``` everything is OK

```
df %>% 
  e_charts(x = State) %>% 
  e_line(serie = Population,
         label = list(show= TRUE, backgroundColor = "yellow", width = 50, height = 40, 
                     verticalAlign = "middle",
                      align = "center")) 
```

**Comment by JohnCoene** [comment]
Ah, sorry, it's going to be somewhat confusing as echarts.js just updated to version 5, the latest version of echarts4r is also on version 5 but the CRAN version is on version  4. Therefore sme of the options you see in the official documentation will not work with the CRAN version.

**Comment by ymansiaux** [comment]
Thanks very much for your quick answers, and for your great work with echarts4r :-)
