### ISSUE TITLE
horizontal bar with axis index

### ISSUE THREAD

**Issue by HRAnalytics** [JohnCoene/echarts4r#28]
I have some trouble with using e_flip_coords() and x.index or y.index. When I use it together I have a blank page. Maybe have another way to build horizontal bar without using e_flip_coords()?

For example:

library(echarts4r)
library(plyr)
library(dplyr)

USArrests %>% 
    mutate(State = rownames(USArrests)) %>%
    slice(1:5) %>%
    e_charts(State) %>%
    e_bar(Murder, y.index = 0) %>%
    e_bar(Rape, y.index = 1) %>%
    e_flip_coords()

Not work, but without e_flip_coords() is working well.

**Comment by JohnCoene** [comment]
That would not work because you can have multiple y axis but not x axis, when you flip them you essentially invert those and end up with two x axis and a single y axis.
