### ISSUE TITLE
Using `e_axis_formatter()` in the axis formatter causes duplicate axis labels

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#281]
Using `e_axis_formatter()` in the axis formatter causes duplicate axis labels.

```r
df <- data.frame(
  x = LETTERS[1],
  group = c(1,1,1,2,2,2),
  a = c(1,0,0,1,1,1),
  b = c(1,0,1,0,1,1),
  c = c(0,1,1,1,1,0)
)

df %>% group_by(group) %>%
  e_charts(x, timeline = TRUE) %>% 
  e_bar(a, stack = "grp") %>% 
  e_bar(b, stack = "grp") %>% 
  e_bar(c, stack = "grp") %>%
  e_hide_grid_lines() %>%
  e_y_axis(axisLabel=list(inside=FALSE),axisLine=list(show=FALSE),axisTick=list(show=FALSE),
           formatter=e_axis_formatter("decimal", locale = "nl-nl"))
```
  
As you can see on the y axis, there are two 1's and two 2's. Is this a bug or is there a way to prevent this?

**Comment by JohnCoene** [comment]
I don't think it duplicates them, it's just that `digits` defaults to `0` so it rounds them

```r
df %>% group_by(group) %>%
  e_charts(x, timeline = TRUE) %>% 
  e_bar(a, stack = "grp") %>% 
  e_bar(b, stack = "grp") %>% 
  e_bar(c, stack = "grp") %>%
  e_hide_grid_lines() %>%
  e_y_axis(
    axisLabel=list(inside=FALSE),
    axisLine=list(show=FALSE),
    axisTick=list(show=FALSE),
    formatter=e_axis_formatter("decimal", locale = "nl-nl", digits = 2)
 ```

**Comment by rdatasculptor** [comment]
Thank you for your quick response. You are absolutely right! I should have thought of that myself.

**Comment by JohnCoene** [comment]
No, it's not that obvious at all :)

**Comment by rdatasculptor** [comment]
Now I only need a way to use both "nl-nl" and to make sure there are no digits (because sometimes it doesn't make sense to use digits, in case of e.g. a bar that respresents a number of people). I will try to figure out :)
