### ISSUE TITLE
Timeline and stacked bars withouth loops

### ISSUE THREAD

**Issue by vituri** [JohnCoene/echarts4r#283]
Hi, John!

Consider the following dataset:

```
library(echarts); library(dplyr)
X = 
  iris %>% 
  mutate(Year = rep(2020:2022, 50)) %>% 
  tidyr::pivot_longer(cols = Sepal.Length:Petal.Width) %>% 
  group_by(Year, Species, name) %>% 
  summarise(value = sum(value))
```
Suppose I want to create a timeline where, for each year, we filter the data for that year and plot the stacked bars, considering the Species on the x axis and the stacked (by "name") amount of "value" on the y axis like this
```
X %>% 
  filter(Year == 2020) %>% # example where year == 2020
  group_by(name) %>%
  e_charts(Species) %>% 
  e_bar(value, stack = "grp")
```
![image](https://user-images.githubusercontent.com/56522687/109869346-80c74f80-7c47-11eb-8bd1-5f47629709c4.png)

I know that this can be done if I put X on the wide format (spreading the "name" column to obtain 4 columns: "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"), and use a for loop to add each bar on top of each other. But I was wondering if there is a way to do the entire job keeping the data in the long (tidy) format and without loops. I've looked into your timeline tutorial but didn't see this kind of problem appearing. Any ideas?

**Comment by JohnCoene** [comment]
I'm afraid not.

It's due to a poor design decision from myself, since `group_by` is used to define both series _and_ timeline steps, they cannot be used together. I wish I had done differently.

**Comment by vituri** [comment]
No problem! I love your package and use it everyday. 

If you have some ideas on how to solve this kind of thing using loops without putting the data in wider format, I'll be listening. :)
