### ISSUE TITLE
How to alter content of tooltip in sankey chart?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#287]
I must admit this may be not a bug of some kind. So if needed, I will close the issue again, unsolved.

My question is how to both control amount of digits of the value in the tooltip content and turn it into a percentage.

This is some example data:

```
df <- data.frame(name = c("start", "start", 
                          "start", "start", "start"), 
                 target = c("node1", "node2", "node3", "node4", "node5"), 
                 Percentage = c(2/3, 1/9, 1/9, 1/18, 1/18), stringsAsFactors = FALSE)

```
If I make a sankey graph including a tooltip using this data frame, like this:

```
df %>%
  e_charts() %>%
  e_sankey(name, target, Percentage) %>%
  e_tooltip()
```
Then there is obviously no % symbol, but also the number of didgets are too large (to my opionion of course :))

I did some expriments using the params object. This is an attempt to put a % after the value:

```
df %>%
  e_charts() %>%
  e_sankey(name, target, Percentage) %>%
  e_tooltip(formatter = htmlwidgets::JS("function(params){return(params.name + ' ' + params.value[0] + '%');}"))

```
As you can see there is % shown. So that part succeeded. But how to get the right value, and how to reduce it's digits?
Can anyone point me in the right direction?

Many thanks in advance!

**Comment by swsoyee** [comment]
There are many way to complete this task, here is a exmaple, reducing digits in R side, and create a JavaScript function to create the tooltip.
```r
df <- data.frame(
  name = c(
    "start", "start",
    "start", "start", "start"
  ),
  target = c("node1", "node2", "node3", "node4", "node5"),
  Percentage = round(c(2 / 3, 1 / 9, 1 / 9, 1 / 18, 1 / 18), 2),
  stringsAsFactors = FALSE
)

df %>%
  e_charts() %>%
  e_sankey(name, target, Percentage) %>%
  e_tooltip(formatter = htmlwidgets::JS(
    "function(params){
      return(`${params.name}   <b>${params.value}%</b>`);
    }"
  ))
```

Tip: If you don't know how to write the correct formatter function, try to use `console.log()` to print all the params in console.
```r
df %>%
  e_charts() %>%
  e_sankey(name, target, Percentage) %>%
  e_tooltip(formatter = htmlwidgets::JS(
    "function(params){
      console.log(params);
    }"
  ))
```
1. Draw the plot;
2. Right click on the view panel;
3. Select `Inspect Element`;
4. Select `Console` tab to check the output.
5. According the ouput structure, write the correct JavaScrpit function to create the formatter.
<img width="1435" alt="截屏2021-03-10 21 28 51" src="https://user-images.githubusercontent.com/20528423/110629693-d1aaeb00-81e7-11eb-8852-716b4d4505d5.png">

**Comment by rdatasculptor** [comment]
thank you for your response! most appreciated :)
The tip of `console.log(params)` seems very useful. I think I need to find a way to do the rounding in javascript, because rounding in R first has some strange numbers as an output in the sankey. Like e.g. 67.00000000001, or something like that. 
I will dig into this.

**Comment by rdatasculptor** [comment]
For my fellow `echarts4r` users who run into the same question/problem. `.toFixed(1)` did the trick.

like this:

```
      e_tooltip(formatter = htmlwidgets::JS(
        "function(params){
      return(`${params.name}   <b>${params.value.toFixed(1)}%</b>`);
    }"
      ))
```
In this case the result is a value with just one decimal. If needed more you can ofcourse use a larger number than 1.
