### ISSUE TITLE
new theme

### ISSUE THREAD

**Issue by patarol** [JohnCoene/echarts4r#29]
Hey @JohnCoene 

You've write an awesome package! 
I was trying to create my own theme (based on [538](https://fivethirtyeight.com/) page), but I have no idea how to start.

I can generate my own theme by editing one `json` that already exists but I don't know how to add this `json` file in `R`.

I'm trying with this:

```
USArrests %>% 
  dplyr::mutate(
    State = row.names(.),
    Rape = -Rape
  ) %>% 
  e_charts(State) %>% 
  e_line(Murder) %>% 
  e_area(Rape, name = "Sick basterd", x.index = 1) %>%  # second y axis
  e_title("Your plot", "Subtext", sublink = "https://john-coene.com") %>% 
  e_x_axis(1, show = FALSE) # hide scond X Axis
```

but I'm stuck in add my own theme (or edit).
any help will be appreciated!

**Comment by JohnCoene** [comment]
Hey, thanks!

You can use the function `e_theme_custom`:

```r
library(echarts4r)

theme <- read.lines("path/to/my/theme.json")

iris %>% 
  group_by(Species) %>% 
  e_charts(Sepal.Length) %>% 
  e_line(Sepal.Width) %>% 
  e_theme_custom(theme)
```

**Comment by patarol** [comment]
That's awesome!

Thank you @JohnCoene 

closing...
