### ISSUE TITLE
How to put mark points on all lines in case of timeline

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#290]
When I do this:

```r
max <- list(
  name = "Max",
  type = "max"
)

iris %>% 
  group_by(Species) %>% 
  e_charts(Sepal.Length, timeline = TRUE) %>% 
  e_line(Sepal.Width) %>% 
  e_line(Petal.Length) %>% 
  e_mark_point(data = max) 
```

Only one line has a marked point. Is there a way to give both lines a marked point?

If I switch off the timeline by `timeline = FALSE`, all the lines have a marked point. So nothing seems to go wrong there. The problem appears when using switching on the timeline.

Many thanks in advance!

**Comment by JohnCoene** [comment]
I pushed a fix, you can reinstall and try again. Feel free to reopen if that does not solve your issues.

**Comment by rdatasculptor** [comment]
thanks again John! your fix did the trick.
