### ISSUE TITLE
How to add a hyperlink for the source of the data at the bottom of the chart

### ISSUE THREAD

**Issue by vincentmanz** [JohnCoene/echarts4r#292]
Hi, 
I would like to add a hyperlink for the source of the data at the bottom of the chart. 
`In markdown: Source: [www.buzzfeed.com](www.buzzfeed.com)`
How can I do that? 

Thanks

**Comment by swsoyee** [comment]
You can use `e_title` to do this (set the `subtext` and `sublink` augments). 
And using `buttom` property to set it to the buttom.
https://echarts.apache.org/en/option.html#title.bottom

**Comment by JohnCoene** [comment]
Yes indeed, you can use the title.

```r
devtools::load_all()

cars %>% 
  e_charts(speed) %>% 
  e_scatter(dist, symbol_size = 10) %>% 
  e_title(
    text = "Source",
    link = "https://john-coene.com",
    bottom = 20,
    right = 0
  )
```

I think, being a JavaScript library it is expected that these are placed outside the chart, e.g.:

```r
plot <- cars %>% 
  e_charts(speed) %>% 
  e_scatter(dist, symbol_size = 10) 

htmltools::browsable(
  htmltools::tagList(
    plot,
    htmltools::a(
      href = "https://john-coene.com",
      "Data source",
      style = "float:right;"  
    )
  )
)
```

**Comment by JohnCoene** [comment]
@vincentmanz did this help at all?

**Comment by vincentmanz** [comment]
Yes brilliant!
