### ISSUE TITLE
Timeline ordering with months

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#295]
Hi, I have a small problem when using the timeline with months. As you can see from the example below, the timeline points are ordered alphabetically, even though I have rearranged the dataset to be in the right order.

```r
library(dplyr)
library(echarts4r)

test_data <- data.frame(
  month = rep(c(3, 1, 6), each = 3),
  x = sample(10:20, 9, replace = T),
  y = sample(10:20, 9, replace = T)
)

test_data %>% 
  arrange(month) %>% 
  mutate(
    month = month.name[month]
  ) %>% 
  group_by(month) %>% 
  e_charts(x, timeline = TRUE) %>% 
  e_scatter(y)
```

![image](https://user-images.githubusercontent.com/52219252/111884081-0e7c9c00-89b7-11eb-9706-be7167e980d5.png)

Is there a simple way to reorder the months? 

Apologies if this is already in the docs but I couldn't find it

**Comment by JohnCoene** [comment]
I'm not behind a laptop but I think echarts4r reorders by default there the `reorder` argument in `e_charts` to prevent that I believe. Let me know if that does not work.

**Comment by etiennebacher** [comment]
`reorder` doesn't work here because `month` is a character (the month name). Even if `month` was a numeric showing the month number, `reorder = F` would not work (i.e the month numbers are still reordered):
```
test_data <- data.frame(
  month = rep(c(3, 1, 6), each = 3),
  x = sample(10:20, 9, replace = T),
  y = sample(10:20, 9, replace = T)
)

test_data %>%
  group_by(month) %>% 
  e_charts(x, timeline = TRUE, reorder = F) %>% 
  e_scatter(y)
```
![image](https://user-images.githubusercontent.com/52219252/111885255-9c0fba00-89be-11eb-8dba-abbf37dcdbfd.png)

In addition to that, using the month number means that I would need a way to show the month name on the timeline, and not the month number.

**Comment by JohnCoene** [comment]
Ah sorry, `reorder` is for the `x` axis.

Use factors to define the order.

```r
library(dplyr)
library(echarts4r)

test_data <- data.frame(
  month = rep(c(3, 1, 6), each = 3),
  x = sample(10:20, 9, replace = T),
  y = sample(10:20, 9, replace = T)
)

test_data %>% 
  arrange(month) %>% 
  mutate(
    month = month.name[month],
    month = factor(month, levels = c("January", "March", "June"))
  ) %>% 
  group_by(month) %>% 
  e_charts(x, timeline = TRUE) %>% 
  e_scatter(y)
```

Let me know if that does not work.

**Comment by etiennebacher** [comment]
Still not working

**Comment by JohnCoene** [comment]
I ran the sample code I shared worked on my machine and it worked just fine. Can you share session info and prints teen please?

**Comment by etiennebacher** [comment]
My fault, I just installed the dev version and your code works, sorry for the inconvenience

**Comment by JohnCoene** [comment]
No problem
