### ISSUE TITLE
Apply `e_visual_map()` to one y index only

### ISSUE THREAD

**Issue by fmmattioni** [JohnCoene/echarts4r#299]
Hi all,

I was wondering if I have dual y-axes (y_index = 0 and y_index = 1), would it be possible to use a `e_visual_map()` on `y_index = 0` only, for example?

reprex:

```r
library(echarts4r)

mtcars %>%
  e_charts(mpg) %>%
  e_line(disp) %>% 
  e_visual_map(disp) %>% 
  e_line(hp, y_index = 1)
```

**Comment by helgasoft** [comment]
yes, easy with parameter [seriesIndex](https://echarts.apache.org/en/option.html#visualMap-continuous.seriesIndex) :
```r
> mtcars %>%
     e_charts(mpg) %>%
     e_line(disp) %>% 
     e_visual_map(disp, seriesIndex=0) %>% 
     e_line(hp)
```

**Comment by fmmattioni** [comment]
Wow, I didn't catch that from the ECharts docs.. thanks a lot, @helgasoft !
