### ISSUE TITLE
Toggle legend items off by default

### ISSUE THREAD

**Issue by tyluRp** [JohnCoene/echarts4r#301]
Is it possible to make a graph where legend items are toggled off by default? For example, if I have 10 categories plotted but only want to show 3 by default.

**Comment by swsoyee** [comment]
@tyluRp Refer to https://github.com/JohnCoene/echarts4r/issues/286#issuecomment-792689134

**Comment by tyluRp** [comment]
Perfect!! Thanks 🙏🏻
