### ISSUE TITLE
`e_mark_area` and other charts: how to use texture in `itemStyle.color`?

### ISSUE THREAD

**Issue by nicholaelaw** [JohnCoene/echarts4r#304]
Relevant documentation: https://echarts.apache.org/en/option.html#series-line.markArea.itemStyle.color

Example: https://echarts.apache.org/examples/en/editor.html?c=pie-pattern

I understand that I should do something like this:

```R
e_pie(..., itemStyle = list(color = list(image = ???, repeat = 'repeat')), ...)
```

but I can't figure out how to translate this Javascript 

```javascript
var piePatternSrc = 'data:image/jpeg;...'
var bgPatternSrc = 'data:image/png;...'

var piePatternImg = new Image();
piePatternImg.src = piePatternSrc;
var bgPatternImg = new Image();
bgPatternImg.src = bgPatternSrc;
```

into R, and then pass it to `e_charts` functions. Help?

**Comment by JohnCoene** [comment]
In the example what they use are base64 encoded images. You can do that from R.

```r
library(echarts4r)

uri <- "https://www.r-project.org/logo/Rlogo.png"

enc <- base64enc::base64encode(uri)
enc <- paste0("data:image/png;base64,", enc)

cars %>% 
  e_charts(speed) %>% 
  e_scatter(dist) %>% 
  e_color(background = list(image = enc))
```

Does this help?

**Comment by nicholaelaw** [comment]
Aha, thank you! I somehow missed the `paste0("data:image/png;base64,", enc)` step!
