### ISSUE TITLE
Color doesn't match legend when using e_add

### ISSUE THREAD

**Issue by leossbr** [JohnCoene/echarts4r#306]
Hello,
Whenever I map a color to a variable using `e_add` the legend still displays the default colors.

```R

library(echarts4r)

df <- data.frame(
  grp = rep(c("a", "b"), each = 7),
  x = rep(letters[1:7], 2),
  y = runif(14, 1, 10)
)

df$color <- ifelse(df$grp == "a", "green", "red")`

df %>%
  group_by(grp) %>%
  e_charts(x) %>%
  e_bar(y) %>%
  e_add("itemStyle", color)
```
The previous code produces this output

![image](https://user-images.githubusercontent.com/31013365/115128802-d157f980-9fb6-11eb-8219-d0c1b3112498.png)

**Comment by JohnCoene** [comment]
With `e_add` colors are not going to match, this is expected.

Use `e_color` instead.

```r
df %>%
  group_by(grp) %>%
  e_charts(x) %>%
  e_bar(y) %>%
  e_color(c("red", "green")) 
```

**Comment by leossbr** [comment]
I see, the best way to map variables to their colors would be to transform them to factors and pass the correct color order in `e_color` ?

**Comment by JohnCoene** [comment]
Yes, something like that. There is, currently, no better way to handle that with echarts4r.
