### ISSUE TITLE
Show node labels in graph GL vis

### ISSUE THREAD

**Issue by chihpoc** [JohnCoene/echarts4r#307]
Is it possible to show node labels when zoomed in at https://echarts4r.john-coene.com/articles/gl.html#graph-gl?

**Comment by JohnCoene** [comment]
Apologies, I don't think this is possible

**Comment by chihpoc** [comment]
thank you for your prompt response!

**Comment by JohnCoene** [comment]
Perhaps [this](https://shiny.john-coene.com/echarts4rShiny/) is helpful (see graph tab), but only works in Shiny.
