### ISSUE TITLE
Echarts4r can't be libraried

### ISSUE THREAD

**Issue by chloropidae** [JohnCoene/echarts4r#309]
After echarts4r was installed, the package can't be libraried.  What should I do

> library(echarts4r)
Error: package or namespace load failed for ‘echarts4r’:
 .onLoad failed in loadNamespace() for 'echarts4r', details:
  call: namespaceExport(ns, exports)
  error: undefined exports: WebSocket, decodeURI, decodeURIComponent, encodeURI, encodeURIComponent, excludeStaticPath, getRNGState, interrupt, ipFamily, listServers, randomPort, rawToBase64, runServer, service, startDaemonizedServer, startPipeServer, startServer, staticPath, staticPathOptions, stopAllServers, stopDaemonizedServer, stopServer
In addition: Warning messages:
1: package ‘echarts4r’ was built under R version 4.0.5 
2: S3 methods ‘format.staticPath’, ‘format.staticPathOptions’, ‘print.staticPath’, ‘print.staticPathOptions’ were declared in NAMESPACE but not found

**Comment by JohnCoene** [comment]
That seems very strange, all checks pass. Could you retry from a clean session?

**Comment by JohnCoene** [comment]
Did you try from a clean session? Did that work?
