### ISSUE TITLE
Calendar Heartmap can not diaplay multiple years data

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/echarts4r#31]
I think currently it can only show one year data in one row calendar graph. Would be nice to be able to show multiple years in multiple rows

**Comment by JohnCoene** [comment]
Well, you technically can but the least I can say is that it's easy let alone evident. I'll see if I can simplify the API.

```r
dates18 <- seq.Date(as.Date("2018-01-01"), as.Date("2018-12-31"), by = "day")
dates17 <- seq.Date(as.Date("2017-01-01"), as.Date("2017-12-31"), by = "day")
values <- rnorm(length(dates18), 20, 6)

df <- data.frame(date18 = dates18, date17 = dates17, values = values)

df %>% 
    e_charts(date18) %>% 
    e_calendar(range = "2018") %>% 
    e_heatmap(values, coord.system = "calendar", calendarIndex = 0, name = "2018") %>% 
    e_data(df, date17) %>% 
    e_calendar(range = "2017", top = 300) %>% 
    e_heatmap(values, coord.system = "calendar", calendarIndex = 1, name = "2017") %>%
    e_visual_map(max = 30) 
```

**Comment by brucefeiwang** [comment]
cool. thanks for giving example.

**Comment by brucefeiwang** [comment]
Hi .  it looks like . for function e_heatmap(),  parameter name,  is not getting used in the graph.

**Comment by JohnCoene** [comment]
The argument `name` is indeed not *necessary*, in the package this argument is often used for the `legend` names.

For instance:

```r
cars %>% 
    e_chart(dist) %>% 
    e_scatter(speed, name ="Vehicle Speed")
```

The argument `name` exists but is not used per se. Perhaps you are after `e_title`?

```r
e_charts() %>% 
    e_calendar(range = "2017") %>% 
    e_title("Chart title", "subtitle")
```

**Comment by brucefeiwang** [comment]
I see. Thanks.

**Comment by brucefeiwang** [comment]
One more thing,  How to make this calendar heatmap adjust its size according to web page size, dynamically.

**Comment by JohnCoene** [comment]
The calendar is, as far as I know, the only non-responsive element of echarts

**Comment by brucefeiwang** [comment]
Thanks

**Comment by JohnCoene** [comment]
@brucefeiwang Could you take a look at #34 I have pushed a solution to this.
