### ISSUE TITLE
Positioning e_datazoom()

### ISSUE THREAD

**Issue by paulr886** [JohnCoene/echarts4r#311]
Hi, 
Is it possible to change the position of e_datazoom() bar manually? 
               The e_datazoom() bar and the x axis labels are overlapping when x axis label are long and rotate to 90.

**Comment by swsoyee** [comment]
You could increase the bottom margin of grid by using `e_grid(bottom = 'xx')`.

**Comment by paulr886** [comment]
Thank you.
