### ISSUE TITLE
Layout problems with multiple charts in a row for RMarkdown

### ISSUE THREAD

**Issue by berkorbay** [JohnCoene/echarts4r#313]
Hi! Here is my problem. I cannot seem to bring 3 pie charts together in a row in an Rmarkdown HTML render.

- Title and legend overlap
- Large whitespace above and below the pie body
- Labels are not displayed properly because pie body is large

Any suggestions?

Here is the end result.

<img width="947" alt="Screen Shot 2021-05-01 at 16 18 21" src="https://user-images.githubusercontent.com/5690139/116783716-09703980-aa99-11eb-9e4f-68e097fbb517.png">

Here is the reproducible Rmd file. (Sorry about the escape characters before chunks)

```
---
title: "MWE for echarts4r layout problem"
output: html_document
---

\```{r setup, include=TRUE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(echarts4r)
library(tidyverse)
\```

## MWE for echarts4r

\```{r}
data1 <- tibble(wood=50,steel=42,cotton=5,spinneedle=124) %>% pivot_longer(everything())
data2 <- tibble(fire=31,water=1,air=325,velociraptor=5) %>% pivot_longer(everything())
data3 <- tibble(table=5,wardrobe=43,refrigirator=10,tv=2) %>% pivot_longer(everything())
\```


\```{r}
plot1 <- data1 %>% e_chart(name) %>% e_pie(value) %>% e_title("My First Data Set")
plot2 <- data2 %>% e_chart(name) %>% e_pie(value) %>% e_title("My Second Data Set")
plot3 <- data3 %>% e_chart(name) %>% e_pie(value) %>% e_title("My Third Data Set")

e_arrange(plot1,plot2,plot3,rows=1,cols=3)
\```

```

Btw, thanks for the package. Charts look amazing!

**Comment by berkorbay** [comment]
After little more searching (additional to hours of search prior to this issue), I found some manual override options that I failed to set before. Here are the full code and result.

```r
plot1 <- data1 %>% e_chart(name,height=350) %>% e_pie(value,label=list(show=FALSE),height=350,radius = c(0, 90)) %>% e_title("My First Data Set",left="center") %>% e_legend(type="plain",top=30)
plot2 <- data2 %>% e_chart(name,height=350) %>% e_pie(value,label=list(show=FALSE),height=350,radius = c(0, 90)) %>% e_title("My Second Data Set",left="center") %>% e_legend(type="plain",top=30)
plot3 <- data3 %>% e_chart(name,height=350) %>% e_pie(value,label=list(show=FALSE),height=350,radius = c(0, 90)) %>% e_title("My Third Data Set",left="center") %>% e_legend(type="plain",top=30)

e_arrange(plot1,plot2,plot3,rows=1,cols=3)
```

<img width="916" alt="Screen Shot 2021-05-01 at 16 51 31" src="https://user-images.githubusercontent.com/5690139/116784616-dda38280-aa9d-11eb-8003-cddbf76f882b.png">

**Comment by JohnCoene** [comment]
Sorry you had to struggle so much, never hesitate to open an issue, I or others are happy to help
