### ISSUE TITLE
How to style title?

### ISSUE THREAD

**Issue by Camil88** [JohnCoene/echarts4r#315]
Hi, I'm trying to style a chart but I got stuck on styling the title (color, font). I'm using `e_text_color` function but it applies only to axes, this is a chunk of my code:

```r
      output$plot <- echarts4r::renderEcharts4r({
        dataChartStats() %>% 
          echarts4r::e_charts(x) %>% 
          echarts4r::e_line(y) %>% 
          echarts4r::e_title("Stats 2021") %>% 
          echarts4r::e_show_loading(hide_overlay = TRUE) %>% 
          echarts4r::e_color("#0089d9") %>% 
          echarts4r::e_text_style(color = "red") 
      
      })
```
Is it possible to style the title independently?
Another small issue - `e_show_loading(hide_overlay = TRUE)` set on TRUE should hide white overlay but it does not, still white backround is displayed. Is it possible to also style overlay background color (e.g. make it transparent when loading)?

**Comment by JohnCoene** [comment]
Sorry for the confusion.

All the options for the title can be found on the [official website](https://echarts.apache.org/en/option.html#title)

```r
dataChartStats() %>% 
  echarts4r::e_charts(x) %>% 
  echarts4r::e_line(y) %>% 
  echarts4r::e_title(
    textStyle = list(
      color = "red",
      fontFamily = "Something"
  )
```

If navigating the options is confusing, there is a small guide [here](https://echarts4r.john-coene.com/articles/get_started.html#navigate-options-1)

You can control the mask for the laoding with the `mask_color`, see [doc](https://echarts4r.john-coene.com/reference/loading.html), defaults to `rgba(255, 255, 255, 0.8)`.

**Comment by Camil88** [comment]
Thanks for your answer! And yes, I found more details in documentation. Anyways, I try to set chart height, according to docs there is `height` attribute in `e_charts`. My code is:
```r
echarts4r::e_charts(statusHrsMin, height = "200px") %>% 
...
```
And it doesn't work. Docs go that height must be valid CSS unit, my code is such one.

**Comment by JohnCoene** [comment]
Numerical values are interpreted as pixel values `e_charts(x, height = 200)`

In Shiny it's, I think, better to set it from UI, `echarts4rOutput('id', height = 200)`

**Comment by Camil88** [comment]
It works, thanks!

**Comment by JohnCoene** [comment]
Feel free to open other issues if you encounter any.
