### ISSUE TITLE
How to dynamically change chart type?

### ISSUE THREAD

**Issue by Camil88** [JohnCoene/echarts4r#316]
I encountered another issue, it's probably more general one but refers to charts. I try to change chart type based on a button click. I would also like to to change some other options. I have no idea what's the way to change plot parts/elements dynamically. I asked on SO, they suggested to add 'if' inside the `output$plot`. My working example is below:
```r
library(shiny)
library(tidyverse)
library(echarts4r)

ui <- fluidPage(

  actionButton("btn", 'Change type'),
  plotOutput("plot")
)

server <- function(input, output) {
  
 btnShow <- reactiveValues(lineChart = TRUE)
  
 observeEvent(input$btn, {
   btnShow$lineChart = !btnShow$lineChart
 })
   
   output$plot <- renderPlot({
     if (btnShow$lineChart) {
       mtcars %>% 
       e_charts(mpg) %>%  
       e_line(disp)
     } else {
       mtcars %>% 
       e_charts(mpg) %>%  
       e_bar(disp)
     }
   })   
}

# Run the application 
shinyApp(ui = ui, server = server)
```
The issue is that the chart above is rather short example - in my case code for creating a plot is much longer and with many options which I'd love to customize. Another issue is that for example if I would like to change 5 chart types (line, bar, pie etc.) I would have to add many `if`s (or `switch`) and insert 5 sepreate code to recreate 5 plots. So,the example above shows that, based on a condition, I need to recreate seperate, totally new chart. It's not dynamic approach or just part-dynamic one. I tried also something like this below, using reactive but it doesn't work (I added here just a piece of my whole code):

```r
      newChartType <- reactive({
        df = switch(
           someCondition,
          '1' = echarts4r::e_line(ColumnName2),
          '2' = echarts4r::e_bar(ColumnName2)
         )        
      }) 

      output$plot <- echarts4r::renderEcharts4r({
        dataChartStats() %>% 
          echarts4r::e_charts(ColumnName1) %>% 
          newChartType() %>% 
          echarts4r::e_legend(show = FALSE)  
      })
```

In general - do you have a solution for changing plot's parts dynamically in the code, mainly: chart type, color, grid?

**Comment by JohnCoene** [comment]
You can try something like that. The `switch` statement should return a function.

```r
library(shiny)
library(echarts4r)

chart_type <- function(type){
  switch(
    type,
    line = echarts4r::e_line,
    scatter = echarts4r::e_scatter,
    e_line # default 
  )
}

ui <- fluidPage(
  selectInput(
    "type",
    "Chart type",
    choices = c(
      "line",
      "scatter"
    )
  ),
  echarts4rOutput("plot")
)

server <- function(input, output, session){
  output$plot <- renderEcharts4r({
    fn <- chart_type(input$type)    

    cars %>% 
      e_charts(speed) %>% 
      fn(dist)
  })
}

shinyApp(ui, server)
```

**Comment by Camil88** [comment]
This is what I was looking for! Great, thanks:)
Just one more question - suppsose I want to customize more plot options. Of course, sometimes I could use reactive expression to do it but sometimes not. I suppose that for a title I could use reactive expr but let's say I want to return in a function following your method. I tried to add `e_title` as a pipe to `e_charts` but it fails. So, if I understand correctly in this case I would have to create seperate, new function which returns `e_title` ? I can't do this somehow in one function `chart_type`?

Below is my try. Commented part is my another try this time with quotation marks but none of them works:
```r
library(shiny)
library(echarts4r)

chart_type <- function(type){
   switch(
      type,
      line = echarts4r::e_line %>% echarts4r::e_title('Line chart CARS'),
      scatter = echarts4r::e_scatter %>% echarts4r::e_title('Line chart BAR'),
      # line = "echarts4r::e_line %>% echarts4r::e_title('Line chart CARS')",
      # scatter = "echarts4r::e_scatter %>% echarts4r::e_title('Line chart BAR')",
      e_line # default 
   )
}

ui <- fluidPage(
   selectInput(
      "type",
      "Chart type",
      choices = c(
         "line",
         "scatter"
      )
   ),
   echarts4rOutput("plot")
)

server <- function(input, output, session){
   output$plot <- renderEcharts4r({
      fn <- chart_type(input$type)    
      
      cars %>% 
         e_charts(speed) %>% 
         fn(dist)
   })
}

shinyApp(ui, server)
```

**Comment by Camil88** [comment]
I also tried to pass data for `e_charts` but there is an error that objects can't be found. Is this a proper way to pass data to `e_charts`?

```r
library(shiny)
library(echarts4r)

chart_type <- function(type){
   switch(
      type,
      line = echarts4r::e_line,
      scatter = echarts4r::e_scatter,
      e_line # default 
   )
}


x_axis <- function(type){
   switch(
      type,
      line = mpg,
      scatter = qsec,
      mpg # default 
   )
}

ui <- fluidPage(
   selectInput(
      "type",
      "Chart type",
      choices = c(
         "line",
         "scatter"
      )
   ),
   echarts4rOutput("plot")
)

server <- function(input, output, session){
   output$plot <- renderEcharts4r({
      fn <- chart_type(input$type) 
      fn2 <- x_axis(input$type)
      
      mtcars %>% 
         e_charts(fn2) %>% 
         fn(hp)
   })
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
It's the `x_axis` switch statement that fails here, it's not valid R code, `mpg` and `qsec` are technically objects that do not exist, hence the error.

When you want to specify columns like that dynamically use the functions that end in `_` and pass it as a string.

```r
library(shiny)
library(echarts4r)

chart_type <- function(type){
   switch(
      type,
      line = echarts4r::e_line,
      scatter = echarts4r::e_scatter,
      e_line # default 
   )
}

ui <- fluidPage(
   selectInput(
      "type",
      "Chart type",
      choices = c(
         "line",
         "scatter"
      )
   ),
   selectInput(
     "var",
     "X var",
     choices = c("hp", "qsec")
   ),
   echarts4rOutput("plot")
)

server <- function(input, output, session){
   output$plot <- renderEcharts4r({
      fn <- chart_type(input$type) 
      
      mtcars %>% 
         e_charts_(input$var) %>% 
         fn(hp)
   })
}

shinyApp(ui, server)
```

To clarify

```r
e_charts_(cars, "speed") %>% e_line_("speed")

**Comment by Camil88** [comment]
Mind blowing! Thanks a lot!
Btw very good library :)
