### ISSUE TITLE
ggplot2::geom_tile Equivalent (Categorical Heatmap) in echarts4r

### ISSUE THREAD

**Issue by szmsu2011** [JohnCoene/echarts4r#318]
Hello,

I have a problem in attempting to generate a heatmap where I want the "tiles" to represent a categorical variable, similar to the `geom_tile` function in ggplot2, and also self-specifying the discrete colour palette. Apparently, the `e_heatmap` and `e_visual_map` from echarts4r cannot achieve that.

For example, with the dummy dataset, I want to produce the plot by running the following code:

```r
library(tidyverse)

set.seed(2021)
v <- LETTERS[1:10]
matrix <- data.frame(
  x = sample(v, 300, replace = TRUE),
  y = sample(v, 300, replace = TRUE),
  z = sample(LETTERS[1:3], 300, replace = TRUE),
  stringsAsFactors = FALSE
) %>%
  dplyr::group_by(x, y) %>%
  dplyr::summarise(z = z) %>%
  dplyr::ungroup()
#> `summarise()` has grouped output by 'x', 'y'. You can override using the `.groups` argument.

matrix %>%
  ggplot(aes(x, y, fill = z)) +
  geom_tile() +
  ggplot2::scale_fill_manual(
    values = c(A = "blue", B = "red", C = "green")
  )
```

However, the following code from the [heatmap example](https://echarts4r.john-coene.com/articles/chart_types.html) modified does not achieve the wanted result:

```r
library(echarts4r)
packageVersion("echarts4r")
#> [1] ‘0.4.0’

matrix %>% 
  e_charts(x) %>% 
  e_heatmap(y, z) %>% 
  e_visual_map(z) %>% 
  e_title("Heatmap")
```

Could you please advise if there exists any function from echarts4r capable of achieving the desired result?

Thank you in advance.

**Comment by JohnCoene** [comment]
Indeed, I can't make this work either, though I was sure it was possible.

**Comment by szmsu2011** [comment]
Is there any alternative method/function (even a hacky one) available in the current version of echarts4r capable in producing categorical visual maps? If not, please consider treating the post as a potential feature request.

Thanks.

**Comment by JohnCoene** [comment]
The issue is not with echarts4r, I'm not sure how to produce that with ECharts.js and I cannot find any such example. If you do please share it with me, it should be reproducible with echarts4r then.

**Comment by helgasoft** [comment]
The ggplot result can be replicated with Echarts and R, [here is the code](https://gist.github.com/helgasoft/eb970a425059be5f13dd5aadc2b112ff).
However, I do not understand what is the meaning of this heatmap since **most of the matrix data is ignored**.  Each square represents only the last row of each group...
![heatmap](https://user-images.githubusercontent.com/13038071/118174837-2df6da80-b3e4-11eb-83d8-afa0130796da.png)

**Comment by JohnCoene** [comment]
OK, so this can be done with echarts4r...

```r
matrix <- data.frame(
  x = sample(v, 300, replace = TRUE),
  y = sample(v, 300, replace = TRUE),
  z = sample(LETTERS[1:3], 300, replace = TRUE),
  stringsAsFactors = FALSE
) %>%
  dplyr::group_by(x, y) %>%
  dplyr::summarise(z = z) %>%
  dplyr::ungroup() %>% 
  mutate(z = case_when(z=='A' ~1, z=='B' ~2, TRUE ~3)) # convert to numeric

matrix %>% 
  e_charts(x) %>% 
  e_heatmap(y, z) %>% 
  e_visual_map(
    z,
    type = "piecewise",
    calculable = FALSE,
    pieces = list(list(value=1,label='C',color='blue'), # map color to label
              list(value=2,label='B',color='red'),
              list(value=3,label='C',color='green'))
  )
```

**Comment by helgasoft** [comment]
Neat, and better! The _slice_tail()_ in my code was redundant.
Now by hovering the legend (A,B,C) one can see all unique records of the dataset, not just the last row of each group.  Replicate that, ggplot !

**Comment by JohnCoene** [comment]
I'll assume this is fixed. Please reopen if this does not solve the problem.
