### ISSUE TITLE
Echarts 5.1.1 has the register_map with the option to choose svg and I’m trying to implement it.

### ISSUE THREAD

**Issue by euriconoleto** [JohnCoene/echarts4r#319]
I’m trying to use the new map svg feature of echarts 5.1.1. So, I have manually updated my echarts4r package to the new version. However, I’m missing something when implementing register_map to svg. Like this example: https://echarts.apache.org/examples/en/editor.html?c=geo-beef-cuts

So I trying to implant this way:
**The Echarts js code:**

```js
 echarts.registerMap('Beef_cuts_France', { svg });
```

**The equivalent in R:**

```r
svg='https://echarts.apache.org/examples/data/asset/geo/Beef_cuts_France.svg'
q$x$registerMap[[1]] = list(mapName="USA", list(svg))
```

As you can se the equivalent would use a named and an unnamed list, and R doesn’t allow that.
Any Idea of what could help?

Complete code:

```r
library(echarts4r)
svg='https://echarts.apache.org/examples/data/asset/geo/Beef_cuts_France.svg'

q=data %>% 
  e_charts() %>% 
  e_map_register("USA", json= json) %>%
  e_map(value, map = "USA")

q$x$registerMap[[1]] = list(mapName="USA", list(svg))
q
```

Thank you

**Comment by JohnCoene** [comment]
It should work after restarting the R session. 

1. Install
2. Restart R/session
3. Try again

**Comment by euriconoleto** [comment]
Thanks!! It is working!
Best regards
