### ISSUE TITLE
Pie chart,  when hover over the pies.  not showing any information. 

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/echarts4r#32]
I'd like to see the underlying stats when hover over part of the pie chart.  Couldn't make it working.

**Comment by JohnCoene** [comment]
See `?e_tooltip` to add tooltips, more documentation [here](https://echarts4r.john-coene.com/articles/tooltip.html).

```r
mtcars %>% 
  head() %>% 
  dplyr::mutate(model = row.names(.)) %>% 
  e_charts(model) %>% 
  e_pie(carb) %>%
  e_tooltip(trigger = "item")
```

**Comment by brucefeiwang** [comment]
Ah Ha.  Thank you so much
