### ISSUE TITLE
dashed/dotted line on e_line

### ISSUE THREAD

**Issue by Jorge-hercas** [JohnCoene/echarts4r#321]
Hello Goodnight. Is there a way to use dotted lines or dashed lines with e_line plots?

**Comment by swsoyee** [comment]
Check the documentation below
https://echarts.apache.org/en/option.html#series-line.lineStyle.type

Sample

```r
iris %>%
  group_by(Species) %>%
  e_charts(Sepal.Length) %>%
  e_line(Sepal.Width, lineStyle = list(type = 'dotted')) %>%
  e_tooltip(trigger = "axis")
```

![image](https://user-images.githubusercontent.com/20528423/119215124-b07b4a80-bb06-11eb-9c1e-88282346b192.png)

**Comment by Jorge-hercas** [comment]
Thanks a lot!
