### ISSUE TITLE
could it draw visual screen?like the visual screen of intelligent weather

### ISSUE THREAD

**Issue by UNIQUE02** [JohnCoene/echarts4r#326]
hope get your reply，thanks.

**Comment by JohnCoene** [comment]
I don't know what that is. Do you have a link for me?

**Comment by UNIQUE02** [comment]
> I don't know what that is. Do you have a link for me?
likethat，link url：https://github.com/hzzly/credit-bi-react

**Comment by swsoyee** [comment]
@UNIQUE02 链接我看了，不过还是没看懂你的需求是什么？
