### ISSUE TITLE
Map coordinates for India different from echarts JS lib

### ISSUE THREAD

**Issue by CharlesBordet** [JohnCoene/echarts4r#328]
Thank you for the amazing package :)

We have an issue when drawing a worldmap with `e_map()`. There are two regions north of India that are not labelled. I believe it is Kashmir.

Example code (from the documentation)

```
library(echarts4r)

choropleth <- data.frame(
  countries = c(
    "France",
    "Brazil",
    "China",
    "Russia",
    "Canada",
    "India",
    "United States",
    "Argentina",
    "Australia"
  ),
  values = round(runif(9, 10, 25))
)
choropleth %>%
  e_charts(countries) %>%
  e_map(values) %>%
  e_visual_map(min = 10, max = 25)
```

![image](https://user-images.githubusercontent.com/7228536/121013898-b1181000-c799-11eb-8617-82a278993855.png)

Notice the two regions in yellow, north of India. When hovering the mouse, the country name should appear (as the name for Greenland appeared when I took the screenshot), but nothing is displayed for these two regions.

This issue doesn't seem to appear on the echarts JS lib, as this example shows: https://codepen.io/jiujiale/pen/RwwpGvE. On the linked example, the southern region is attributed to India, while the northern region is attributed to Pakistan.

I tried replacing the `world.js` script (https://github.com/JohnCoene/echarts4r/blob/master/inst/htmlwidgets/lib/echarts-4.8.0/world.js) with the one from the JS lib (https://github.com/apache/echarts/blob/master/test/data/map/js/world.js), but this didn't change anything.

Any idea how to update the worldmap to have something similar like the echarts JS lib? With the Kashmir region attributed to India for the southern part and Pakistan for the northern part.

Thanks!

**Comment by JohnCoene** [comment]
Interesting how many people pick this up (also received emails), I had not noticed myself to be honest.

Use the GeoJSON API to use another map.

```r
library(echarts4r)

url <- "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json"
geojson <- jsonlite::read_json(url)

e_charts() %>% 
  e_map_register("WORLD", geojson) %>% 
  e_geo(map = "WORLD")

# if you want to use e_map instead of e_geo see:
# https://echarts4r.john-coene.com/articles/map.html#geojson-support
```

Replacing the js file will not work because the codepen you shared uses ECharts.js v4, {echarts4r} is on ECharts.js v5.

Personally, I like the solution, any world map is bound to annoy people (Taiwan, Kashmir, Hong Kong, etc.)

**Comment by CharlesBordet** [comment]
Thanks for the super quick response! :) This solved the issue indeed.
