### ISSUE TITLE
Save echarts4r results to high resolution figures?

### ISSUE THREAD

**Issue by wangshisheng** [JohnCoene/echarts4r#33]
Hi John,

So great package you have developed! Well, could we save the results to high-resolution figures? For example, 600dpi PNG or TIF figure, even the pdf format. As you know, many journals require high-resolution figures in papers for publication.

Bests,
Shisheng

**Comment by JohnCoene** [comment]
There is a way to export the visualisation to an image natively but I'm unsure whether it is of a high enough resolution.

```r
USArrests %>% 
  e_charts(UrbanPop) %>% 
  e_line(Assault) %>% 
  e_area(Murder, y.index = 1, x.index = 1) %>% 
  e_toolbox() %>%
  e_toolbox_feature() #adds all the features by default
```

You will see a download icon in the top-right.

**Comment by wangshisheng** [comment]
Yeah, it is a way to export as an image (a PNG format as default). But it is not enough for journals to publish papers.

Anyway, thanks a lot^_^

Regards,
Shisheng

**Comment by JohnCoene** [comment]
Oh too bad. I would open the browser visualization in the browser (should fill by default) then take a printscreen: not sure it will be of a higher resolution though

**Comment by wangshisheng** [comment]
Hi John,

I think printscreen is not a good way to get a high resolution image, maybe you can try and check the resolution.

If possible, PDF format is an ideal approach, because it saves results as vector figures. I know it is a little hard to save echarts4r results as PDF format (you know, I have tried some ways by myself to resolve it, but so far so bad...). 

Thanks very much.

Bests,
Shisheng

**Comment by versipellis** [comment]
@wangshisheng in #16 SVG renders are supported for vector graphics. Does that address your needs?

**Comment by JohnCoene** [comment]
This should now be possible. Rmarkdown saves htmlwidgets as png using webshot, see #97

**Comment by mabuimo** [comment]
I second that It would be amazing to have the capability to save an echart4r object in R to .pdf or .svg formats to preserve quality, for example for publishing the figure in an article.
