### ISSUE TITLE
e_tooltip() with trigger = "axis" and custom formatter drops shiny inputs

### ISSUE THREAD

**Issue by wurli** [JohnCoene/echarts4r#330]
Hi John,

Thanks for the fantastic package :) Linking back to a previous issue #107 you posted a solution showing how to use a custom formatter when using `trigger = "axis"`. Unfortunately, when used with shiny this seems to result in all the useful inputs being dropped, e.g. `input$chart_mouseover_data` etc are no longer available. Here is a minimal example from the previous issue:

```r
library(shiny)
library(echarts4r)

ui <- fluidPage(
  h1("Chart:"),
  echarts4rOutput("chart"),
  h1("Available inputs:"),
  verbatimTextOutput("inputs")
)

server <- function(input, output, session) {
  
  set.seed(123)
  
  output$chart <- renderEcharts4r({
    iris %>% 
      as_tibble %>% 
      mutate(index = 1:nrow(.),
             eff =  sample(c(0,1), 150,
                           replace = TRUE, prob = c(.9,.1))) %>%
      tibble::column_to_rownames("index") %>%
      group_by(Species) %>%   
      tibble::rownames_to_column("model") %>%
      e_charts(Sepal.Width) %>%
      e_line(Sepal.Length, bind = model) %>% 
      e_effect_scatter(Sepal.Length,  eff) %>%
      e_tooltip(trigger = 'axis',
                formatter =htmlwidgets::JS(
                  "function(params){
                var tp = [];
                params.forEach(function(x){
                  tp.push([x.seriesName, x.value].join('-'))
                });
                return(tp.join('<br/>'))
              }"))
  }) 
  
  output$inputs <- renderText({
    names(input)
  })
  
}

shinyApp(ui, server)
```

**Comment by JohnCoene** [comment]
This works for me (`renderPrint`)

```r
  output$inputs <- renderPrint({
    print(names(input))
  })
```

![image](https://user-images.githubusercontent.com/7833796/122404809-d23de500-cf7f-11eb-8049-f215c29f6d5b.png)

Which version of echarts4r and shiny are you on?

**Comment by wurli** [comment]
Thanks for the quick response! I was using echarts4r 1.4.0 and shiny 1.6.0, but after updating *all* the dependencies for echarts4r it seems to work. Apologies for having taken up your time when the solution was so trivial, and thank you very much for your help :)

**Comment by JohnCoene** [comment]
No need to apologise!
