### ISSUE TITLE
[Feature Request] Add Slider Range to Callback

### ISSUE THREAD

**Issue by szmsu2011** [JohnCoene/echarts4r#334]
Hi there,

I wonder if it is possible to add `elementId` + `_dataZoomSlider` as one of the callback events in Shiny which returns the current selection/range of the x/y-axis slider? Thanks a lot.

**Comment by JohnCoene** [comment]
You can use `e_capture` to capture such events that are not implemented. The example in the documentation is precisely for the dataZoom slider; see [echarts4r.john-coene.com/reference/e_capture.html](https://echarts4r.john-coene.com/reference/e_capture.html).
