### ISSUE TITLE
e_arrange

### ISSUE THREAD

**Issue by xiaodaowuzhi** [JohnCoene/echarts4r#335]
Hi John,

Is there any way to set the interval of column when using e_arrange? The default is too wide for me, thanks.

![e_arrange](https://user-images.githubusercontent.com/37204813/123732009-d517ce80-d8cb-11eb-95f0-3ca95b4bd061.PNG)

**Comment by swsoyee** [comment]
You could set the margin of each plot to reduce the interval.

```r
e1 <- cars %>%
  e_charts(speed) %>%
  e_scatter(dist) %>%
  e_grid(right = "10px") %>% # <- here
  e_datazoom(show = FALSE) %>%
  e_group("grp")

e2 <- cars %>%
  e_charts(dist) %>%
  e_scatter(speed) %>%
  e_datazoom() %>%
  e_grid(left = "30px") %>% # <- here
  e_group("grp") %>%
  e_connect_group("grp")

e_arrange(e1, e2, title = "Linked datazoom", cols = 2, rows = 1)
```

**Comment by JohnCoene** [comment]
@swsoyee Good idea, I had not thought of that.

Otherwise you have to resort to CSS. Is this intended for Rmarkdown or Shiny? Below is an example of the latter.

```r
library(shiny)
library(echarts4r)

ui <- fluidPage(
  tags$head(
    tags$style(
      ".wrapper .col-sm-6{
        padding: 0px;
      }"
    )
  ),
  div(
    class = "wrapper",
    fluidRow(
      column(6, echarts4rOutput("e1")),
      column(6, echarts4rOutput("e2"))
    )
  )
)

server <- function(input, output){

  output$e1 <- renderEcharts4r({
    mtcars |> 
      e_charts(
        mpg,
        height = 200,
        elementId = "chart1" # specify id
      ) |> 
      e_scatter(wt)
  })
  
  output$e2 <- renderEcharts4r({
    mtcars |> 
      e_charts(
        qsec,
        height = 200
      ) |> 
      e_scatter(hp)
  })
}

shinyApp(ui, server)
```

**Comment by xiaodaowuzhi** [comment]
Thanks, swsoyee, it works fine using e_grid().
Also thanks John, I run the codes in Rstudio and capture the plot. Just as you said, there is no need to use e_arrange() in shiny, I remove it from shiny app and just put them in different columns, thanks.
But I wonder whether e_arrange() could work in shiny? There is no output when using e_arrange() in shiny

**Comment by swsoyee** [comment]
It's a known issue that `e_arrange()` is not able to be used in `{shiny}` #49.

**Comment by JohnCoene** [comment]
@xiaodaowuzhi I've had many requests to make it work, I may look into it eventually. It just looks like a lot of work for something that can already be achieved with ease.
