### ISSUE TITLE
Error using e_flip_coords with e_boxplot

### ISSUE THREAD

**Issue by vituri** [JohnCoene/echarts4r#336]
Here is a repex:

```
iris %>% 
  e_charts() %>% 
  e_boxplot(Petal.Length) %>% 
  e_flip_coords()
```

which gives the error `Erro: $ operator is invalid for atomic vectors`. Browsing a little the `e_flip_coords` function it seems that the issue is cause in a loop, where `e$x$opts$series[[i]]$data[[j]]$value` appears. More precisely, 
```
> e$x$opts$series[[i]]$data[[j]]
[1] 1.00 1.60 4.35 5.10 6.90
```

**Comment by JohnCoene** [comment]
Thanks for reporting this. I just pushed a fix to Github, please install the dev version and try again.

```r
remotes::install_github("JohnCoene/echarts4r")
```

Feel free to reopen if it does not work.
