### ISSUE TITLE
e_add("itemStyle",color) doesn't always seem to work with bar chart

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#338]
If I make a rose pie like this and give labels their own colors (as a way of use timeline and sub groups), everything goes as expected:
```r
df <- data.frame(group=c(1,1,1,1,2,2,2,2),type=c("type1","type1","type2","type2","type1","type1","type2","type2"),
                 value=c(3,3,2,1,4,3,1,2),label=c("name1","name2","name3","name4","name1","name2","name3","name4"),
                 color=c("blue","purple","red","yellow","blue","purple","red","yellow"),
                 stringsAsFactors = FALSE)

df %>%
  group_by(group) %>%
  e_charts(type, timeline = TRUE) %>% 
  e_pie(
    value, 
    roseType = "radius", 
    label = list(
      formatter = htmlwidgets::JS("function(params){
        console.log(params);
        return params.data.label.label;
      }"
      )
    )) %>%
  
  e_add("itemStyle",color) %>%
  e_add("label",label) %>%
  e_legend(show = TRUE, selectedMode="single")
```
If I want something similar with a bar chart, the colors are as expected with the "type1" variable, but not for the "type2" variable. The colors of this second variable seem at random. In my case both bars are green; according to the data frame they shouldn't. In fact there isn't a color green in my df data frame. Could this be a bug?

Here you can see what I mean (please click "type2" in the legend):
```r
df2 <- df %>% spread(type,value)
df2[is.na(df2)] <- 0
df2 %>% group_by(group) %>%
  e_charts(label, timeline=TRUE) %>%
 e_bar(type1) %>%
e_bar(type2) %>%
 e_legend(TRUE,
           selectedMode="single") %>%
  e_add("itemStyle",color)

```

Many thanks in advance!

**Comment by JohnCoene** [comment]
Thanks for reporting this. I pushed a fix, could you reinstall and let me know if it works.

**Comment by rdatasculptor** [comment]
yes, your fix did the job! thanks!
