### ISSUE TITLE
Conflict Between Axis "type" and Axis "formatter" In Heatmaps For Dates as "category"

### ISSUE THREAD

**Issue by szmsu2011** [JohnCoene/echarts4r#339]
Hi there,

I noticed a clash between the `type` and `formatter` arguments for `e_axis()`, such that, formatting the axis as a date destroys the categorical nature of the variable when constructing a daily time-series heatmap.

To illustrate the issue, per following example:

```r
library(tidyverse)
library(lubridate)
library(echarts4r)

packageVersion("echarts4r")
# > [1] ‘0.4.0’

set.seed(2021)
data <- tibble(
  date = seq(ymd(20180107), by = "1 day", length = 1e3),
  week_start = floor_date(date, "week"),
  wday = wday(date, label = TRUE),
  z = rnorm(length(date))
)

data %>%
  e_charts(week_start) %>%
  e_heatmap(wday, z) %>%
  e_visual_map(z) %>%
  e_axis_labels(x = "Week Beginning") %>%
  e_y_axis(inverse = TRUE) %>%
  e_x_axis(nameLocation = "center")
```

Which gives the following daily heatmap:
![heatmap1](https://user-images.githubusercontent.com/77832417/124376144-a2ba0700-dcf9-11eb-8f99-a798e67baec8.JPG)

Then I attempted to re-format the x-axis to as a date:

```r
data %>%
    e_charts(week_start) %>%
    e_heatmap(wday, z) %>%
    e_visual_map(z) %>%
    e_axis_labels(x = "Week Beginning") %>%
    e_y_axis(inverse = TRUE) %>%
    e_x_axis(
        nameLocation = "center",
        type = "time"
    ) %>%
    e_datazoom(x_index = 0)
```

![heatmap2](https://user-images.githubusercontent.com/77832417/124376192-e01e9480-dcf9-11eb-9834-545b1c095743.JPG)
![heatmap3](https://user-images.githubusercontent.com/77832417/124376227-03e1da80-dcfa-11eb-9e3d-ec9c5e3035ce.JPG)

The formatting looks perfect, yet the rectangular tiles become line segments, the visual of the heatmap is broken.

Is there a way to resolve such a clash in formatting the axis as if `type = "time"` whilst retaining its categorical nature?

**Comment by JohnCoene** [comment]
echarts4r infers the axis types from the data it is provided. However, the heatmap in Echarts.js only works with categorical data, hence the function `e_heatmap` forces this here https://github.com/JohnCoene/echarts4r/blob/670d4bcd4a9e8a53f56407814d9eb5f6b9ad3d5e/R/add_.R#L957

What do you want to achieve? Why converting to a time type?

**Comment by szmsu2011** [comment]
My goal is to produce a heatmap with rectangular tiles and x-axis following the format as per the 2nd and 3rd screenshot.

Each column of the heatmap corresponds to one week of data (7 rows), thus simply leaving the x-axis as-is (i.e., yyyy-dd-mm) gives a misleading perception that each row represents one day instead.

**Comment by JohnCoene** [comment]
I would do something like this.

```r
library(tidyverse)
library(lubridate)
library(echarts4r)

set.seed(2021)
data <- tibble(
  date = seq(ymd(20180107), by = "1 day", length = 1e3),
  week_start = floor_date(date, "week"),
  wday = wday(date, label = TRUE),
  z = rnorm(length(date)),
  week = sprintf("week %s", week(date))
)

data %>%
  e_charts(week) %>%
  e_heatmap(wday, z) %>%
  e_visual_map(z) %>%
  e_axis_labels(x = "Week Beginning")
```

![image](https://user-images.githubusercontent.com/7833796/124379831-944bfb00-dcb9-11eb-9e24-ed8bbc8bbf64.png)

**Comment by szmsu2011** [comment]
For data ranging across several years, labeling the x-axis with week might be a bit confusing.

But thanks a lot for providing some inspiration. I found a way that at least achieves my purpose, although the formatting is still not as good as the one from natural date/time axis.

```r
mutate(data, week_start = paste(
  year(week_start),
  month(week_start, label = TRUE),
  day(week_start) # Making them unique
)) %>%
  e_charts(week_start) %>%
  e_heatmap(wday, z) %>%
  e_visual_map(z) %>%
  e_y_axis(inverse = TRUE) %>%
  e_x_axis(formatter = htmlwidgets::JS("
      function(value) {
        return value.substring(0, 8);
      }
  "))
```
![image](https://user-images.githubusercontent.com/77832417/124380912-a0fd3d00-dd13-11eb-9f21-fd007e1b96f6.png)

**Comment by JohnCoene** [comment]
I'm going to close this, please feel free to reopen if the solution is really inadequate. Thanks!
