### ISSUE TITLE
Unable to Isolate "e_connect()" Solely for "datazoom"

### ISSUE THREAD

**Issue by szmsu2011** [JohnCoene/echarts4r#340]
Hi there,

I am trying to link two `echarts4r` objects with `e_connect()` to synchronise their "datazoom" sliders. Take the modified example from [the e_connect documentation](https://echarts4r.john-coene.com/reference/connections.html):

```r
library(tidyverse)
library(echarts4r)

packageVersion("echarts4r")
# > [1] ‘0.4.0’

some_data <- tibble(
  x = rnorm(100),
  y = rnorm(100)
)

e1 <- cars %>%
  e_charts(
    speed,
    height = 200
  ) %>%
  e_scatter(dist) %>%
  e_datazoom(show = FALSE) %>%
  e_tooltip() %>%
  e_group("grp")

e2 <- some_data %>%
  e_charts(
    x,
    height = 200
  ) %>%
  e_scatter(y) %>%
  e_datazoom() %>%
  e_tooltip() %>%
  e_group("grp") %>%
  e_connect_group("grp")

if (interactive()) {
  e_arrange(e1, e2, title = "Linked datazoom")
}
```

When I hover-over the points on the top plot, tooltips pop up in both plots. Contextually, the points in plot 1 and 2 are completely different observations thus it makes no sense (in my case) to link them together.

Is there a way to isolate the connection just for "datazoom"? If it is not possible, is it possible to at least break the tooltip linking? (I tried something like assigning `axisPointer = list(link = NULL)` to `e_tooltip()` but it did not work.)

Thank you in advance.

**Comment by JohnCoene** [comment]
I'm afraid the JavaScript connect function just connects everything, it does not take any argument.

What you want to do can be achieved without. Arranging the series on a single plot by playing with the grid and having the datazoom work on both x axis.

I know the API is not great but it works. There is more documentation [here](https://echarts4r.john-coene.com/articles/grid.html).

```r
library(echarts4r)

some_data <- tibble(
  x = rnorm(100),
  y = rnorm(100)
)

cars %>%
  e_charts(speed) |> 
  e_scatter(dist) |> 
  e_data(some_data, x) |> 
  e_scatter(y, x_index = 1, y_index = 1) |> 
  e_tooltip() |> 
  e_grid(height = "35%") |> 
  e_grid(height = "35%", top = "50%") |> 
  e_y_axis(gridIndex = 1) |> # put x and y on grid index 1
  e_x_axis(gridIndex = 1) |> 
  e_datazoom(x_index = c(0, 1))
```

**Comment by szmsu2011** [comment]
My apologies for the confusion, upon writing up this post, for simplicity, it seemed like I wanted to achieve the plots altogether. In fact the two actual plots I am working on are to be implemented in two separate but linked shiny modules.

Just to confirm is there any else doable in such a situation? If not, I should probably just discard the tooltip for the moment.

**Comment by JohnCoene** [comment]
Yes I'm afraid that will not work. I really do not see any argument anywhere to control this. [see connect](https://echarts.apache.org/en/api.html#echarts.connect)

**Comment by szmsu2011** [comment]
Hi there,

I see a [solution by helgasoft](https://gist.github.com/helgasoft/963e6dbe9742f7b1076ae36c423fe82c#gistcomment-3802279). Is it achievable in the current version of **echarts4r**?

If not, it would be useful if similar solutions could be implemented in **echarts4r** some time in the future.

**Comment by JohnCoene** [comment]
Yes.

```r
library(shiny)
library(tidyverse)
library(echarts4r)

ui <- fluidPage( 
  tags$head(tags$script(HTML("
    function bindAction(chartList) {
      echarts.util.each(chartList, function (fromChart) {
          echarts.util.each(chartList, function (toChart) {
            if (fromChart === toChart) {
                return;
            }

            fromChart.on('updateAxisPointer', function (params) {
                toChart.dispatchAction(
                    toChart.makeActionFromEvent(params),
                    true
                );
            });

            fromChart.on('dataZoom', function (params) {
              console.log(params);
                toChart.dispatchAction({
                    type: 'dataZoom',
                    dataZoomIndex: 1,
                    start: params.start,
                    end: params.end
                }, true);
            });
          });
      });
    };

    function bindCharts(){
      let ch1 = get_e_charts('chart1');
      let ch2 = get_e_charts('chart2');
      bindAction([ch1, ch2]); 
    }
  "))), 
  echarts4rOutput('chart1', height='300'),
  echarts4rOutput('chart2', height='300')
)

server <- function(input, output, session) {
  some_data <- tibble(
    x = sample(1:100, 33),
    y = sample(1:100, 33)
  )
  
  output$chart1 <- renderEcharts4r({
    cars %>%
      e_charts(
        speed
      ) %>%
      e_scatter(dist) %>%
      e_datazoom(show = FALSE) %>%
      e_tooltip()
  })
  output$chart2 <- renderEcharts4r({
    some_data %>%
      e_charts(
        x
      ) %>%
      e_scatter(y) %>%
      e_datazoom() %>%
      e_tooltip() %>% 
      htmlwidgets::onRender(
        "bindCharts();"
      )
  })
}

shinyApp(ui = ui, server = server)
```

**Comment by szmsu2011** [comment]
Thank you very much, much appreciated.
