### ISSUE TITLE
Proxy with e_color: Error in !: invalid argument type

### ISSUE THREAD

**Issue by etiennebacher** [JohnCoene/echarts4r#347]
Hello, I used the example from the [Proxies](https://echarts4r.john-coene.com/articles/proxies.html) page, but modified it to change the color of the points instead of adding a line.

```r
library(shiny)
library(echarts4r)

# phoney data
df <- data.frame(
  x = 1:100,
  y = runif(100),
  z = runif(100)
)

ui <- fluidPage(
  actionButton("add", "Add z serie"), # button
  echarts4rOutput("chart")
)

server <- function(input, output){
  
  output$chart <- renderEcharts4r({
    e_charts(df, x) |> 
      e_scatter(y, z)
  })
  
  observeEvent(input$add, {
    echarts4rProxy("chart", data = df, x = x) |>  # create a proxy
      e_color("red") |> 
      e_execute()
  })
  
}

shinyApp(ui, server)
```
This returns an error:
```
Warning: Error in !: invalid argument type
```

whereas adding `e_color` outside the shiny environment works well:

```r
e_charts(df, x) |> 
  e_scatter(y, z) |>
  e_color("red")
```

**Comment by JohnCoene** [comment]
I just added it to the dev version but it may not behave as you expect it. Let me know what you are trying to achieve.

```r
library(shiny)
library(echarts4r)

# phoney data
df <- data.frame(
  x = 1:100,
  y = runif(100),
  z = runif(100)
)

ui <- fluidPage(
  actionButton("add", "Add z serie"), # button
  echarts4rOutput("chart")
)

server <- function(input, output){
  
  output$chart <- renderEcharts4r({
    e_charts(df, x) |> 
      e_scatter(y, z) |> 
      e_color("red")
  })
  
  observeEvent(input$add, {
    echarts4rProxy("chart", data = df, x = x) |>  # create a proxy
      e_line(y, name = 'hello') |> 
      e_color("blue") |> 
      e_execute()
  })
  
}

shinyApp(ui, server)
```

**Comment by etiennebacher** [comment]
Thanks, but that's not what I had in mind: with your example the added line is blue, whereas I just wanted to change the color of the points that are already present, not add a new line.

Basically, in my app I have a plot with 4 lines, one per person. I also have 4 buttons, and each button should highlight the curve of one person. So what I had in mind was:

* start with 4 lines displayed in different colours
* click on person A's button
* make the line for person A red and the 3 other lines grey (so that the line of person A is highlighted compared to others)
* click on a "reset" thing, and go back to first plot

This is why I need to use `e_color()` in a proxy. But if you have other ideas, please tell me.

**Comment by JohnCoene** [comment]
OK.

The issue is that there is no specific method in ECharts that allows changing the color of a specific series. `e_send_p` sends recreates a chart in a sense and uses `setOption` to redefine the options that define the chart. The vector of colors for the 
series is part of those options.

So the only way to do this is to add an `append` argument to the `e_color` function to allow either replacing this vector of 
colors or to append to it (when using the proxy).

```r
library(shiny)
library(echarts4r)

# phoney data
df <- data.frame(
  x = 1:100,
  y = runif(100),
  z = runif(100)
)

ui <- fluidPage(
  actionButton("add", "Add z serie"), # button
  echarts4rOutput("chart")
)

server <- function(input, output){

  colors <- c("red")
  
  output$chart <- renderEcharts4r({
    e_charts(df, x) |> 
      e_scatter(y, z) |> 
      e_color(colors)
  })
  
  observeEvent(input$add, {
    colors <- append(colors, "blue")
    echarts4rProxy("chart", data = df, x = x) |>  # create a proxy
      e_line(y, name = 'hello') |> 
      e_color(colors, append = FALSE) |> 
      e_execute()
  })
  
}

shinyApp(ui, server)
```

The only tricky bit with this is that you have to keep track of this vector of colors (see above).

Let me know if that helps and is clear at all.
Sorry I cannot come up with clearer than this.

**Comment by etiennebacher** [comment]
Thanks for the explanation and the fix. The example doesn't produce what I want: I don't want to add a new line, just change the color of the points. But I could find a way by slightly modifying the code in your previous comment. Here's the version that does what I had in mind:
```
library(shiny)
library(echarts4r)

# phoney data
df <- data.frame(
  x = 1:100,
  y = runif(100),
  z = runif(100)
)

ui <- fluidPage(
  actionButton("add", "Add z serie"), # button
  echarts4rOutput("chart")
)

server <- function(input, output){
  
  colors <- c("red")
  
  output$chart <- renderEcharts4r({
    e_charts(df, x) |> 
      e_scatter(y, z) |> 
      e_color(colors)
  })
  
  observeEvent(input$add, {
    colors <- "blue"
    echarts4rProxy("chart", data = df, x = x) |>  # create a proxy
      e_color(colors, append = FALSE) |> 
      e_execute()
  })
  
}

shinyApp(ui, server)
```
I close this for now, and will reopen if it turns out something's wrong in my real app. Thanks again for the quick fix!
