### ISSUE TITLE
Feature request: chart element remains highlighted on click

### ISSUE THREAD

**Issue by u9090** [JohnCoene/echarts4r#350]
Hello,

First of all, thank you for your great package !

It does not seem possible to get a chart element (e.g. a bar in a bar plot) to remain highlighted (or to display a different color, ...) when clicked. The element is highlighted only on mouseover.
It would be great if this feature could be implemented.

Example:
```r
mtcars %>% 
   tibble::rownames_to_column("model") %>% 
   tail() %>% 
   e_charts(model) %>% 
   e_bar(cyl)
```

**Comment by JohnCoene** [comment]
This is already possible.

```r
library(echarts4r)

mtcars |> 
  tibble::rownames_to_column("model") |> 
  tail() |> 
  e_charts(model) |>
  e_bar(
    cyl,
    selectedMode = "multiple", # or single
    select = list(
      itemStyle = list(
        color = "black",
        fillColor = "black"
      )
    )
  )
```

More options [here](https://echarts.apache.org/en/option.html#series-bar.select)

Feel free to reopen if this does not solve the issue

**Comment by u9090** [comment]
Sorry @JohnCoene, this is not working.

**Comment by JohnCoene** [comment]
Can you install the latest version and check again? This was added a long time ago and really should work, latest CRAN is OK

**Comment by u9090** [comment]
Thanks @JohnCoene !
Unfortunately, I cannot install the latest CRAN version (requires R >= 4.1.0, but organization runs earlier version).
Would it be possible using the `formatter` parameter maybe?

**Comment by JohnCoene** [comment]
You can try `remotes::install_github("JohnCoene/echarts4r@v0.3.3")` this does not required v4.1.0

**Comment by u9090** [comment]
Sorry again @JohnCoene , still not working with v0.3.3.

**Comment by JohnCoene** [comment]
Sorry, I think that previous version did not have that feature in at the time. My bad I thought it did.

There's not much I can do to make it work on previous versions. Apologies.
