### ISSUE TITLE
How can I install the package in centos 7.6 (R version 3.6)?

### ISSUE THREAD

**Issue by xiaodaowuzhi** [JohnCoene/echarts4r#355]
Hi John,

For Centos 7.6, the latest R is version 3.6, so how can I install this package in R 3.6? An error occured, "ERROR: this R is version 3.6.0, package 'echarts4r' requires R >= 4.1.0", thanks

**Comment by swsoyee** [comment]
Hi, You could try to use v3.3. https://github.com/JohnCoene/echarts4r/issues/350#issuecomment-888118163

**Comment by xiaodaowuzhi** [comment]
Hi swsoyee,

Thanks, it works fine for me.

**Comment by JohnCoene** [comment]
Thanks @swsoyee! @xiaodaowuzhi you may be missing a few minor features that were added later on but that version should be good.
