### ISSUE TITLE
X-axis max doubled when adding stacked e_bars?

### ISSUE THREAD

**Issue by sharlagelfand** [JohnCoene/echarts4r#357]
Hi! Thanks for this great package :)

I'm running into a strange issue where the x-axis max is doubled (?) when I'm adding two `e_bar()`s that are stacked. I want to create a bar chart where one bar is "highlighted", so I'm accomplishing that with two series.

The x limits in the data are the same, and they each appear separately just fine:

```r
library(echarts4r)
library(dplyr)

df_1 <- data.frame(
  x = 1:5, 
  y_1 = c(1, 2, 3, NA, 5)
)

df_1 %>%
  e_chart(x) %>%
  e_bar(y_1)
```

<img width="1252" alt="Screen Shot 2021-08-05 at 2 17 32 PM" src="https://user-images.githubusercontent.com/15895337/128400995-a6f2da3e-ba0c-4cb4-b05c-9c65db2a2b98.png">

```r
df_2 <- data.frame(
  x = 1:5, 
  y_2 = c(NA, NA, NA, 4, NA)
)

df_2 %>%
  e_chart(x) %>%
  e_bar(y_2)
```

<img width="1229" alt="Screen Shot 2021-08-05 at 2 17 51 PM" src="https://user-images.githubusercontent.com/15895337/128401008-d2f06f7e-5da1-459c-8754-3ee04c08c239.png">

When I combine, the styling looks as desired - I'm "fake" stacking them I guess, because I don't want the dodged behaviour, and that looks fine - but the x-axis max is doubled, going all the way to 10 instead of 5:

```r
df_combined <- df_1 %>%
  left_join(df_2, by = "x")

df_combined %>%
  e_chart(x) %>%
  e_bar(y_1, stack = "group") %>%
  e_bar(y_2, stack = "group")
```

<img width="1208" alt="Screen Shot 2021-08-05 at 2 18 46 PM" src="https://user-images.githubusercontent.com/15895337/128401018-0d7299cb-3dec-4082-b7c3-36f775172148.png">

Any ideas why this might be? I'm using the latest version from github. I know you can manually set the limits, but it's hard to do that on a dynamic / not-manual basis. Thank you!

**Comment by JohnCoene** [comment]
If that's of any consolation, it was difficult for me to figure out too.

In Echarts.js the `bar` serie is "optimised" for a categorical x axis, it never really works right with a number type on the x axis.
Internally, echarts4r infers the type it sets in Echarts.js based on the data it is being fed.
Converting `x` to `factor` or `categorical` corrects this.

```r
df_combined %>%
  mutate(x = as.factor(x)) %>% 
  e_chart(x) %>%
  e_bar(y_1, stack = "group") %>%
  e_bar(y_2, stack = "group")
```

With the above echarts4r observes that the data on the x axis is `factor` and correctly communicates to Echarts.js that
 the x axis should be `categorical`.

Let me know if this is not clear.
I should probably makes this clearer in the documentation.

**Comment by JohnCoene** [comment]
I've added a note about it in the documentation.

I should perhaps force the data type to `categorical` internally but I'm worried this may impact other things. I'll think about it.

Thanks again for reporting this.

**Comment by sharlagelfand** [comment]
Ahhh that makes sense, thanks for clarifying! Looks great now.

Also helps me understand why manually setting the limits didn't really do what I want - was definitely acting factor-like! Thanks!
