### ISSUE TITLE
how to set font size of parallel axis label, e_y_axis doesn't work

### ISSUE THREAD

**Issue by eltonC1990** [JohnCoene/echarts4r#358]
I'am a new to echarts. here is my code.it seems the "e_y_axis" doesn't work.
dt_ex=data.frame(x=LETTERS[1:5],y=rnorm(5,1,2),z=rnorm(5,500,1))
dt_ex %>% 
  e_charts() %>% 
  e_parallel(y:z) %>% 
  e_y_axis(axisLabel=list(fontSize=20))

**Comment by JohnCoene** [comment]
This should work. What are you trying to achieve exactly?
