### ISSUE TITLE
Is there a way to use endLabel to identify a series group on a line chart?

### ISSUE THREAD

**Issue by smach** [JohnCoene/echarts4r#359]
I have a multi-series line chart that I'm generating with a grouped data frame. Is there any way to get the end label to show the **series** and not the **x or y values**? For example, if I have this data frame of daily Covid cases for 4 states:

`mydf <- data.frame(State = c("Florida", "Florida", "Florida", "Florida", 
                         "Florida", "Florida", "Florida", "Florida", "Massachusetts", 
                         "Massachusetts", "Massachusetts", "Massachusetts", "Massachusetts", 
                         "Massachusetts", "Massachusetts", "Massachusetts", "New York", 
                         "New York", "New York", "New York", "New York", "New York", "New York", 
                         "New York", "South Carolina", "South Carolina", "South Carolina", 
                         "South Carolina", "South Carolina", "South Carolina", "South Carolina", 
                         "South Carolina"), 
                      CasesPer100K = c(397, 575, 579, 591, 617, 733, 654, 690, 54, 79, 83, 88, 92, 76, 104, 107, 84,  89, 95, 101, 106, 123, 125, 133, 151, 249, 287, 249, 259, 245, 371, 378), 
                   Date = c("2021-08-02", "2021-08-03", "2021-08-04", "2021-08-05", "2021-08-06", "2021-08-09", "2021-08-10", "2021-08-11",  "2021-08-02", "2021-08-03", "2021-08-04", "2021-08-05", "2021-08-06", "2021-08-09", "2021-08-10", "2021-08-11", "2021-08-02", "2021-08-03", "2021-08-04", "2021-08-05", "2021-08-06", "2021-08-09", "2021-08-10", "2021-08-11", "2021-08-02", "2021-08-03", "2021-08-04", "2021-08-05", "2021-08-06", "2021-08-09", "2021-08-10", "2021-08-11"), stringsAsFactors = FALSE) `

I'd like the end labels to be Florida, Massachusetts, New York, and South Carolina, but instead I either get the case number or the date. This doesn't work to change it to State, the labels show the last x values instead. Thanks!

```
library(dplyr)
library(echarts4r)
mydf %>%
  group_by(State) %>%
  e_chart(Date) %>%
  e_line(CasesPer100K,  endLabel = list(show = TRUE, formatter = "{@[State]}")) %>%
  e_tooltip()
```

**Comment by JohnCoene** [comment]
When you `group_by` the groups are not really passed within the data, the group is used, by default as series name. Therefore: `formatter = "{a}"` works.

**Comment by smach** [comment]
Thank you!!! I tried `formatter = "{@a}"` and that did not work. No `@`, just `{a}`. Got it! Thanks again!
