### ISSUE TITLE
Possible adding zoom feature in map?

### ISSUE THREAD

**Issue by u9090** [JohnCoene/echarts4r#362]
Is it possible to zoom in/out a map (either using '+'/'-' buttons or by mouse scrolling)?

**Comment by JohnCoene** [comment]
You can set `roam` to `TRUE` and then use the mousewheel.

```r
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
  country = cns,
  value = runif(length(cns), 1, 100)
)

cns |> 
  e_charts(country) |> 
  e_map(value, roam = TRUE) |> 
  e_visual_map(value)
```

**Comment by u9090** [comment]
Thank you @JohnCoene, that's awesome !

If I may ask, is it possible as well to:
. add a reset button to retrieve the orignal view,
. set a zoom limit to the original view when zooming out (i.e. the user cannot obtain a smaller map than the original)

I tried to use `e_dispatch_action_p`, `e_datazoom` and `e_toolbox_feature` with the `"dataZoom"` action, but it does ot seem to be for geo plots.

**Comment by JohnCoene** [comment]
To limit the zoom you can use `scaleLimit`

```r
cns |> 
  e_charts(country) |> 
  e_map(
    value, 
    roam = TRUE,
    scaleLimit = list( # limit zoom
      min = 1,
      max = 0
    )
  ) |> 
  e_visual_map(value) |>
  e_toolbox(
    show = TRUE,
    feature = list(
      restore = list() # restore button
    )
  )
```

The [documentation for it](https://echarts.apache.org/en/option.html#series-map.scaleLimit) is very sparse so it's difficult to use correctly.

**Comment by u9090** [comment]
Great !
Thanks @JohnCoene
