### ISSUE TITLE
Using themes makes the tooltips go transparent gray

### ISSUE THREAD

**Issue by Alik-V** [JohnCoene/echarts4r#363]
Hi John,

Thanks again for working on the package! I think I found a bug when trying to use tooltips together with themes:

```r
  data.frame(
    x = 1:10,
    y = runif(10, 5, 10)
  ) %>%
    e_charts(x) %>%
    e_line(y, symbol = 'none') %>%
    e_theme("inspired") %>% # same for "infographic" theme, haven't tried others
    e_tooltip(trigger = "axis", formatter = e_tooltip_pointer_formatter(digits = 1))
```

This results in a gray-transparent tooltips that are hard to read:
![image](https://user-images.githubusercontent.com/43731270/129759345-019098af-dc18-478a-af07-bb9cf4eab7d6.png)

**Comment by JohnCoene** [comment]
I though it must be a bug but it seems echarts.js changed the default background color of
the tooltip to this: bit ugly. See [here](https://echarts.apache.org/en/option.html#tooltip.backgroundColor)

```r
library(echarts4r)

data.frame(
  x = 1:10,
  y = runif(10, 5, 10)
) |> 
  e_charts(x) |> 
  e_line(y, symbol = 'none') |> 
  e_theme("inspired") |>  # same for "infographic" theme, haven't tried others
  e_tooltip(
    trigger = "axis", 
    formatter = e_tooltip_pointer_formatter(digits = 1),
    backgroundColor = "rgba(255,255,255,0.7)"
  )
```

You can use any valid HTML color, e.g.: `rgba()` to add use transparency, `rgb(255,255,255)`, hex `#ffffff` or valid names `black`.
Plenty more options are available [here](https://echarts.apache.org/en/option.html#tooltip).

**Comment by Alik-V** [comment]
Thanks for the swift reply! 
It is pretty ugly now, wonder what their reasoning was... 
This solves the issue and thank you for this information. Hope you have a good evening!
