### ISSUE TITLE
e_flip_coords does not work properly with outliers in boxplot

### ISSUE THREAD

**Issue by Laurent-Smeets-GSS-Account** [JohnCoene/echarts4r#365]
Outliers are shown when running this code (per example)

```r
df <- data.frame(
  x = c(1:10, 25),
  y = c(1:10, -6)
)

df |>
  e_charts() |>
  e_boxplot(y, outliers = TRUE) |>
  e_boxplot(x, outliers = TRUE) 
```

but not when adding  `e_flip_coords `

```r
df <- data.frame(
  x = c(1:10, 25),
  y = c(1:10, -6)
)

df |>
  e_charts() |>
  e_boxplot(y, outliers = TRUE) |>
  e_boxplot(x, outliers = TRUE) |>
  e_flip_coords() 
```

This might have something to do with https://github.com/JohnCoene/echarts4r/issues/336#issue-932833281, but installing the latest GitHub release did not fix it for me.

**Comment by JohnCoene** [comment]
I pushed a fix, please reinstall the latest version and let me know if that works as expected.
