### ISSUE TITLE
change fontSize of e_gauge, render it in 'darkMode'

### ISSUE THREAD

**Issue by shahreyar-abeer** [JohnCoene/echarts4r#366]
For the font-size, I've tried this. But this doesn't seem to be working.

```r
e_charts() |> 
  e_gauge(28, "Per hour") |>
  e_labels(textStyle = list(color = "#fff", fontSize = '1rem'))

```

And as for the darkMode, setting the `e_common(theme = 'dark')` simply sets the background to dark, the actual plot remains as is.

**Comment by JohnCoene** [comment]
This is responsive on my end.

![image](https://user-images.githubusercontent.com/7833796/131502494-72026df3-b1a7-4e9b-9cff-f4d41ddd7b92.png)

For the theme I'm sorry I cannot really help, these themes are built-in but I'm fairly certain they mostly ignore the gauge.
I would advice modifying the theme with the [builder](https://echarts.apache.org/en/theme-builder.html) then use [this](https://echarts4r.john-coene.com/articles/themes.html#custom-1) to apply it to echarts4r.
