### ISSUE TITLE
Resizing the whole chart

### ISSUE THREAD

**Issue by Camil88** [JohnCoene/echarts4r#369]
Hello, is it there any option to resize a chart? I mean not resize inner chart area (since it's possible, I know) but the whole chart. In other words - to make a whole chart bigger by clicking any button/widget embedded to a chart?

**Comment by JohnCoene** [comment]
Not within the chart, this would be a functionality from outside echarts4r. Echarts.js is responsive so any resizing should work fine. Can you explain a bit more what you are trying to achieve?

**Comment by Camil88** [comment]
Ok, got it. So generally speaking I would like to click a button somewhere on a chart which will resize the whole chart. This is because I created a dashboard and the chart I embedded is quite small - by resizing it on a full screen (or half screen) I could show it better.

**Comment by JohnCoene** [comment]
Is [this](https://github.com/etiennebacher/shinyfullscreen) what you need? @etiennebacher

**Comment by Camil88** [comment]
That's nice, thanks!
