### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by williamorim** [JohnCoene/echarts4r#372]
Hi, thanks for the great package!

How can I translate automatic labels to other languages? For example: in the plot below I would like to translate the month names to Portuguese. I know I can use a JS function in the axis `formatter` argument, but I would like to set the chart locale as specified here: https://echarts.apache.org/en/api.html#echarts.init

![image](https://user-images.githubusercontent.com/8967307/133334896-5b7903ec-9b7c-4036-9ff0-3622f4921c26.png)

Thanks for your attention!

**Comment by JohnCoene** [comment]
Can you reinstall the package from Github and try `e_locale` ([doc](https://echarts4r.john-coene.com/reference/e_locale.html))?

**Comment by williamorim** [comment]
It works! Thank you very much John.

Reprex:

```
df <- tibble::tibble(
  date = lubridate::make_date(
    year = 2021,
    month = 1:12,
    day = 1
  ),
  value = cumsum(sample(1:10, 12, TRUE))
)

df |> 
  echarts4r::e_chart(x = date) |> 
  echarts4r::e_line(serie = value) |> 
  echarts4r::e_locale(locale = "PT-BR")
```

![image](https://user-images.githubusercontent.com/8967307/135851119-e7192bf8-a855-4615-b502-f6694d81510e.png)


```
df |> 
  echarts4r::e_chart(x = date) |> 
  echarts4r::e_line(serie = value) |> 
  echarts4r::e_locale(locale = "FR")
```

![image](https://user-images.githubusercontent.com/8967307/135851210-95e0549e-dbf4-419e-afc1-39db8fcc58cd.png)

**Comment by JohnCoene** [comment]
Pleasure!
