### ISSUE TITLE
maximizability issues - charts don't show up with width/height set to `'auto'`

### ISSUE THREAD

**Issue by yogat3ch** [JohnCoene/echarts4r#373]
Hi @JohnCoene ,
We're really enjoying the aesthetic of the echarts package and appreciate your efforts to create it!

Our echarts are contained in `bs4Dash::bs4Card`s because our users are asking for the ability to maximize the charts and we imagined that the maximize functionality on the cards will suit this purpose. 

In the [echarts docs](https://echarts.apache.org/en/api.html#echarts) under `opts` it indicates the following:
  - `width` Specify width explicitly, in pixel. If setting to null/undefined/'auto', width of dom (instance container) will be used.
  - `height` Specify height explicitly, in pixel. If setting to null/undefined/'auto', height of dom (instance container) will be used.
  
In the reprex below, we've followed these instructions but as you will see, the echarts don't show up. 
Any advice on how to create an echart inside a DOM element and have it size to match it's container?

````r
library(shiny)

# Define UI for application that draws a histogram
ui <- fluidPage(

    # Application title
    titlePanel("E-charts fullscreen issue"),

    # Sidebar with a slider input for number of bins 
    bs4Dash::dashboardPage(
        header = bs4Dash::dashboardHeader(disable = TRUE),
        body = bs4Dash::dashboardBody(
            shiny::fluidRow(
                bs4Dash::bs4Card(width = 4),
                bs4Dash::bs4Card(echarts4r::echarts4rOutput("chart", height = "auto", width = "auto"), width = 4, maximizable = TRUE),
                bs4Dash::bs4Card(width = 4)
            )
            
        ),
        sidebar = bs4Dash::bs4DashSidebar(disable = TRUE)
    )
)

# Define server logic required to draw a histogram
server <- function(input, output) {

    
        # generate bins based on input$bins from ui.R
        p = iris |> 
            dplyr::group_by(Species) |>
            echarts4r::e_charts(x = Petal.Width, height = 'auto', width = 'auto') |>
            echarts4r::e_line(Petal.Length, symbol = "none") |>
            echarts4r::e_y_axis(scale = TRUE) |>
            echarts4r::e_band2(lower = Sepal.Length, upper = Sepal.Width, itemStyle = list(opacity = 0.4)) |>
            echarts4r::e_tooltip(trigger = "axis") |>
            echarts4r::e_datazoom() |>
            echarts4r::e_toolbox(orient = "vertical", itemSize = 10) |>
            echarts4r::e_toolbox_feature(feature = c("saveAsImage" ,"dataZoom", "restore"))
        
     
        
        
        
        
        # setting outputs
        output$chart = echarts4r::renderEcharts4r({ p })
    
}

# Run the application 
shinyApp(ui = ui, server = server)
````

@keatonwilson

**Comment by JohnCoene** [comment]
I'm not behind a laptop for the week, sorry.

This is because the `height` and `width` that are passed to `e_charts` is not used in the JavaScript API and is instead used for the parent container.

Generally, one keeps the chart itself responsive and instead defines the dimensions of the parent container.
Though I think this only really works for the width and will not resize the height.

I will expose those options in echarts4r via another function.

**Comment by yogat3ch** [comment]
Hi @JohnCoene,
Thanks for the answer while you're away! 
That makes sense, I noticed that the output of the `div` from the `echarts4rOutput` and the containing `div` made by `e_chart` seemed to have the height/width settings specified while the `canvas` with the chart did not. It looks like height/width just get passed down to the `htmlwidgets` function.

>I will expose those options in echarts4r via another function.

Does that entail creating another JS handler like [`e_resize`](https://github.com/JohnCoene/echarts4r/blob/e606b197b5c6180d602a08e7725948f247160faf/R/proxies.R#L507) and then providing an custom messange handler that [calls the associated JS Handler](https://github.com/JohnCoene/echarts4r/blob/2d08c2e9872d475f8e5fd88d95ccd9c790b92242/inst/htmlwidgets/echarts4r.js#L357)?

Though in this case the JS handler would be more [like this](https://github.com/JohnCoene/echarts4r/blob/2d08c2e9872d475f8e5fd88d95ccd9c790b92242/inst/htmlwidgets/echarts4r.js#L334) since it would just be setting an option?

I'm considering attempting a PR if I'm clear on what to do. 
If you'd rather implement it yourself when you return, that's fine too.

Thanks!

**Comment by JohnCoene** [comment]
@divadnojnarg it seems the full screen for the card does not trigger a resize even if the htmlwidget wrapper/parent is fully responsive (e.g.: `100%`)

How can I make it such that it responds to it properly?

**Comment by JohnCoene** [comment]
@divadnojnarg I don't see other htmlwidgets responding to it either.

```r
library(shiny)
devtools::load_all()

ui <- bs4Dash::dashboardPage(
  header = bs4Dash::dashboardHeader(disable = TRUE),
  body = bs4Dash::dashboardBody(
    shiny::fluidRow(
      bs4Dash::bs4Card(plotly::plotlyOutput("plot"), width = 4, maximizable = TRUE),
      bs4Dash::bs4Card(echarts4r::echarts4rOutput("chart"), width = 4, maximizable = TRUE),
      bs4Dash::bs4Card(width = 4)
    )
  ),
  sidebar = bs4Dash::bs4DashSidebar(disable = TRUE)
)

# Define server logic required to draw a histogram
server <- function(input, output) {

  # generate bins based on input$bins from ui.R
  p <- iris |> 
    dplyr::group_by(Species) |>
    echarts4r::e_charts(x = Petal.Width) |>
    echarts4r::e_line(Petal.Length, symbol = "none") |>
    echarts4r::e_y_axis(scale = TRUE) |>
    echarts4r::e_band2(lower = Sepal.Length, upper = Sepal.Width, itemStyle = list(opacity = 0.4)) |>
    echarts4r::e_tooltip(trigger = "axis") |>
    echarts4r::e_datazoom() |>
    echarts4r::e_toolbox(orient = "vertical", itemSize = 10) |>
    echarts4r::e_toolbox_feature(feature = c("saveAsImage" ,"dataZoom", "restore")) |> 
    echarts4r::e_dims()
  # setting outputs
  output$chart <- echarts4r::renderEcharts4r(p)

  output$plot <- plotly::renderPlotly({
    plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
  })
    
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by JohnCoene** [comment]
Grand! thanks @DivadNojnarg!

@yogat3ch does that answer your question?

**Comment by yogat3ch** [comment]
Hi @DivadNojnarg, 
Thanks for chiming in here - 
I actually implemented something quite similar to this derived from [RinteRface/bs4Dash#146](https://github.com/RinteRface/bs4Dash/issues/146)

```
cardTag <- shiny::tags$div(class = cardCl, id = id, style = style)
  cardTag <- shiny::tagAppendChildren(cardTag, headerTag, bodyTag, footerTag)
  
  # wrapper
  shiny::tags$div(
    class = if (!is.null(width)) paste0("col-sm-", width),
    cardTag,
    # config script to be used by card input binding
    shiny::tags$script(
      type = "application/json",
      `data-for` = id,
      jsonlite::toJSON(
        x = props,
        auto_unbox = TRUE,
        json_verbatim = TRUE
      )
    ),
    if (maximizable)
      shiny::tags$script(
        type = "text/javascript",
        paste0("
               $(document).ready(function() {
               $('[data-card-widget=\"maximize\"]').on('click', function() {
                setTimeout(function() {
                  var isMaximized = $('html').hasClass('maximized-card');
                  if (isMaximized) {
                   window.location.reload()
                  }
                }, 300);
                $('#",ifelse(is.null(id), "", paste0("#",id)),"').trigger('resize');
              });
               }
               ")
      )
      
  )
```

However, it didn't seem to work. I'll try calling the `resize` method directly and see if that works. Will report back soon

**Comment by yogat3ch** [comment]
@DivadNojnarg 
Does this have to be applied at the level of the `dashboardbody`? If so, I tried this solution since we have > 24 plots contained within cards, all with different ids and it didn't seem to resolve. My JS is not so good though so there might be issues with this code that I'm not taking into account. If it has to be deployed at the `dashboardBody` level, any idea how I could modify this code to make it work for all plots embedded in cards?

Or perhaps I should just wait for a PR?

```
        paste0("
        $(document).ready(function() {
        var ids = $('div",ifelse(is.null(id), "", paste0("#",id))," div.card-body div').map(function(){
      return $(this).attr('id');
      }).get();
      function resizeBoxContent(trigger, target) {
              var target = '#' + target
              $(trigger).on('click', function() {
                setTimeout(function() {
                  var isMaximized = $('html').hasClass('maximized-card');
                    if (isMaximized) {
                      $(target).css('height', '100%');
                      $(target).css('width', 'auto');
                    } else {
                      $(target).css('height', '400px');
                      $(target).css('width', 'auto');
                    }
                  console.log('resizing '+ target)
                }, 300);
                $(target).trigger('resize');
              });
            };
      setTimeout(function() {
              ids.map(function(x){
                resizeBoxContent('div.card button[data-card-widget=\"maximize\"]', x);
              })

            }, 500);
      console.log(ids);
      });")
```

**Comment by yogat3ch** [comment]
Hey @JohnCoene & @DivadNojnarg,
Modified the JS attached to a `bs4Card` to be as follows:

```
cardTag <- shiny::tags$div(class = cardCl, id = id, style = style)
  cardTag <- shiny::tagAppendChildren(cardTag, headerTag, bodyTag, footerTag)
  
  # wrapper
  shiny::tags$div(
    class = if (!is.null(width)) paste0("col-sm-", width),
    cardTag,
    # config script to be used by card input binding
    shiny::tags$script(
      type = "application/json",
      `data-for` = id,
      jsonlite::toJSON(
        x = props,
        auto_unbox = TRUE,
        json_verbatim = TRUE
      )
    ),
    if (maximizable)
      shiny::tags$script(
        type = "text/javascript",
        paste0("
              
               $('[data-card-widget=\"maximize\"]').on('click', function() {
        
                $('",ifelse(is.null(id), "", paste0("#",id)),"').resize();
              });
               }
               ")
      )
      
  )
```


Then I noticed using Chrome browser dev tools that the ID points to the card and not the plot itself, so I modified it to point to the plot inside a specific card and it did not work.
```

               
               $('[data-card-widget="maximize"]').on('click', function() {
                
                $('#body-body_reservoirs-mead_elev_ribbon-res_elev_viz').resize();
              });
               
               
```

I think that attempts to run the `resize` method might be thwarted by echarts applying a fixed height/width setting on the nested `div` and `canvas` used to render the plot:

![image](https://user-images.githubusercontent.com/32208821/135147039-b1e531eb-8a8c-48e1-b11b-ee5c42365830.png)

**Comment by JohnCoene** [comment]
Argh, same problem again, the parent doesn't resize.

This works on my machine.

```r
library(shiny)
library(echarts4r)

ui <- bs4Dash::dashboardPage(
  header = bs4Dash::dashboardHeader(disable = TRUE),
  body = bs4Dash::dashboardBody(
    tags$script(
      "$(function(){
        $('#maxCard').find('[data-card-widget=\"maximize\"]').on('click', function() {
          // it may take some time for the resizing of the card to happen
          setTimeout(function(){
            let $el = $('#maxCard');
            let w = $el.width();
            let h = $el.height();
            console.log(w);
            $('#chart').parent().css({
              width: w + 'px',
              height: h + 'px'
            })
            get_e_charts('chart').resize({width: w, height: h});
          }, 250);
        });
      });"
    ),
    shiny::fluidRow(
      bs4Dash::bs4Card(plotly::plotlyOutput("plot"), width = 4, maximizable = TRUE),
      bs4Dash::bs4Card(echarts4r::echarts4rOutput("chart"), width = 4, maximizable = TRUE, id = "maxCard"),
      bs4Dash::bs4Card(width = 4)
    )
  ),
  sidebar = bs4Dash::bs4DashSidebar(disable = TRUE)
)

# Define server logic required to draw a histogram
server <- function(input, output) {

  # generate bins based on input$bins from ui.R
  p <- iris |> 
    dplyr::group_by(Species) |>
    echarts4r::e_charts(x = Petal.Width) |>
    echarts4r::e_line(Petal.Length, symbol = "none") |>
    echarts4r::e_y_axis(scale = TRUE) |>
    echarts4r::e_band2(lower = Sepal.Length, upper = Sepal.Width, itemStyle = list(opacity = 0.4)) |>
    echarts4r::e_tooltip(trigger = "axis") |>
    echarts4r::e_datazoom() |>
    echarts4r::e_toolbox(orient = "vertical", itemSize = 10) |>
    echarts4r::e_toolbox_feature(feature = c("saveAsImage" ,"dataZoom", "restore"))
  # setting outputs
  output$chart <- echarts4r::renderEcharts4r(p)

  output$plot <- plotly::renderPlotly({
    plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
  })
    
}

# Run the application 
shinyApp(ui = ui, server = server)
```

**Comment by JohnCoene** [comment]
@DivadNojnarg on my machine the `.card-body` does not take the full screen hence @yogat3ch the graph does not either.

**Comment by yogat3ch** [comment]
Ah interesting @JohnCoene, so it sounds like the `.card-body` needs to inherit it's width/height from the parent `card` element - will the `echarts` nested within automatically adjust to the `.card-body` if it does? Or does it need to have `resize` method called on one of the output `div`s or `canvas`s from `echarts`?

**Comment by helgasoft** [comment]
@yogat3ch, is this the horizontal resizing/maximizing you are looking for ?  Or maybe you need vertical also ?
```r
library(shiny);  library(magrittr);  library(bs4Dash);  library(echarts4r)

ui <- dashboardPage(
	header = dashboardHeader(disable = TRUE),
	body = dashboardBody(
		tags$script(
		  "$(function(){
                      $('#card1').find('[data-card-widget=\"maximize\"]').on('click', function() {
                         $('#plot').resize();  });
                      $('#card2').find('[data-card-widget=\"maximize\"]').on('click', function() {
                         $('#chart').resize();  });
                  });"
		),
		shiny::fluidRow(
			bs4Card(id = "card1", plotly::plotlyOutput("plot"), width = 4, maximizable = TRUE),
			bs4Card(id = "card2", echarts4rOutput("chart"), width = 4, maximizable = TRUE),
			bs4Card(width = 4)
		)
	)
	,sidebar = bs4DashSidebar(disable = TRUE)
)

server <- function(input, output) {
	p <- iris %>%
		dplyr::group_by(Species) %>%
		e_charts(x = Petal.Width) %>%
		e_line(Petal.Length, symbol = "none") %>%
		e_y_axis(scale = TRUE) %>%
		e_band2(lower = Sepal.Length, upper = Sepal.Width, itemStyle = list(opacity = 0.4)) %>%
		e_tooltip(trigger = "axis") %>%
		e_datazoom() %>%
		e_toolbox(orient = "vertical", itemSize = 10) %>%
		e_toolbox_feature(feature = c("saveAsImage" ,"dataZoom", "restore"))
	# setting outputs
	output$chart <- renderEcharts4r(p)

	output$plot <- plotly::renderPlotly({
		plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
	})
}

shinyApp(ui = ui, server = server)
```

**Comment by yogat3ch** [comment]
Hi @helgasoft,
Almost! 
We have >24 charts embedded in `bs4Card`s, so ideally we're looking for Javascript that can be appended to each `bs4card` in order to easily paste it's `id` into the JS as the example above demonstrates. 

Either that or a top-level script for the `dashboardBody` as you have here that could map over every `div` with class `.card` and identify all `id`s nested within and trigger a `resize` whenever the card is maximized.

I'm thinking something along what is scrapped together below. This is untested & my JS is poor, if you see errors please provide suggestions! I'll test this out with suggested modifications tomorrow
```
function resizeBoxContent(trigger, target) {
              var target = '#' + target;
              $(trigger).on('click', function() {
                setTimeout(function() {
                  var isMaximized = $('html').hasClass('maximized-card');
                    if (isMaximized) {
                      $(target).css('height', '100%');
                      $(target).css('width', 'auto');
                    } else {
                      $(target).css('height', '400px');
                      $(target).css('width', 'auto');
                    }
                  console.log('resizing '+ target);
                }, 300);
                $(target).trigger('resize');
              });
            }
            
var card_ids = $('.card').map(function(){
      return $(this).attr('id');
      });
card_ids.map(function(id) {
   var ids = $('div' + id + ' div.card-body div').map(function() { return $(this).attr('id'); });

   ids.map(function(plot_id){ resizeBoxContent('div' + id + ' button[data-card-widget=\"maximize\"]', plot_id) });

});

```

**Comment by helgasoft** [comment]
here you go
```r
library(shiny);  library(magrittr);  library(bs4Dash);  library(echarts4r)

ui <- dashboardPage(
	header = dashboardHeader(disable = TRUE),
	body = dashboardBody(
		tags$script(
		"$('.card').map(function(){ 
		    let tmp = $(this).attr('id');
		    if (tmp) {
		       let chrt = $('#'+tmp+' div.card-body div').attr('id');
		       $('#'+tmp).find('[data-card-widget=\"maximize\"]').on('click', 
					function() { $('#'+chrt).resize(); } ); 
                    }
		});"
		),
		shiny::fluidRow(
			bs4Card(id = "card1", plotly::plotlyOutput("plot"), width = 4, maximizable = TRUE),
			bs4Card(id = "card2", echarts4rOutput("chart"), width = 4, maximizable = TRUE),
			bs4Card(width = 4)
		)
	)
	,sidebar = bs4DashSidebar(disable = TRUE)
)

server <- function(input, output) {

	p <- iris %>% dplyr::group_by(Species) %>%
		e_charts(x = Petal.Width) %>%
		e_line(Petal.Length, symbol = "none") %>%
		e_y_axis(scale = TRUE)

	output$chart <- renderEcharts4r(p)
	output$plot <- plotly::renderPlotly({
		plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
	})
}

shinyApp(ui = ui, server = server)
```

**Comment by yogat3ch** [comment]
Thank you for this updated script @helgasoft !

Unfortunately, it looks like it isn't actually running when the card is maximized. I add `console.log` statements throughout as indicated below:
```
"$('.card').map(function(){ 
		    let tmp = $(this).attr('id');
		    console.log('tmp=' + tmp)
		    if (tmp) {
		       let chrt = $('#'+tmp+' div.card-body div').attr('id');
		    console.log('chrt=' + chrt)
		       $('#'+tmp).find('[data-card-widget=\"maximize\"]').on('click', 
					function() { 
					console.log('#'+chrt)
					$('#'+chrt).resize(); } ); 
                    }
		});"
```
and nothing is logged to the console :-/ 
I think that script might be running randomly as soon as `dashboardBody` loads because it doesn't appear to have code that actually associated it with the click of the `maximize` button, but I might be misunderstanding the JS.
I modified it as follows:
```
"$(document).ready(function() {
        $('.card').map(function(){ 
		    let tmp = $(this).attr('id');
		    console.log('tmp=' + tmp)
		    if (tmp) {
		       let chrt = $('#'+tmp+' div.card-body div').attr('id');
		    console.log('chrt=' + chrt)
		       $('#'+tmp).find('[data-card-widget=\"maximize\"]').on('click', 
					function() { 
					console.log('#'+chrt)
					$('#'+chrt).resize(); } ); 
                    }
		});
        })
        "
```
And the following two console messages appeared when the app loaded - but no further messages when the cards were maximized.
```
tmp=box_scenario_chooser
chrt=undefined
```

On another note, as soon as I open browser devtools, it shifts to fullsize, as does moving/resizing the browser window. I am assuming this is because the browser runs a resize on everything when those actions are performed. 

Even if that top level div was resized, would the fixed width/height values in the nested `div` ([2] in SS) and the nested `canvas` ([3] in SS) actually adapt accordingly?
In the SS I added `100%` manually to [2], and when I added the same to the width of the canvas [3] the chart disappears entirely - as demoed in the reprex.

I think the distilled approach to solving this issue, if possible given the echarts library, would be to allow CSS width/height settings of "100%" or "auto" on all of the echarts related DOM elements. It should then adjust to whatever container it's in, right?

![image](https://user-images.githubusercontent.com/32208821/135340392-54abf719-2084-42bd-8a6b-e9704b35d248.png)

**Comment by JohnCoene** [comment]
I don't think there is any resize event on the wrapper for an htmlwidget. Have you tried the snippet I shared? I can adapt to work on any card.

**Comment by yogat3ch** [comment]
This one @JohnCoene ?
```
tags$script(
      "$(function(){
        $('#maxCard').find('[data-card-widget=\"maximize\"]').on('click', function() {
          // it may take some time for the resizing of the card to happen
          setTimeout(function(){
            let $el = $('#maxCard');
            let w = $el.width();
            let h = $el.height();
            console.log(w);
            $('#chart').parent().css({
              width: w + 'px',
              height: h + 'px'
            })
            get_e_charts('chart').resize({width: w, height: h});
          }, 250);
        });
      });"
    )
```
I'll see if I can adapt @helgasoft 's JS with this functionality to make it work for all of the cards on the app as we will have ~24

**Comment by JohnCoene** [comment]
It's late where I am and I'm not behind a laptop yet but I will adapt it, it's fairly easy.

Look for the `echarts4r` class within card with jQuery `find` the loop and it should do the trick

**Comment by yogat3ch** [comment]
Ok, will do! Thanks for the pointer

**Comment by helgasoft** [comment]
@yogat3ch,
_"full width seems to work when I maximize a card on a floating Rstudio browser window"_ - yes, I tested it only in RStudio.
RStudio has its own (older) browser, not identical to latest Chrome. The update below works in latest Chrome and Firefox.
```r
library(shiny);  library(magrittr);  library(bs4Dash);  library(echarts4r)

ui <- dashboardPage(
	header = dashboardHeader(disable = TRUE),
	sidebar = bs4DashSidebar(disable = TRUE),
	body = dashboardBody(
		fluidRow(
			bs4Card(id = "card1", plotly::plotlyOutput("plot"), width = 4, maximizable = TRUE),
			bs4Card(id = "card2", echarts4rOutput("chart"), width = 4, maximizable = TRUE),
			bs4Card(width = 4)
			,tags$script(
				"function setResize(ev) { 
					$('.card').map(function(){ 
		   			let tmp = $(this).attr('id');
		   		if (tmp) {
		      		let chrt = $('#'+tmp+' div.card-body div').attr('id');
				       $('#'+tmp).find('[data-card-widget=\"maximize\"]').on('click', 
							function() { $('#'+chrt).resize(); } ); 
            		        }
					}); 
				}
				window.onload = setResize(event);"
			)
		)
	)
)

server <- function(input, output) {
	
	p <- iris %>% dplyr::group_by(Species) %>%
		e_charts(x = Petal.Width) %>%
		e_line(Petal.Length, symbol = "none") %>%
		e_y_axis(scale = TRUE)
	
	output$chart <- renderEcharts4r(p)
	output$plot <- plotly::renderPlotly({
		plotly::plot_ly(data = iris, x = ~Sepal.Length, y = ~Petal.Length)
	})
}

shinyApp(ui = ui, server = server)
```

**Comment by yogat3ch** [comment]
Hey @helgasoft ,
I tried out this reprex and it does indeed seem to be functioning. 
When I plug it into the main app, whether at the `dashboardBody` level, or the `fluidRow` level, it doesn't work.

One difference that I'm noticing is this error in the console when I run our main app:

![image](https://user-images.githubusercontent.com/32208821/135364073-d94dfd4e-61f9-4e4d-9fd2-0327560c8d4d.png)

It looks like something is going wrong with `jquery` which could be interfering with the functioning of this script since it's reliant on `jquery`. 
I'm guess it's related to a `jquery` dependency being appended by some widget we're using that is either out of date, or has an error in it. 
I think these two files are bundled with `shiny` so I'm going to first try updating `shiny`. If you have any other ideas as to what might be preventing the script that working, please do share. Or if you think it is related to this error and you know how to resolve it, I'm open to ideas.

**Comment by yogat3ch** [comment]
Actually, that can't be a `shiny` issue because the reprex is using the same version of `shiny. So I'm not sure where this is coming from.

**Comment by helgasoft** [comment]
message says it quite clearly - "_**missing ) after argument list**_" - it's a syntax error in your code.

**Comment by yogat3ch** [comment]
Hmm, I haven't added any JS to this app except this snippet. I did alter the JS in `bs4Dash` but I don't encounter the error when `bs4Dash` loads in the reprex. I'll take a look at Keaton's code since some of the echarts use JS and see if I can find where this is happening.

**Comment by keatonwilson** [comment]
If there is a syntax error in any of the custom JS code, I'm likely the culprit. :) @yogat3ch Commenting out the ribbon tooltip formatter and x-axis formatter is probably the quickest way to quickly see if that's the issue. I'll try and take a look tomorrow too.

**Comment by yogat3ch** [comment]
Good news: I found the issue - it was a `console.log` statement I added to see if the script was triggering.
Bad news: Fixing that error didn't make the script work :-/

It's loaded here at the bottom of the `fluidRow`, but fullsizing the card doesn't affect the graph
![image](https://user-images.githubusercontent.com/32208821/135370333-55febb5c-4eab-41af-afd9-8cadd71ee28f.png)

**Comment by yogat3ch** [comment]
Moving it from the `fluidRow` to the `dashboardBody` makes it run once, but with the same results as before:
![image](https://user-images.githubusercontent.com/32208821/135371065-5986de0e-5d67-42ee-98c9-74a7295c3d90.png)

**Comment by yogat3ch** [comment]
The `box_scenario_chooser` is the only card loaded on app load - the graphs that need maximization are displayed on a view with an associated module. 
I'll try moving it to the top level `tagList` in the associated module and see what happens.

**Comment by yogat3ch** [comment]
I tried adding it to the top-level `tagList` in that module and the `fluidPage` in the rendering function to no avail. 
My guess is that tethering the action to the `$(window).on('load'` trigger isn't suited for content rendering in a tab. I assume the browser considers the tabs loading to be after the window has loaded judging by the fact that the only time it ran was when nested under `dashboardBody` in the body UI module. 

>I think the distilled approach to solving this issue, if possible given the echarts library, would be to allow CSS width/height settings of "100%" or "auto" on all of the echarts related DOM elements. It should then adjust to whatever container it's in, right?

Circling back around to this - is this feasible? If it is, it seems like this is the only way to solve this in a robust enough manner to account for all the various scenarios an echart might be nested in?

**Comment by JohnCoene** [comment]
@yogat3ch @keatonwilson this works on my machine, it does not use any fancy ES6 and so should work on all browsers.

```r
library(shiny)
library(echarts4r)

ui <- bs4Dash::dashboardPage(
  header = bs4Dash::dashboardHeader(disable = TRUE),
  body = bs4Dash::dashboardBody(
    tags$script(
      "$(function(){
        $('.card')
        .find('[data-card-widget=\"maximize\"]')
        .on('click', function(e) {
          // it may take some time for the resizing of the card to happen
          setTimeout(function(){
            let chart = $(e.target)
              .closest('.card')
              .find('.echarts4r')
              .first();

            if(!chart)
              return;

            let id = chart.attr('id')

            let $parent = $(chart).parent(); 
            let w = $parent.width();
            let h = $parent.height();
            console.log(h);
            $('#chart').parent().css({
              width: w + 'px',
              height: h + 'px'
            })
            get_e_charts(id).resize({width: w, height: h});
          }, 250);
        });
      });"
    ),
    shiny::fluidRow(
      bs4Dash::bs4Card(echarts4r::echarts4rOutput("chart1"), width = 4, maximizable = TRUE),
      bs4Dash::bs4Card(echarts4r::echarts4rOutput("chart2"), width = 4, maximizable = TRUE),
      bs4Dash::bs4Card(width = 4)
    )
  ),
  sidebar = bs4Dash::bs4DashSidebar(disable = TRUE)
)

# Define server logic required to draw a histogram
server <- function(input, output) {

  # generate bins based on input$bins from ui.R
  p <- iris |> 
    dplyr::group_by(Species) |>
    echarts4r::e_charts(x = Petal.Width) |>
    echarts4r::e_line(Petal.Length, symbol = "none") |>
    echarts4r::e_y_axis(scale = TRUE) |>
    echarts4r::e_band2(lower = Sepal.Length, upper = Sepal.Width, itemStyle = list(opacity = 0.4)) |>
    echarts4r::e_tooltip(trigger = "axis") |>
    echarts4r::e_datazoom() |>
    echarts4r::e_toolbox(orient = "vertical", itemSize = 10) |>
    echarts4r::e_toolbox_feature(feature = c("saveAsImage" ,"dataZoom", "restore")) |> 
    echarts4r::e_dims()
  # setting outputs
  output$chart1 <- echarts4r::renderEcharts4r(p)

  output$chart2 <- echarts4r::renderEcharts4r(p)
}

# Run the application 
shinyApp(ui = ui, server = server)
```

What may be happening is that you are attaching event observers on card that are not present in the DOM yet (e.g.: in other tabs or modules not called/rendered yet).

Does this example work for you?
What is the structure of your app?

**Comment by yogat3ch** [comment]
Hi @JohnCoene ,
> Does this example work for you?
No.
> What is the structure of your app?
The app uses `bs4Dash` & `golem`. It has a body module with a single output `bodyui`. The server for this module uses the selected tab name to call the appropriate tab module with `rlang::exec`
![image](https://user-images.githubusercontent.com/32208821/135460917-321c9272-92ab-4c8e-93c9-add39210f161.png)

The tab modules have `fluidPage`s with rows of info & visualization specific to the tab. Each element on this page is wrapped in a `bs4Card`. All `bs4Card`s for visualizations have `maximizable = TRUE`. 



>I think the distilled approach to solving this issue, if possible given the echarts library, would be to allow CSS width/height settings of "100%" or "auto" on all of the echarts related DOM elements. It should then adjust to whatever container it's in, right?

>In the echarts docs under opts it indicates the following:
> - `width` Specify width explicitly, in pixel. If setting to null/undefined/'auto', width of dom (instance container) will be used.
> - `height` Specify height explicitly, in pixel. If setting to null/undefined/'auto', height of dom (instance container) will be used.

![image](https://user-images.githubusercontent.com/32208821/135461918-d8d4aed1-d6a1-4948-bda1-04fe05e12a3f.png)

>This is because the height and width that are passed to e_charts is not used in the JavaScript API and is instead used for the parent container.

The documentation for echarts seems to suggest that both the parent div and the canvas element have an `init` method that accepts `width`/`height`. If the docs are inaccurate and the ability to supply `width`/`height` to both of these `DOM` elements is not working, that seems like it merits a bug report to Apache?

**Comment by JohnCoene** [comment]
The example I shared above should really work. 

Reinstall the Github version of echarts4r to access `e_dims` (which exposes the part of the API you mention) and run the example code I shared. At this point this should simply work. If it does not, could you share any error or warning you observe in the console?

![maximise](https://user-images.githubusercontent.com/7833796/135464295-6702f805-4742-4d7f-82bc-0121d05a6ea1.gif)

What matters here is that, in your application, you create the observers on the "+" buttons AFTER said cards have rendered; if they run before than the observers cannot be bound since the elements are not yet in the DOM.

Like I said before these `width` and `height` arguments come from htmlwidgets, not echarts4r. htmlwidgets wraps every visualisation in a parent `<div>` by default. Then, echarts4r automatically resizes when that parent element resizes. Hence, to resize the chart, first resize the parent. `e_charts(data, x, widht = "auto")` produces a `<div style='width:auto;'></div>`, that's not what we want here.

**Comment by yogat3ch** [comment]
I'm installing the Github version. The resize script is currently nested inside the `dashboardBody` element on the body module in which `renderUI` is called - it sounds like the fact that it's loading before that `renderUI` runs and the cards show up is the reason it's not working. I'll try moving that script to one of the `fluidRows` that the cards are loaded into which happens inside the tab module called by the body module. Maybe that will fix the issue you're referring to?

**Comment by yogat3ch** [comment]
🎉 success with the `e_dims` method!
Moving the script to the tab module `fluidPage` call did not work but adding the `e_dims` method to the first chart seems to have worked!

![image](https://user-images.githubusercontent.com/32208821/135471596-934fe149-34f3-4bca-9740-75b458446c23.png)

I'll apply `e_dims` to all the visualizations and report back!

**Comment by yogat3ch** [comment]
I take back what I said earlier - it looks like its a combination of the script - deployed in the appropriate place and , and the `e_dims` method, and using default settings on the output widget. 
Here's the solution as far as I can tell:
1. The script that @JohnCoene provided has to be deployed on an element that loads simultaneous to the cards containing the visualization.  Thanks for guiding us through this bit!
```
tags$script(
      "$(function(){
        $('.card')
        .find('[data-card-widget=\"maximize\"]')
        .on('click', function(e) {
          // it may take some time for the resizing of the card to happen
          setTimeout(function(){
            let chart = $(e.target)
              .closest('.card')
              .find('.echarts4r')
              .first();

            if(!chart)
              return;

            let id = chart.attr('id')

            let $parent = $(chart).parent(); 
            let w = $parent.width();
            let h = $parent.height();
            console.log(h);
            $('#chart').parent().css({
              width: w + 'px',
              height: h + 'px'
            })
            get_e_charts(id).resize({width: w, height: h});
          }, 250);
        });
      });"
    )
```
_Note that the timeout duration cannot be reduced._

2. The script above will resize the charts ~50% of the time when minimizing/maximizing, if `e_dims` is used as well as the script, resizing works ~90% of the time. This could be related to timeout duration and how quickly the card is maximized/minimized, rather than `e_dims`, it's hard to say.

3. The `height` parameter of the `echarts4rOutput` must have a fixed height because the `bs4Card` seems to use it's content to determine it's height which will cause the height of the echart to get set to `0` causing the "invisible" chart issue first reported. With the script, the chart will appear when the card is resized, but then retain it's height but not it's width when the card is minimized resulting in a very distorted graph. When the `echarts4rOutput` has a fixed height & the script is deployed on a synchronous element, the height changes appropriately on resize.

I'm not sure if it's possible to deploy this script as a part of the `e_chart` function to look for a `card` or `modal` ancestor and perform the resize such that `echarts` become compatible with the Bootstrap library and the maximize features but it seems like that would solve this one for good.

Much appreciation for @JohnCoene, @helgasoft & @DivadNojnarg for your patience and expertise in solving this! 

@keatonwilson

**Comment by yogat3ch** [comment]
An update on this, shortly after making the changes for all our plots I realized that a card with multiple plots was only resizing the first plot, if at all.
![sometimes-resize1](https://user-images.githubusercontent.com/32208821/135494211-ac16a28b-bb62-4cb9-8324-0aa6ebd020a8.gif)

I manage to get this modification of @JohnCoene's script working for cards with multiple echarts embedded and it appears to be working:

```
$(function(){
        $('.card')
        .find('[data-card-widget=\"maximize\"]')
        .on('click', function(e) {
          // it may take some time for the resizing of the card to happen
          setTimeout(function(){
            let charts = $(e.target)
              .closest('.card')
              .find('.echarts4r')
            charts.each(function(index){
              let chart = charts[index];

              if(!chart)
                return;
  
              let id = $(chart).attr('id');
              
  
              let $parent = $(chart).parent(); 
              let w = $parent.width();
              let h = $parent.height();
              console.log(id);
              console.log(h);
              $('#chart').parent().css({
                width: w + 'px',
                height: h + 'px'
              })
              get_e_charts(id).resize({width: w, height: h});
            })  

            
            
          }, 250);
        });
      });
```

**Comment by JohnCoene** [comment]
Great news! Very glad it's now working!
