### ISSUE TITLE
`coordRange` does not work in `e_dispatch_action_p`

### ISSUE THREAD

**Issue by ajmoralesa** [JohnCoene/echarts4r#378]
I am using `e_dispatch_action_p` to programatically brush plot areas. It works well when using `range` but not when using `coordRange`. From the official [echarts documentation][2]: "If `brushType` is `"lineX"` or  `'lineY'`: `range` and `coordRange` is: `[min, maxX]`"

As an example, this works using `range`:

    library(shiny)
    library(echarts4r)
    
    
    ui <- fluidPage(
      fluidRow(
        column(8, echarts4rOutput("chart")),
        column(4, actionButton("zoom", "Zoom"))
      )
    )
    
    server <- function(input, output, session) {
      output$chart <- renderEcharts4r({
        cars %>% 
          e_charts(speed) %>% 
          e_scatter(dist) %>% 
          e_brush()
      })
      
      observe({
        req(input$zoom)
        echarts4rProxy("chart") %>%
            e_dispatch_action_p(
            "brush",
            areas = list(
              list(
                brushType = 'lineX',
                range = list(50, 150),
                xAxisIndex = 0
              )
            )
          )
      })
    }
    
    shinyApp(ui, server)

[![enter image description here][3]][3]

But the brushed area does not renders when trying to use `coordRange`:

    library(shiny)
    library(echarts4r)
    
    
    ui <- fluidPage(
      fluidRow(
        column(8, echarts4rOutput("chart")),
        column(4, actionButton("zoom", "Zoom"))
      )
    )
    
    server <- function(input, output, session) {
      output$chart <- renderEcharts4r({
        cars %>% 
          e_charts(speed) %>% 
          e_scatter(dist) %>% 
          e_brush()
      })
      
      observe({
        req(input$zoom)
        echarts4rProxy("chart") %>%
            e_dispatch_action_p(
            "brush",
            areas = list(
              list(
                brushType = 'lineX',
                coordRange = list(5, 15),
                xAxisIndex = 0
              )
            )
          )
      })
    }
    
    shinyApp(ui, server)

Am I doing something wrong? 

  [2]: https://echarts.apache.org/en/api.html#action.brush
  [3]: https://i.stack.imgur.com/rMV4a.png

**Comment by JohnCoene** [comment]
Yes, that's normal.

The documentation reads:

```js
// Only for "coordinate system area", define the area with the
            // coordinates.
            coordRange:[]
```

You are trying to use this function [here](https://echarts.apache.org/en/api.html#action.brush.brush)

Hope this helps!

**Comment by ajmoralesa** [comment]
Thank you for your answer. [In documentation](https://echarts.apache.org/en/api.html#action.brush.brush), I read : _If the area is "coordinate system area" (i.e., geoIndex or xAxisIndex or yAxisIndex is specified), we should use coordRange_ In my example, `brushType = 'lineX',` is indicated.

Apologies but I still do not see how I can adapt the code within `e_dispatch_action_p` to brush on specific cartesian coordinates (and not pixels)?

Many thanks in advance if any help can be provided on this.
