### ISSUE TITLE
Is there a way to put a border around the chart area?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#379]
I can put a border around the chart itself, using `e_grid()` like this:

```r
df <- state.x77 %>%
  as.data.frame() %>%
  tibble::rownames_to_column("State")

df %>%
  e_charts(x = State) %>%# initialise and set x
  e_line(serie = Population) %>%
  e_grid(show = T)
```

Now I am wondering if there is a way to put a border around the chart area as a whole? So  I would like to make a bordered rectange that includes things like the title ande axis labels as well. 

Is this possible? I couldn't find anything in the documentation.

Many thanks in advance!

**Comment by JohnCoene** [comment]
I don't think you would use echarts.js for that.

```r
df %>%
  e_charts(x = State, elementId = "MYPLOT") %>%# initialise and set x
  e_line(serie = Population) %>%
  e_grid(show = T) %>% 
  htmlwidgets::prependContent(
    htmltools::tags$style(
      "#MYPLOT{
        border: 2px solid black;
        margin: 50px;
      }"
    )
  )
```

Note that I use `margin` simply because it runs locally and will display full screen (cannot see the border).
If you want to apply this to all charts you can replace the `#MYPLOT` with `.echarts4r`

**Comment by rdatasculptor** [comment]
thank you for your quick answer! And it is a perfect answer to my question. It works nicely.

I use echarts4r a lot within `combineWidgets()` and present it using flexdashboard. When I do that in combination with your solution nothing seems to happen. Is there a something I can do to make it work there as well?

**Comment by rdatasculptor** [comment]
great solution! thanks! :)

I doesn't seem te work in combination with flexdashaboard and withing `combineWidgets()` though. Any additional ideas about solving that problem...?

**Comment by JohnCoene** [comment]
The `prependContent` is not going to work in shiny I believe, you need to place that CSS elsewhere, in an CSS file, within `tags$head()`, etc.

**Comment by rdatasculptor** [comment]
Thanks, I will manage.

**Comment by rdatasculptor** [comment]
ah yesssss, for adding this to my .rmd filde did the trick:

```
```{css my-content, echo = FALSE}
#MYPLOT {
        border: 2px solid black;
        margin: 2px;
      }
```
```
