### ISSUE TITLE
Combine two plots from different data.frames

### ISSUE THREAD

**Issue by nvelden** [JohnCoene/echarts4r#385]
With `ggplot` you can combine plots from two different data.frames like below:

```
ggplot() + 
geom_line(data=Data1, aes(x=A, y=B), color='green') + 
geom_line(data=Data2, aes(x=C, y=D), color='red') 
```

How would you do this with `e_charts`?

**Comment by JohnCoene** [comment]
With `e_data`, examples online
https://echarts4r.john-coene.com/reference/init.html

**Comment by nvelden** [comment]
Awesome! Thanks a lot. I missed it in the documentation

So this should work

```
e_plot <-
  df1 %>%
  e_charts(x1) %>%
  e_line(y1) %>%
  e_data(df2, x2) %>%
  e_line(y2)
```

**Comment by JohnCoene** [comment]
Yes indeed, let me know if it does not

**Comment by nvelden** [comment]
It works and thanks a lot for this awesome package!
