### ISSUE TITLE
Jitter on categorical variables? 

### ISSUE THREAD

**Issue by christophsax** [JohnCoene/echarts4r#387]
I would like to use 'jitter' to avoid overlapp of dots in a scatter plot. I see [from the documentation](https://echarts4r.john-coene.com/articles/advanced.html#jitter) that this works nicely on numerical data. However, for categorical variables (factors), it seems not to work:

```r
library(echarts4r)
iris |> 
  e_charts(Species) |>
  e_scatter(
    Petal.Length,
    symbol_size = 20,
    jitter_factor = 0.2
  ) 
```

As mentioned, it works if I make Species numerical, but then I loose the x-axis labels:

```r
iris |> 
  mutate(Species = as.integer(Species)) |> 
  e_charts(Species) |>
  e_scatter(
    Petal.Length,
    symbol_size = 20,
    jitter_factor = 0.2
  ) 
```

What I am looking for is something like this:

```r
library(ggplot2)
iris |> 
  ggplot(aes(x = Species, y = Petal.Length)) + 
  geom_jitter(width = 0.1)
```

![](https://i.imgur.com/vWjutcf.png)

<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Is it a limmitation or am I using it incorrectly?

**Comment by JohnCoene** [comment]
Identical to #388
