### ISSUE TITLE
No areaStyle in e_area?

### ISSUE THREAD

**Issue by berkorbay** [JohnCoene/echarts4r#391]
Hi,

I want to adjust the area opacity in area chart but only `itemStyle` is accepted. `itemStyle` affect area color but not the opacity. `areaStyle` seems to be ineffective. Am I doing something wrong here?

```r
library(dplyr)
library(lubridate)
library(echarts4r)
set.seed(421)
df1 <- tibble(date = as_date("2021-11-01") + months(0:11),x=12*10^6 + rnorm(12,0,2000000),y=12*10^6 + rnorm(12,0,1000000))
df1 %>% e_charts(date) %>% 
    e_area(x,itemStyle=list(color="#ccc")) %>%
    e_area(y,areaStyle=list(opacity=0.1,color="#fff")) 
```

**Comment by JohnCoene** [comment]
Sorry for the much belated response to this. It's probably too late (work + moving + other issues kept me away from open source projects).

```r
library(dplyr)
library(lubridate)
library(echarts4r)

set.seed(421)

df1 <- tibble(
  date = as_date("2021-11-01") + months(0:11),
  x = 12*10^6 + rnorm(12,0,2000000),
  y = 12*10^6 + rnorm(12,0,1000000)
)

df1 |> 
  e_charts(date) |>
  e_line(x,itemStyle=list(color="#ccc"), areaStyle = list()) |> 
  e_line(y,areaStyle=list(opacity=0.1,color="#fff")) 
```

`e_area` is just a convenience wrapper around `e_line` you can access everything from it.

**Comment by berkorbay** [comment]
Just maintaining a project like this is amazing work. 

I think I got it, thank you! I also realized that my example was not illustrious enough so I am leaving an updated version combined with your answer.

```r
library(dplyr)
library(lubridate)
library(echarts4r)

set.seed(421)

df1 <- tibble(
  date = as_date("2021-11-01") + months(0:11),
  x = 12*10^6 + rnorm(12,0,2000000),
  y = 12*10^6 + rnorm(12,0,1000000)
)

df1 |> 
    e_charts(date) |>
    e_line(x,itemStyle=list(color="#f00"), areaStyle = list(opacity=0.5)) |> 
    e_line(y,areaStyle=list(opacity=0.7)) 
```
<img width="1376" alt="Screen Shot 2021-12-28 at 09 04 49" src="https://user-images.githubusercontent.com/5690139/147533568-83f1e600-d7f5-4956-8d10-bd7f5cdeea67.png">
