### ISSUE TITLE
Add grid lines at axis with categories

### ISSUE THREAD

**Issue by svenb78** [JohnCoene/echarts4r#393]
Hi, 

I would like to know how to add grid lines (?) at axis tick marks. The only way I figured out so far is using e_mark_line as follows: 

tmp <- data.frame(
  Variable = LETTERS[1:5]
  , Value = rnorm(5)
)

e2 <- tmp %>%
  e_charts(x = Variable) %>%
  e_line(serie = Value) %>%
  e_grid(show = TRUE) %>%
  e_mark_line(data = list(yAxis = 0, lineStyle = list(color = "#DADCDD")), symbol = "none", label = list(show = FALSE)) %>%
  e_mark_line(data = list(yAxis = 1, lineStyle = list(color = "#DADCDD")), symbol = "none", label = list(show = FALSE)) %>%
  e_mark_line(data = list(yAxis = 2, lineStyle = list(color = "#DADCDD")), symbol = "none", label = list(show = FALSE)) %>%
  e_mark_line(data = list(yAxis = 3, lineStyle = list(color = "#DADCDD")), symbol = "none", label = list(show = FALSE)) %>%
  e_mark_line(data = list(yAxis = 4, lineStyle = list(color = "#DADCDD")), symbol = "none", label = list(show = FALSE)) %>%
  e_x_axis(type = "category", axisTick = list(show = TRUE, alignWithLabel = TRUE)) %>%
  e_flip_coords

e2

But I hope, there is an easier way to do so ... 

Thanks for help!

**Comment by JohnCoene** [comment]
It's not intuitive, sorry.

```r
cars |> 
  e_chart(speed) |> 
  e_scatter(dist) |> 
  e_x_axis(splitLine = list(show = TRUE, lineStyle = list(color = "red"))) |> 
  e_y_axis(splitLine = list(show = TRUE, lineStyle = list(color = "blue")))
```

All docs [here](https://echarts.apache.org/en/option.html#xAxis.axisLine)
