### ISSUE TITLE
Clicking on blank area?

### ISSUE THREAD

**Issue by astro-nomad** [JohnCoene/echarts4r#394]
Is there a way to return the data points when the user click on an empty area of an echart proxy?

In shiny we can retrieve click event data like `elementId + _clicked_data` for an echarts proxy. However when the user clicks on the empty area of the chart, nothing is returned. In the echarts documentations there's a part that address this: https://apache.github.io/echarts-handbook/en/concepts/event/ (at the very end). But im not sure if there's an R function that captures this.

A shiny example:

```
library(shiny)
library(echarts4r)

ui <- fluidPage(
        mainPanel(
            echarts4rOutput('chart1')
            , verbatimTextOutput('selected_point')
        )
    )
)

server <- function(input, output) {

    output$chart1 <- renderEcharts4r({

        head(mtcars) |> 
            e_charts(x = wt) |> 
            e_area(mpg) |> 
            e_tooltip(trigger = 'axis')

    })
    
    output$selected_point <- renderPrint({
        print(input$chart1_clicked_data)
    })
    
    chart1proxy <- echarts4rProxy('chart1')
    
    observeEvent(input$chart1_clicked_data, {
        print(paste0('chart1_clicked_data: ', input$chart1_clicked_data))
    })
}

shinyApp(ui = ui, server = server)


```

**Comment by astro-nomad** [comment]
Updated the issue. Clicking on the same data point works after I updated the package version. However clicking on the background or empty area still does not return anything.

**Comment by astro-nomad** [comment]
@JohnCoene  could this be possible by adding something like?
```
chart.getZr().on("click", function(e){
  Shiny.onInputChange(el.id + '_clicked_data' + ":echarts4rParse", e.data);
  ...
});
```

**Comment by JohnCoene** [comment]
You can use `input$plot_global_out`, it's here https://github.com/JohnCoene/echarts4r/blob/00042178b30e5bd1a283a206b77d65b8b6c17992/inst/htmlwidgets/echarts4r.js#L83

**Comment by troyjcross** [comment]
> @JohnCoene could this be possible by adding something like?
> 
> ```
> chart.getZr().on("click", function(e){
>   Shiny.onInputChange(el.id + '_clicked_data' + ":echarts4rParse", e.data);
>   ...
> });
> ```

I would love to see this functionality implemented too :-) I'm currently working on a project where I'd like to return raw XY values (or pixels) when a user clicks on the blank canvas area. Is there any simple way of exposing the `.getZr()` method a la: https://apache.github.io/echarts-handbook/en/concepts/event/#listen-to-events-on-the-blank-area ?

**Comment by JohnCoene** [comment]
Sorry, work is very busy, plus I moved this week so had little time.

You should now be able to capture this with `input$plotId_clicked_zr`.

Requires reinstalling the dev version.

Feel free to reopen if there are issues.

**Comment by JohnCoene** [comment]
Apologies, but I've had to push a breaking to this.

It so happens that observing for clicks on `getZr()` can break other such events,
thus I've had to make this feature optional.

You can still get it by simply adding `e_get_zr()` to your chart.

Sorry if this breaks anything.
