### ISSUE TITLE
Using e_capture to capture events from ECharts event documentation

### ISSUE THREAD

**Issue by troyjcross** [JohnCoene/echarts4r#395]
I was wondering if I may be doing something wrong when implementing `e_capture()` in my example Shiny App below. I am currently exploring the event functionality with ECharts and `echarts4r` and was trying to play around with the `e_capture()` function to bind some mouse events like `'dblclick'`, `'mousemove'` etc. However, as I worked my way through the list of these mouse events, I found that only a couple of them worked (e.g., `'globalout'`).

Then I started exploring the other events listed on the [Event Documentation](https://echarts.apache.org/en/api.html#events) page. And again - only a handful worked with the `e_capture()` function (e.g., `'datazoom'` as illustrated in the `e_capture()` example; `'selectchanged'` also seemed to work). A lot of other events like `'legendunselect'`,  did not.

I was wondering if I'm just not using `e_capture()` correctly? Or is this something I'd need to use `e_on()` for instead?

```r
library(shiny)
library(echarts4r)
library(nycflights13)
library(shiny)

data <- flights %>% 
  mutate(date = as.Date(time_hour)) %>% 
  filter(date <= as.Date('2013-01-31')) %>% 
  select(date, time_hour, carrier, tailnum, origin, dest) %>% 
  arrange_all()

ui <- fluidPage(
  fluidRow(
    echarts4rOutput('chart'),
    column(6,h2('Mouseup event'),verbatimTextOutput('mouseup_event_output')),
    column(6,h2('Selectchanged event'), verbatimTextOutput('selected_event_output'))
  )  
)

server <- function(input, output, session) {
  
  output$chart <- renderEcharts4r({
    data |> 
      count(date) |> 
      e_charts(date) |>
      e_line(
        serie = n, 
        name = 'Number of flights',
        symbolSize = 12
      ) |>
      e_tooltip(axisPointer = list(type = 'cross')) |>
      e_axis_labels(y = 'Number of flights') |>
      e_mark_line(data = list(xAxis = as.Date('2013-01-16'))) |>
      e_datazoom() |>
      e_capture("mouseup") |>
      e_capture("selectchanged")
  })
  
  observeEvent(input$chart_mouseup, {
    
    # This event doesn't seem to work?

    output$mouseup_event_output <- renderPrint({
      input$chart_mouseup
    })
    
  })
  
  observeEvent(input$chart_selectchanged, {
    
    # This event does work
    
    output$selected_event_output <- renderPrint({
      input$chart_selectchanged
    })
    
  })
  
  
}

shinyApp(ui, server)
```

**Comment by troyjcross** [comment]
...I'm wondering if my issues have something to do with the nature of the data that is being returned from some of these events. 

Here I'm trying to manually bind the output of the 'click' event from ECharts to a ShinyInput called "chart_clicked":

```
e_on(NULL, handler =  'function(params){
           console.log(params);
           Shiny.setInputValue("chart_clicked", params);
      }')
```
However, when looking at the console output in the inspector, I get this error message about a circular JSON structure...
![image](https://user-images.githubusercontent.com/75189640/146697794-4d82dbaa-f371-438a-9422-80b4f3f46f95.png)

However, if I try returning the data element of the object returned by 'click' I don't receive an error at all and I am able to read the output of the JS handler function:
```
e_on(NULL, handler =  'function(params){
           console.log(params);
           Shiny.setInputValue("chart_clicked", params.data);
      }')
```

Is there perhaps something strange about the object returned by the 'click' event in ECharts which makes it difficult to convert to a readable list format in R? (RE: the circular JSON issue?)

**Comment by JohnCoene** [comment]
Apologies, a new feature in #394 accidentally broke things elsewhere. 
This is fixed (reinstall github version). The code below works

```r
library(shiny)
library(dplyr)
library(nycflights13)
library(echarts4r)

data <- flights %>% 
  mutate(date = as.Date(time_hour)) %>% 
  filter(date <= as.Date('2013-01-31')) %>% 
  select(date, time_hour, carrier, tailnum, origin, dest) %>% 
  arrange_all()

ui <- fluidPage(
  fluidRow(
    echarts4rOutput('chart'),
    verbatimTextOutput('clicked') 
  )  
)

server <- function(input, output, session) {
  
  output$chart <- renderEcharts4r({
    data |> 
      count(date) |> 
      e_charts(date) |>
      e_line(
        serie = n, 
        name = 'Number of flights',
        symbolSize = 12
      ) |>
      e_tooltip(axisPointer = list(type = 'cross')) |>
      e_axis_labels(y = 'Number of flights') |>
      e_mark_line(data = list(xAxis = as.Date('2013-01-16'))) |>
      e_datazoom() |>
      e_on(
        "series.line",
        "function(){
          Shiny.setInputValue('chart_on_click', true, {priority: 'event'});
        }"
      )
  })
  
  output$clicked <- renderText({
    print(input$chart_on_click)
  })
  
}

shinyApp(ui, server)
```

Note: do not place `render*` functions inside `observe*` functions, there is no need.

**Comment by JohnCoene** [comment]
I'm going to assume this was solved and close this, feel free to reopen if it is not.
