### ISSUE TITLE
How to change margins

### ISSUE THREAD

**Issue by Laurent-Smeets-GSS-Account** [JohnCoene/echarts4r#397]
For plots without a legend and no axis titles the canvas is rendered with pretty wide white margins, changing width and height does not change these. How would it be possible to remove these margins?

For example:

```r
iris %>% 
  e_charts(height =  250) %>% 
  e_histogram(Sepal.Length, breaks = 25)
```
![image](https://user-images.githubusercontent.com/79904977/147123219-88252dd3-db39-43b7-b57e-400c6c126a45.png)

**Comment by JohnCoene** [comment]
You can change them with `e_grid`

```r
library(echarts4r)

iris %>% 
  e_charts(height =  250) |> 
  e_histogram(Sepal.Length, breaks = 25) |> 
  e_grid(
    left = 20,
    right = 10,
    top = 10,
    bottom = 20
  )
```

**Comment by JohnCoene** [comment]
I'm going to assume this was solved and close this, feel free to reopen if it is not.
