### ISSUE TITLE
Using template variables with formatter in e_tooltip?

### ISSUE THREAD

**Issue by smach** [JohnCoene/echarts4r#4]
Hi, great package, thanks! I was wondering if there's a way to use the echarts template variables in e_tooltip as described here at [https://ecomfe.github.io/echarts-doc/public/en/option.html#tooltip.formatter]( https://ecomfe.github.io/echarts-doc/public/en/option.html#tooltip.formatter)

When I use e_tooltip(formatter = "{c}") in a scatter plot, I get both the x and y values returned in a single comma-separated result like "x,y", such as "100,215". I was wondering if you know whether it's possible to call an _individual value_ such as described in the echarts documentation, using {c0} for the first data value or {c1} for the second? As far as I can see, both {c} and {c0} return the comma-separated x and y values together and {c1} isn't functioning as a template variable. Thanks!

**Comment by JohnCoene** [comment]
This does not always work as expected, this does, however.

```r
USArrests %>% 
  e_charts(Assault) %>% 
  e_effect_scatter(UrbanPop, Murder) %>% 
  e_tooltip(formatter = htmlwidgets::JS("
    function(params){
      return('X:' + params.value[0] + '<br>Y: ' + params.value[1] + '<br>Size: ' + params.value[2])
    }
  ")
)
```

**Comment by smach** [comment]
Thanks very much, I will use that format instead. I'm guessing there's no way to include a column from the data frame that's not in the plot. For example, if USArrests had a column for State (instead of just row names for states), to also show the State name as part of the tooltip?

By the way I've added echarts4r to my list of useful R packages at Computerworld: [https://www.computerworld.com/article/2921176/business-intelligence/great-r-packages-for-data-import-wrangling-visualization.html](https://www.computerworld.com/article/2921176/business-intelligence/great-r-packages-for-data-import-wrangling-visualization.html)

**Comment by smach** [comment]
Oh this is great, so the code below would do exactly what I want with a regression line and custom tooltip:

    mtcars %>% 
      tibble::rownames_to_column("model") %>% 
      e_charts(wt) %>% 
      e_scatter(mpg, bind = model) %>%
      e_lm(mpg ~ wt, name = "linear regression") %>%
      e_tooltip(formatter = htmlwidgets::JS("
                     function(params){
                     return('<strong>' + params.name + '</strong><br />wt: ' + params.value[0] + '<br />mpg: ' + params.value[1]) 
                            }
                      "))

**Comment by smach** [comment]
Here's my suggested addition to the e_tooltip() documentation on this:

Tooltip customization

You can display a _default_ tooltip by adding `e_tooltip()` to the code that creates your visualization, such as 

    mtcars %>%
      e_charts(wt) %>%
      e_scatter(mpg) %>%
      e_tooltip()
	  
In order to _customize_ the tooltip, though, you'll need to be comfortable adding a little JavaScript to your R code. Tooltip customization uses the format

    e_tooltip(formatter = htmlwidgets::JS("
        function(params){
		return( )
		}
		"))
		
Where the specific information you'd like to appear goes within return(). 

Here's what you need to know about adding variables into that return() code:

The x-axis variable is `params.value[0]`. The y-axis variable is `params.value[1]`. If you added another, size variable to the scatter plot, that would be `params.value[2]`. (Note that because this is JavaScript, indexing starts with 0 as in most computer languages, and not 1 as in R.)

Here's how you might customize a tooltip for a scatter plot of mtcars wt and mpg, in order to show both wt and mpg in the tooltip::

    mtcars %>%
      e_charts(wt) %>%
      e_scatter(mpg) %>%
      e_tooltip(formatter = htmlwidgets::JS("
          function(params){
                 return('wt: ' + params.value[0] + '<br />mpg: ' + params.value[1])
                 }
           "))

If you'd like to add information about a data frame column that's not included in the chart, you can pass in that data using the `bind` argument. As an example, you might want to include the name of the car model in the tooltip. With this particular data set, you'd first need to create that column, which you can do with code such as  `mtcars <- tibble::rownames_to_column(mtcars, "model")` . Then, you can pass that column into your scatter plot visualization with `e_scatter(mpg, bind = model)`. 

To _use_ that passed-in value within the e_tooltip() formatter code, refer to it as `params.name`. For example:

    mtcars %>%  
      e_charts(wt) %>% 
      e_scatter(mpg, bind = model) %>%
      e_tooltip(formatter = htmlwidgets::JS("
                     function(params){
                     return('<strong>' + params.name + '</strong><br />wt: ' + params.value[0] + '<br />mpg: ' + params.value[1]) 
                            }
                      "))

**Comment by JohnCoene** [comment]
Added [tooltip documentation](http://echarts4r.john-coene.com/articles/tooltip.html) :+1:

**Comment by smach** [comment]
👍

**Comment by JohnCoene** [comment]
Hi @smach I put you as author of the [tooltip documenation](file:///home/jp/Packages/echarts4r/docs/articles/tooltip.html) as it it essentially is a copy paste your issues(s) - feel free to re-open if you're not OK with this.

**Comment by smach** [comment]
Thanks!

**Comment by ddrogen** [comment]
Thanks! I use this example in my line chart with 3 categories, but the interactivity is not working. If I leave e_tooltip(trigger="axis"), I am able to un-click the legend to see the desire series. Why inserting JS into the tooltip lead to that behaviour?
Thanks
