### ISSUE TITLE
When switch between timeline ,  echart map randomly highlight a country, which is weird. 

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/echarts4r#400]
When switch between timeline ,  map randomly highlight a country, which is weird. 

```r
library(gapminder)

datos_gapminder_map <- gapminder %>%
  mutate(Name = recode_factor(country,
                              `Congo, Dem. Rep.`= "Dem. Rep. Congo",
                              `Congo, Rep.`= "Congo",
                              `Cote d'Ivoire`= "Côte d'Ivoire",
                              `Central African Republic`= "Central African Rep.",
                              `Yemen, Rep.`= "Yemen",
                              `Korea, Rep.`= "Korea",
                              `Korea, Dem. Rep.`= "Dem. Rep. Korea",
                              `Czech Republic`= "Czech Rep.",
                              `Slovak Republic`= "Slovakia",
                              `Dominican Republic`= "Dominican Rep.",
                              `Equatorial Guinea`= "Eq. Guinea"))

datos_gapminder_map %>%
  group_by(year) %>%
  e_chart(Name, timeline = TRUE) %>%
  e_map(lifeExp) %>%
  e_visual_map(min= 30, max= 90,
               type = 'piecewise') %>%
  e_title("Life expectancy by country and year", left = "center") %>%
  e_tooltip(
    trigger = "item",
    formatter = e_tooltip_choro_formatter())


```

![temp](https://user-images.githubusercontent.com/3085202/148037483-7ecd5916-f36a-45f0-a249-e20c5879a0b1.png)

**Comment by JohnCoene** [comment]
Which version of echarts4r do you have?

I believe this issue was reported and fix; I cannot reproduce it on the latest CRAN or dev version.

**Comment by brucefeiwang** [comment]
R version 4.1.2 (2021-11-01)
![temp](https://user-images.githubusercontent.com/3085202/148044500-d6c490be-2bee-49b9-bda3-a2666970b68e.png)

 Could it be a problem with Windows only ?
![temp](https://user-images.githubusercontent.com/3085202/148044661-1388996f-b552-4aa5-bf40-e74e1dc41db5.png)

**Comment by JohnCoene** [comment]
Strange this.

Could you reinstall from CRAN now, restart the R session and open the visualisation in your web browser?

**Comment by brucefeiwang** [comment]
tried this , did not work 
```remotes::install_github("JohnCoene/echarts4r")```

If you click auto play button,  it is ok.   it only happens when you manually click different years.

**Comment by brucefeiwang** [comment]
I see. thanks
