### ISSUE TITLE
How to use e_map_register_p

### ISSUE THREAD

**Issue by guybrettrobertson** [JohnCoene/echarts4r#411]
It would be really helpful if someone could please explain how I could use `e_map_register_p`, perhaps by adapting the standard example given in the documentation here: https://echarts4r.john-coene.com/articles/map.html#geojson-support-1.

I would like to see if assigning `e_map_register_p` once and then referring to it many times is faster than calling `e_map_register` many times.

Thank you!

**Comment by JohnCoene** [comment]
I recommend using `e_map_register_ui`

It should, dependending on the app and how frequently you render the map, immensely improve performances

```r
library(shiny)
devtools::document()
devtools::load_all()

ui <- fluidPage(
  e_map_register_ui(
    "MAP",
    "https://raw.githubusercontent.com/shawnbot/topogram/master/data/us-states.geojson"
  ),
  echarts4rOutput("chart")
)

server <- function(input, output) {

  output$chart <- renderEcharts4r({
    USArrests |>
      tibble::rownames_to_column("states") |> 
      e_charts(states) |>
      e_map(Murder, map = "MAP") |> 
      e_visual_map(Murder)
  })
}

shinyApp(ui, server)
```
