### ISSUE TITLE
Date class on x axis not showing up by default in tooltip

### ISSUE THREAD

**Issue by smach** [JohnCoene/echarts4r#416]
Hi John! I'm still enjoying echarts4r :-) FYI when my data set has a date class on the x axis, the date information doesn't show up automatically in the tooltip the same way that character strings on the x axis do. I'm not sure that's intentional? I can get around this by turning my dates into character strings or by setting up a custom tooltip formatter, but neither are quite as good as the default. (The custom tooltip doesn't show the nice little color dot for series in the tooltip the way the default does, unless there's a way for me to add that back? And I like how dates show month and year in the x axis)

**Comment by JohnCoene** [comment]
Hi Sharon,

Glad it's still useful to you!

echarts4r itself doesn't do anything to the tooltip, it's all handled by the JavaScript library.
The type of the `x` data is used to determine the `type` of axis in echarts.js.
If it's a `date` or `POSIX` echarts4r sets said type as `time`. 
This has the advantage that it will scale the axis nicely if you have missing dates.
If the data on the `x` axis is set to `categorical` which then does not benefit from the aforementioned scaling/missing dates.

These two types do indeed result in different tooltips.
Here are just two potential solutions.

```r
library(echarts4r)

# dataset
df <- data.frame(
  date = seq.Date(Sys.Date() - 10L, Sys.Date(), by = "day"),
  n = runif(11, 1, 10)
)

# base plot
e <- df |> 
  e_charts(date) |> 
  e_line(n)

# trigger axis
e |> e_tooltip(trigger = "axis")

# marker
e |> 
  e_tooltip(
    formatter = htmlwidgets::JS(
      "(e) => {
        return `${e.marker} ${e.value[1]} - <strong>${e.value[0]}</strong>`;
      }"
    )
  )
```

1. Changing the trigger shows the date.
2. You can get the marker from the `event` object from the template (`event.marker`)

**Comment by smach** [comment]
Thank you! I'll try that tonight!!
