### ISSUE TITLE
Change the color of a line on parallel plot

### ISSUE THREAD

**Issue by yogat3ch** [JohnCoene/echarts4r#418]
Hi @JohnCoene ,
Thanks for your assistance on the parallel plot brush ranges issue! I'm gradually learning JS to hopefully take on a full PR for the functionality we accomplished in that thread. 

This is probably a stupid question but I'm struggling to find how to change the color of single line on the parallel plot? The parallel plot doesn't use the `e_line` modifier function. I was thinking that `e_visual_map` might allow this, but it appears to map a range to a color, rather than just specifying the color of a specific element. 

Could you point me in the right direction on this?

**Comment by JohnCoene** [comment]
A bit of a weird case this parallel line

Does that do what you want?

```r
library(echarts4r)

df <- data.frame(
  price = rnorm(7, 10),
  amount = rnorm(5, 15),
  letter = LETTERS[1:5]
)

df |> 
  e_charts() |> 
  e_parallel(price, amount, letter) |> 
  e_title("Parallel chart") |> 
  e_visual_map(
    inRange = list(
      color = c("red", "blue")
    ),
    dimension = 0L, # 0 = price, # 1 = amount, etc
    min = 7L,
    max = 10L,
    calculable = FALSE
  ) 
```

**Comment by yogat3ch** [comment]
Hi @JohnCoene,
Thanks for this, I was able to get this working but it's not quite doing what I had hoped. 
My use case is to highlight a line that is single clicked by using `input$clicked_data`.
It's going to be tricky to use `input$clicked_data` to form a range for `inRange` and not inadvertently select other lines that share the same value for a given dimension. I supposed I could iterate over all the columns of data and form ranges based on `input$clicked_data` but this seems error prone. 
I'm looking at the [parallel chart preview example](https://echarts.apache.org/en/option.html#series-parallel) where line colors appear to be defined by the `color` option that corresponds to data names:
```
color: ["#c23531", "#91c7ae", "#dd8668"],
  legend: {
    top: 10,
    data: ["北京", "上海", "广州"],
    itemGap: 20
  }
 ```

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/32208821/162266822-06f5f30c-6d2d-485e-b18b-302057c93f62.png">

I tried inputting a named list for `data` to `e_chart` to see if I could specific multiple series and customize the color for each one using subsequent `echarts4r::e_parallel` calls but it appears that `dplyr::select` is used on `data` and thus it doesn't handle lists.

The handling appears to be via S3 methods: `echarts4r:::echarts.Node` & `echarts4r:::echarts.default`, so it seems like a `list` method could be created. 
Is this the approach that would support specifying line colors - by differentiating them into series and allows for labeled list data to be passed to `data` or am I barking up the wrong tree?

**Comment by yogat3ch** [comment]
Hi @JohnCoene,
Related to this - I'm wondering why the only properties of the click event showing up in the `input` for the app is `chart_clicked_data` when it looks like [you've also mapped the `dataIndex`](https://github.com/JohnCoene/echarts4r/blob/96c33a0636fa8acd577397b01e30cce0304b5802/inst/htmlwidgets/echarts4r.js#L108) to an event as well as the `seriesName`?
