### ISSUE TITLE
Theme name check introduced to address #407 doesn't work for custom themes

### ISSUE THREAD

**Issue by jonmcalder** [JohnCoene/echarts4r#422]
I may have overlooked something, but it seems to me that the theme name checks introduced to address #407 assume that one is using one of the built-in themes and not a custom theme with a different name?

With the latest development version of echarts4r when registering a custom theme using `e_theme_register()` and then using `e_common()` or `e_theme()` then the match.arg check introduced [here](https://github.com/JohnCoene/echarts4r/blob/96c33a0636fa8acd577397b01e30cce0304b5802/R/themes.R#L45) fails. Would it be possible to make this check be more dynamic / include custom registered themes?

Apologies if I've misunderstood or overlooked something here.

**Comment by JohnCoene** [comment]
Apologies!

I don't think you overlooked anything, I pushed a fix, could you reinstall and let me know whether it works?

**Comment by jonmcalder** [comment]
Yes that works thanks 👍
