### ISSUE TITLE
How to change Tooltips' BKG color to White (not transparent...)

### ISSUE THREAD

**Issue by sfd99** [JohnCoene/echarts4r#425]
**_Hi John,_**

echarts4r pkg is great.

_**Q:**_
How to change (simply, pls!) , 
    the Tooltips BKG color to solid **White** and
          Tooltips FGD color to solid **Black**
 (ie: not transparent 
   and hard to read tooltip contents...)?.

EX from **"Get Started"** pg: (R-code+Chart)
https://echarts4r.john-coene.com/articles/get_started.html#htmlwidget-b08558d05569fec55f72

See? 
Text Content of Tooltips are hard to read
when hovering cursor, 
on some parts of this Example Chart.

Ideal Tooltip content color (IMHO):
Black on White...

Thanks, John!
**SFd99
San Francisco
echarts4r V 0.4.3
R, Rstudio, Ubuntu Linux (latest versions)
=================**

**Comment by rdatasculptor** [comment]
I have not tested it yet and just a thought, but why not `e_tooltip(backgroundColor = "#ffffff)`?

**Comment by sfd99** [comment]
@rdatasculptor
yes!, 
that would be a good idea to include.

**Comment by rdatasculptor** [comment]
I mean, try that :). According to the main JavaScript documentation it works like that. [Tooltip Documentation](https://echarts.apache.org/en/option.html#tooltip.backgroundColor)

**Comment by sfd99** [comment]
@rdatasculptor
Ah, got it!.
Thanks for that quick reply.

Have a nice weekend.
