### ISSUE TITLE
Add Internalization when using CDN for code

### ISSUE THREAD

**Issue by geebeetoo** [JohnCoene/echarts4r#429]
This is an amazing product! Great work guys!

I am new to it and I researched how I to use i18n for French and Spanish. I use PHP and Javascript only. I link to eCharts with CDN:
https://cdn.jsdelivr.net/npm/echarts@5.3.2/dist/echarts.min.js

I don't know how to get the i18n for French and Spanish.

I tried the registerLocale and init locale but of course that is not enough, I need to have the lang files pointed to somewhere.

How do i do this?

Thank you!

**Comment by JohnCoene** [comment]
In echarts4r you would only use `e_locale`, see [docs](https://echarts4r.john-coene.com/reference/e_locale.html)
