### ISSUE TITLE
Is it possible to use the dutch locale?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#432]
I am trying to set the local to the dutch one.

I tried things like `e_locale("nl")` with no luck. Maybe that is obvious, because dutch isn't mentioned [here](https://echarts4r.john-coene.com/reference/e_locale.html).

Is there a way to add the dutch locale?

Many thanks in advance!

**Comment by JohnCoene** [comment]
It could be but is not available, I made those [here](https://github.com/apache/echarts/tree/master/i18n)

I could make the function work with local files, or you could make a PR on echarts.js itself.

**Comment by rdatasculptor** [comment]
If you would be in the position (and having time for it), it would be very helpful to make the function work with local files!

Also I will explore the possibility to make a PR on echarte.js.

**Comment by JohnCoene** [comment]
I added a new function for it, making it work with the existing one would have made for an awkward API.

I tested it and it seems to work file.

```r
cars |> 
  e_charts(speed) |> 
  e_scatter(dist) |> 
  e_datazoom() |> 
  e_locale_manual("JA", "./path/to/file.js")
```

**Comment by rdatasculptor** [comment]
whow, thanks John!

Am I right to persume that I need to make a dutch translation of an object like [this ]([url](https://github.com/apache/echarts/blob/master/i18n/langEN.js))one?

**Comment by rdatasculptor** [comment]
(sorry, didn't add the hyperlink to the js object properly, but I updated it)

**Comment by JohnCoene** [comment]
Yes, that's what is expected.

**Comment by rdatasculptor** [comment]
your new function works!! very helpful :) thanks!

**Comment by JohnCoene** [comment]
Glad to hear it!
