### ISSUE TITLE
Adding measures of uncertainty to charts?

### ISSUE THREAD

**Issue by Huh** [JohnCoene/echarts4r#44]
This is a question, but perhaps also an enhancement.  There is a demo of building a confidence band on the echarts main site, shown below with a subtitle built in metricsgraphics.js.

![image](https://user-images.githubusercontent.com/483064/48988312-1c210000-f0e2-11e8-8e46-1c4bb370b1ff.png)

Is there a means of building this type of plot?  Alternatively, a line segement could be used to build a dumbell plot where a point is paired with a vertical line(s) to show uncertainty about an estimate.  After reading all of the documentation (great work) I don't see too many options for representing uncertainty.  Any thoughts would be appreciated.

If this functionality does not yet exist I would strongly support this type of addition to an already amazing package.  Thanks.

**Comment by JohnCoene** [comment]
It's quite a big job but doable, I'll work on implementing error bars and the like. In the meantime, you can build the confidence band like they do in the example.

```r
require(nlme)

set.seed(101)
mp <-data.frame(year=1990:2010)
N <- nrow(mp)

mp <- within(mp,
         {
             wav <- rnorm(N)*cos(2*pi*year)+rnorm(N)*sin(2*pi*year)+5
             wow <- rnorm(N)*wav+rnorm(N)*wav^3
         })

m01 <- gls(wow~poly(wav,3), data=mp, correlation = corARMA(p=1))
fit <- predict(m01)

V <- vcov(m01)
X <- model.matrix(~poly(wav,3),data=mp)
se.fit <- sqrt(diag(X %*% V %*% t(X)))

predictions <- with(mp,data.frame(year,wav,
                                wow=fit,lwr=fit-1.96*se.fit,upr=fit+1.96*se.fit))
library(dplyr)

predictions %>% 
    mutate(
        year = as.character(year), # stack only works with categorical x axis
        min = wow - lwr,
        max = wow - upr
    ) %>% 
    e_charts(year) %>% 
    e_line(wow) %>% 
    e_area(min, stack = "stack") %>% 
    e_area(max, stack = "stack")
```

**Comment by Huh** [comment]
Thank you for the helpful reply!

**Comment by JohnCoene** [comment]
I have `e_bands` now implemented. Let me know if you are happy with the implementation, I can always change things. An example of it on the [website](https://echarts4r.john-coene.com/articles/stats.html).

**Comment by Huh** [comment]
Thanks for getting to this so quickly, much appreciated.  The function does work well under most conditions, but I see a few places where things get odd.  As you read this please keep in mind that I am new to the package and may not be fully understanding the correct implementation of the package.

A few conditions I know I will encounter:
- X is of some class that is not a date like class
- Missing values in the x column
- Ability to draw lines when series bounces around 0, mixed positive and negative values

From `?echarts4r::e_band`, I copied the example code and modified to build the following scenarios.

1) Line goes above and below 0
  - Creates odd behavior, difficult to describe, see image below

```R
df <- tibble::tibble(
  x = as.character(1:6), 
  y = runif(6, -1, 1), 
  lwr = y - .2, 
  upr = y + .2
) %>%
data.frame(.)

df %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_band(
    y, 
    lwr, 
    upr
  )

```
![image](https://user-images.githubusercontent.com/483064/49333526-b28b7080-f57d-11e8-8e44-8ec27931cfd7.png)


2) Implicit missing values in `x`
  - upper seems to fill from upr to lwr and not upr to y
  - lower seems to fill from lwr to -Inf
  - the location of upr and lwr seems way off

```R
df <- tibble::tibble(
  x = as.character(c(1, 2, 5, 6, 7, 9)), 
  y = runif(6, 10, 20), 
  lwr = y - 2, 
  upr = y + 2
) %>%
data.frame(.)

df %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_band(
    y, 
    lwr, 
    upr
  )
```
![image](https://user-images.githubusercontent.com/483064/49333538-dc449780-f57d-11e8-9496-b587770c93fb.png)


3) Explicit missing `x`
  - upper seems to fill from upr to lwr and not upr to y
  - lower seems to fill from lwr to 0
  - drawing a line between lwr and y and upr and y for the last point might be a nice touch given that everything else is filled

```R
df <- tibble::tibble(
  x = as.character(c(1, 2, NA, NA, 5, 6, 7, NA, 9)), 
  y = (10 + as.integer(x)) , 
  lwr = y - 2, 
  upr = y + 2
) %>%
data.frame(.)

df %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_band(
    y, 
    lwr, 
    upr
  )
```

![image](https://user-images.githubusercontent.com/483064/49333604-e61aca80-f57e-11e8-941d-c478f5a6ab6f.png)


4) Explicit missing `x`, but no coercion `as.character(x)`, this may be improper handling of the x variable?
  - x-axis double the max
  - fill goes in odd directions

```R
df <- tibble::tibble(
  x = c(1, 2, NA_integer_, NA_integer_, 5, 6, 7, NA_integer_, 9), 
  y = (10 + x) * runif(length(x), -2, 2), 
  lwr = y - 2, 
  upr = y + 2
) %>%
data.frame(.)

df %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_band(
    y, 
    lwr, 
    upr
  )
```  

![image](https://user-images.githubusercontent.com/483064/49333582-87555100-f57e-11e8-9e84-b512169eb3b1.png)

5) In an attempt to make the problem more simple I created the following which matches my expectation of how the package works and may illustrate that I am incorrectly approaching the package 

```R
df <- data.frame(
  x = as.character(1:5), 
  y = rep(10, 5), 
  lwr = rep(8, 5), 
  upr = rep(12, 5)
)

df %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_band(y, lwr, upr)
```

![image](https://user-images.githubusercontent.com/483064/49333872-1153e880-f584-11e8-98ef-2518f6a124a9.png)



If you prefer this post in another form I can rework the examples etc.  Thanks again for getting to this feature so quickly.

**Comment by JohnCoene** [comment]
Thank you for the very detailed bug report! I apologise for the late response.

I have addressed many of the issues above, one remains, and I am afraid will; when there is a mix of positive and negative values. This is because the way this is implemented is a bit hacky; there are no "confidence bands" serie type in ECharts.

Note that now, `e_band` only takes the lower and upper limits and not longer takes `y`, e.g:

```r
data <- jsonlite::fromJSON(
    paste0(
        "https://ecomfe.github.io/echarts-examples/public/",
        "data/asset/data/confidence-band.json"
    )
)

data %>% 
  dplyr::mutate(
    date = as.Date(date, "%Y-%m-%d"),
    l = l + value,
    u = u - value
  ) %>% 
  e_charts(date) %>% 
  e_line(value, symbol = "none") %>% 
  e_band(
    l, u, 
    areaStyle = list(list(color = "grey"), list(color = "grey"))
  )
```

Note that I have also added [error bars](https://echarts4r.john-coene.com/articles/stats.html#error-bars). All of this on CRAN already.

**Comment by Huh** [comment]
Thank you for the reply and the implementation of error bars.  I think at this point the package will meet my needs and replace some existing rbokeh plots.  Thanks for the great package.
