### ISSUE TITLE
echarts4r 3D renderer="svg" doesn't show graphics

### ISSUE THREAD

**Issue by wdb-web** [JohnCoene/echarts4r#445]
library(echarts4r)
v <- LETTERS[1:10]
matrix <- data.frame(
  x = sample(v, 300, replace = TRUE), 
  y = sample(v, 300, replace = TRUE), 
  z = rnorm(300, 10, 1),
  stringsAsFactors = FALSE
) 
#> `summarise()` has grouped output by 'x'. You can override using the `.groups`
#> argument.
  
matrix |> 
  e_charts(x,renderer="svg") |> 
  e_scatter_3d(y, z)
```

result is blank

**Comment by JohnCoene** [comment]
Yes 3D cannot be svg.
