### ISSUE TITLE
How to modify the color of point on line

### ISSUE THREAD

**Issue by richardliu11** [JohnCoene/echarts4r#449]
I draw a line chart.
I want based on the data of a certain attribute changes an individual color.
Used to identify the abnormal data.

**Comment by JohnCoene** [comment]
Do you have an example from the official website or some code to get started?

**Comment by richardliu11** [comment]
First of all thank you for your reply.

**example:
X axis is time,Y axis is sales number
i want make some point red( type is 'mark'),another points's color is normal.**


dates <- seq.Date(as.Date("2017-01-01"), as.Date("2018-12-31"), by = "day")
values <- rnorm(length(dates), 20, 6)

plot_df <- data.frame(date = dates, values = values)
plot_df$type <-NA
plot_df$type[c(1:10,18:35,100:178,200:350,700:709)]<-c('mark')

plot_df %>%
  e_charts(date) %>%
  e_line(values)

**Comment by rdatasculptor** [comment]
I am not quite sure what you intend, but do you mean something like this? Since I don't know what you mean by a "normal" color I chose one myself, blue :)

```
dates <- seq.Date(as.Date("2017-01-01"), as.Date("2018-12-31"), by = "day")
values <- rnorm(length(dates), 20, 6)

plot_df <- data.frame(date = dates, values = values)
plot_df$type <-NA
plot_df$type[c(1:10,18:35,100:178,200:350,700:709)]<-c('mark')
plot_df <- plot_df %>% mutate(type = ifelse(is.na(type), "not mark", type), 
                              color = ifelse(type=="mark", "red", "blue"))

plot_df %>%
  e_charts(date) %>%
  e_line(values, lineStyle = list(color = "blue")) %>%
  e_add_nested("itemStyle", color)
```

**Comment by richardliu11** [comment]
> 

Thanks for your reply, it solved my problem.

I didn't notice the e_add_nested function before.

**Comment by richardliu11** [comment]
Thanks again for the replies of @rdatasculptor  and @JohnCoene , it helped me a lot!

**Comment by JohnCoene** [comment]
Thanks @rdatasculptor !
