### ISSUE TITLE
e_label formatter multiple values

### ISSUE THREAD

**Issue by versipellis** [JohnCoene/echarts4r#45]
I'm referencing the official documentations [here](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.label.formatter), but I'm not quite sure if the syntax is translating over to echarts4r the same way. It seems to be that this way should work:

```
  e_labels(show = TRUE,
          position = "insideTopLeft",
          formatter = "{b}\n{c}\n{@relativeValue}",
          fontSize = 10)
```

...But it doesn't. `{b}` resolves to the line item name and `{c}` resolves to the line item first value just fine, but I can't seem to get the third column (relativeValue) to render with `{@relativeValue}` - it outputs the same as `{b}`. Particularly, this is the part of the documentation I'm referencing:

```
{@xxx}: the value of a dimension named'xxx', for example,{@product}refers the value of'product'` dimension
```

Likewise, referencing this part of the documentation:

```
{@[n]}: the value of a dimension at the index ofn, for example,{@[3]}` refers the value at dimensions[3].
```

The below code block should work too, using the index, but it doesn't. 

```
  e_labels(show = TRUE,
          position = "insideTopLeft",
          formatter = "{b}\n{c}\n{@[3]}",
          fontSize = 10)
```

**Comment by JohnCoene** [comment]
Hi thanks for reporting. The issue comes from the fact that `e_labels` does not actually correspond to that option; `e_labels`adds the `label` under `data` as described [here](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.data.labelhttps://ecomfe.github.io/echarts-doc/public/en/option.html#series-line.data.label).

```r
cars %>% 
    e_charts(speed) %>% 
    e_line(
        dist, 
        label = list(
            show = TRUE,
            formatter = "{b}\n{c}\n{@[3]}"
        )
    )
```

`e_labels` is somewhat documented [here](https://echarts4r.john-coene.com/articles/advanced.html#show-labels). It is, technically a wrapper to [`e_add`](https://echarts4r.john-coene.com/articles/advanced.html#nested-data):

```r
mtcars %>% 
  dplyr::mutate(fontSize = 19, show = TRUE) %>% 
  e_chart(wt) %>% 
  e_scatter(qsec, cyl) %>% 
  e_add("label", fontSize, show)
```

So the code above is similar to using `e_labels`, which I created in hope to make things clearer, the irony is not lost on me haha. I'm always open to improving the API, please feel free to let me know another way to make this clear.

**Comment by JohnCoene** [comment]
`e_labels` is useful if you want to pass different options to different labels, show some labels but not others, or show labels in different colors as shown on the website. Otherwise the global option passed to e.g.: `e_line` is fine, it'll apply to all labels and will also more efficient (computation wise and less load on the browser as reduced data). Make sense?

**Comment by versipellis** [comment]
So, I'm still having a little trouble still. Your example code also displayed the same piece of data for both `{c}` and `{@[3]}`, which was the exact same symptom I had using `e_labels`. I'm referencing the [treemaps docs](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-treemap.label.formatter) specifically for labeling, trying to get my labels to display more than dimension of data. Am I still doing this wrong?

```
  data %>%
  e_charts() %>%
  e_treemap(grouping,
            name,
            value,
            itemStyle = c(borderColor = "black"),
            label = list(show = TRUE,
                         position = "insideTopLeft",
                         formatter = "{b}\n{c}\n{@percent}",
                         fontSize = 10))
```

This code looks analogous to your example above, but still only displays one dimension of data for both data fields.

**Comment by JohnCoene** [comment]
The issue here is that these are the only dimensions, `{name: "Serie", value: 20}`. On other chart types that have more dimensions it works. 

For instance, `e_scatter` which has x, y, z (size).

```r

iris %>% 
    dplyr::filter(Species == "setosa") %>% 
    dplyr::slice(1:5) %>% 
    e_charts(Sepal.Length) %>% 
    e_scatter(
      Petal.Length, 
      Sepal.Width,
      label = list(
        show = TRUE,
        color = "black",
        position = list(
          "80%",
          "80%"
        ),
        formatter = "x: {@[0]}\ny: {@[1]}\nz: {@[2]}" # JavaScript array start at 0
      )
    ) %>% 
    e_x_axis(min = 4, max = 5.5)  %>% 
    e_y_axis(min = .9, max = 1.6)
```

Somewhat "unsual" chart types tend to be a pain for labels and tooltips: is the output of the code below what you are after?

```r

tm <- data.frame(
  parent = c("earth", "earth", "earth", "mars", "mars"), 
  child = c("forest", "ocean", "iceberg", "elon", "curiosity"),
  value = ceiling(rnorm(5, 10, 2))
)

tm %>% 
  e_charts() %>% 
  e_treemap(
    parent, child, value,
    label = list(
      show = TRUE,
      formatter = htmlwidgets::JS("
        function(params){
          return params.name + ': ' +
          params.value;
        }
      ")
    )
  )
```

Sadly those things are very fidly (it's not the package) but the original libraries, I hope this gets fixed: I'll keep the source JavaScript files updated.

**Comment by versipellis** [comment]
Aaah, I understand. Not a problem! I had come across [this vignette](https://ecomfe.github.io/echarts-examples/public/editor.html?c=treemap-obama) in the original library's [treemaps docs](https://ecomfe.github.io/echarts-doc/public/en/option.html#series-treemap), and I wanted to do something similar where two values were displayed.

Unfortunately even using `htmlwidgets::JS()` doesn't work, and looking at the aforementioned vignette, looks like it might potentially be possible by wrangling the data into an array of vectors for the `value` passed into `value`, and then calling `params.value[1]` and `params.value[2]`.

**Comment by JohnCoene** [comment]
To be fair it's the `e_treemap` function that is not ideal. It should rely on the `treemap`package rather than try to take input from a `data.frame`, I'll make that as enhancement and will work on that next 👍

**Comment by JohnCoene** [comment]
Thanks! 👍

**Comment by henry090** [comment]
@JohnCoene but how can I paste strings?

```
df <- data.frame(
  label = rep('A',50),
  x = seq(50),
  y = rnorm(50, 10, 3),
  z = rnorm(50, 11, 2),
  w = rnorm(50, 9, 2)
)
df %>% 
  head(10) %>% 
  e_charts(x) %>% 
  e_effect_scatter(y, z,legend = F,
                   label= list(show = T,formatter = "{@label]}", #labels should be here
                               position= 'right',
                               show= T) ) %>% 
  e_visual_map(z) %>% # scale color
  e_legend(FALSE) # hide legend
```

**Comment by JohnCoene** [comment]
There are a few things happening here.

First, despite the data.frame `df` including `label` this is not passed to `e_charts`. Secondly the data that is passed to the JavaScript side is often structured differently than in the example.

Before explaining, there is the function `e_inspect` that is useful to debug such things.

```r
df <- data.frame(
  label = rep('A',50),
  x = seq(50),
  y = rnorm(50, 10, 3),
  z = rnorm(50, 11, 2),
  w = rnorm(50, 9, 2)
)
df %>% 
  head(10) %>% 
  e_charts(x) %>% 
  e_effect_scatter(y, z,legend = F,
                   label= list(show = T,
                                     formatter = "{@label}", #labels should be here
                                     position= 'right',
                                     show= T)
  ) %>% 
  e_visual_map(z) %>% # scale color
  e_legend(FALSE) %>%
  e_inspect(json = TRUE, pretty = TRUE) # display JSON options
```

Running the above reveals that the series' data does not contain the `label`. One way to produce the output you are after is by passing the `label` to the `bind` argument (admittedly very poorly named =/) which will pass the `label` to the data as `name`.

With the latter you can produce what you want with.

```r
df <- data.frame(
    label = rep(LETTERS[1:2], 25),
    x = seq(50),
    y = rnorm(50, 10, 3),
    z = rnorm(50, 11, 2),
    w = rnorm(50, 9, 2)
)
df %>% 
    head(10) %>% 
    e_charts(x) %>% 
    e_effect_scatter(
        y, z, bind = label, 
        legend = F,
        label= list(
            show = TRUE, 
            formatter = "{b}", # accessed with {b} 
            position= 'right',
            show= TRUE
        )
    ) %>% 
    e_visual_map(z) %>% 
    e_add("label", label)
```

It's more convoluted than it should, I will look into simplifying that by allowing users to pass additional columns to the data.
