### ISSUE TITLE
the picture exceeds the x axis

### ISSUE THREAD

**Issue by lengyuyeke** [JohnCoene/echarts4r#46]
`
mtcars %>% 
  group_by(am)%>%
  e_charts() %>% 
  e_histogram(mpg) %>% 
  e_tooltip(trigger = "axis")
`

Just run the code, you will see the bug.

**Comment by JohnCoene** [comment]
Yes, I'm afraid I'm aware of this bug, it's also referenced in #22: the histogram breaks when grouped. It's painful to fix, the issue is not on the R side but ECharts, as far I can make out, I will look into that again.
