### ISSUE TITLE
Problem with timeline tooltip

### ISSUE THREAD

**Issue by svenb78** [JohnCoene/echarts4r#461]
Hello, 

I use the attached data. 

[df_data.txt](https://github.com/JohnCoene/echarts4r/files/9526326/df_data.txt)

With that data, I greate a scatter plot with a timeline using the following code: 

```
tmp01 <- readr::read_delim(file = "df_data.txt", delim = ";")

plot_e <- tmp01 %>%
  dplyr::ungroup() %>%
  dplyr::group_by(datum) %>%
  echarts4r::e_charts(x = visits_delta_rel, timeline = TRUE) %>%
  echarts4r::e_scatter(
    serie = visits_delta_abs
    , bind = var_col
    , symbol_size = 20
    , label = list(show = TRUE, formatter = "{b}", rotate = 30, position = "top")
    , colorBy = "series"
  ) %>%
  echarts4r::e_tooltip(
    trigger = "item"
    , axisPointer = list(type = "cross")
    , formatter = htmlwidgets::JS("function(params){return('delta rel: ' + params.value[0] + '<br> ' + 'delta abs: ' + params.value[1] );}")
  ) %>%
  echarts4r::e_legend(show = FALSE) %>%
  echarts4r::e_y_axis(
    name = "Absoulte Veränderung Vormonat"
    , position = "left"
    , nameRotate = 90
    , nameLocation = "middle"
    , nameTextStyle = list(align = "middle", padding = 50, fontSize = 16, fontWeight = "bold")
  ) %>%
  echarts4r::e_x_axis(
    name = "Relative Veränderung Vormonat"
    , nameLocation = "middle"
    , nameTextStyle = list(align = "middle", padding = 20, fontSize = 16, fontWeight = "bold")
  ) %>%
  echarts4r::e_add_nested("itemStyle", color) %>%
  echarts4r::e_timeline_opts(
    top = 0
    #, label = list(formatter = "{b}")
  ) %>%
  echarts4r::e_title(text = "")

plot_e
```

Please, hover over the timeline? Why is the `formatter` changing for the timeline? How can I change this back to the values of `datum`?

**Comment by svenb78** [comment]
Hi, 

I added a screenshot: 

![tooltip](https://user-images.githubusercontent.com/86719356/190363778-ba88711d-f21e-4a16-805b-2e4e9bcffba3.jpg)

To be more precise: It is the tooltip of the timeline that changes. But why, and how can I change that behaviour?

**Comment by helgasoft** [comment]
```formatter = '{a}'   ## htmlwidgets::JS("function(params){console.log(params);}")```
will give you the _name_ of the serie which is the date, as explained [here](https://echarts.apache.org/en/option.html#tooltip.formatter).
Does this answer your question?

**Comment by svenb78** [comment]
No, unfortunately. 

Following the documentation, I tried `{a}`, `{b}` and so an. But I cannot see any difference. No matter what I use, the scatter-tooltip looks like that: 

![tooltip_b](https://user-images.githubusercontent.com/86719356/190575511-ca806203-badc-4010-ae25-84bc0347e586.jpg)

Indeed, the timeline-tooltip looks like I want. But: The tooltip I would prefer for the points within the scatter plot is like that: 
 
![tooltip_preferred](https://user-images.githubusercontent.com/86719356/190576840-1fb737c7-cb90-401c-aeda-a2e96c6945a3.jpg)

And that tooltip I get using `formatter = htmlwidgets::JS("function(params){return('delta rel: ' + params.value[0] + '<br> ' + 'delta abs: ' + params.value[1] );}")`.

One can reproduce the issue using the example [here](https://echarts4r.john-coene.com/articles/tooltip.html): 

```
mtcars |>
  e_charts(wt) |>
  e_scatter(mpg, qsec) |>
  e_tooltip(formatter = htmlwidgets::JS("function(params){return('wt: ' + params.value[0] + '<br />mpg: ' + params.value[1])}")
  )
```

Modify the example to 

``` 
mtcars |>
  group_by(cyl) |>
  e_charts(wt, timeline = TRUE) |>
  e_scatter(mpg, qsec) |>
  e_tooltip(formatter = htmlwidgets::JS("function(params){return('wt: ' + params.value[0] + '<br />mpg: ' + params.value[1])}")
  )
```
, and by hovering over the timeline you will see that the timeline tooltip looks strange. 

![tooltip_strange](https://user-images.githubusercontent.com/86719356/190577610-bfd6b683-a814-4827-a365-866fe218e2c7.jpg)


However: THANKS FOR HELPING! :-)

**Comment by helgasoft** [comment]
ok, looks like the question is how to have correct tooltips on **both** timeline and series.
ECharts has two tooltip formatters - [general](https://echarts.apache.org/en/option.html#tooltip.formatter) and [series](https://echarts.apache.org/en/option.html#series-scatter.tooltip.formatter).
Setting the _general_ will apply to both timeline and series tooltips, thus the discrepancy. 
I think the solution is to leave the timeline alone and set tooltip only for _series_:
```r
plot_e <- tmp01 %>%
	dplyr::ungroup() %>%
	dplyr::group_by(datum) %>%
	echarts4r::e_charts(x = visits_delta_rel, timeline = TRUE) %>%
	echarts4r::e_scatter(
		serie = visits_delta_abs
		, bind = var_col
		, symbol_size = 20
		, label = list(show = TRUE, formatter = "{b}", rotate = 30, position = "top")
		, colorBy = "series"
		,tooltip= list(formatter= htmlwidgets::JS("function(params){return('delta rel: ' + params.value[0] + '<br> ' + 'delta abs: ' + params.value[1] );}"))
	) %>%
	echarts4r::e_tooltip(
		trigger = "item"
		, axisPointer = list(type = "cross")
	) %>%
	echarts4r::e_legend(show = FALSE) %>%
	echarts4r::e_y_axis(
		name = "Absoulte Veränderung Vormonat"
		, position = "left"
		, nameRotate = 90
		, nameLocation = "middle"
		, nameTextStyle = list(align = "middle", padding = 50, fontSize = 16, fontWeight = "bold")
	) %>%
	echarts4r::e_x_axis(
		name = "Relative Veränderung Vormonat"
		, nameLocation = "middle"
		, nameTextStyle = list(align = "middle", padding = 20, fontSize = 16, fontWeight = "bold")
	) %>%
	echarts4r::e_add_nested("itemStyle", color) %>%
	echarts4r::e_timeline_opts(
		top = 0
	)
plot_e
```
![image](https://user-images.githubusercontent.com/13038071/190693209-630f5c3d-460b-464c-8702-eb999e064bd3.png)

**Comment by svenb78** [comment]
Magic! :-) 

Thank you.
