### ISSUE TITLE
How to change color, border, border-width?

### ISSUE THREAD

**Issue by ravinder387** [JohnCoene/echarts4r#463]
df |>
e_chart() |>
  e_histogram(Age)

**Comment by helgasoft** [comment]
It's all in the [ECharts documentation](https://echarts.apache.org/en/option.html#series-bar.itemStyle.borderColor)
```r
mtcars |>
	e_charts() |>
	e_histogram(mpg, name = "histogram", colorBy='data', itemStyle= list(borderWidth=3, borderColor='red'))
```
![image](https://user-images.githubusercontent.com/13038071/192855449-35ccca95-2538-4957-9f27-e39ea20f0573.png)

**Comment by ravinder387** [comment]
thnks
