### ISSUE TITLE
Issues w/ Background Color

### ISSUE THREAD

**Issue by versipellis** [JohnCoene/echarts4r#47]
Here's an interesting one I'm finding but not really sure of the root cause yet.

```
mtcars %>%
  e_charts(cyl) %>%
  e_bar(mpg) %>%
  e_theme("westeros") %>%
  e_toolbox_feature(feature = "saveAsImage") %>%
  e_color(background = "red")
```

It appears that `e_color` doesn't properly apply the background colors, even without `e_theme`. What's more, using the "save as image" button saves a png with alpha transparency for the white background. However, if you set `e_theme("dark")`, the background correctly changes to black, including when using "save as image".

My initial gut feeling here says that it's something to do with how it prints to the RStudio Viewer, which is then transferred to `htmlwidgets::saveWidget()`. Given `htmlwidgets` various issues, I'm almost wondering if an `echarts4r` function to export the plots to html/svg directly would be a good enhancement - I've come across other `saveWidget()` issues when using `renderer="svg"`.

**Comment by JohnCoene** [comment]
The problem of the background not being applied was just a bug I stupidly inserted as I integrated the timeline component, sorry about that, and thanks for reporting it.

```r
mtcars %>% 
  e_charts(drat) %>% 
  e_line(mpg) %>% 
  e_area(qsec) %>% 
  e_color(
    c("red", "blue"),
    "#d3d3d3"
  ) %>% 
    e_toolbox_feature("saveAsImage")
```

It should be working now. It also keeps the background colour on the saved image for me.

**Comment by versipellis** [comment]
No problem! Pulling down the Github version now and going to test.

**Comment by versipellis** [comment]
Background color applies correctly, hurrah! (ditto with saving when background color is explicitly specified)

May I suggest an improvement by setting the default background color to white rather than null? I noticed that if your theme does not explicitly set a background color (i.e. `westeros` vs `dark`), it still saves with an alpha transparency background, which might be confusing as its not the expected behavior :)

**Comment by JohnCoene** [comment]
I'm not sure it is a good idea to set the background color as, using themes or not, the transparent background makes it blend in whatever document or Shiny app you use.

**Comment by versipellis** [comment]
That's fair. There isn't really a good way (without changing the JS package itself) to set the background to white before rendering, either. I'm closing this issue in the meantime since the original issue is resolved :)
