### ISSUE TITLE
Wrapping text in e_tooltip

### ISSUE THREAD

**Issue by svenb78** [JohnCoene/echarts4r#471]
Hi, 

it's me again. :-) 

Given the following example: 

```
library("dplyr")
library("echarts4r")

df <- data.frame(
  label = c(
    "This is a long label which should be wrapped for displaying"
    , "This is another label even longer which also should be wrapped"
  )
  , values = c(10, 40)
) %>%
  mutate(wrapped_label = stringr::str_wrap(label, 10))

plot_e <- df %>%
  e_charts(x = wrapped_label) %>%
  e_pie(serie = values) %>%
  e_legend(show = FALSE) %>%
  e_tooltip(trigger = "item")

plot_e
```

How can I wrap the text within the tooltip? Following the [apache docu](https://echarts.apache.org/en/option.html#tooltip), I tried `textStyle = list(width = 2, overflow = "break")` but that did not work.

**Comment by rdatasculptor** [comment]
I haven't run your example yet (I must admit)  but what exactly should the result be, what should the text be doing?

Does it help to use \n in the text perhaps? Something like this: "This is another label\neven longer which\nalso should be wrapped"

**Comment by helgasoft** [comment]
Solution is to use these two together or alone in **tooltip**:
```extraCssText= 'white-space:pre-wrap;', confine= TRUE```
