### ISSUE TITLE
e_mark_point not working

### ISSUE THREAD

**Issue by mabuimo** [JohnCoene/echarts4r#473]
Thank you for your work on this awesome R package.

I do not get the e_mark_point 's using this syntax:
```
multiplier_tbl %>% 
   filter(date > "2000-01-01") %>% 
    e_charts(date) %>% 
    e_line(multiplier_wld_bin5, symbol = "none", name = "multiplier") %>% 
    e_mark_point("multiplier_wld_bin5", data = list(type = "min")) %>% 
    e_mark_point("multiplier_wld_bin5", data = list(type = "max"))
```
![image](https://user-images.githubusercontent.com/20048041/194727056-fd595eff-8133-4eef-860f-70c9efab2903.png)

On a different note, how could I change the number of years shown in the x-axis, and/or make sure that the last year, 2020, is shown?
Thank you.

**Comment by rdatasculptor** [comment]
Hi @mabuimo, can you add the data frame you used? Then it is easier for me to track the error. Thanks!

**Comment by munoztd0** [comment]
Close because of inactivity
