### ISSUE TITLE
e_labels comma in big numbers bar chart

### ISSUE THREAD

**Issue by oobd** [JohnCoene/echarts4r#480]
I have the following bar chart 

```r
iris %>%
  mutate(Petal.Length = Petal.Length * 1000) %>% 
  group_by(Species) %>% 
  summarise(Petal.Length = sum(Petal.Length)) %>% 
  e_charts(Species) %>%
  e_bar(Petal.Length) %>% 
  e_tooltip('axis') %>%
  e_flip_coords() %>%
  e_hide_grid_lines() %>%
  e_labels(position = 'right', fontSize = 10, offset = c(0, 0.5),
           formatter = "{c}")

```

![image](https://user-images.githubusercontent.com/115593238/197716480-afa3b07b-44cc-4eaa-a986-31efbdc1515d.png)

It gives me a label like that at the end but I want to get rid of the ,species part and make the numbers have a comma separator so label would just be 277,600

How would I got about doing that? 
Sorry if really basic, I did try to look at past issues on github and found a similar one but it seemed to break down when I flipped the coordinates. 

Thanks!

**Comment by rdatasculptor** [comment]
@oobd  Not yet a comma seperator in the number itself, but at least you can get rid of the species name this way:

```
iris %>%
  mutate(Petal.Length = Petal.Length * 1000) %>% 
  group_by(Species) %>% 
  summarise(Petal.Length = sum(Petal.Length)) %>% mutate(label = Petal.Length) %>%
  e_charts(Species) %>%
  e_bar(Petal.Length, bind = label, label = list(show = TRUE, formatter = "{b}", position = "right")) %>% 
  e_tooltip('axis') %>%
  e_flip_coords() %>%
  e_hide_grid_lines()
```

**Comment by JohnCoene** [comment]
You can try this.

```r
```
