### ISSUE TITLE
Struggling with the order of heatmap axes

### ISSUE THREAD

**Issue by avenn98** [JohnCoene/echarts4r#484]
Hello! I'm having difficulties with getting my heat map axes to order properly. I've tried arranging the data, and setting reorder = FALSE, but only one axis will be ordered properly: either the y-axis is in proper numeric order (1 - 24), or the x-axis is ordered properly (day of week, ordered factor), but never both. 
<img width="508" alt="image" src="https://user-images.githubusercontent.com/118836272/203360602-a13b8669-673d-4770-80c7-1d2625a18b20.png">
<img width="508" alt="image" src="https://user-images.githubusercontent.com/118836272/203360745-92c4feb8-85b3-4efe-9b40-0a1f55156129.png">

Here is my code:
```
heatmap_df <- df %>% group_by(hour_of_day, day_of_week) %>% 
  summarise(jobs = n()) %>% 
  dplyr::ungroup() %>% 
  arrange(day_of_week) 
#arrange by day_of_week provides the correct x-axis, arrange by hour_of_day provides the correct y-axis

 
 heatmap_df |>
   e_charts(day_of_week, reorder = FALSE) |> 
   e_heatmap(hour_of_day, jobs) |> 
   e_visual_map(jobs) |> 
   e_title(text = "Heatmap of Successful API Requests by Day and Hour",
           subtext = "24 hour clock") %>% 
   e_tooltip(trigger = "item") 
```

**Comment by kanahia** [comment]
Hi @avenn98, could you kindly share how you managed to reorder x axis based on factor levels?
I read in the manual one can reorder yaxis by echarts4r::e_y_axis(inverse = TRUE) but I am struggling to order x axis according to my factors levels. Any help is appreciated, thanks!
