### ISSUE TITLE
How to loop through a vector to add a variable number of e_bar

### ISSUE THREAD

**Issue by avenn98** [JohnCoene/echarts4r#485]
I am creating a visual that will add a stacked bar for every column (except the first, which is the x-axis) of a dataframe. However, the number of columns will change, so I wanted to write some sort of loop that would run e_bar for every column df[,2:length(df)]. However, echarts doesn't seem to like any of the options I've tried, giving an error that says it cannot subset columns that do not exist. 
```
library(echarts4r)
library(dplyr)

#Creating data
set.seed(1234)

random <- data.frame(round(runif(50, 1, 50), 0))

names(random) <- "value"

#random$job <- rep(c("1", "2", "3", "4", "5"), 10)

random$job <- round(runif(50, 1, 5), 0)

random$date <- as.Date(rep(c('2022-01-01', '2022-01-02', '2022-01-03', 
                           '2022-01-04', '2022-01-05', '2022-01-06', 
                           '2022-01-07', '2022-01-08', 
                           '2022-01-09', '2022-01-10'), 5))

random <- random %>% 
  group_by(job, date) %>% 
  summarise(value = sum(value)) %>% 
  ungroup() %>% 
  spread(job, value)

#Creating base echart

e <- random |>
  e_charts(x = date) %>% 
  e_datazoom(
    type = "slider", 
    toolbox = FALSE,
    bottom = -5
  ) %>% 
  e_title("Jobs by Day") %>% 
  e_x_axis(date, axisPointer = list(show = TRUE)) %>% 
  e_tooltip(trigger = "item") 

#Attempt at a loop
for (i in seq_along(df)){
  e |>
    e_bar(i, stack = "grp")
}

```

<img width="339" alt="image" src="https://user-images.githubusercontent.com/118836272/203605823-56e5f6fa-906f-4b3a-97cf-58db3b5fd905.png">

**Comment by rdatasculptor** [comment]
What if you try `e  <-  e |> e_bar_(i, stack = "grp")`  inside the loop instead of `e |>  e_bar(i, stack = "grp")`?
If that doesn't help, I will try to come with a solution tomorrow. I think I had this same issue before.

**Comment by avenn98** [comment]
@rdatasculptor That did not fix it for me :/ Sorry. But thank you!

**Comment by JohnCoene** [comment]
It's unclear what you are trying to do, and why you loop over the columns.What @rdatasculptor suggests is correct

**Comment by avenn98** [comment]
@JohnCoene I'm sorry, I'm trying to make a stacked bar chart. Like this (made with ggplot)
<img width="626" alt="image" src="https://user-images.githubusercontent.com/118836272/204011897-db8b239b-e34e-475d-8d8a-a229da326aee.png">
I thought, to do this with echarts, you needed an e_bar() statement for each group. But the number of groups isn't always the same, so I can't just make stagnant code for 6 bars or whatever. I made the change rdatasculptor selected but the error didn't change.

**Comment by JohnCoene** [comment]
Because you `spread` your data (wide) when echarts4r expects tidy data (long), see [grouping](https://echarts4r.john-coene.com/articles/advanced.html#grouping).

Don't loop

```r
# change `grp` to your variable
e <- random |>
  group_by(grp) %>%
  e_charts(x = date) %>% 
  e_datazoom(
    type = "slider", 
    toolbox = FALSE,
    bottom = -5
  ) %>% 
  e_title("Jobs by Day") %>% 
  e_x_axis(date, axisPointer = list(show = TRUE)) %>% 
  e_tooltip(trigger = "item") %>%
  e_bar(grp, stack = "grp")
```

**Comment by avenn98** [comment]
Well, I certainly like that idea a lot more than looping! It gave me this though.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/118836272/204029604-2fdc11b1-97db-4edc-a81e-8dcace742ffc.png">
I used the code you gave, just changing "grp" into the actual name of the grouping variable (job). Am I missing a step?

**Comment by rdatasculptor** [comment]
Peculiar. Can you post your exact code @avenn98?

**Comment by rdatasculptor** [comment]
@avenn98 Ah yes, I see what you mean.

I guess @JohnCoene will have better ideas about how to do this because the legend doesn't inherit the colors of the jobs now, but you can use your initial idea to make the stacked bars properly. Please take a look:

```
library(echarts4r)
library(dplyr)
library(tidyr)

#Creating data
set.seed(1234)

random <- data.frame(round(runif(50, 1, 50), 0))

names(random) <- "value"

#random$job <- rep(c("1", "2", "3", "4", "5"), 10)

random$job <- round(runif(50, 1, 5), 0)

random$date <- as.Date(rep(c('2022-01-01', '2022-01-02', '2022-01-03', 
                             '2022-01-04', '2022-01-05', '2022-01-06', 
                             '2022-01-07', '2022-01-08', 
                             '2022-01-09', '2022-01-10'), 5))

random <- random %>% 
  group_by(job, date) %>% 
  summarise(value = sum(value)) %>% 
  ungroup() %>% 
  spread(job, value)

e <- random |>
  e_charts(x = date) %>% 
  e_datazoom(
    type = "slider", 
    toolbox = FALSE,
    bottom = -5
  ) %>% 
  e_title("Jobs by Day") %>% 
  e_x_axis(date, axisPointer = list(show = TRUE)) %>% 
  e_tooltip(trigger = "item")

for (i in 2:length(random)){
  e <- e |>
    e_bar_(i, stack = "grp")
}

```

**Comment by avenn98** [comment]
@rdatasculptor It's the same thing we're trying to do now with the stacked bar chart! It's a different dataset, so it does look like it's cumulative, but it isn't. It's just a geom_bar with position="stack" and stat="identity".

Thank you! That's definitely really close, I just need to figure out how to get the colors to show up. I appreciate the help!

**Comment by avenn98** [comment]
@JohnCoene I have an email that you responded asking for the exact code of the funky graph, but I'm not seeing it in the thread, so idk what happened. But here's the exact, replicable code that made the strange chart:

```
library(echarts4r)
library(dplyr)

#Creating data
set.seed(1234)

random <- data.frame(round(runif(50, 1, 50), 0))

names(random) <- "value"

random$job <- round(runif(50, 1, 5), 0)

random$date <- as.Date(rep(c('2022-01-01', '2022-01-02', '2022-01-03', 
                           '2022-01-04', '2022-01-05', '2022-01-06', 
                           '2022-01-07', '2022-01-08', 
                           '2022-01-09', '2022-01-10'), 5))

random <- random %>% 
  group_by(job, date) %>% 
  summarise(value = sum(value)) %>% 
  ungroup()

random |>
  group_by(job) %>%
  e_charts(x = date) %>% 
  e_datazoom(
    type = "slider", 
    toolbox = FALSE,
    bottom = -5
  ) %>% 
  e_title("Jobs by Day") %>% 
  e_x_axis(date, axisPointer = list(show = TRUE)) %>% 
  e_tooltip(trigger = "axis") %>%
  e_bar(value, stack = "grp")

```

**Comment by helgasoft** [comment]
@avenn98, if you don't mind having **xAxis** as _category_ instead of _time_ :
```r
library(echarts4r)
library(dplyr)

#Creating data
set.seed(1234)
random <- data.frame(value= round(runif(50, 1, 50), 0),
	job= round(runif(50, 1, 5), 0),
	date= as.Date(rep(c('2022-01-01', '2022-01-02', '2022-01-03', 
			'2022-01-04', '2022-01-05', '2022-01-06', 
			'2022-01-07', '2022-01-08', '2022-01-09', '2022-01-10'), 5))
)
df <- random |>  
	group_by(job, date) |> 
	summarise(value = sum(value)) |>
	ungroup() |> group_by(job) |> arrange(date)

df |>
	e_charts(x = date) |>
	e_bar(serie= value, stack= "grp") |>
	e_datazoom(type= "slider", toolbox = FALSE, bottom = -5) |> 
	e_title("Jobs by Day") |>
	e_x_axis(date, axisPointer= list(show= TRUE), 
		type='category', axisLabel= list(rotate=45)) |> 
	e_tooltip(trigger = "item")
```
![image](https://user-images.githubusercontent.com/13038071/204378425-f66a5a73-ad66-4bfc-906f-deb885280f88.png)

**Comment by avenn98** [comment]
@helgasoft thank you!! That worked perfectly

**Comment by rdatasculptor** [comment]
@helgasoft! Well done! @avenn98 you can close the issue now I guess

**Comment by JohnCoene** [comment]
I get the same issue using the JavaScript library without going through the R package. It's something with the time axis.
