### ISSUE TITLE
Ambiguity and missing selection in `.build_data` and `.build_data2`

### ISSUE THREAD

**Issue by fenguoerbian** [JohnCoene/echarts4r#486]
Currently, `.build_data` and `.build_data2` are designed as

```
.build_data <- function(e, ...) {
  data <- e$x$data[[1]] |>
    dplyr::select(...)
  
 # remaining script
}
```

and

```
.build_data2 <- function(data, ...) {
  row.names(data) <- NULL
  data <- data |>
    dplyr::select(...)
```

There are some flaws in this `dplyr::select(...)` design:

First is the ambiguity in its usage. For example, they can be called, like from this line in [`e_scatter_3d`](https://github.com/JohnCoene/echarts4r/blob/ab1f5e29a59b88301a962393ed5d4df4f2cf2d46/R/add_.R#L1775), with the form

```
data <- .build_data2(e$x$data[[i]], e$x$mapping$x, y, z, color, size)
```

and `color`, `size` are just character variables storing the name of corresponding columns in `e$x$data[[i]]`. (By the way I think here this usage is not what have been tested in [test-build_data2.R](tests/testthat/test-build_data2.R), multiple parameters are supplied, not a vector of variables.)

Then this type of use causes the _selection ambiguity_ described in [this post of tidyselect](https://tidyselect.r-lib.org/reference/faq-external-vector.html).

Specificly, let's assume `color` stores the character `"my_color"`, but the data contains both columns `"color"` and `"my_color"`, then this call of `.build_data2` will select the column `color`， instead of `my_color`. This can be shown in the following example

```
library(echarts4r)

test_dat <- iris[1 : 5, ]
test_dat$a <- 1 : 5
test_dat$color <- (1 : 5) * 10

p <- test_dat |>
    e_charts(x = Sepal.Length) |>
    e_scatter_3d(
        y = Sepal.Width, 
        z = Petal.Length,
        color = a,
        size = Petal.Width
    )

p$x$opts$series
```

Here in `e_scatter_3d` we set `color = a`, which ranges from 1 to 5 in `test_dat`. But unfortunately the resulting data picks the `color` column in `test_dat`.

Another problem is that `dplyr::select` will only pick the column once even if its stated multiple times in `...`. So a script like

```
p <- test_dat |>
    e_charts(x = Sepal.Length) |>
    e_scatter_3d(
        y = Sepal.Width, 
        z = Petal.Length,
        color = Petal.Width,
        size = Petal.Width
    )

p$x$opts$series
```

with `color` and `size` both set to use `Petal.Width` will not work. And I believe this is causing #474 .

If the calls of `.build_data` and `.build_data2` in this package all takes the same routine as passing character variables storing the column names, then I suggest replacing

```
  data <- data |>
    dplyr::select(...)
```

with

```
data <- data[, c(...), drop = FALSE]
```

as a simple fix for both of these two problems. But then some testing and validation is necessary and I believe there are multiple instances of `dplyr::select(...)` in [utils.R](R/utils.R).

**Comment by JohnCoene** [comment]
Indeed!
