### ISSUE TITLE
Help in replicating the graphic-label-overlay 

### ISSUE THREAD

**Issue by ambarja** [JohnCoene/echarts4r#489]
Someone could I help me in replicate this example with echarsts4r ? 

![image](https://user-images.githubusercontent.com/23284899/204170401-abeb9d6e-dc02-41b4-a4f1-41a6f6771751.png)
I recently I have seen  in the website of echarts this [example](https://echarts.apache.org/examples/en/editor.html?c=graph-label-overlap).
Thanks

**Comment by rdatasculptor** [comment]
@ambarja Do you have example data for this chart? Help is easier if you have a data file that you want to turn into this graph. Thanks!

**Comment by rdatasculptor** [comment]
@ambarja thanks! Actually I meant an R file or list. For me it costs a little bit of work to turn it all in R objects :). You can take a look [here](https://echarts4r.john-coene.com/articles/graph.html)  for object structures as they are needed in echarts4r.(nodes and edges).
