### ISSUE TITLE
Pass group variables without using dplyr

### ISSUE THREAD

**Issue by AdrianAntico** [JohnCoene/echarts4r#496]
Is there a way to pass group variables to e_scatter_ with timeline=T without using a dplyr::group_by to pass data?

**Comment by JohnCoene** [comment]
No there is not, why do you want to do differently?

**Comment by AdrianAntico** [comment]
As a package creator myself, I try do my best to limit outside dependencies and dplyr is a big one, coming with a ton of other dependencies. Aside from that, data.table is almost always a better option, if you have to go there. 

Their only dependency is the bit64 package, it's a faster processing engine, and it uses less memory for the same data set sizes and characteristics. dplyr has had backwards compatibility issues where data.table does not, which could mean less maintenance from your end. 

Lastly, I think you can add a parameter that simply requests the info supplied by group_by. It appears that the only thing different is that is contains some metadata about the unique levels from the group variables, which could easily be passed via a new parameter.


Great package nonetheless, I'm already a big fan.

**Comment by JohnCoene** [comment]
Yes, I appreciate that but {dplyr} is a hard dependency of the package anyway.
You could mimic group by (it's just an attribute or something like)

https://github.com/JohnCoene/echarts4r/blob/bddcb361fa983bab00fba0545c42d6de162e90d6/DESCRIPTION#L21
