### ISSUE TITLE
linear regression line?

### ISSUE THREAD

**Issue by smach** [JohnCoene/echarts4r#5]
One more question, if you know whether it's possible to draw a linear regression line on a chart, similar to these? [https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-anscombe-quartet](https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-anscombe-quartet) I see instructions on how to draw a line for average with e_mark_line at [http://echarts4r.john-coene.com/reference/mark.html](http://echarts4r.john-coene.com/reference/mark.html) but don't see how to turn that into e_mark_line() with a type of "MarkLineOpt". Thanks one more time.

**Comment by JohnCoene** [comment]
Interesting, I didn't know this could be done. I think the package should provide a helper function to draw regression lines, will add that. 

In the meantime, you can use it like so (ECharts native JS way):

```r
line <- list(
  list(
    coord = c(0, 0),
    symbol = 'none'
  ),
  list(
    coord = c(350, 18),
    symbol = 'none'
  )
)

USArrests %>% 
  e_charts(Assault) %>% 
  e_scatter(Murder, Rape) %>% 
  e_mark_line(data = line)
```

**Comment by JohnCoene** [comment]
Just pushed `e_lm` you can give it a spin, I will add other methods later on.

```r
# reinstall
devtools::install_github("JohnCoene/echarts4r")

mtcars %>% 
  e_charts(mpg) %>% 
  e_scatter(qsec) %>% 
  e_lm(qsec ~ mpg, name = "y = ax + b")
```

**Comment by smach** [comment]
Oh cool, thanks! Works with both your example and my data

**Comment by JohnCoene** [comment]
Added `e_glm` and `e_loess` :+1:
