### ISSUE TITLE
gridIndex for more than two charts

### ISSUE THREAD

**Issue by hnasko** [JohnCoene/echarts4r#50]
Probably the property `gridIndex` is the closest analog in the library of `facet_grid ` from `ggplot2` . For two charts grid works fine. But when there are appear more than two charts top charts just merge with each other. How it can be fixed?
```
df <- data.frame(
  weekDay = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
              "Sunday"),
  a = rnorm(7, 15, 3),
  b= rnorm(7, 10, 4),
  c = rnorm(7, 8, 5)
)

df %>%
  e_charts(weekDay) %>%
  e_bar(a) %>%
  e_bar(b, x_index = 1, y_index = 1) %>%
  e_bar(c, x_index = 2, y_index = 2) %>%
  e_grid(height = "20%") %>%
  e_grid(height = "20%", top = "35%") %>%
  e_grid(height = "20%", top = "65%") %>%
  e_tooltip(trigger = "axis") %>%
  e_legend(bottom = 1, textStyle = list(color = "#bdbdbd")) %>%
  e_title(text = toupper("Title")) %>%
  e_y_axis(gridIndex = 0) %>%
  e_x_axis(gridIndex = 0) %>%
  e_y_axis(gridIndex = 1) %>%
  e_x_axis(gridIndex = 1) %>%
  e_y_axis(gridIndex = 2) %>%
  e_x_axis(gridIndex = 2) %>%
  e_color(color = c("#00e5ff", "#33ff99", "#ff33b8"))
```

**Comment by JohnCoene** [comment]
The `gridIndex`, `x_index`, and `y_index`combined allow building something to ggplot2 facets. Though in `echarts4r` it is much more convoluted; I genuinely hope to improve that later on in order to have something that looks very much like `ggplot2`.

You are on the right track, you are only missing one thing. First you plot all three bar charts on their respective indices 👍. What you need to do then is put those indices against their respective "grids." 

```r
df <- data.frame(
    weekDay = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
                "Sunday"),
    a = rnorm(7, 15, 3),
    b= rnorm(7, 10, 4),
    c = rnorm(7, 8, 5)
)

df %>%
    e_charts(weekDay) %>%
    e_bar(a) %>%
    e_bar(b, x_index = 1, y_index = 1) %>%
    e_bar(c, x_index = 2, y_index = 2) %>%
    e_grid(height = "20%") %>%
    e_grid(height = "20%", top = "35%") %>%
    e_grid(height = "20%", top = "65%") %>%
    e_tooltip(trigger = "axis") %>%
    e_legend(bottom = 1, textStyle = list(color = "#bdbdbd")) %>%
    e_title(text = toupper("Title")) %>%
    e_y_axis(gridIndex = 0, index = 0) %>% # add the grids
    e_x_axis(gridIndex = 0, index = 0) %>%
    e_y_axis(gridIndex = 1, index = 1) %>%
    e_x_axis(gridIndex = 1, index = 1) %>%
    e_y_axis(gridIndex = 2, index = 2) %>%
    e_x_axis(gridIndex = 2, index = 2) %>%
    e_color(color = c("#00e5ff", "#33ff99", "#ff33b8"))
```

You did plot the graphs against their respective axis but all the axis were still on the same grid. I hope this helps!

**Comment by hnasko** [comment]
Thanks for your support. I didn't get that `gridIndex` should be used together with `index` .

**Comment by nvelden** [comment]
For some reason this does not work with timeline:

```
df <- data.frame(
    weekDay = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday",
                "Sunday"),
    a = rnorm(7, 15, 3),
    b= rnorm(7, 10, 4),
    c = rnorm(7, 8, 5)
) %>% group_by(weekDay)

df %>%
    e_charts(weekDay, timeline = TRUE) %>%
    e_bar(a) %>%
    e_bar(b, x_index = 1, y_index = 1) %>%
    e_bar(c, x_index = 2, y_index = 2) %>%
    e_grid(height = "20%") %>%
    e_grid(height = "20%", top = "35%") %>%
    e_grid(height = "20%", top = "65%") %>%
    e_tooltip(trigger = "axis") %>%
    e_legend(bottom = 1, textStyle = list(color = "#bdbdbd")) %>%
    e_title(text = toupper("Title")) %>%
    e_y_axis(gridIndex = 0, index = 0) %>% # add the grids
    e_x_axis(gridIndex = 0, index = 0) %>%
    e_y_axis(gridIndex = 1, index = 1) %>%
    e_x_axis(gridIndex = 1, index = 1) %>%
    e_y_axis(gridIndex = 2, index = 2) %>%
    e_x_axis(gridIndex = 2, index = 2) %>%
    e_color(color = c("#00e5ff", "#33ff99", "#ff33b8"))
```

![image](https://user-images.githubusercontent.com/45127542/143283832-be91fff5-23e2-4bb4-afbf-767ff40edf28.png)

**Comment by JohnCoene** [comment]
Honestly, I've sort of given up on the grid-stuff. Even the JavaScript API is too convoluted.

The reason I gave up though is that it's not really necessary since you can connect charts.

```r
e1 <- df |> 
  e_charts(weekDay, timeline = TRUE) |> 
  e_bar(a) |> 
  e_group("grp") |> 
  e_timeline_opts(show = FALSE)

e2 <- df |> 
  e_charts(weekDay, timeline = TRUE) |> 
  e_bar(a) |> 
  e_group("grp") |> 
  e_timeline_opts(show = FALSE)

e3 <- df |> 
  e_charts(weekDay, timeline = TRUE) |> 
  e_bar(a) |> 
  e_group("grp") |> 
  e_connect_group("grp")

e_arrange(e1, e2, e3, rows = 3)
```

Note `e_arrange` is just for convenience, you can use anything you want to layout the plot in Shiny or Rmarkdown, see [this vignette](https://echarts4r.john-coene.com/articles/connect.html)

**Comment by nvelden** [comment]
Can you use `e_arrange()` for more complex layouts like the one below?

![image](https://user-images.githubusercontent.com/45127542/143372840-940fd3fa-ba62-4459-acb6-5d739303f415.png)

**Comment by JohnCoene** [comment]
You don't need `e_arrange`, this is just a convenience function to run from console.

You can lay it out as above with simple tags/HTML. Are you in shiny or rmarkdown?

**Comment by nvelden** [comment]
Both 😀. I know how to do it. I really like the CSS flexbox framework for these tasks. I was just wondering if it would have been possible using `e_arrange()`.
