### ISSUE TITLE
Can't pass areaStyle to e_area()

### ISSUE THREAD

**Issue by gacolitti** [JohnCoene/echarts4r#501]
I can pass a lineStyle and itemStyle to `e_area()`, but `areaStyle` does not work.

For example:

```r
library(echarts4r)
data.frame(x = seq.int(1, 5, 1),
           y = 10) %>% 
  e_chart(x = x) %>% 
  e_area(
    serie = y,
    areaStyle = list(opacity = 0),
    lineStyle = list(opacity = 0),
    itemStyle = list(opacity = 0)
  )
```

Please see [this](https://stackoverflow.com/questions/75250996/how-to-change-area-style-with-echarts4re-area/75251232#75251232) stackoverflow.

**Comment by JohnCoene** [comment]
Yes, sorry, this is going to be overridden.

Use `e_line` with `areaStyle`.

(In echarts.js an area chart is essentially this: a line with `areaStyle`)

**Comment by gacolitti** [comment]
Yep, I should have thought of trying that. Thanks!

Here it is again with `e_line()`:

```r
library(echarts4r)
library(magrittr)

data.frame(x = seq.int(1, 5, 1),
           y = 10) %>% 
  e_chart(x = x) %>% 
  e_line(
    serie = y,
    areaStyle = list(opacity = 0),
    lineStyle = list(opacity = 0),
    itemStyle = list(opacity = 0)
  )
```

**Comment by rdatasculptor** [comment]
@gacolitti I think you can close the issue 🙂, thanks!
