### ISSUE TITLE
Opening and closing prices interchanged within the e_candle function

### ISSUE THREAD

**Issue by benj7** [JohnCoene/echarts4r#502]
I've noticed that the opening and closing prices are interchanged within the e_candle function. 

<img width="1197" alt="Capture d’écran 2023-01-29 à 18 31 32" src="https://user-images.githubusercontent.com/7905765/215344774-cdf34505-5694-4734-8f0f-c70d5197b636.png">

Thanks for the great package and all the stuff you've made for the R community :)

**Comment by JohnCoene** [comment]
Sorry about that! Should be fixed now.

**Comment by benj7** [comment]
No worries and thanks again for the great work!

**Comment by munoztd0** [comment]
Is it really though ?
