### ISSUE TITLE
e_datazoom: largest data point omitted at seemingly random zoom starting values (v0.4.4)

### ISSUE THREAD

**Issue by awcm0n** [JohnCoene/echarts4r#506]
It depends on the zoom starting value whether the data point with the largest x value is shown. The figure contains an illustration based on the following code:

```
library(echarts4r)
library(tidyverse)

df <- tibble(x = c(1, 2, 3, 4, 5),
             y = c(1, 2, 3, 4, 5),
             z = c(1, 2, 3, 4, 10))

df |> 
  e_charts(x) |>
  e_scatter(y, size = z) |>
  e_datazoom()
```
<img width="245" alt="e_datazoom" src="https://user-images.githubusercontent.com/29875025/224832981-cd2e15d2-ea56-4fcf-8feb-00d7b8efefc3.png">

**Comment by rdatasculptor** [comment]
I see what you mean. I guess it is a problem caused by something at the js side, not the R side. 

At least you can use a trick by picking a higher x axis maximum (e.g. 5%). This way the problem is not eminent anymore:

```
df |> 
  e_charts(x) |>
  e_scatter(y, size = z) |>
  e_datazoom() %>%
  e_x_axis(max = max(df$x) + (0.05 * max(df$x)))
```
Maybe not the cleanest solution, but does this help you?
