### ISSUE TITLE
Long label text exceeds edge in bar plot

### ISSUE THREAD

**Issue by pplanger** [JohnCoene/echarts4r#508]
Hey! 

I'm using echarts4r in our Shiny App. Since there is text in our graphs (horizontal bar charts), I noticed that the text for shorter bars goes over the edge. Below you can find an illustrative example:

`library(echarts4r) # charts
library(tidyverse) # general use
library(lubridate) # dates and times
library(prophet) # forecasting
library(nycflights13) # data

top_destinations <- flights %>% 
  count(dest) %>% 
  top_n(5, n) %>% 
  arrange(n)

top_destinations %>%
  e_charts(x = dest) %>%
  e_bar(n, legend = FALSE, name = "Flights") %>% 
  e_labels(position = "insideLeft", formatter = c("This is a long text which is only produced to exceed some bars."), fontSize = 20) %>% 
  e_tooltip() %>% 
  e_title("Flights by destination", "Top 5 destinations") %>% 
  e_flip_coords() %>% 
  e_y_axis(splitLine = list(show = FALSE)) %>% 
  e_x_axis(show = FALSE)`

![tempsnip](https://user-images.githubusercontent.com/126692514/226865773-fba94ee8-2568-4cc0-8991-d52d7bf9d057.png)

**Comment by rdatasculptor** [comment]
How would you wish the label to behave?

**Comment by rdatasculptor** [comment]
Im your case the font size would get really small. Maybe it's better to put a '\n' in the labels somewhere? You can make a script that counts the number of words. If the number exceeds a certain number, put a '\n' in the text. Could this be something? I can make an example of what I mean later this evening.

**Comment by pplanger** [comment]
This might also be an option. But couldn't it be that the font size is then too large in terms of the height of the font (i.e. width of the bars) rather than the length, if a line break is made within the bar? Also, the text in our Shiny App within each bar is usually not as long as in the example here. 

But of course I am very grateful about your help and would like to try it with the "\n".

**Comment by rdatasculptor** [comment]
something like this:

```
library(echarts4r) # charts
library(tidyverse) # general use
library(lubridate) # dates and times
library(prophet) # forecasting
library(nycflights13) # data

top_destinations <- flights %>%
  count(dest) %>%
  top_n(5, n) %>%
  arrange(n)

# breakpoint determines after which word in the label we will put the line break
labelbreaker <- function(x, breakpoint = 8){
  x <- unlist(strsplit(x, " "))
 if (length(x) > breakpoint){
   x[breakpoint] <- paste0( x[breakpoint], "\n")
 }
 x <- paste(x, collapse = " ")
 return(x)
}

top_destinations %>%
  e_charts(x = dest) %>%
  e_bar(n, legend = FALSE, name = "Flights") %>%
  e_labels(position = "insideLeft", formatter = labelbreaker(c("This is a long text which is only produced to exceed some bars."), breakpoint = 8), fontSize = 20) %>%
  e_tooltip() %>%
  e_title("Flights by destination", "Top 5 destinations") %>%
  e_flip_coords() %>%
  e_y_axis(splitLine = list(show = FALSE)) %>%
  e_x_axis(show = FALSE)
```

**Comment by pplanger** [comment]
First of all, thank you very much!

I tried it today, but unfortunately the text in the bar is then too large in height and crosses the edges at the top and bottom instead of the right. So, I think the issue can only be solved by automatically adjusting font sizes.
