### ISSUE TITLE
Is there a way to convert the R code back to JS?

### ISSUE THREAD

**Issue by lillianlu-nz** [JohnCoene/echarts4r#510]
Hi there,

I'm an R user and love the echarts4r package. However, I was recently asked whether I can provide the code in JS so the graph can be embedded on our website easily. I don't know much JavaScript so it'd be difficult to write it from scratch. 

Is there a way/function to convert what I've created in R into the code like this: https://echarts.apache.org/examples/en/editor.html?c=area-basic

I imagine it'd be similar to running the shiny widgets in RStudio console to get the HTML code output.

 I tried the jsonlite package but it didn't work. No luck with Chat GPT too...

Thank you so much!

**Comment by JohnCoene** [comment]
You can retrieve the JSON

https://echarts4r.john-coene.com/reference/echartsnjson?q=Json#null

Let me know if that worked

**Comment by lillianlu-nz** [comment]
Thank you for your prompt response! It worked well. It adds quotation marks to all the properties though, so I did some wrangling to get rid of them.

`  # Convert R code to JSON
  json <- plot |>
    e_inspect(
      json = TRUE,
      pretty = TRUE
    )
  
  # Get rid of "" around properties
  json_output <- gsub('"(\\w+)"\\s*:', '\\1:', json)
  
  # Get rid of "" around formatter functions
  json_output <- gsub('"(?=.*function)|(?<=;})"', '', json_output, perl = TRUE)`

**Comment by JohnCoene** [comment]
Technically JSON should have these, you can leave them in its valid
