### ISSUE TITLE
e_tooltip formatter recognising strings like label formatter

### ISSUE THREAD

**Issue by Mkranj** [JohnCoene/echarts4r#515]
When making a bar chart, I can use code like the following: 
```
e_bar(y,
              label = list(show = T,
                           formatter = "{@y}%",
                           position = "top")
)
```
And the value I want will be printed exactly how I want it.
However, in e_tooltip, passing a string to the formatter option doesn't seem to do anything. I've tried passing Javascript code, but I'm never sure what variables I'm dealing with, for example, if my chart includes multiple calls to e_bar, e_area and such.
Can a simple string based formatter be implemented for tooltips? The text on hover is surprisingly non-customiseable compared to most other things in the package. The amount of options present for most things is why I've started using it in the first place :)

**Comment by munoztd0** [comment]
We are sorry but we not going to implement a simple string based formatter for now.

But don't hesitate to ask question on how to create integrate your javascript code..
