### ISSUE TITLE
Can't seem to modify Axis Labels (visible tick values) 

### ISSUE THREAD

**Issue by DeepanshKhurana** [JohnCoene/echarts4r#518]
Hello 👋🏼 

I have a plot that is based on currencies. I have a custom function to shorten prices based on Indian denominations. All I'm trying to do is achieve something similar to what is shown in the eCharts Documentation [here](https://echarts.apache.org/en/option.html#yAxis.axisLabel.formatter).

```
// Use string template; template variable is the default label of axis {value}
formatter: '{value} kg'
// Use callback.
formatter: function (value, index) {
    return value + 'kg';
}
```

But I cannot seem to plug it in correctly (or maybe it is not supported).

- `e_axis_labels` seems to be a separate functionality to only add x- and y-axis labels such as "distance" or "speed".
- `e_y_axis` and `e_y_axis_` do not seem to allow for these parameters in the formatted
  - I am aware there is a currency formatter, but the Indian system of currencies is different and follows separate locations for commas. This is not included even if I set `currency = "INR"` as a param in the formatter
  - _**Please check my newest comment for an update on the comma problem, using `locale` solves it, but there is still a need to be able to wrap the values in a function to display them.**_

For reference, here is a [gist](https://gist.github.com/DeepanshKhurana/fa917b5b881cd57cef65bcb8cbd15668) with the function I'm hoping to use.

Assuming there are two columns, `Account` and `Balance`, where `Balance` is numeric, I can simply create a bar chart using the following snippet.

```
data |>
  e_charts(Account) |>
  e_bar(Balance)
```

_Note: The values are random here_

<img width="729" alt="Screenshot 2023-04-22 at 1 25 50 PM" src="https://user-images.githubusercontent.com/26517718/233770963-dcb5c5b7-c3de-4d64-8c4f-648d947615cb.png">

The behaviour I am talking about is to be able to apply any function on the y-axis labels to display.

Something akin to the following,

```
data |>
  e_charts(Account) |>
  e_bar(Balance) |>
  e_y_axis_labels(shorten_price(Balance))
```

which would give me a plot where the y-axis is processed (the screenshot below is edited with Photoshop for illustration)

<img width="729" alt="Screenshot 2023-04-22 at 1 30 09 PM" src="https://user-images.githubusercontent.com/26517718/233771251-5cbcaa0c-2398-4139-a3ad-47d1f1e2b7c6.png">

Is something like this possible or in the pipeline?

**Comment by DeepanshKhurana** [comment]
I think I missed checking the `locale` parameter. Part of my problem gets solved here, since the commas are visible now! 

```
data |>
  e_charts(Account) |>
  e_bar(Balance) |>
  e_y_axis(
          formatter = e_axis_formatter(
            style = "currency",
            currency = "INR",
            local = "en-IN")
  )

```

However, it would still be really neat just to be able to modify the tick labels however we want, especially using a wrapper function.

**Comment by sactyr** [comment]
Hope this is what you're after @DeepanshKhurana. I have added JS wrapper function (there is probably a better way to write this wrapper function, my JS knowledge is very limited).
```
set.seed(123)

df <- data.frame(
  Account = LETTERS[1:6]
  ,Balance = rnorm(6, mean = 1000000, sd = 500000)
)


shorten_currency <- 'function (value) {

val = Math.round(value)/10000

val = val + "L"

return val

}'


df %>% 
  e_charts(Account) %>% 
  e_bar(Balance) %>% 
  e_y_axis(
    axisLabel = list(
      show = TRUE
      ,formatter = htmlwidgets::JS(shorten_currency)
    )
  )
  
```
![image](https://github.com/JohnCoene/echarts4r/assets/5043835/32ce12b5-9ddb-4f5a-b9d7-73c876c5b7bc)

**Comment by DeepanshKhurana** [comment]
@sactyr Thank you for this. This sets me up in a good direction. 💯
