### ISSUE TITLE
Multiple country-level map (but not at world map level)

### ISSUE THREAD

**Issue by lgnbhl** [JohnCoene/echarts4r#523]
Hello,
Would it be possible to create a country-level Europe map, but which doesn't render as a world map? For example creating a chloropleth map of Europe, but showing only European country shapes.

Following the reproductible example below, would it be possible to visualize only European countries? Another idea would be to zoom on Europe (but I don't know if it is possible to do this).

```r
choropleth <- data.frame(
  countries = c(
    "France",
    "Germany",
    "Spain",
    "Italy"
  ),
  values = round(runif(4, 10, 25))
)

choropleth |>
  e_charts(countries) |>
  e_map(values, map = "world") |> # would be cool to be able to choose "europe", "asia", "africa", etc.
  e_visual_map(min = 10, max = 25) 
  # adding here another function which zoom on Europe?
```
Thanks a lot!

**Comment by JohnCoene** [comment]
Hi Felix,

You can zoom in, as is done [here](https://echarts4r.john-coene.com/articles/brush.html#brush)

Or you can find and use a custom map as demonstrated [here](https://echarts4r.john-coene.com/articles/make-geo-json.html)

**Comment by JohnCoene** [comment]
I think [this](https://geojson-maps.ash.ms/) will let you download GeoJSON for Europe

**Comment by lgnbhl** [comment]
Thanks a lot John! I searched but was not able to find the code for zooming. It's perfect. Yes, using GeoJSON would be also a good option :).
Have a nice day,
Felix
