### ISSUE TITLE
echarts4r and shiny downloadHandler

### ISSUE THREAD

**Issue by svenb78** [JohnCoene/echarts4r#528]
Hi, 

some time ago, I made a shiny app which allows users to export plots -- made with ggplot2 -- into a Word document. I would like to use echarts graphs instead of ggplot, but I don't find a way to export them using a downloadHandler (--> check boxes). I found the  `e_toolbox_feature` and `saveAsImage` argument, but that is not what I'm looking for. 

Can someone help, e.g. with a minimal example for an _echarts4r_to_PPTX_ export function. :-)

**Comment by rdatasculptor** [comment]
Have you tried webshot? 
Take a look here for some inspiration https://gist.github.com/dantonnoriega/0744e7537076128ac4a026b8b7f38f09

**Comment by rdatasculptor** [comment]
I tried webshot myself, but no luck. So if we find a way to export echarts4r plots as an image (e.g. png), this would be most welcome!

**Comment by JohnCoene** [comment]
Echarts has a functionality for this, we can integrate.

**Comment by rdatasculptor** [comment]
Export as images programmatically? (I am aware of the save image feature). This would be brillant!

**Comment by JohnCoene** [comment]
Ah programmatically, missed that.

Rmarkdown does it, when you use an htmlwidget in a document rendered to PDF.

Maybe something to look at.

**Comment by JohnCoene** [comment]
You probably get a white image because of the [animation](https://echarts4r.john-coene.com/reference/e_animation.html).

Set `e_animation(show = FALSE)`

**Comment by munoztd0** [comment]
Yeah it's an issue form webshot [see here](https://www.ozturkibrahim.com/export-save-r-graphs-with-webshot/) 

Works well with webshot2 though, @svenb78 is it really impossible to get chrome from your environment ?

**Comment by rdatasculptor** [comment]
webshot2 works! At least for me it does. if it works for you as well  @svenb78, then we can close this issue.

**Comment by svenb78** [comment]
@rdatasculptor : I will check and talk to my admin.

**Comment by svenb78** [comment]
John's suggestion works and fits my needs. Many thanks for the help!

I will close the issue.

**Comment by JohnCoene** [comment]
We should probably document that somewhere, or even provide a wrapper around that download functionality
