### ISSUE TITLE
Control decimal and big numbers marks

### ISSUE THREAD

**Issue by artemklevtsov** [JohnCoene/echarts4r#53]
Hi,

How can I control big mark sign for the large numbers (like `big.mark` arg in the `prettyNum`)?

**Comment by artemklevtsov** [comment]
I found related issue: https://github.com/apache/incubator-echarts/issues/4180
But workaround should be applied on every axis and tooltip.

**Comment by JohnCoene** [comment]
I know this is not ideal. To reproduce the issue you reference in echarts4r you can do:

```r
library(echarts4r)

df %>% 
    e_charts(x) %>% 
    e_bar(y) %>% 
    e_y_axis(axisPointer = list(label = htmlwidgets::JS("function(a){return a.value.toFixed(2)}"))) %>% 
    e_tooltip(trigger = "axis",axisPointer = list(type = "cross"))
```

I'm unsure how to improve this aspect of the package, suggestions are welcome :)

**Comment by JohnCoene** [comment]
Hi Artem,

Thanks for that. I was thinking of implementing similar helpers. I think however it is better to provide them on their own (separately like column formatters in DT) rather than wrap them all in a single function, it might get confusing.

**Comment by JohnCoene** [comment]
Hi Artem,

Thanks again for this, really useful!

I've implemented the axis formatter, [here](https://github.com/JohnCoene/echarts4r/commit/8896675bff862b343af22e32dd39512116ee00c4)

`e_axis` takes a new argument `formatter` to which one passes the formatter. I've made the `locale` optional and is inferred from `Sys.getlocale()` and changed the default currency to USD. 

```r
library(echarts4r)

cars %>% 
  e_charts(speed) %>% 
  e_scatter(dist) %>% 
  e_y_axis(
    formatter = e_axis_formatter("currency")
  ) 
``` 

I've done something similar for the tooltips [here](https://github.com/JohnCoene/echarts4r/commit/f61e3726a9cf9cd9f46e842331dea92976944f91), however I cannot get them to work for some reason. There are errors in the JS or I use them wrongly.

```r
# does not work
cars %>% 
  dplyr::mutate(
    dist = dist / 25
  ) %>% 
  e_charts(speed) %>% 
  e_scatter(dist) %>% 
  e_tooltip(
    item_formatter = e_tooltip_item_formatter("percent")
  )
```

Let me know what you think.

**Comment by artemklevtsov** [comment]
Error in `e_tooltip_item_formatter` because:

```r
> cat(e_tooltip_item_formatter("percent"))
function(params, ticket, callback) {
        var fmt = new Intl.NumberFormat('LC', percent);
        return params.value[0] + '<br>' +
               params.marker + ' ' +
               params.seriesName + ': ' + fmt.format(parseFloat(params.value[1]));
    }
function(params, ticket, callback) {
        var fmt = new Intl.NumberFormat('LC', 0);
        return params.value[0] + '<br>' +
               params.marker + ' ' +
               params.seriesName + ': ' + fmt.format(parseFloat(params.value[1]));
    }
function(params, ticket, callback) {
        var fmt = new Intl.NumberFormat('LC', 0);
        return params.value[0] + '<br>' +
               params.marker + ' ' +
               params.seriesName + ': ' + fmt.format(parseFloat(params.value[1]));
    }
function(params, ticket, callback) {
        var fmt = new Intl.NumberFormat('LC', USD);
        return params.value[0] + '<br>' +
               params.marker + ' ' +
               params.seriesName + ': ' + fmt.format(parseFloat(params.value[1]));
    }
```

**Comment by artemklevtsov** [comment]
You should convert `opts` to JSON.

**Comment by artemklevtsov** [comment]
For the multiple series with different style we can pass opts as array (same length as series) and uses `parseFloat(params[i].value[1]).toLocaleString(styles[i], opts[i])`.

**Comment by JohnCoene** [comment]
Indeed works now, thanks Artem!

**Comment by JohnCoene** [comment]
I think it's all good now. I've also added your helpers to the documentation mentioning your contrinutions.

- [tooltips](https://echarts4r.john-coene.com/articles/tooltip.html)
- [grid](https://echarts4r.john-coene.com/articles/grid.html)

Let me know if this _does not_ work for you, otherwise I assume we can close this :)

Thanks again for all the work!

**Comment by artemklevtsov** [comment]
Seems `e_tooltip_item_formatter` not work for the pie chart.

**Comment by artemklevtsov** [comment]
Thank you. Last commit looks fine. Note you should import the `jsonlite` explicitly also.
