### ISSUE TITLE
POSIXct does not work with echarts4r

### ISSUE THREAD

**Issue by NilsToft** [JohnCoene/echarts4r#550]
After upgrading to latest Version of R (4.3.0) and echarts4r (0.4.4) POSIXct formatted time does not work:

library(tidyverse)
library(echarts4r)
td <- tibble(time=seq(from=as.POSIXct("2023-06-01 00:00:00"),by="day",length.out=24),val=runif(24),day=as.Date(time)) 

This produce a plot as expected:
td |>  e_chart(x=day) |> e_line(val)

This does not work:
td |> e_chart(x=time) |> e_line(val)

It gives the Error message:
Error in cl == "character" || cl == "factor" : 
  'length = 2' in coercion to 'logical(1)'

**Comment by JohnCoene** [comment]
You need the latest GitHub version. It will be on CRAN soon

**Comment by munoztd0** [comment]
closed with #548 , new version on CRAN
