### ISSUE TITLE
mouseout feature for Shiny

### ISSUE THREAD

**Issue by swsoyee** [JohnCoene/echarts4r#557]
Hi John, I notice that the [mouseout](https://echarts.apache.org/en/api.html#events.Mouse%20events.mouseout) are not support now.
There is only mouseover supported:
https://github.com/JohnCoene/echarts4r/blob/16a6fa12ad2a77246cacef38a955be5ec98e58a0/inst/htmlwidgets/echarts4r.js#L119-L123

Do you have any plan to implement this feature? 
Thank you!

**Comment by JohnCoene** [comment]
You should be able to implement it with `e_on`

https://echarts4r.john-coene.com/reference/callbacks

**Comment by swsoyee** [comment]
Thank you! I will have a try later.
