### ISSUE TITLE
How to put javascript function in json rendered by e_inspect()?

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#560]
Consider this chart:

```
USArrests |>
  e_charts(Assault) |>
  e_scatter(Murder) |>
  e_tooltip(formatter = htmlwidgets::JS("
          function(params){
            return('Assault: ' + params.value[0] + 
          '<br />Murder: ' + params.value[1])
          }
        ") )
```

The chart contains tooltips:

![image](https://github.com/JohnCoene/echarts4r/assets/16539796/c6b04ed8-9bc6-4e0e-98f3-a7779dc6aebc)

So what if I change the chart first in a json by using `e_inspect()` and change it back again to an echart by using `echarts_from_json()`? 
like this:

```
USArrests |>
  e_charts(Assault) |>
  e_scatter(Murder) |>
  e_tooltip(formatter = htmlwidgets::JS("
          function(params){
            return('Assault: ' + params.value[0] + 
          '<br />Murder: ' + params.value[1])
          }
        ") ) |> 
  e_inspect(json = TRUE) |>
  echarts_from_json()

```

this is the result:

![image](https://github.com/JohnCoene/echarts4r/assets/16539796/b7dca622-cd9f-4522-b98c-89bdc418f157)

Obviously the tooltip javascript function is not recogized anymore. 

Any ideas about how to deal with this? Is there  a way (in R) to store the javascript function of the tooltip in the json in such a way that it can retrieved properly after changing it back to an echart?

**Comment by rdatasculptor** [comment]
great work @munoztd0 !!! it works like a charm :) You solved this one really fast. Very cool.

Another (entirely different) issue is that the json doesn't contain the renderer parameter if you set it as "svg". Do you think that can be added to the json as well somehow? Maybe I will file another issue for that.

**Comment by munoztd0** [comment]
Can you please open a new issue for this

**Comment by rdatasculptor** [comment]
Take a look at what @helgasoft did: https://github.com/helgasoft/echarty/issues/3#issuecomment-1728137024
Very interesting approach. I will dig into this. Not sure yet if echarts4r can benefit from it.
