### ISSUE TITLE
Multiple label positions in e_pie chart

### ISSUE THREAD

**Issue by Mariaf1714** [JohnCoene/echarts4r#563]
Hallo,
Is it possible to display a part of the label (for example `formatter = "{c} %"`) using `position = "inside" `and another part of the label (`formatter = '{b}'`) with the `position = "outside"` in a **e_pie** chart? The names in {b} should not be displayed in a legend.

Thank you!

**Comment by rdatasculptor** [comment]
Hi @Mariaf1714 

You can use two equivalent e_pie charts with different label positions. 

Like this:

```
library(echarts4r)

df <- data.frame(name = c("this", "is", "an", "example"),
                 score1 = c(1, 2, 3, 4),
                 score2 = c(1, 2, 3, 4))

df |>
  e_charts(name) %>%
  e_pie(score1, 
        label = list(formatter = "{c} %",
                     position = "inside")) |>
  e_pie(score2, 
        label = list(formatter = '{b}'))
```

the result looks  like this:

![image](https://github.com/JohnCoene/echarts4r/assets/16539796/887f0f8e-3ff0-4763-9ecb-e99391c44286)

Is this the result you intended?
If yes, please clsoe the the issue, thanks!

**Comment by Mariaf1714** [comment]
This is exactly the result that I intended. Thank you!!

**Comment by Mariaf1714** [comment]
The code works. Thank you very much.
