### ISSUE TITLE
How to omit empty categorical group combinations

### ISSUE THREAD

**Issue by jzadra** [JohnCoene/echarts4r#575]
How can I adjust an echart so that if there is no data for a combination of x-axis category and grouping variable, the empty space is removed?

ie in the chart below, the group2/A combo and the group1/C combo have no data, so I would like for the space for them to be removed.  

Example:

```r
library(tidyverse)
library(echarts4r)
x <- rep(c("A", "B", "C"), each = 100)
y <- rep(c("group1", "group2"), each = 150)
z <- runif(300, max = 10)

df <- tibble(x, y, z)

df %>% 
  group_by(y) %>% 
  e_charts(x) %>% 
  e_bar(z)
```

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/NZyeS.png

I have seen a potential solution using a custom serie, but my actual use case has many bars and I'd prefer to have an automatic solution rather than having to specify the width of each individual bar.

While I'm doing this in R, I can translate Javascript solutions.

**Comment by rdatasculptor** [comment]
I think this question was quite similar: https://github.com/JohnCoene/echarts4r/issues/55. For me e_morph did the trick, but that won't be te solution for you. But maybe you can get some inspiration from it: https://github.com/JohnCoene/echarts4r/issues/551

**Comment by jzadra** [comment]
Why closed?

**Comment by jzadra** [comment]
#551 does not apply to my question.

**Comment by munoztd0** [comment]
Well tell us why it doesn't ?

**Comment by jzadra** [comment]
1) Both of the charts in #551 still show empty space where there are no values for one of the A/B groups in each x-axis category. 
2) I'm not doing a transition or timeline

**Comment by rdatasculptor** [comment]
@jzadra just curious, why is'nt removing empty bars using R before you render the echart a solution in your case?

**Comment by jzadra** [comment]
My example was created thinking I was going to do something differently, but then what I had worked for illustrative purposes so I just left it.

I"m not sure what you mean about removing the extra bars using R beforehand.  Echarts is allocating space for two bars in each letter group, despite the fact that there is no combination of group1/A and group2/C.  That isn't in the data, so there's nothign to remove.

**Comment by JohnCoene** [comment]
I don't think it's possible.

Also, I'm wondering if it is possible with other libraries (e.g.: ggplot2), this would make for an irregular grid which is supported in some libraries but is done to display areas more than bars.

Do you have an example in another library for us so that we can take a look?

**Comment by rdatasculptor** [comment]
@jzadra I think... that this is 90% of what you intended :). Completely different approach, but maybe you can use it for some inspiration:

```
library(echarts4r)
x <- rep(c("A", "B", "C"), each = 100)
y <- rep(c("group1", "group2"), each = 150)
z <- runif(300, max = 10) 

df <- tibble(x, y, z) %>%
  group_by(x, y) %>%
  filter(z == max(z)) %>% # pick the maximum z value per x y combination
  ungroup() %>% 
  mutate(label = x,
         x = 1:n())
df1 <- df %>%
  filter(y == "group1") %>% rename(group1 = z)
df2 <- df %>%
  filter(y == "group2") %>% rename(group2 = z)

df1 %>% 
  e_charts(x) %>% 
  e_bar(group1, legend = TRUE,
        bind = label,
        label = list(show = TRUE,
                     formatter = "{b}",
                     position = "bottom",
                     offset = c(0, 10)),
        barWidth = "80%") %>%
  e_data(df2, x) %>%
  e_bar(group2, legend = TRUE,
        bind = label,
        label = list(show = TRUE,
                     formatter = "{b}",
                     position = "bottom",
                     offset = c(0, 10)),
        barGap = "-100%",
        barWidth = "80%") %>%
  e_x_axis(axisLabel = list(show = FALSE),
           axisTicks = list(show = FALSE))
```
