### ISSUE TITLE
Possible enhancement: extract raw Javascript 'option' object from a plot

### ISSUE THREAD

**Issue by kovla** [JohnCoene/echarts4r#58]
Hi John,

First of all, I would like to thank you again for creating this wonderful package, which brings Echarts 4 a lot closer to R users. I work with eCharts a lot lately, and I try to use `echarts4r ` as much as possible due to its simplicity. However, sometimes it is still easier to embed raw Javascript code to generate a plot. The reason is quite simple. 

There are a lot of examples of Javascript-based plots for Echarts (obviously), and quite often it is practical to depart from an existing chart and to adapt it to your own needs, rather than start from scratch. Unfortunately, it is often difficult to translate those rather complex Javascript examples with many parameters to R code. In other words, it is not always obvious how to reproduce a certain Javascript `option `object in R syntax. What would really help in this process, is a view of the current state of the `option ` object that is being produced by R code. For example: 

```
### R code
dat <- structure(list(X1 = c(10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5), 
    X2 = c(8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 
    4.82, 5.68)), class = "data.frame", row.names = c(NA, -11L
)) 

dat %>%  
  e_charts(X1) %>%
  e_scatter(X2, symbol_size = 20) %>%
  e_legend(show = FALSE) -> p

```
```
/// Corresponding JS object

option = {
    xAxis: {},
    yAxis: {},
    series: [{
        symbolSize: 20,
        data: [
            [10.0, 8.04],
            [8.0, 6.95],
            [13.0, 7.58],
            [9.0, 8.81],
            [11.0, 8.33],
            [14.0, 9.96],
            [6.0, 7.24],
            [4.0, 4.26],
            [12.0, 10.84],
            [7.0, 4.82],
            [5.0, 5.68]
        ],
        type: 'scatter'
    }]
};
```
In this particular example it was easy to guess that the `symbolSize` parameter is passed in `e_scatter()`, and that turning off the legend would be controlled by `e_legend()`. However, in many cases more obscure options are passed to Javascript via `...`, and then it is not entirely obvious where these should be put. Which is why seeing the resulting `option` object would help. I am not sure how easy or difficult it would be to implement such an extraction, or perhaps it is there somewhere already (the `echarts4r `plot object seems to contain something very similarly structured, but not entirely&#8212;one cannot just `JSON.parse()` it and paste it directly into JSFiddle, for example). This would certainly be helpful in designing more complex plots. 

Kind regards,
Maxim

**Comment by JohnCoene** [comment]
Hi Maxim,

Thank you for the message. Indeed, I do that myself all the time while developing the package.

I just added a function to inspect the object built by the package.

Install the dev version (I just pushed to CRAN recently so there are no major changes).

```r
# install.packages("remotes")
remotes::install_github("JohnCoene/echarts4r")

# this will return a list
mtcars %>% 
  e_charts(mpg) %>% 
  e_scatter(wt, qsec) %>% 
  e_inspect()

# this will return the JSON
# pretty = TRUE to make it readable
mtcars %>% 
  e_charts(mpg) %>% 
  e_scatter(wt, qsec) %>% 
  e_inspect(
    json = TRUE,
    pretty = TRUE
  )
```

I've added the enhancement label. Perhaps a function to create an echarst4r plot object from the JSON options would also be useful?

**Comment by kovla** [comment]
Hello John,

Thanks for the *very* prompt response. Unfortunately, I am unable to use the dev version. After the installation: 

> library(echarts4r)
Error: package or namespace load failed for ‘echarts4r’ in runHook(".onLoad", env, package.lib, package):
 lazy-load database 'C:/Users/[edited]/Documents/R/win-library/3.5/echarts4r/R/echarts4r.rdb' is corrupt
In addition: Warning message:
In runHook(".onLoad", env, package.lib, package) :
  internal error -3 in R_decompress1

**Comment by JohnCoene** [comment]
You probably had the package loaded when you reinstall. Re-open an R console or RStudio, reinstall from Github, then load the package. It should work fine.

**Comment by kovla** [comment]
(Solved it - manually deleting the package folder helped.) 

Overall, I think this is a great addition, because it allows to experiment in environments like JSFiddle and fine-tune your plots very quickly. From that perspective, the reverse function to create an echarst4r plot object from the JSON would also be extremely useful for simplifying the workflow. 

There may be still some kinks left to iron out. For example, when I try to replicate my initial example: 

```
dat %>%  
    e_charts(X1) %>%
    e_scatter(X2, symbol_size = 20) %>%
    e_legend(show = FALSE) %>% e_inspect(json = TRUE, pretty = TRUE)
```

The following object is generated: 

```
{
  "yAxis": [
    {
      "show": true
    }
  ],
  "xAxis": [
    {
      "type": "value"
    }
  ],
  "legend": {
    "data": [
      "X2"
    ],
    "show": false,
    "type": "plain"
  },
  "series": [
    {
      "data": [
        {
          "value": [4, 4.26]
        },
        {
          "value": [5, 5.68]
        },
        {
          "value": [6, 7.24]
        },
        {
          "value": [7, 4.82]
        },
        {
          "value": [8, 6.95]
        },
        {
          "value": [9, 8.81]
        },
        {
          "value": [10, 8.04]
        },
        {
          "value": [11, 8.33]
        },
        {
          "value": [12, 10.84]
        },
        {
          "value": [13, 7.58]
        },
        {
          "value": [14, 9.96]
        }
      ],
      "name": "X2",
      "type": "scatter",
      "symbol": {},
      "coordinateSystem": "cartesian2d",
      "yAxisIndex": 0,
      "xAxisIndex": 0,
      "symbolSize": 20
    }
  ]
}
```

However, when run in JSFiddle, it doesn't generate a complete plot: https://jsfiddle.net/autarkie/k7vpL61m/15/. One has to comment out line 61 (`"symbol": {},`) for the proper result to appear. 

Things like that aside, I think the function (and its possible reverse) will simplify the practical workflow quite much, and also facilitate working with the API documentation of the Echarts library.

**Comment by JohnCoene** [comment]
Woops, thanks for reporting. I'm afraid it might hit and miss, please keep reporting such issues if you have the patience.

It now works.

R `NULL` are now turned to JavaScript `null` instead of empty arrays (`{}`).  If you change symbol to `null` it works. 

Note that some things charts might not work just as is because they contain JavaScript functions which are _forced_ parsed to JSON by `jsonlite` to a string. This is a [jsfiddle](https://jsfiddle.net/79w3oajf/) for the example below.

```r
mtcars %>% 
  e_charts(mpg) %>% 
  e_scatter(wt, qsec) %>% 
  e_inspect(
    json = TRUE,
    pretty = TRUE
  )
```

Produces:

```js
{
  "yAxis": [
    {
      "show": true
    }
  ],
  "xAxis": [
    {
      "type": "value"
    }
  ],
  "legend": {
    "data": [
      "wt"
    ]
  },
  "series": [
    {
      "data": [
        {
          "value": [10.4, 5.25, 17.98, 8.8714]
        },
        {
          "value": [10.4, 5.424, 17.82, 8.5095]
        },
        {
          "value": [13.3, 3.84, 15.41, 3.0583]
        },
        {
          "value": [14.3, 3.57, 15.84, 4.031]
        },
        {
          "value": [14.7, 5.345, 17.42, 7.6048]
        },
        {
          "value": [15, 3.57, 14.6, 1.2262]
        },
        {
          "value": [15.2, 3.78, 18, 8.9167]
        },
        {
          "value": [15.2, 3.435, 17.3, 7.3333]
        },
        {
          "value": [15.5, 3.52, 16.87, 6.3607]
        },
        {
          "value": [15.8, 3.17, 14.5, 1]
        },
        {
          "value": [16.4, 4.07, 17.4, 7.5595]
        },
        {
          "value": [17.3, 3.73, 17.6, 8.0119]
        },
        {
          "value": [17.8, 3.44, 18.9, 10.9524]
        },
        {
          "value": [18.1, 3.46, 20.22, 13.9381]
        },
        {
          "value": [18.7, 3.44, 17.02, 6.7]
        },
        {
          "value": [19.2, 3.44, 18.3, 9.5952]
        },
        {
          "value": [19.2, 3.845, 17.05, 6.7679]
        },
        {
          "value": [19.7, 2.77, 15.5, 3.2619]
        },
        {
          "value": [21, 2.62, 16.46, 5.4333]
        },
        {
          "value": [21, 2.875, 17.02, 6.7]
        },
        {
          "value": [21.4, 3.215, 19.44, 12.1738]
        },
        {
          "value": [21.4, 2.78, 18.6, 10.2738]
        },
        {
          "value": [21.5, 2.465, 20.01, 13.4631]
        },
        {
          "value": [22.8, 2.32, 18.61, 10.2964]
        },
        {
          "value": [22.8, 3.15, 22.9, 20]
        },
        {
          "value": [24.4, 3.19, 20, 13.4405]
        },
        {
          "value": [26, 2.14, 16.7, 5.9762]
        },
        {
          "value": [27.3, 1.935, 18.9, 10.9524]
        },
        {
          "value": [30.4, 1.615, 18.52, 10.0929]
        },
        {
          "value": [30.4, 1.513, 16.9, 6.4286]
        },
        {
          "value": [32.4, 2.2, 19.47, 12.2417]
        },
        {
          "value": [33.9, 1.835, 19.9, 13.2143]
        }
      ],
      "name": "wt",
      "type": "scatter",
      "symbol": null,
      "coordinateSystem": "cartesian2d",
      "yAxisIndex": 0,
      "xAxisIndex": 0,
      "symbolSize": "function(data){ return data[3];}" // this should NOT be in quotes
    }
  ]
}
```

**Comment by JohnCoene** [comment]
Turns out this is a pretty awesome idea Maxim.

```r
p <- cars %>% 
  e_charts(dist) %>% 
  e_scatter(speed, symbol_size = 10) 
 
p # plot

# extract the JSON 
json <- p %>% 
  e_inspect(
    json = TRUE,
    pretty = TRUE
  )
  
# print json
json
  
# rebuild plot
echarts_from_json(json) 

# and further modify the list
echarts_from_json(json) %>%
  e_theme("dark")
```

Let me know what you think.

**Comment by artemklevtsov** [comment]
With `echarts_from_json` and `glue::glue` we can use an any example from the web with our data.

**Comment by kovla** [comment]
> Let me know what you think.

Thanks for implementing this so quickly, John. I think this new functionality opens up some attractive avenues to work with Echarts from R, and gives the `echarts4r `package extra flexibility. Using and easily modying JSON examples found elsewhere, working more transparently with Echarts API Documentation, creating more complex Shiny plots with way more ease than before. Also a great idea from @artemklevtsov to use `glue()`, that will come in handy in reactive environments I imagine.
