### ISSUE TITLE
Unable to install echarts for R version 4.3.1 using install.packages()

### ISSUE THREAD

**Issue by j-kind** [JohnCoene/echarts4r#586]
Hello, I've enjoyed using echarts so far, but I'm now having an issue after updating to the latest version of R. 

When I attempt to install echarts using install.packages() I get the error that echarts is not available for my version of R, which is 4.3.1.

**Comment by JohnCoene** [comment]
It is supported on that version, I just tried on 4.3.2 and successfully installed it.

Could you share more about how you try to install it and what error you encounter?
