### ISSUE TITLE
aria decal only on bottom bar 

### ISSUE THREAD

**Issue by oobd** [JohnCoene/echarts4r#589]
If I apply aria decal to a stacked bar chart like below, I get an output where both top and bottom bars have the decal applied.
Is there a way to specify only the top bar as having decal? 

I have tried e_add_nested but that doesn't seem to work for decals 

```{r}
library(echarts4r)
library(tidyverse)


d <- data.frame(
   xaxis = c(rep("a", 2), rep("b", 2)),
   groups  = c("c", "d", "c", "d"),
   value = rnorm(4, mean = 50)
   ) |>
   group_by(xaxis) |>
   dplyr::mutate(Label = value)

d |>
  group_by(groups) |>
  e_chart(xaxis) |>
  e_bar(value, stack = "groups",
     bind = Label,
     label = list(
       show = TRUE,
       formatter = "{b}",
       position = "inside"
     )
  ) |>
  e_aria(enabled = TRUE, decal = list(show = TRUE))

```

![image](https://github.com/JohnCoene/echarts4r/assets/115593238/30022d2c-50b6-490a-879e-88b1a84b74a1)

**Comment by JohnCoene** [comment]
I'm afraid not it's [this option](https://echarts.apache.org/en/option.html#aria), it's a global that's applied to all series though some customisation is avaialble

**Comment by oobd** [comment]
thanks John
