### ISSUE TITLE
Cannot pass `align` property to rich in `e_title()`

### ISSUE THREAD

**Issue by gacolitti** [JohnCoene/echarts4r#590]
I would like to control the alignment of the title text and subtext separately and thought this was possible by passing `align` to rich.

For example:

```r
mtcars |>
  e_charts_("qsec") |>
  e_line(mpg) |> 
  echarts4r::e_legend(show = F) |> 
  e_title(text = "This is not centered", 
          subtext = "This is not left aligned",
          textStyle = list(rich = list(align = "center")),
          subtextStyle = list(rich = list(align = "left")),
          left = "50%")
```

But the use of the align property here doesn't seem to have any effect.

![image](https://github.com/JohnCoene/echarts4r/assets/29231016/e2cb2e51-b7b0-4b23-8436-ea855e8f5000)

**Comment by rdatasculptor** [comment]
Hi @gacolitti You are mentioning subtext, but it isn't in your code. Maybe you can add it? It helps finding a solution.

**Comment by gacolitti** [comment]
The reprex I gave you didn't illustrate the issue. Just updated the code and screenshot.

**Comment by rdatasculptor** [comment]
So the subtext should be placed at the left side above the chart?

**Comment by munoztd0** [comment]
Moving the title alone without moving the subtext is not supported by echarts see https://github.com/apache/echarts/issues/9968
