### ISSUE TITLE
e_bar chart  combine with e_pie chart

### ISSUE THREAD

**Issue by pizifan** [JohnCoene/echarts4r#603]
I am experimenting with e_bar and e_pie in one chart, like the demo shows: https://echarts.apache.org/examples/en/editor.html?c=mix-timeline-finance. But the result is empty。

DF<- data.frame(year=c(2021,2021,2022,2022,2023,2023),
                         type=c('1','2','1','2','1','2'),
                         value=c(100,200,200,150,180,200))%>%
    group_by(year)

 DF%>%
    e_charts(type,timeline = T)%>%
    e_bar(value)%>%
    e_data(DF,type)%>%
    e_pie(value,'test',center=list('75%', '35%'),
          radius='28%'）

How can i  set to get the correct result? thank you very much!

**Comment by rdatasculptor** [comment]
As far as I can see this currently not possible with echarts4r. But it would really be a very nice feature. In my imagination I am thinking of complete dashboards with all kinds of charts put together this way.  Maybe a nice puzzle for you @munoztd0 :)

**Comment by JohnCoene** [comment]
It's technically possible but it's a pain to configure, see [this](https://echarts4r.john-coene.com/articles/brush)

Generally I just find arranging using CSS/JavaScript much easier

**Comment by rdatasculptor** [comment]
Thanks @JohnCoene , I forgot about that example
