### ISSUE TITLE
In R Markdown,  can not configure fig sizes. 

### ISSUE THREAD

**Issue by brucefeiwang** [JohnCoene/echarts4r#61]
Tried `

```
{r fig1 ,  fig.height=1, fig.width=1}
e_charts() %>% 
  e_gauge(41, "PERCENT") 
```

`

size won't change .

**Comment by brucefeiwang** [comment]
A unrelated question ,  is there a circular indicator plot available here ?
like this one https://www.jqueryscript.net/loading/Simple-Circle-Progress-Indicator-Plugin-with-jQuery-CSS3-Progress-Circle.html

**Comment by JohnCoene** [comment]
Bit hack~ish but it can be done, it's essentially a very thin pie chart with the label in the center.

```r
data.frame(
    value = c(25, 75),
    label = c("25%", "") # one hidden label
) %>% 
    e_charts(label) %>% 
    e_pie(value, radius = c(80, 85), label = list(position = "center")) %>% 
    e_color(color = c("#d80000", "rgba(216,0,0,.1)"))
```

**Comment by brucefeiwang** [comment]
This is  awesome ! 
Thanks a lot.
Fei
