### ISSUE TITLE
Question on shared dataset charts

### ISSUE THREAD

**Issue by stvanh** [JohnCoene/echarts4r#611]
Hi there, I would like to know if we can do the same as in the following: https://echarts.apache.org/examples/en/editor.html?c=dataset-link

**Comment by JohnCoene** [comment]
Yes, there is an example [here](https://echarts4r.john-coene.com/articles/brush)

**Comment by stvanh** [comment]
Thank you very much, John. Could you please give me an example in which the information of the pie chart will be updated when I point to a point of the line chart? I would like to increase the interactivity of the plot like the original link. That is what I really want to see. Thanks in advance :)

**Comment by JohnCoene** [comment]
This feature is really tricky to use, I'm the author of the package and I don't fully understand it either: it's complexity coming from echarts.js

I would suggest looking at [connect feature](https://echarts4r.john-coene.com/articles/connect) it's far easier to use

**Comment by stvanh** [comment]
Ok I see. Thanks for your support. Really appreciate your awesome work. I close this issue here.
