### ISSUE TITLE
timeline in combination with calendar

### ISSUE THREAD

**Issue by rdatasculptor** [JohnCoene/echarts4r#630]
I know that the calendar chart does not officially support timeline, but isn';t there a smart way to only show the month of the timeline instead of all the months in the range with only the content of the month shown that is picked by the timeline?

```
dates <- seq.Date(as.Date("2017-01-01"), as.Date("2018-12-31"), by = "day")
values <- rnorm(length(dates), 20, 6)

year <- data.frame(date = dates, values = values) %>%
  mutate(month = as.character(date),
         month = substr(month, 6, 7))

year |> 
  group_by(month) |>
  e_charts(date, timeline = TRUE) |> 
  e_calendar(range = c("2018")) |> 
  e_heatmap(values, coord_system = "calendar") |> 
  e_visual_map(max = 30) |> 
  e_title("Calendar", "Heatmap")

```

**Comment by JohnCoene** [comment]
It looks like you can be more specific with the [range](https://echarts.apache.org/en/option.html#calendar.range), e.g.: `range = c('2017-01-02', '2017-02-23')` Does that work?

**Comment by rdatasculptor** [comment]
the range can't be determined by the timeline so it seems. But maybe there is a workaround somehow?

**Comment by rdatasculptor** [comment]
Okay, the moment I asked that question, I thought of a solution:

dates <- seq.Date(as.Date("2017-01-01"), as.Date("2018-12-31"), by = "day")
values <- rnorm(length(dates), 20, 6)

```
year <- data.frame(date = dates, values = values) %>%
  mutate(month = as.character(date),
         month = substr(month, 6, 7))

calendarList <- list()
months <- unique(year$month)
months <- months[order(months)]
for (i in 1:length(months)){
  if (i < length(months)) calendarList[[i]] <- list(range = c(paste0("2017-", months[i]), paste0("2017-", months[i+1])))
  if (i == length(months)) calendarList[[i]] <- list(range = c(paste0("2017-", months[i]), "2018-01"))
}

year |> 
  group_by(month) |>
  e_charts(date, timeline = TRUE) |> 
  e_timeline_serie(calendar = calendarList) %>%
  e_heatmap(values, coord_system = "calendar") |> 
  e_visual_map(max = 30) |> 
  e_title("Calendar", "Heatmap")
``
```
The sub ranges should be chosen more carefully, but I will manage. I will close this issue.
