### ISSUE TITLE
dashboard on https://shinyapps.io/

### ISSUE THREAD

**Issue by henry090** [JohnCoene/echarts4r#64]
Hi,  ```e_effect_scatter``` and some things do not work on  https://shinyapps.io/

Shiny server
<img width="1279" alt="screen shot 2019-02-07 at 4 34 44 pm" src="https://user-images.githubusercontent.com/38523699/52411913-b9db7700-2af6-11e9-89c1-f2eb3510186e.png">

---
---

Locally

![dashboard](https://user-images.githubusercontent.com/38523699/52411940-cd86dd80-2af6-11e9-81ed-ed57077e3b2c.png)

**Comment by JohnCoene** [comment]
(nice dashboard!)

Sorry if these questions sound idiotic, I deploy on Shiny Community Server and I'm not familiar with shinyapps.io. 

- Is there a log you could share?
- Do you have the same versions installed locally and remotely?

Note that it always worked fine for me on Shiny Server.

**Comment by henry090** [comment]
Here it is: 
[logs.txt](https://github.com/JohnCoene/echarts4r/files/2840928/logs.txt)

**Comment by JohnCoene** [comment]
Logs do not give much information on the packages installed. May I see the dahsboard? If you could share a link I could look at the front-end JavaScript

**Comment by henry090** [comment]
https://turgut.shinyapps.io/azal_dashboard/

I can share Rmd file, too.

**Comment by JohnCoene** [comment]
This definitely due to package versions being different but it's a hard to tell which since I can't see which versions were installed on the Shiny server.

![image](https://user-images.githubusercontent.com/7833796/52415430-38c8b380-2ae7-11e9-8860-2b702465313b.png)

Perhaps reinstalling `echarts4r` with `devtools` and re-publish will do?

**Comment by henry090** [comment]
> Perhaps reinstalling `echarts4r` with `devtools` and re-publish will do?

Yes, you are right :)  It works!

**Comment by henry090** [comment]
@JohnCoene  I have noticed that application does not sleep ...
For a free account, we have 25 Active Hours.

Is it due to some animation on a plot?
otherwise, it will destroy my free account.

**Comment by JohnCoene** [comment]
That's strange, it should not be. You can try:

```r
server = function(input, output, session) { session$onSessionEnded(function() { stopApp() }) 
}
```

**Comment by JohnCoene** [comment]
FYI: added a note on shinyapps.io in [documentation](https://echarts4r.john-coene.com/articles/shiny.html). Let me know if application shut down above works.

**Comment by JohnCoene** [comment]
Did that do the trick?

**Comment by henry090** [comment]
> FYI: added a note on shinyapps.io in [documentation](https://echarts4r.john-coene.com/articles/shiny.html). Let me know if application shut down above works.

Hi, sorry for the late reply,  I don't know why but previously default sleeping time was 5 min. However, now, it is changed to 15 min on Shiny server. 
<img width="1029" alt="screen shot 2019-02-08 at 2 33 17 pm" src="https://user-images.githubusercontent.com/38523699/52473256-c15e5700-2bae-11e9-9305-c3b0aca6b11a.png">

**Comment by JohnCoene** [comment]
OK got it.
