### ISSUE TITLE
Custom JS tooltip not displayed when 'x' is a date or string date.

### ISSUE THREAD

**Issue by GitHunter0** [JohnCoene/echarts4r#642]
Hey @JohnCoene , first congratulations for this awesome package. 

I'm almost replacing `plotly` with `echarts4r`, this tooltip issue is probably the last thing I need to figure out. However, I can't find a solution anywhere, so I'm asking here.

Consider the MWE below, the tooltip is not displayed when I use `date` or `date_str` in `e_charts(x = .)` but it works fine when `x_num` is used instead. 

Is this a bug? How can I circumvent that? 

``` r
library(echarts4r)
data.frame(
    g=c("aaaaa", "aaaaa", "aaaaa", "b", "b", "b",
        "dddddddddd", "dddddddddd", "dddddddddd"),
    x_num=c(0,1,2,0,1,2,0,1,2),
    date_str=c(
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01'
    ),
    date=as.Date(c(
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01'
    )),    
    y=c(1.234, 2.12, 3.55, 5.6, 7.97, 8.999, 4.33567, 10.4324321, 12)
) |>
  group_by(g) |>
  e_charts(x = date_str) |>
  e_line(y) |>
  e_tooltip(
    trigger = "axis",
    formatter = htmlwidgets::JS(r"--[
      function(params) {
        var xValue = params[0].value[0];
        var tooltipHtml = '<div><strong>' + xValue + '</strong></div>';

        for (var i = 0; i < params.length; i++) {
          tooltipHtml += '<div style="display: flex; justify-content: space-between;">' +
                         '<span>' + params[i].seriesName + ': &nbsp</span>' +
                         '<span style="text-align: right;">' + params[i].value[1].toFixed(2) + '%</span>' +
                         '</div>';
        }
        return tooltipHtml;
      }
    ]--")
  )
```

```r
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

other attached packages:
[1] echarts4r_0.4.5
```

Thank you.

**Comment by rdatasculptor** [comment]
unfortenately I am no js expert, but I was wondering, why do you use only one escape in your js code?  there are more than one "

**Comment by GitHunter0** [comment]
Thanks @rdatasculptor , actually there is no need to have any scape since `r"--[...]--"` allows to have literal quotes inside it. Therefore, I edited my code removing the scape (but the tooltip issue persists).

**Comment by JohnCoene** [comment]
You have errors in the console: `Uncaught TypeError: params[i].value[1].toFixed is not a function`.

I think `params[i].value` doesn't exist, it's `params[i].data.value[y]`, see example below.

```r
data.frame(
    g=c("aaaaa", "aaaaa", "aaaaa", "b", "b", "b",
        "dddddddddd", "dddddddddd", "dddddddddd"),
    x_num=c(0,1,2,0,1,2,0,1,2),
    date_str=c(
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01'
    ),
    date=as.Date(c(
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01',
      '2000-01-01', '2001-01-01', '2002-01-01'
    )),    
    y=c(1.234, 2.12, 3.55, 5.6, 7.97, 8.999, 4.33567, 10.4324321, 12)
) |>
    group_by(g) |>
    e_charts(x = date_str) |>
    e_line(y) |>
    e_tooltip(
      trigger = "axis",
      formatter = htmlwidgets::JS(r"--[
        function(params) {
        console.log(params);
          return params.map((param) => {
            return `${param.seriesName}: ${param.data.value[0]}, ${param.data.value[1]}`
          }).join('<br/>');
        }
      ]--")
    )
})
```

**Comment by GitHunter0** [comment]
Thank you for the feedback @JohnCoene , I tested and saw that the error in the console only appears when `x` is a **date** or a **string date (date_str)**; when it is a number (as `x_num` in my example), everything works perfectly and as expected, with no error at all. 
That's why I'm wondering if it is a bug since I can't find a reason for that strange behavior.

**Comment by JohnCoene** [comment]
Apparently this gets converted to a string, so you can `parseFloat(param.data.value[1]).toFixed()`

I don't think it's a bug.

**Comment by GitHunter0** [comment]
> so you can `parseFloat(param.data.value[1]).toFixed()`

@JohnCoene , I tried that but now I receive `Uncaught TypeError: Cannot read properties of undefined (reading 'value')`
