### ISSUE TITLE
text on y_axis

### ISSUE THREAD

**Issue by henry090** [JohnCoene/echarts4r#65]
Hi @JohnCoene ,

The Bar plot is OK but it is not possible to see text on y_axis.
<img width="1280" alt="screen shot 2019-02-16 at 5 42 20 pm" src="https://user-images.githubusercontent.com/38523699/52900728-df613280-3212-11e9-98a5-cc45d46defee.png">

```
feature_desc    feature_weight
OverTime = Yes     0.23952812
YearsSinceLastPromotion <= 1    -0.14215328
4 < NumCompaniesWorked     0.10344836
3 < EnvironmentSatisfaction    -0.09764720
JobInvolvement <= 2     0.09499731
MaritalStatus = Single     0.07384738
YearsWithCurrManager <= 2     0.07421330
YearsInCurrentRole <= 2     0.07126696
Department = Research & Development    -0.06006977
YearsAtCompany <= 3    -0.06213960
JobRole = Laboratory Technician     0.05528830
JobLevel <= 2     0.05509913
StockOptionLevel <= 1     0.05436929
Gender = Male     0.04728787
1162 < DailyRate    -0.04032256
```
```
explanation1 %>% 
  e_charts(feature_desc) %>% 
  e_bar(feature_weight, name = "Serie 1") %>% 
  e_flip_coords() %>% e_tooltip(trigger = 'axis') %>% 
  e_legend(F) %>% e_color(color= color)
```

At the same time the sequence of plotting the rows is not the same. Should I use ```fct_relevel``` or somehow it is possible to fix that via echarts.

**Comment by JohnCoene** [comment]
Factor levels are not taken into account. It should plot following the order of the rows.  You can make room for the axis text using `e_grid(right=100)`

**Comment by henry090** [comment]
> the order of the rows

It is in the form of descending.
For example, rows are given in the form of ascending but ```e_bar()``` plots it in the form of descending.
Please, look at the 1st row in ```df```  and the last row on the plot

**Comment by JohnCoene** [comment]
Hi @henry090, very much apologise for the very late fix. It had to do with the timeline feature addition and should be fixed now (_on dev branch_). Feel free to re-open if not.

```r
df <- mtcars
df$models <- row.names(df)

df %>% 
  e_charts(models) %>% 
  e_bar(disp) %>% 
  e_flip_coords()
```

Reordered

```r
df %>% 
  dplyr::arrange(-disp) %>% 
  e_charts(models) %>% 
  e_bar(disp) %>% 
  e_flip_coords()
```
