### ISSUE TITLE
e_facet not recognized as a function?

### ISSUE THREAD

**Issue by ghost** [JohnCoene/echarts4r#67]
Hi John,

I'm in the process of learning this package, and I wanted to implement facetting, using the equivalent of `facet_wrap()` in ggplot2. It looks like `e_facet()` is the function to use, but I'm getting a "could not find function" error.

Say for instance I would like to do a scatter plot of the iris dataset, using the Species variable for the facetting. Here's an attempt, using the GH version (0.2.2):

```
library(tidyverse)
library(echarts4r)
#> Welcome to echarts4r
#> 
#> Docs: echarts4r.john-coene.com

iris %>% 
  e_charts(Sepal.Width) %>% 
  e_scatter(Sepal.Length) %>%
  e_facet() # Where do I specify to do this by the Species variable?
#> Error in e_facet(., Species): could not find function "e_facet"
```

Is it possible to have an example using facetting? I'm unclear as to why it's not even recognizing the function.

**Comment by JohnCoene** [comment]
Hi,

Sorry it was a mistake on my part to export `e_facet`, it's an unfinished function that I am still working on. I'll mark this as a bug and will let you know once it is fixed.

Apologies :(

**Comment by philstraforelli** [comment]
No worries! Thanks for the quick reply. Am I correct in interpreting it as `ggplot2::facet_wrap()`?

**Comment by JohnCoene** [comment]
Yes, the ultimate goal is to achieve the same as ggplot2, echarts4r already allows producing the facetted output but it's too painful: https://echarts4r.john-coene.com/articles/grid.html
