### ISSUE TITLE
How to flip coordinates?

### ISSUE THREAD

**Issue by shizidushu** [JohnCoene/echarts4r#7]
How to flip coordinates? Like `coord_flip` in ggplot2

**Comment by JohnCoene** [comment]
Just added it 👍 

```r
df <- data.frame(
  x = LETTERS[1:5],
  y = runif(5, 1, 5),
  z = runif(5, 3, 10)
)

df %>%
 e_charts(x) %>%
 e_bar(y) %>% 
 e_line(z) %>%
 e_flip_coords()
```

Hope this works as you expected.

**Comment by shizidushu** [comment]
Thank you for your quick response. It works well.

Besides, the package size is so large (about 40 mb ) that I find it difficult to install it. The network connection to github is very slow in China (about 30 kb per second in my local machine).

**Comment by JohnCoene** [comment]
Indeed, assets are quite large, I will try to keep the [coding repo](https://coding.net/u/JohnCoene/p/echarts4r/git?public=true) up to date

**Comment by Leo-Lee15** [comment]
@shizidushu  I've encountered the same problem of bad network connection. My solution is to use Rstudio's `project` which downloads the whole repo to your computer through Git (which is much faster.) and you can build the package from source code.
