### ISSUE TITLE
`aes()` function in echarts4r

### ISSUE THREAD

**Issue by Leo-Lee15** [JohnCoene/echarts4r#8]
Thanks for creating such an awesome package!

Recently, I use the `echarts4r` package to make a line plot in which there are many lines in a plot. However, I  find that it is a little difficult to plot multiple series in a single chart using the `e_line()` function. Here is an example:
```r
library(echarts4r)
USArrests %>% 
  dplyr::mutate(State = row.names(.)) %>% 
  e_charts(Assault) %>% 
  e_line(Murder) %>% 
  e_line(UrbanPop) %>%
  e_line(Rape) %>% 
  e_tooltip(trigger = "axis")
```
It seems that I need use the `e_line()` function three times to obtain the desired results. I'm a .newcomer to `echarts4r` package. I don't know whether there is a more elegant solution to this problem in `echarts4r` package just like the `aes()` function in `ggplot2`.

In particular, I  find that the `hcaes()` function in package [`highcharter`](https://github.com/jbkunst/highcharter) is very handy to use  when solving the above problem. Here is an example:
```r
library(dplyr)
library(tidyr)
library(highcharter)
dtemp <- tibble::tibble(
  month = month.abb, 
  tokyo = c(7, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5,
            23.3, 18.3, 13.9, 9.6),
  new_york = c(-0.2, 0.8, 5.7, 11.3, 17, 22, 
               24.8, 24.1, 20.1, 14.1, 8.6, 2.5),
  berlin = c(-0.9, 0.6, 3.5, 8.4, 13.5, 17,
             18.6, 17.9, 14.3, 9, 3.9, 1),
  london = c(3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 
             17, 16.6, 14.2, 10.3, 6.6, 4.8)
)
dtemp
dtemp %>% 
  mutate(month = Sys.Date() + 1:12) %>% 
  rename(date = month) %>% 
  gather(key = "City", value = "Temperature", -date) %>% 
  hchart(type = "line",
         hcaes(x = date, y = Temperature, group = City)) %>% 
  hc_title(text = "Avg. Temperature") %>% 
  hc_xAxis(title = list(text = "Month")) %>% 
  hc_yAxis(title = list(text = "Avg. Temperature")) %>% 
  hc_add_theme(hc_theme_monokai())
```
So would you consider adding `eaes()` function in the `echarts4r` package?

**Comment by JohnCoene** [comment]
You are absolutely right.

I had to deal with this issue myself, see the airlines example in the [gallery](http://echarts4r.john-coene.com/articles/gallery.html), which though works is ugly code.

This is something I'm working on at the moment, it's quite a bit of work but will eventually be implemented, when it does it won't take the form of an aesthetics argument (`aes()`) but will take the `group_by` dplyr function (as group of course).

**Comment by JohnCoene** [comment]
Happy to say that this is now implemented. Simply group your data with `dplyr::group_by`, i.e.:

```r
df <- data.frame(
  grp = rep(LETTERS[1:10], 20),
  x = runif(200),
  y = runif(200)
)

df %>% 
  group_by(grp) %>% 
  e_charts(x) %>% 
  e_line(y) %>% 
  e_title("Grouped data")
```
