### ISSUE TITLE
group by two variable

### ISSUE THREAD

**Issue by student3841701** [JohnCoene/echarts4r#82]
How to simultaneously display two variable (gear & cyl) for selection in legend?
Is it possible to change the symbol based on the third variable (cyl)?

mtcars %>% 
group_by(gear) %>% 
e_charts(mpg) %>% 
e_scatter(disp,cyl) 

Thanks!

![image](https://user-images.githubusercontent.com/9252143/59919178-558fd300-9459-11e9-8e32-2e2507186ce6.png)

**Comment by JohnCoene** [comment]
Hi, 

You cannot group by two variables. I'm not sure what plot you are attempting to make, could you share something with me?

Grouping by two variables would not work, in fact, ggplot2 does not allow it either (what would the second do/represent?)

You can use icons, there is the companion package `echarts4r.assets` which [includes some icons](https://echarts4r-assets.john-coene.com/articles/icons.html).
