### ISSUE TITLE
e_text_g

### ISSUE THREAD

**Issue by deepanshu88** [JohnCoene/echarts4r#87]
I tried using both e_text_g and e_image_g in the same chart. It didn't work. One of them can be used but not together.

**Comment by JohnCoene** [comment]
This was fixed.

**Comment by jordancampbell23** [comment]
Possibly related, is it possible to use two e_text_g functions in the same chart? Thanks!

**Comment by JohnCoene** [comment]
The graphics API is poorly documented and not used in the examples of the official website. I'm having a touch time debugging this. Would you have an example of what you are trying to achieve?

**Comment by jordancampbell23** [comment]
The primary purpose would be to create and adjust axis labels.

Example:

`example_df <- data.frame(type = c("a", "b"),
                         value = c(10, 20))

example_df %>% echarts4r::e_charts(type) %>%
  echarts4r::e_bar(value) %>%
  echarts4r::e_text_g(
    style = list(
      text = "Type"
      ),
    right = "50%",
    #setOption = list(action = "merge"),
    rotation = 0,
    bottom = "2%"

  ) %>%
  echarts4r::e_text_g(
    style = list(
      text = "Value"
    ),
    right = "95%",
    #setOption = list(action = "merge"),
    rotation = 1.56,
    bottom = "50%"

  )
`

The commented out "setOption" was my attempt at parsing through the echarts documentation. 

I appreciate you the time to look at this minor issue. Thanks for all your work on this fantastic charting library.

**Comment by JohnCoene** [comment]
Apologies for the confusion. The functions ending in `_g` are somewhat peculiar to add "graphical" items to charts. They are seldom used. 

You can use the `e_axis*` functions to tweak labels, you can check this bit of [the official documentation](https://echarts.apache.org/en/option.html#xAxis) for options.

```r
example_df <- data.frame(type = c("a", "b"),
                         value = c(10, 20))

example_df %>% echarts4r::e_charts(type) %>%
  echarts4r::e_bar(value) %>%
  echarts4r::e_x_axis(
    name = "Type",
    nameLocation = "middle",
    nameTextStyle = list(
      color = "blue",
      fontSize = 19
    ),
    axisLabel = list(
      fontSize = 15,
      color = "red",
      align = "right"
    )
  )
```

I understand the confusion with `setOption`, there's a small section on the site about navigating the official documentation [here](https://echarts4r.john-coene.com/articles/get_started.html#navigate-options).

**Comment by jordancampbell23** [comment]
How simple. Thanks again for your time!

**Comment by issactoast** [comment]
Hi, thanks for making this awesome pacakge!

I was trying to use e_text_g and e_image_g but it still seems doesn't work.

``` r
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.1.3
#> Warning: package 'ggplot2' was built under R version 4.1.3
#> Warning: package 'tibble' was built under R version 4.1.3
#> Warning: package 'dplyr' was built under R version 4.1.3
library(echarts4r)
#> Warning: package 'echarts4r' was built under R version 4.1.3
example_df <- data.frame(type = c("a", "b"),
                         value = c(10, 20))

example_df %>% echarts4r::e_charts(type) %>%
    echarts4r::e_bar(value) %>%
    e_draft() %>%
    e_image_g(
        right = 20,
        top = 20,
        z = -999,
        style = list(
            image = "https://www.r-project.org/logo/Rlogo.png",
            width = 150,
            height = 150,
            opacity = .6
        )
    )
```

![](https://i.imgur.com/dIz5NTL.png)

<sup>Created on 2022-07-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
