### ISSUE TITLE
Update link to echarts documentation for the "tooltip" option

### ISSUE THREAD

**Issue by jmcastagnetto** [JohnCoene/echarts4r#90]
The link at https://github.com/JohnCoene/echarts4r/blob/b6fa12e7444cf7e70efab3a0e425af038ee1000e/vignettes/get_started.Rmd#L115 should point to https://echarts.apache.org/en/option.html#tooltip

**Comment by JohnCoene** [comment]
Hi Jesus, thanks for pointing this out :+1:  ECharts' official documentation in english changed domain; the github repository now holds all correct links (they had to be changed in oh so many places).
