### ISSUE TITLE
Change documentation for low level graphic functions from "g_*_g()" to "e_*_g()"

### ISSUE THREAD

**Issue by jmcastagnetto** [JohnCoene/echarts4r#91]
As implemented in `R/graphic.R` (https://github.com/JohnCoene/echarts4r/blob/master/R/graphic.R), their names are `e_*_g()` but the documentation still refers to them as `g_*_g()`

https://github.com/JohnCoene/echarts4r/blob/b6fa12e7444cf7e70efab3a0e425af038ee1000e/R/graphic.R#L9-L21

https://github.com/JohnCoene/echarts4r/blob/2a316282531760305496f1102fd34154c845ac35/vignettes/graphics.Rmd#L30-L42

https://github.com/JohnCoene/echarts4r/blob/fc08cc65998a45bffa80369e4c3eff398a75b4ac/NEWS.md#echarts4r-012

**Comment by JohnCoene** [comment]
Thanks!
