### ISSUE TITLE
Color by Factor in Scatter 3D

### ISSUE THREAD

**Issue by JonP-16** [JohnCoene/echarts4r#93]
Hello,

I'm attempting to color by a factor in _e_scatter_3d_. I realize we can't color by factor when using a timeline (perhaps an enhancement for the future?), but I thought this might be a bug given the fact that we can do it in _e_scatter_. In any case, thank you for the package; it's great and I look forward to it's continued growth!

```r
# Colors by Species factor
iris %>% 
  group_by(Species) %>% 
  e_charts(Sepal.Length) %>% 
  e_scatter(Sepal.Width, symbol_size = 10) 

# Doesn't color by Species (didn't expect to since 'color' is an argument of 'e_scatter_3d')
iris %>% 
  group_by(Species) %>%
  e_charts(Sepal.Length) %>% 
  e_scatter_3d(Sepal.Width, Petal.Length) 

# Doesn't color by Species
iris %>% 
  e_charts(Sepal.Length) %>% 
  e_scatter_3d(Sepal.Width, Petal.Length, color=Species) 

# Doesn't color by the numeric species even though there is now a mapping
iris2 = iris
iris2$color = as.numeric(as.factor(iris2$Species))
iris2 %>% 
  e_charts(Sepal.Length) %>% 
  e_scatter_3d(Sepal.Width, Petal.Length, color=color) %>% 
  e_visual_map(
    color,
    dimension = 4 # third dimension 0 = x, y = 1, z = 2, size = 3, color = 4
  )
```

**Comment by JohnCoene** [comment]
Hmmm, indeed. Problem is I cannot find an example where this works. None of the examples [official documentation](https://echarts.apache.org/examples/en/#chart-type-scatter3D) display the legend. I have just looked at the source code (R) and all series are added and named properly, I wonder if it's not on the JS side.

**Comment by JonP-16** [comment]
Hmmm...in that case, I'll do some more digging online to see if I can find any more examples and if not, I can post to their Github issue page. I'm just a little surprised they don't have an example given that it seems like it would be a natural thing to do.

**Comment by JohnCoene** [comment]
I couldn't agree more; It should be possible but I just can't see any example of it nor make it work.

**Comment by swsoyee** [comment]
May be a little bit too late for answering this issue, but I can make this plot successfully.

```r
library(echarts4r)

df <- iris

df$color <- as.character(as.factor(iris$Species))

df %>%
  e_charts(Sepal.Length) %>%
  e_scatter_3d(Sepal.Width, Petal.Length, color = Species) %>%
  e_visual_map(
    color,
    type = "piecewise",
    categories = unique(iris$Species),
    dimension = 3
  )
```
![image](https://user-images.githubusercontent.com/20528423/95220384-61abc980-0831-11eb-9848-7d579dea4a42.png)

In JavaScript, the index is start from `0`, so the color index is `3` not `4`.
If you want to use visual map for category data, you should use `type = "piecewise"`, also provide the unique category argument `categories = unique(iris$Species)`.

There should be a better way for making this kind of plot I think, and my solution just is one of them.
