### ISSUE TITLE
echarts_from_json on raw code

### ISSUE THREAD

**Issue by deepanshu88** [JohnCoene/echarts4r#95]
I am trying to create chart using raw code using **echarts_from_json( )** function. I am using the example from https://echarts.apache.org/examples/en/editor.html?c=line-simple It is showing validation error. I know it's easy to with echarts4r line function but I want to convert code directly from echarts gallery to chart.

```
json <- paste0("
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
")

json2 = gsub("\\s+", "", gsub('[\n\r]', "", json))
jsonlite::validate(json2)

echarts_from_json(json2)

```

**Comment by JohnCoene** [comment]
A few things.

1) you only take what is within `options`
2) you make sure the JSON is actually valid (I used [freeformatter.com](https://www.freeformatter.com/json-formatter.html#ad-output) below).

```r
library(echarts4r)

# formatted JSON from https://www.freeformatter.com/json-formatter.html#ad-output
json <- '{
   "xAxis": {
      "type": "category",
      "data": [
         "Mon",
         "Tue",
         "Wed",
         "Thu",
         "Fri",
         "Sat",
         "Sun"
      ]
   },
   "yAxis": {
      "type": "value"
   },
   "series": [
      {
         "data": [
            820,
            932,
            901,
            934,
            1290,
            1330,
            1320
         ],
         "type": "line"
      }
   ]
}'

echarts_from_json(json)
```

The error is due to the fact you included `options = ` which is not valid JSON and because JSON should use double quotes.

Please close if this fixes your issue 👍

**Comment by deepanshu88** [comment]
Thanks. It works like a charm!

**Comment by deepanshu88** [comment]
Sorry for bothering you again! Is there any way to add javascript functions or variables in JSON?
```
var myColor : ["#eb2100", "#eb3600", "#d0570e", "#d0a00e", "#34da62", "#00e9db", "#00c0e9", "#0096f3", "#33CCFF","#33FFCC"]
function(params){ var num = myColor.length;return myColor[params.dataIndex % num]}
```
I put function within quotes " " but it is not evaluating as it's become string. It does not return error in terms of validation but it does not return desired output. Any other alternative to do this task (Instead of JSON, run the JS code)? 

Source code - https://gallery.echartsjs.com/editor.html?c=xhmv-1o6XS

`
library(echarts4r)

json <- '{
  "var myColor": [
"#eb2100",
"#eb3600",
"#d0570e",
"#d0a00e",
"#34da62",
"#00e9db",
"#00c0e9",
"#0096f3",
"#33CCFF",
"#33FFCC"
],
"backgroundColor": "#0e2147",
"grid": {
"left": "11%",
"top": "12%",
"right": "0%",
"bottom": "8%",
"containLabel": true
},
"xAxis": [
{
  "show": false
}
],
"yAxis": [
{
  "axisTick": "none",
  "axisLine": "none",
  "offset": "27",
  "axisLabel": {
  "textStyle": {
  "color": "#ffffff",
  "fontSize": "16"
  }
  },
  "data": [
  "南昌转运中心",
  "广州转运中心",
  "杭州转运中心",
  "宁夏转运中心",
  "兰州转运中心",
  "南宁转运中心",
  "长沙转运中心",
  "武汉转运中心",
  "合肥转运中心",
  "贵州转运中心"
  ]
},
  {
  "axisTick": "none",
  "axisLine": "none",
  "axisLabel": {
  "textStyle": {
  "color": "#ffffff",
  "fontSize": "16"
  }
  },
  "data": [
  "10",
  "9",
  "8",
  "7",
  "6",
  "5",
  "4",
  "3",
  "2",
  "1"
  ]
  },
  {
  "name": "分拨延误TOP 10",
  "nameGap": "50",
  "nameTextStyle": {
  "color": "#ffffff",
  "fontSize": "16"
  },
  "axisLine": {
  "lineStyle": {
  "color": "rgba(0,0,0,0)"
  }
  },
  "data": []
  }
  ],
  "series": [
  {
  "name": "条",
  "type": "bar",
  "yAxisIndex": 0,
  "data": [
  4,
  13,
  25,
  29,
  38,
  44,
  50,
  52,
  60,
  72
  ],
  "label": {
  "normal": {
  "show": true,
  "position": "right",
  "textStyle": {
  "color": "#ffffff",
  "fontSize": "16"
  }
  }
  },
  "barWidth": 12,
  "itemStyle": {
  "normal": {
  "color": "function(params){ var num = myColor.length; return myColor[params.dataIndex % num] }"
  }
  },
  "z": 2
  },
  {
  "name": "白框",
  "type": "bar",
  "yAxisIndex": 1,
  "barGap": "-100%",
  "data": [
  99,
  99.5,
  99.5,
  99.5,
  99.5,
  99.5,
  99.5,
  99.5,
  99.5,
  99.5
  ],
  "barWidth": 20,
  "itemStyle": {
  "normal": {
  "color": "#0e2147",
  "barBorderRadius": 5
  }
  },
  "z": 1
  },
  {
  "name": "外框",
  "type": "bar",
  "yAxisIndex": 2,
  "barGap": "-100%",
  "data": [
  100,
  100,
  100,
  100,
  100,
  100,
  100,
  100,
  100,
  100
  ],
  "barWidth": 24,
  "itemStyle": {
  "normal": {
  "color": "function(params){ var num = myColor.length;return myColor[params.dataIndex % num] }",
  "barBorderRadius": 5
  }
  },
  "z": 0
  },
  {
  "name": "外圆",
  "type": "scatter",
  "hoverAnimation": false,
  "data": [
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
  ],
  "yAxisIndex": 2,
  "symbolSize": 35,
  "itemStyle": {
  "normal": {
  "color": "function(params){ var num = myColor.length;return myColor[params.dataIndex % num]}",
  "opacity": 1
  }
  },
  "z": 2
  }
  ]
  }
'
  
echarts_from_json(json)
`
