### ISSUE TITLE
graphs not displayed properly when Knit to word/pdf

### ISSUE THREAD

**Issue by hiffman** [JohnCoene/echarts4r#97]
Hi John,
    When I put the report Knit to word or pdf ，I found some graphs colud not be displayed properly. Maybe need to set some knit parameters, or not support this feature? Below is my code and result.

```r
mtcars %>% 
  head() %>% 
  dplyr::mutate(model = row.names(.)) %>% 
  e_charts(model) %>% 
  e_pie(carb, radius = "40%", legend = FALSE)
```
![image](https://user-images.githubusercontent.com/17642875/62142792-8816d080-b321-11e9-8233-4bc90626ddf1.png)

```r
mtcars %>% 
  mutate(
    model = row.names(.),
    total = mpg + qsec
  ) %>% 
  arrange(desc(total)) %>% 
  e_charts(model) %>% 
  e_bar(mpg, stack = "grp") %>% 
  e_bar(qsec, stack = "grp")

```
![image](https://user-images.githubusercontent.com/17642875/62142868-a67ccc00-b321-11e9-9fa4-19b697804585.png)

**Comment by JohnCoene** [comment]
{echarts4r} is html/css/javascript for interactive visualisations which obviously do not work in word or PDf. I believe that when you knit to any of the latter rmarkdown uses {webshot} to take a screenshot of the visualisation and you what you are seeing is a graph where the animation has not finished.

Try knitting to word/PDF with:

```r
mtcars %>% 
  mutate(
    model = row.names(.),
    total = mpg + qsec
  ) %>% 
  arrange(desc(total)) %>% 
  e_charts(model) %>% 
  e_bar(mpg, stack = "grp") %>% 
  e_bar(qsec, stack = "grp") %>%
  e_animation(show = FALSE) # disable animation
```

Please let me know if it does not work.

**Comment by hiffman** [comment]
It's working.Thank you for your patiently answer.

**Comment by artemklevtsov** [comment]
I suggest to add a note to the docs anywhere.

**Comment by JohnCoene** [comment]
Yes, I should add an Rmarkdown vignette
