### ISSUE TITLE
e_radar some parameters don't work

### ISSUE THREAD

**Issue by hiffman** [JohnCoene/echarts4r#98]
Hi John,
when I want to change the radar layout,  I find (center, radius )parameters don't work. Below is my code.

```{r}
score_subset = data.frame(
  key = LETTERS[1:5],
  value = c(50,70,80,90,82)
)

e_charts(score_subset, key) %>% 
  e_radar(serie = value, max=100, 
          legend = FALSE, center = c('20%', '45%'),
          radius=100) %>%  
  e_labels(show = TRUE,position = "top") 
  
```
![image](https://user-images.githubusercontent.com/17642875/62144300-23a94080-b324-11e9-95e3-2b7075c1a096.png)

**Comment by JohnCoene** [comment]
I'm afraid [radar series do not have `center` parameter](https://echarts.apache.org/en/option.html#series-radar.radarIndex). What are you trying to accomplish?

**Comment by hiffman** [comment]
I want to draw multiple radar, [like this](https://echarts.baidu.com/examples/editor.html?c=radar-multiple). In this example, I find center parameter can adjust position, radius parameter can adjust size.

**Comment by JohnCoene** [comment]
OK. Coming back to this issue. I apologise, I was a bit hasty in saying it's not doable. There is indeed a `center` parameter but is passed to the `radar` indicator and not the radar `serie`. 

1. You can pass that `center` argument using `e_radar_opts`. Note that this function is actually already available in the CRAn version  but is buggy so resintall from Github with

```r
install.packages("remotes")
remotes::install_github("JohnCoene/echarts4r")
```

2. I did try to [work on better using the echarts4r grid](https://echarts4r.john-coene.com/articles/grid.html) but it was rather complicated in R and I realised that most of the types of charts (multiple charts that share interactions/legends) can actually be put together ver easily [using arrange and connect](https://echarts4r.john-coene.com/articles/connect.html) so I forcused on the latter.

The example below produces pretty much the same output as you want,

```r
df <- data.frame(
  x = LETTERS[1:5],
  y = runif(5, 1, 5),
  z = runif(5, 3, 7),
  w = runif(5, 2, 6)
)

r1 <- df %>%
  e_charts(x, elementId = "radar1") %>%
  e_radar(y, max = 7) %>%
  e_radar_opts(center = c("50%", "35%"))

r2 <- df %>%
  e_charts(x, elementId = "radar2") %>%
  e_radar(z, max = 7) 

r3 <- df %>%
  e_charts(x, elementId = "radar3") %>%
  e_radar(w, max = 7) %>%
  e_radar_opts(center = c("50%", "35%")) %>%
  e_connect(c("radar1", "radar2", "radar3")) # connect

e_arrange(r1, r2, r3, cols = 3, rows = 1)
```

I hope this helps.

**Comment by hiffman** [comment]
It's a very good solution . Thank you !
